### ISSUE TITLE
pmacct on 64bit musl-libc [patch]

### ISSUE THREAD

**Issue by acoul** [pmacct/pmacct#109]
compiling pmacct on void-linux musl 64bit I bumped onto [this](http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h). the attached patch deals with this issue.

[pmacct-musl_libc.patch.txt](https://github.com/pmacct/pmacct/files/792480/pmacct-musl_libc.patch.txt)

**Comment by paololucente** [comment]
Thanks for this, it makes sense to me. Do you want to issue a PR yourself and close this issue or you prefer me to patch the code? Either way is fine for me. Paolo

**Comment by acoul** [comment]
I issued a PR [here](https://github.com/pmacct/pmacct/pull/110). thank you.
