### ISSUE TITLE
comma is not an ideal CSV delimiter

### ISSUE THREAD

**Issue by job** [pmacct/pmacct#11]
The not-configurable CSV delimiter is ```,```, but this is far from ideal because if one configures the aggregate to dump AS_PATH, it could occur that Atomic Aggregation comes into play, which separates the aggregated ASNs with ```,```.

As can be seen from this example:
```
0,0,5650,65130,2914:370_2914:1205_2914:2204_2914:3200,8928_29286_{7155,64513,64646,65100,65104,65105,65130},120,0,8928,129.250.0.112,81.25.197.186,299,462,50.32.0.0,95.210.0.0,12,16,1,40
```

Correctly parsing ```8928_29286_{7155,64513,64646,65100,65104,65105,65130}``` within the context of of comma separated fields, puts an unnecessary burden on the file parser.

I think there are some ways forward:

* make the default delimiter not a ```,``` but a ```|``` (but this might break peoples scripts)
* make the delimiter configurable: introduce a ```csv_delimiter```

**Comment by paololucente** [comment]
CSV delimeter can actually be configured via print_output_separator, ie. "print_output_separator: ;" to set it to ';' which is indeed a more AS-PATH friendly choice.
