### ISSUE TITLE
pmacct & as-stats

### ISSUE THREAD

**Issue by acoul** [pmacct/pmacct#113]
Greetings,

I've setup on a Gentoo/rolling/latest 32bit, a freshly/git compiled pmacct as a netflow exporter to feed as-stats for our IP/BGP/AS private 10.0.0.0/8 [AWMN](https://en.wikipedia.org/wiki/Athens_Wireless_Metropolitan_Network) network. 

I followed [this guide](https://blog.ohrensessel.net/2016/10/27/pmacct-and-as-stats/). 

My pmacctd-nfprobe-simple.conf

daemonize: false
promisc: true
interface: eth0
plugins: nfprobe
nfprobe_receiver: 127.0.0.1:9000
nfprobe_version:9
nfacctd_net: bgp
nfacctd_as_new: bgp
nfprobe_peer_as: true
bgp_peer_src_as_type: bgp
bgp_src_as_path_type: bgp
bgp_src_std_comm_type: bgp
bgp_src_ext_comm_type: bgp
bgp_peer_src_as_map: /etc/pmacct/peers.map
bgp_daemon_pipe_size: 1310710
bgp_daemon: true
bgp_daemon_ip: 10.2.19.10
bgp_daemon_id: 10.2.19.10
bgp_agent_map: /etc/pmacct/agent_to_peer.map
bgp_daemon_port: 17917
bgp_daemon_max_peers: 2
bgp_daemon_msglog: false
bgp_follow_nexthop: 10.2.19.0/24, 10.2.146.0/24, 10.0.0.0/8
pcap_filter: net 10.0.0.0/8
aggregate: src_host, dst_host, src_port, dst_port, src_as, dst_as, as_path, peer_src_as, peer_dst_as, proto

my /etc/pmacct/peers.map
id=bgp                  ip=10.2.146.10          in=100

my  /etc/pmacct/agent_to_peer.map
bgp_ip=10.2.146.10      ip=10.0.0.0/8

pmacctd -d -f pmacctd-nfprobe-simple.conf 

DEBUG: [pmacctd-nfprobe-simple.conf] plugin name/type: 'default'/'core'.
DEBUG: [pmacctd-nfprobe-simple.conf] plugin name/type: 'default'/'nfprobe'.
DEBUG: [pmacctd-nfprobe-simple.conf] daemonize:false
DEBUG: [pmacctd-nfprobe-simple.conf] promisc:true
DEBUG: [pmacctd-nfprobe-simple.conf] interface:eth0
DEBUG: [pmacctd-nfprobe-simple.conf] nfprobe_receiver:127.0.0.1:9000
DEBUG: [pmacctd-nfprobe-simple.conf] nfprobe_version:9
DEBUG: [pmacctd-nfprobe-simple.conf] nfacctd_net:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] nfacctd_as_new:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] nfprobe_peer_as:true
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_peer_src_as_type:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_src_as_path_type:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_src_std_comm_type:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_src_ext_comm_type:bgp
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_peer_src_as_map:/etc/pmacct/peers.map
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_pipe_size:1310710
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon:true
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_ip:10.2.19.10
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_id:10.2.19.10
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_agent_map:/etc/pmacct/agent_to_peer.map
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_port:17917
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_max_peers:2
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_daemon_msglog:false
WARN: [pmacctd-nfprobe-simple.conf:39] Unknown key: bgp_daemon_msglog. Ignored.
DEBUG: [pmacctd-nfprobe-simple.conf] bgp_follow_nexthop:10.2.19.0/24, 10.2.146.0/24, 10.0.0.0/8
DEBUG: [pmacctd-nfprobe-simple.conf] pcap_filter:net 10.0.0.0/8
DEBUG: [pmacctd-nfprobe-simple.conf] debug:true
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.6.2-git (20170221-01)
INFO ( default/core ): 
INFO ( default/core ): Reading configuration file '/etc/pmacctd/pmacctd-nfprobe-simple.conf'.
INFO ( default/nfprobe ): plugin_pipe_size=4096000 bytes plugin_buffer_size=220 bytes
INFO ( default/nfprobe ): ctrl channel: obtained=163840 bytes target=74472 bytes
INFO ( default/nfprobe ): NetFlow probe plugin is originally based on softflowd 0.9.7 software, Copyright 2002 Damien Miller <djm@mindrot.org> All rights reserved.
INFO ( default/nfprobe ):           TCP timeout: 3600s
INFO ( default/nfprobe ):  TCP post-RST timeout: 120s
INFO ( default/nfprobe ):  TCP post-FIN timeout: 300s
INFO ( default/nfprobe ):           UDP timeout: 300s
INFO ( default/nfprobe ):          ICMP timeout: 300s
INFO ( default/nfprobe ):       General timeout: 3600s
INFO ( default/nfprobe ):      Maximum lifetime: 604800s
INFO ( default/nfprobe ):       Expiry interval: 60s
INFO ( default/nfprobe ): Exporting flows to [127.0.0.1]:9000
INFO ( default/core ): link type is: 1
INFO ( default/core ): [/etc/pmacct/agent_to_peer.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/agent_to_peer.map] map successfully (re)loaded.
DEBUG ( default/core/BGP ): 1 thread(s) initialized
INFO ( default/core/BGP ): maximum BGP peers allowed: 2
INFO ( default/core/BGP ): bgp_daemon_pipe_size: obtained=327680 target=1310710.
INFO ( default/core/BGP ): waiting for BGP data on 10.2.19.10:17917
INFO ( default/core/BGP ): [10.2.146.10] BGP peers usage: 1/2
INFO ( default/core/BGP ): [10.2.146.10] Capability: MultiProtocol [1] AFI [1] SAFI [1]
INFO ( default/core/BGP ): [10.2.146.10] Capability: 4-bytes AS [41] ASN [22128]
INFO ( default/core/BGP ): [10.2.146.10] BGP_OPEN: Local AS: 22128 Remote AS: 22128 HoldTime: 180
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE received
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE sent
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE received
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE sent
DEBUG ( default/nfprobe ): ADD FLOW seq:1 [10.2.146.10]:41317 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:2 [10.2.146.10]:37399 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:3 [10.2.19.4]:50843 <> [192.168.1.69]:53 proto:17
DEBUG ( default/nfprobe ): ADD FLOW seq:4 [10.2.146.10]:46665 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:5 [10.2.146.10]:41227 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:6 [10.2.146.10]:39279 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:7 [10.2.146.10]:44941 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:8 [10.2.146.10]:39761 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:9 [10.2.146.10]:43403 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:10 [10.2.146.10]:43069 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:11 [10.2.146.10]:38175 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:12 [10.2.146.10]:38129 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:13 [10.2.146.10]:33419 <> [10.2.168.5]:179 proto:6
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE received
DEBUG ( default/core/BGP ): [10.2.146.10] BGP_KEEPALIVE sent
DEBUG ( default/nfprobe ): ADD FLOW seq:14 [10.2.146.10]:34519 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:15 [10.2.146.10]:34677 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:16 [10.2.146.10]:35381 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:17 [10.2.146.10]:35919 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:18 [10.2.146.10]:40011 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:19 [10.2.146.10]:45617 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:20 [10.2.146.10]:45333 <> [10.74.80.1]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:21 [10.2.146.10]:33561 <> [10.2.168.5]:179 proto:6
DEBUG ( default/nfprobe ): ADD FLOW seq:22 [10.2.146.10]:34705 <> [10.74.80.1]:179 proto:6
^CWARN ( default/nfprobe ): Shutting down on user request.
DEBUG ( default/nfprobe ): Starting expiry scan: mode -1
DEBUG ( default/nfprobe ): Queuing flow seq:3 (0x927d628) for expiry
DEBUG ( default/nfprobe ): Queuing flow seq:1 (0x927d3c8) for expiry
DEBUG ( default/nfprobe ): Queuing flow seq:2 (0x927d4f8) for expiry
DEBUG ( default/nfprobe ): Queuing flow seq:4 (0x927d758) for expiry
DEBUG ( default/nfprobe ): Queuing flow seq:5 (0x927d888) for expiry
DEBUG ( default/nfprobe ): Queuing flow seq:6 (0x927d9b8) for expiry

netstat -nap | grep 9000
udp        0      0 127.0.0.1:52016         127.0.0.1:9000          ESTABLISHED 18010/pmacctd: Netf

tcpdump -n -i lo port 9000

11:30:25.323368 IP 127.0.0.1.60543 > 127.0.0.1.9000: UDP, length 504
11:30:25.323424 IP 127.0.0.1.60543 > 127.0.0.1.9000: UDP, length 480

there is no netflow data generated and/or fed to port 9000. 

what am I missing?

**Comment by paololucente** [comment]
Hi,

Can you clarify my understanding is correct that - via tcpdump - you actually see packets being sent to 127.0.0.1:9000 by pmacctd/nfprobe and that the problem is that as-stats, listening on such port, does not receive them? If yes, actually, what i miss and would expect to see instead as part of the "netstat -nap | grep 9000" is something like (this example is made with nfacctd listening on port 9000):

udp6       0      0 :::9000                 :::*                                27321/nfacctd: Core

Is it possible the as-stats daemon is not started or it is listening on a different port?

Paolo

**Comment by acoul** [comment]
Hi Paolo and thank you for your feedback.

let me explain a bit my setup. I have two 32bit gentoo systems A and B.  Both systems reside on the same network setup doing different tasks so things are flexible if I need to change this setup. A runs pmacct with nfbrobe plugin only. B runs quagga and as-stats.

I've made some progress which I report on this new bug report [here](https://github.com/manuelkasper/AS-Stats/issues/58)

back on pmacct. I use pcap_filter on traffic selection and noticed that when I setup sampling_rate I get zero results from pmacct/nfprobe.

I understand that this is not an actual bug report. If you think it's not useful as a feedback to others, feel free to treat it accordingly.

**Comment by paololucente** [comment]
Hi,

Ack all & thanks for the further elaboration. If i'm not mistaken at this point the isue with the sampling_rate be the only defect you are bumping into on the pmacct side of the things. Can you confirm: 1) sampling_rate is not set, all goes well; 2) sampling_rate is set to 1 (equivalent to #1), all still goes well; 3) sampling_rate is set to 2, you see no output from nfprobe? 

Paolo

**Comment by acoul** [comment]
Paolo, 

your question about sampling_rate gave me an idea to start testing pmacct/nfprobe from a minimal setup in order to get a stable output and try to locate the issue. thereof I found a minimal working setup, meaning that netflows are properly generated each time  pmacct runs, with the following config:

daemonize: false
promisc: true
plugin_buffer_size: 10240  
plugin_pipe_size: 10240000
pcap_filter: net 10.0.0.0/8
interface: eth0
plugins: nfprobe
nfprobe_receiver: 10.2.19.18:9000
nfprobe_version:9
nfprobe_direction: tag
nfprobe_ifindex: tag2
pre_tag_map: /etc/pmacct/pre_fix_tag.map
aggregate: tag, tag2, src_host, dst_host, src_port, dst_port, src_as, dst_as, as_path, peer_src_as, peer_dst_as, proto

 /etc/pmacct/pre_fix_tag.map : 
id=1 filter='ether src 00:22:15:bf:5a:xx'
id=2 filter='ether dst 00:22:15:bf:5a:xx'

the above setup is working steadily each time pmacct runs generating proper netflows. the above setup also works with a sampling_rate: 128

apparently my problem with pmacct/nfprobe has to do with the following settings:

nfacctd_net: bgp
nfacctd_as_new: bgp
bgp_peer_src_as_type: bgp
bgp_src_as_path_type: bgp
bgp_src_std_comm_type: bgp
bgp_src_ext_comm_type: bgp
bgp_daemon_pipe_size: 1310710
bgp_daemon: true
bgp_daemon_ip: 10.2.19.4
bgp_daemon_id: 10.2.19.4
bgp_agent_map: /etc/pmacct/agent_to_peer.map
bgp_daemon_port: 17917
bgp_daemon_max_peers: 2
bgp_daemon_msglog: false
bgp_follow_nexthop: 10.2.19.0/24, 10.2.146.0/24, 10.0.0.0/8

/etc/pmacct/agent_to_peer.map :
bgp_ip=10.2.146.10 ip=10.0.0.0/8

I will do further troubleshooting on this and get back to you

**Comment by acoul** [comment]
The issue has been resolved. 

I was using an experimental read-only ebgp-multihop quagga collector that we use internally at AWMN for locating various issues in BGP and this apparently drove nuts pmacct. Switching to a normal bgp speaker seems to resolve my issue.

I am closing this "ticket" while expressing my gratitude for such a great and unique open-source project.

**Comment by paololucente** [comment]
Thanks very much for your kind words and for driving the whole investigation to conclusion. Paolo
