### ISSUE TITLE
add new type of aggregation

### ISSUE THREAD

**Issue by plockaby** [pmacct/pmacct#121]
Among the many things we do with netflow is count how much IPv4 versus IPv6 traffic is going across our routers. It'd make my processing a lot easier if there were an aggregate type that distinguished between v4 and v6 rather than me having to look at each IP and decide.

**Comment by paololucente** [comment]
Dear Paul,

It looks you are looking for the existing 'etype' aggregation primitive. Can you give it a try and confirm that is what you would be looking for? It would say 0x800 vs 0x86dd rather than v4 vs v6 but i guess that is good enough?

Paolo

**Comment by plockaby** [comment]
That would likely solve my problem! Are there any other values that it could have? Where does the "etype" come from?

**Comment by paololucente** [comment]
Legit question: some basic euristics are performed: like presence or not of field type #60 (IP protocol version). If not present or value is 4 then etype value is set to 0x800; if set to 6 then etype value is set to 0x86dd. The choice of values is to harmonise expectations out of libpcap/NetFlow/sFlow/IPFIX.
