### ISSUE TITLE
pmacct doesn't export NetFlow Data even though it says sending

### ISSUE THREAD

**Issue by fcntl** [pmacct/pmacct#124]
I configured it like QUICKSTART, and I get this in the log:

DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 480, template ID = 1024, total len = 460, # elements = 8
DEBUG ( default/nfprobe ): Sending NetFlow v9/IPFIX packet: len = 480
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 138, template ID = 1024, total len = 118, # elements = 2
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 252, template ID = 1024, total len = 232, # elements = 4
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 366, template ID = 1024, total len = 346, # elements = 6
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 480, template ID = 1024, total len = 460, # elements = 8
DEBUG ( default/nfprobe ): Sending NetFlow v9/IPFIX packet: len = 480
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 138, template ID = 1024, total len = 118, # elements = 2
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 252, template ID = 1024, total len = 232, # elements = 4
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 366, template ID = 1024, total len = 346, # elements = 6
DEBUG ( default/nfprobe ): Building NetFlow v9 packet: offset = 480, template ID = 1024, total len = 460, # elements = 8

But my collector gets nothing, if I run netcat -l it doesn't see any incoming connections at all.

**Comment by paololucente** [comment]
Hi,

Can you please refer to "XXII. Miscellaneous notes and troubleshooting tips" section "c", where it advices to use tcpdump for debugging purposes? Reason being that in case of a filter, the tcpdump socket is served anyway but the netcat one will not. Plus, in case nfprobe is on a different box than the collector, you can use tcpdump also on the exporter box to confirm packets are getting out. Finally, "netcat -l" would listen on a TCP port whereas NetFlow is UDP and "netcat -l -u" is needed.

Paolo
