### ISSUE TITLE
Question: how can I limit maximum entries?

### ISSUE THREAD

**Issue by whitetiger21022014** [pmacct/pmacct#125]
Hi @paololucente,
I install pmacct for embedded Linux Box(openWRT), with total RAM of box 128MBytes, so will reserve only **30->40 Mbytes for pmacct**
pmacct with nprobe and nfacctd, will monitor only 2-4 clients

nfacctd uses memory as below
............
imt_buckets: 6550
imt_mem_pools_size: 8192
**imt_mem_pools_number: 0**

with imt_mem_pools_number: 0 it works for along time
command pmacct -s. Result "For a total of: .... entries", entries will be increase then decrease then increase again. When it reaches ~28k entries, I got error as below

_ERROR ( out/memory ): We are missing data.
If you see this message once in a while, discard it. Otherwise some solutions follow:
- increase shared memory size, 'plugin_pipe_size'; now: '0'.
- increase buffer size, 'plugin_buffer_size'; now: '0'.
- increase system maximum socket size._

I can use crond for erasing with pmacct -e  
But for situation if crond has problem, so **how can I limit maximum entries, ex: 2000 entries**  or any advices for small memory device?
Thanks you,

**Comment by paololucente** [comment]
Hi,

Working with the space constraint in mind, ie. 30-40MB, is better than trying to squeeze a fixed amount of entries. This extract from the INTERNALS document is something that may help you for the sizing part:

==
Using a fixed table places a maximum limit to the number of entries the table is able
to store; the following calculation may help in building a fixed table:
ES (Entry Size) ~ 50 bytes
NE (Number of entries)

   NE = ('imt_mem_pools_number' * 'imt_mem_pools_size') / ES

Default values are: imt_mem_pools_number = 16; imt_mem_pools_size = 8192; this will let
the default fixed table to contain a maximum of slightly more than 2600 aggregates.
==

One relevant note: that Entry Size is surely outdated. Plus it's very variable (that is why i was saying it's better to work with the space constraint): with compiling options you may enable/disable IPv6 or L2 primitives and that has an effect on this number; plus now there is support for custom primitives, optional data structures (MPLS, NAT, BGP, etc.) and all hugely affect what the Entry Size would be. A config knob should be added to make pmacct do these calculations for you, ie. given a target amount of entries work out the memory structure, but reality is not much dev is made nowadays around the IMT plugin anymore.

Hope this helps.

Paolo

**Comment by whitetiger21022014** [comment]
Thanks you
