### ISSUE TITLE
nfacctd not applying pretag.map tags when subnet/CIDR is specified

### ISSUE THREAD

**Issue by regulatre** [pmacct/pmacct#126]
Hello! 

I'm replicating netflow with nfacctd, and in pretag.map I can apply tags based on an IP using ip= field, but when I try to apply tags based on subnet (ip=x.x.x.x/cidr OR filter='src net x.x.x.x/cidr') nfacctd doesn't seem to apply the tags (and associated sources don't get replicated). In the case of specifying filter=, I get a keyname error in nfacctd.log, but in the case of specifying a CIDR network in the ip= field of the set_tag directive there is no error and the line seems to be silently ignored.

The documentation I have been following is here: 
https://github.com/pmacct/pmacct/blob/master/examples/pretag.map.example

I may be reading it wrong, but based on my understanding nfacctd is supposed to allow a CIDR network specified in the ip= field of the set_tag pretag configuration.

**Comment by paololucente** [comment]
Hi Brad,

To confirm that, yes, 'filter' is not supported when the pre_tag_map is applied to a replication scenario. I agree that documentation can be improved in this area - let me do so and put some notes about keys supported when replicating.

Wrt the 'ip' keyword, according to the docs: that would apply to "the source IP address of the device originating NetFlow packets; in sfacctd this is compared against the AgentId field of received sFlow samples.". Is that your goal or you are rather trying to filter against source/destination IP address of specific flow records?

Paolo
