### ISSUE TITLE
No exporter information available (NF9_EXPORTER_IPV4_ADDRESS/NF9_EXPORTER_IPV6_ADDRESS)

### ISSUE THREAD

**Issue by pgastinger** [pmacct/pmacct#130]
Hi, 

_Disclaimer, this is an enhancement request!_

We are currently looking for an IPFIX collector and pmacct is on our short list. Unfortunately, nfacctd does not collect/store any exporter information included in IPFIX packets.

Although it is defined in src/nfacctd.h, it is not further used. 

> src/nfacctd.h:#define NF9_EXPORTER_IPV4_ADDRESS 130
> src/nfacctd.h:#define NF9_EXPORTER_IPV6_ADDRESS 131

Are there any plans for using this attributes in the future? 

Thanks!

Peter

**Comment by paololucente** [comment]
Hi Peter,

As you can see, this is done. Can you please check the field is read correctly? You'd need to have 'peer_src_ip' as part of your 'aggregate' aggregation method.

Cheers,
Paolo

**Comment by pgastinger** [comment]
Hi Paolo, 

Thanks for the fast response and implementation. I compiled the latest commited version, configured the print module and used `src_host, dst_host, peer_src_ip, peer_dst_ip, in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, src_mask, dst_mask, src_as, dst_as, tcpflags` as aggregate value:

```
root@centos:/data/nfacctd/2017/2017-04/2017-04-27# cat file-20170427-0145.txt
SRC_AS,DST_AS,PEER_SRC_IP,PEER_DST_IP,IN_IFACE,OUT_IFACE,SRC_IP,DST_IP,SRC_MASK,DST_MASK,SRC_PORT,DST_PORT,TCP_FLAGS,PROTOCOL,TOS,TIMESTAMP_START,TIMESTAMP_END,PACKETS,BYTES
...
```
Everything looks good, I can see the exporter IP address of our Juniper MX routers in the PEER_SRC_IP column. Thanks!

best regards, 
Peter

**Comment by paololucente** [comment]
Fantastic! Thanks for confirming. Paolo
