### ISSUE TITLE
Problems with IPFIX flows aggregation into MYSQL database

### ISSUE THREAD

**Issue by FabioLiv** [pmacct/pmacct#131]
Hi all,
I need help because I have problems with mysql plugin. It's just a question, it's not a bug. I'm developing a network monitoring system to detect alerts and prevent loss connectivity. I found that PMACCT is the most suitable tool for my system to store IPFIX flows in a relational database. I use PMACCT to store aggregated flows in a mysql table and another process uses this table to perform operations (i.e. deleting closed sessions, computing throughput). I'm using PMACCT for 4 months and sometimes I have a big problem: too much DB writer processes queued that make the whole system useless! That's the output of `ps` command:

`root     26996  0.4  0.2  34980  8524 pts/1    S    14:06   0:09 nfacctd: Core Process [default]`
`root     26997  0.3  3.4 133032 105732 pts/1   S    14:06   0:08 nfacctd: MySQL Plugin [default_mysql]`
`root     29840  1.0  3.3 209004 102816 pts/1   S    14:41   0:02 nfacctd: mysql Plugin -- DB Writer [default_mysql]`
`root     29920  0.0  3.3 209004 102816 pts/1   S    14:42   0:00 nfacctd: mysql Plugin -- DB Writer [default_mysql]`
`root     29997  0.0  3.3 209004 102816 pts/1   S    14:43   0:00 nfacctd: mysql Plugin -- DB Writer [default_mysql]`
`root     30075  0.0  3.3 209004 102816 pts/1   S    14:44   0:00 nfacctd: mysql Plugin -- DB Writer [default_mysql]`
`root     30152  0.0  3.3 209004 102816 pts/1   S    14:45   0:00 nfacctd: mysql Plugin -- DB Writer [default_mysql]`
`root     30221  0.0  3.3 209004 102816 pts/1   S    14:46   0:00 nfacctd: mysql Plugin -- DB Writer [default_mysql]`

As you can guess the database server is always busy, the process that should use the table to delete closed sessions can't connect to db and the table grows hugely. The monitoring system experiments a "deadlock" and the memory increases quickly, so I need to stop it. I set PMACCT to store data each 60 seconds and I set the cache to the max value. I also installed the latest release (1.6.2). That's my configuration file:
`plugins: mysql `
`nfacctd_port: 2055`
`sql_host: localhost`
`sql_db: collector`
`sql_optimize_clauses: true`
`sql_table: sessions`
`aggregate: vlan, src_host, dst_host, src_port, dst_port, proto`
`sql_user: root`
`sql_passwd: ***`
`sql_history: 1m`
`sql_history_roundoff: m`
`sql_refresh_time: 60`
`sql_cache_entries: 259991`

My system runs in a research campus, so there are a huge amount of active flows. Could PMACCT have problems to handle so many data? 
Anyway I hope I'm wrong and you can help me to find a solution. Thanks in advance!

kind regards, 
Fabio

**Comment by paololucente** [comment]
Ciao Fabio, what you are running into is actually the typical behaviour of the relational database (not pmacct) not keeping up with the whole inserting, indexing, answering queries, etc. Since inserts are protected by locks, if an insert is slow (or gets stuck), further inserts will pile up (which is what you see in your process list) waiting for the lock. Given your aggregation method, which will generate for sure quite some tuples, have you considered a different backend than relational databases? Like, for exmaple, ElasticSearch?

**Comment by FabioLiv** [comment]
Ciao Paolo,
the first release of my project included a main c++ multi-threaded process, a database server and an sFlow collector used to store broadcast traffic. The main process connects to the database to perform computations. That's why I decided at the beginning to use mysql as relational database. Now my project is "growing up" so maybe I have to reengineer the whole system. Anyway I need a backend that provides c++ api. I will look for something could solve my problem!
Thanks for the answer!

Fabio

**Comment by paololucente** [comment]
Yes, using the Kafka or RabbitMQ plugins, you can really hook up any Big Data solution of your choice - including of course InfluxDB. If you end up venturing in this direction, don't hesitate to write me by email. Paolo
