### ISSUE TITLE
Support sql_multi_values key with PostgreSQL

### ISSUE THREAD

**Issue by Gabalino** [pmacct/pmacct#134]
Is it possible to make PostgreSQL support for the sql_multi_values key?

**Comment by paololucente** [comment]
Hi, i'm not positive unless you may volunteer to write it. Did you already try the "kind of equivalent" feature sql_use_copy for PostgreSQL? Or you opposed to it for some (good) reason? Paolo

**Comment by Gabalino** [comment]
Hello! I need to save information about all connections. The load is 2 million records per minute. MySQL has time to store information in the database, and PostgreSQL does not have time. I enclose my configuration. Can you tell me the best solution for my task?

daemonize: true
pidfile: /var/run/nfacctd.pid

aggregate: src_host, dst_host, dst_port, post_nat_src_host, timestamp_start
plugins: pgsql[pg],mysql[my]
plugin_buffer_size: 10240
plugin_pipe_size: 5120000
logfile: /var/log/nfacctd.log

nfacctd_ip: 10.0.0.10
nfacctd_port: 9995

sql_host[pg]: 10.0.0.1
sql_db: pmacct
sql_table[my]: acct
sql_table[pg]: acct
sql_user: pmacct
sql_passwd: pwd

sql_history_roundoff[my]: m
sql_cache_entries[pg]: 160000
sql_cache_entries[my]: 320000
sql_max_writers[my]: 15
sql_max_writers[pg]: 15

sql_num_hosts: true
sql_num_protos: true

sql_optimize_clauses: true
sql_dont_try_update: true
#sql_use_copy: true
sql_multi_values[my]: 100000
sql_multi_values[pg]: 100000
sql_locking_style[my]: none
sql_locking_style[pg]: table
timestamps_secs: true
timestamps_since_epoch: true
