### ISSUE TITLE
Possible bug with flow stitching

### ISSUE THREAD

**Issue by FabioLiv** [pmacct/pmacct#136]
Hi all,
I decided to compare IPFIX data that pmacct stores into my db with the traffic I captured with tcpdump because I noticed that the throughput I compute with pmacct data related to the traffic of my research area is very higher compared to the real throughput of the area. The table of my database is the following:
`vlan ip_src ip_dst src_port dst_port ip_proto packets bytes stamp_inserted stamp_updated timestamp_min timestamp_min_residual timestamp_max timestamp_max_residual`
Maybe I noticed a problem related to the aggregation of the flow in the table. Let me show you an example! This is a row of the table of the db:
`0  150.146.116.71  146.48.101.199  443  64253  tcp  1599  2394232  2017-05-30 10:40:00  2017-05-30 10:42:00  2017-05-30 10:40:06  11000  2017-05-30 10:40:49  13800`
Using Whireshark to analyse the tcpdump track I found that, for the above flow, I had 2 packets. This is the first: 
![flow1_correct](https://cloud.githubusercontent.com/assets/18170093/26587876/eec9ba9c-4553-11e7-9283-81c4be56a5ee.png)
This is the second:
![flow2_correct](https://cloud.githubusercontent.com/assets/18170093/26588053/7761d0ce-4554-11e7-8ff0-8bc595520284.png)
As you can see total bytes and total duration "match" with the ones stored by pmacct. 

Now let me show another example. This is the row of the db:
`0  150.146.116.71  146.48.101.199  443  64454  tcp  1512  2260592  2017-05-30 10:41:00   2017-05-30 10:43:00  2017-05-30 10:41:23  95000 2017-05-30 10:41:23  89000`
Through wireshark I found the flow in 2 packets, just like the previous example. 
This is the first packet:
![flow1_uncorrect](https://cloud.githubusercontent.com/assets/18170093/26588393/81ce7ca0-4555-11e7-8677-63ba293a4d2a.png)
And this is the second:
![flow2_uncorrect](https://cloud.githubusercontent.com/assets/18170093/26588434/9e88cd1e-4555-11e7-93aa-a6332a8d9e0f.png)
As you can see total bytes match exactly with the value in the db while the total duration results lower than 1 second. So the total amount of bytes is correctly aggregated while the total duration seems to be equal to the duration of the value in the second packet. Since I noticed the same behavior each time tcpdump captured 2 packets and "the most duration" of the flow was stored in the second packet, is it possible that there is a problem about aggregation of timestamp_min/timestamp_max fields?
If you need a more detailed explanation, don't hesitate to write me!

Best regards,
Fabio

**Comment by paololucente** [comment]
Ciao Fabio,

This is interesting. Can you please follow up by private email with the following: 1) a capture of the flows so that i can replay in my testbed and we reason on the same set of data, 2) your current config and 3) the pmacct version as output by a "nfacctd -V".

Thanks,
Paolo

**Comment by FabioLiv** [comment]
Solved by commit [62e548d](url). Thanks Paolo!
