### ISSUE TITLE
nfacctd with IPFIX application information export rfc6759

### ISSUE THREAD

**Issue by zamog** [pmacct/pmacct#137]
Hi all,
i'm trying to export with IPFIX application information from Cisco ASR1K running AVC / NBAR2
When configuring the aggregate with 'class' im getting only unknown records.
If i configure custom primitives with application id 95 and raw semantics (didnt find octetArray type) i see the flows but i prefer to get the application name/sub application name.
i attached below some debug outputs

10x
Gilad

!nfacctd version:
/usr/local/sbin/nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.6.2-git (20170223-01)
 '--enable-jansson' '--enable-kafka' '--enable-rabbitmq' '--enable-ipv6'

!debug output:
DEBUG ( default/core ): NfV10 agent         : 192.168.1.1:1024
DEBUG ( default/core ): NfV10 template type : flow
DEBUG ( default/core ): NfV10 template ID   : 269
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
DEBUG ( default/core ): | 0          | ip version         [60   ] |      0 |      1 |
DEBUG ( default/core ): | 0          | L4 protocol        [4    ] |      1 |      1 |
DEBUG ( default/core ): | 0          | 195                [195  ] |      2 |      1 |
DEBUG ( default/core ): | 0          | 95                 [95   ] |      3 |      4 |
DEBUG ( default/core ): | 0          | 58                 [58   ] |      7 |      2 |
DEBUG ( default/core ): | 0          | 234                [234  ] |      9 |      4 |
DEBUG ( default/core ): | 0          | input snmp         [10   ] |     13 |      4 |
DEBUG ( default/core ): | 0          | 239                [239  ] |     17 |      1 |
DEBUG ( default/core ): | 0          | output snmp        [14   ] |     18 |      4 |
DEBUG ( default/core ): | 0          | direction          [61   ] |     22 |      1 |
DEBUG ( default/core ): | 0          | 235                [235  ] |     23 |      4 |
DEBUG ( default/core ): | 9          | 9252               [9252 ] |     27 |      1 |
DEBUG ( default/core ): | 9          | 9253               [9253 ] |     28 |      1 |
DEBUG ( default/core ): | 0          | in bytes           [1    ] |     29 |      8 |
DEBUG ( default/core ): | 0          | in packets         [2    ] |     37 |      4 |
DEBUG ( default/core ): | 0          | first switched     [22   ] |     41 |      4 |
DEBUG ( default/core ): | 0          | last switched      [21   ] |     45 |      4 |
DEBUG ( default/core ): | 0          | 278                [278  ] |     49 |      4 |
DEBUG ( default/core ): | 0          | 279                [279  ] |     53 |      8 |
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): Netflow V9/IPFIX record size : 61
DEBUG ( default/core ):
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [32753]
DEBUG ( default/core ): NfV10 agent         : 192.168.1.1:768
DEBUG ( default/core ): NfV10 template type : flow
DEBUG ( default/core ): NfV10 template ID   : 268
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
DEBUG ( default/core ): | 0          | ip version         [60   ] |      0 |      1 |
DEBUG ( default/core ): | 0          | L4 protocol        [4    ] |      1 |      1 |
DEBUG ( default/core ): | 0          | 195                [195  ] |      2 |      1 |
DEBUG ( default/core ): | 0          | 234                [234  ] |      3 |      4 |
DEBUG ( default/core ): | 0          | input snmp         [10   ] |      7 |      4 |
DEBUG ( default/core ): | 0          | 95                 [95   ] |     11 |      4 |
DEBUG ( default/core ): | 0          | 58                 [58   ] |     15 |      2 |
DEBUG ( default/core ): | 0          | 239                [239  ] |     17 |      1 |
DEBUG ( default/core ): | 0          | direction          [61   ] |     18 |      1 |
DEBUG ( default/core ): | 9          | 9252               [9252 ] |     19 |      1 |
DEBUG ( default/core ): | 0          | output snmp        [14   ] |     20 |      4 |
DEBUG ( default/core ): | 0          | 235                [235  ] |     24 |      4 |
DEBUG ( default/core ): | 9          | 9253               [9253 ] |     28 |      1 |
DEBUG ( default/core ): | 0          | in bytes           [1    ] |     29 |      8 |
DEBUG ( default/core ): | 0          | in packets         [2    ] |     37 |      4 |
DEBUG ( default/core ): | 0          | first switched     [22   ] |     41 |      4 |
DEBUG ( default/core ): | 0          | last switched      [21   ] |     45 |      4 |
DEBUG ( default/core ): | 0          | 278                [278  ] |     49 |      4 |
DEBUG ( default/core ): | 0          | 279                [279  ] |     53 |      8 |
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): Netflow V9/IPFIX record size : 61
DEBUG ( default/core ):
DEBUG ( default/core ): NfV10 agent         : 192.168.1.1:6
DEBUG ( default/core ): NfV10 template type : options
DEBUG ( default/core ): NfV10 template ID   : 262
DEBUG ( default/core ): ------------------------------------------------
DEBUG ( default/core ): |         field type         | offset |  size  |
DEBUG ( default/core ): | app id             [95   ] |      0 |      4 |
DEBUG ( default/core ): | 97                 [97   ] |      4 |      4 |
DEBUG ( default/core ): | 109                [109  ] |      8 |     80 |
DEBUG ( default/core ): | 110                [110  ] |     88 |     80 |
DEBUG ( default/core ): ------------------------------------------------
DEBUG ( default/core ): Netflow V9/IPFIX record size : 168
DEBUG ( default/core ):
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [255487]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [255492]
DEBUG ( default/core ): NfV10 agent         : 192.168.1.1:6
DEBUG ( default/core ): NfV10 template type : options
DEBUG ( default/core ): NfV10 template ID   : 263
DEBUG ( default/core ): ------------------------------------------------
DEBUG ( default/core ): |         field type         | offset |  size  |
DEBUG ( default/core ): | app id             [95   ] |      0 |      4 |
DEBUG ( default/core ): | 45000              [45000] |      4 |     32 |
DEBUG ( default/core ): | 0                  [0    ] |     36 |      9 |
DEBUG ( default/core ): | 45001              [45001] |     45 |     32 |
DEBUG ( default/core ): | 0                  [0    ] |     77 |      9 |
DEBUG ( default/core ): | 45002              [45002] |     86 |     32 |
DEBUG ( default/core ): | 0                  [0    ] |    118 |      9 |
DEBUG ( default/core ): | 45011              [45011] |    127 |     32 |
DEBUG ( default/core ): | 0                  [0    ] |    159 |      9 |
DEBUG ( default/core ): ------------------------------------------------
DEBUG ( default/core ): Netflow V9/IPFIX record size : 168
DEBUG ( default/core ):
DEBUG ( default/core ): NfV10 agent         : 192.168.1.1:6
DEBUG ( default/core ): NfV10 template type : options
DEBUG ( default/core ): NfV10 template ID   : 0
DEBUG ( default/core ): ------------------------------------------------
DEBUG ( default/core ): |         field type         | offset |  size  |
DEBUG ( default/core ): | 10                 [10   ] |      0 |    289 |
DEBUG ( default/core ): | 10                 [10   ] |    289 |    290 |
DEBUG ( default/core ): | 10                 [10   ] |    579 |    263 |
INFO: unable to read next Options Template Flowset (malformed template): nfacctd=0.0.0.0:9993 agent=192.168.1.1:55798 seq=255492
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [256513]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [256520]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [256527]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.1.1:55798] version [10] seqno [256534]

**Comment by paololucente** [comment]
Hi Gilad,

From the output you sent, i understand what is not working: while field type 95 (application ID) is present, field type 96 (application name) is not present. But there are other fields, 97 109 and 110. I bet one of these will somehow do. Can you please send me via private email a trace in libpcap format, ie. taken with tcpdump, so that i can do some analysis with Wireshark and replay it in my testbed?

If unfamiliar with tcpdump, you can read chapter "XXII. Miscellaneous notes and troubleshooting tips " section D of the QUICKSTART ( https://github.com/pmacct/pmacct/blob/master/QUICKSTART ) document.

Cheers,
Paolo

**Comment by paololucente** [comment]
Summarizing from email conversation with Gilad:

The problem is different than originally thought: app description is actually included as part of option templates exported by the Cisco ASR1K; but such template contains a bug: option scope value is malformed according to https://tools.ietf.org/html/rfc7011#section-3.4.2.1 specs. pmacct has a fallback in case of no/invalid scope being supplied but this also fails as it tries to match data to options within the same IPFIX Observation Domain ID but flow data and options happen to be exported with different domain IDs. Resolution appears to be: open a case with Cisco to fix the issue.

**Comment by paololucente** [comment]
Hi @zamog , with the latest code and specifying "nfacctd_disable_opt_scope_check: true" as part of your config, you should now see nfacctd correctly correlating options to flows. Can you please give it a try and confirm this working for you? Thanks, Paolo

**Comment by zamog** [comment]
Working well.
10x !
Gilad
