### ISSUE TITLE
stamp_inserted as epoch time?

### ISSUE THREAD

**Issue by hyperopticadam** [pmacct/pmacct#142]
Hi,

Is there any way to set the stamp_inserted to return an epoch time instead of a string when I output to a file? 

I'm using sfacctd and currently it looks like this in the output log

`{"event_type": "purge", "as_src": 0, "as_dst": 0, "as_path": "", "peer_as_dst": 0, "peer_ip_src": "172.16.0.77", "peer_ip_dst": "", "ip_src": "93.184.221.131", "ip_dst": "100.64.81.62", "port_src": 80, "port_dst": 58563, "stamp_inserted": "2017-07-17 16:39:00", "stamp_updated": "2017-07-17 16:40:01", "packets": 1, "bytes": 1500}
`

Thanks in advance

Adam

**Comment by paololucente** [comment]
Hi Adam, yes, you are looking for: "timestamps_since_epoch: true". Paolo

**Comment by hyperopticadam** [comment]
Hi Paolo, 

Thanks that worked a treat, must have missed in the documentation.

Adam :)
