### ISSUE TITLE
QUICKSTART missing build instructions for configure.ac in recent releases

### ISSUE THREAD

**Issue by mpenning** [pmacct/pmacct#144]
Please either update QUICKSTART with build instructions that use configure.ac, or include a configure script in the releases.  The configure script is currently missing from releases.

**Comment by paololucente** [comment]
Hi Mike, you mean the master code in GitHub does not come with a configure script but you need to do the autogen.sh step first, true? This is documented in README.md but i agree a few words can be spent in the QUICKSTART too, i will do that. I was puzzled only about one thing, you mention 'releases': i checked release 1.6.2 and the configure is definitely there. Paolo

**Comment by mpenning** [comment]
Hello Paolo,

Thank you for the quick response.

Indeed, there is no `configure` script unless you run `autogen.sh`; this step is missing in `QUICKSTART`.   If it was me, I would also add in build requirements such as pkg-config, automake, and libtool.  All this is of course up to your discretion, but it stumped me for a while until I managed to put it together.

**Comment by paololucente** [comment]
Hi Mike, absolutely. That is all explained in README.md that is the document that GitHub shows on the front page (so scrolling to the bottom, it's all shown there). But you are right such info is not mentioned in the QUICKSTART doc - which is a bit the entry point for the rest of documentation. The commit i just made addresses this. Let me know if satisfactory. Paolo
