### ISSUE TITLE
A question regarding time

### ISSUE THREAD

**Issue by aimdev** [pmacct/pmacct#149]
Hi

Sorry if this is not the correct place, but in my pursuit for a 
pmacctd-->rabbitmq-->telegraf-->influx-->grafna
influx requires time in unix format. Perhaps you could point me to the area of code where the message is assembled so I could investigate hacking the code to see if this gets over the problem.

Thanks

Aimee

**Comment by paololucente** [comment]
Hi Aimee, you should be looking for "timestamps_since_epoch: true", let me know if that works. Paolo

**Comment by aimdev** [comment]
Hi

Yes, see them as unix time, but apparently the requirements for input to influx are very pedantic!!, so its still erroring.
Was hoping that the fix would be easy!!, never mind, at  least the time stamp issue from pmacctd is resolved,
I get the feeling I will have to write a plugin specially, in Go, that will be a first for me

Thanks again.

Aimee

**Comment by paololucente** [comment]
Hi Aimee, i see. Although i'm no expert of the TICK framework, i believe what you refer to is to customise Telegraf (that is why you specifically mention Go language) so to accomplish its purpose in the stack. I will then close this issue. Paolo
