### ISSUE TITLE
nfacctd - memory plugin stops getting updated

### ISSUE THREAD

**Issue by sm3ulc** [pmacct/pmacct#156]
Running this config with two exporters. After an hour or so pmacct no longer add flows after doing a -r in the query. It just returns and empty set. Seems odd so I hope I just made a configuration error and not found a bug.

nfacctd -d -b 199999 -m 0 -s 65536 -f nfacctd_internal.conf

DEBUG: [nfacctd_internal.conf] plugin name/type: 'default'/'core'.
DEBUG: [nfacctd_internal.conf] plugin name/type: 'display'/'memory'.
DEBUG: [nfacctd_internal.conf] syslog:daemon
DEBUG: [nfacctd_internal.conf] promisc:true
DEBUG: [nfacctd_internal.conf] interface:lo
DEBUG: [nfacctd_internal.conf] nfacctd_port:8001
DEBUG: [nfacctd_internal.conf] pmacctd_flow_lifetime:10
DEBUG: [nfacctd_internal.conf] pmacctd_flow_buffer_buckets:65536
DEBUG: [nfacctd_internal.conf] pmacctd_conntrack_buffer_size:10240000
DEBUG: [nfacctd_internal.conf] plugin_pipe_size:10240000
DEBUG: [nfacctd_internal.conf] plugin_buffer_size:102400
DEBUG: [nfacctd_internal.conf] aggregate[display]:src_host, dst_host, src_port, dst_port, proto,TIMESTAMP_START,TIMESTAMP_END,timestamp_arrival
DEBUG: [nfacctd_internal.conf] debug:true
DEBUG: [nfacctd_internal.conf] imt_buckets:199999
DEBUG: [nfacctd_internal.conf] imt_mem_pools_number:0
DEBUG: [nfacctd_internal.conf] imt_mem_pools_size:65536

**Comment by paololucente** [comment]
Hi @sm3ulc, it unfortunately smells like a bug and, even worse, one of those it will be hard to reproduce.  The specific query you are performing may be of help. Also, would access to your box be an option? As a quick workaround - especially if you are looking to throw large amount of entries at the memory table, as your 'aggregate' and buffer settings suggest - i may recommend you to move away from the memory plugin and look at the print one (to output to flat-files) to remain in the same ballpark of complexity. Paolo

**Comment by sm3ulc** [comment]
Hi!

Trying to develop very fast detection of certain type of flows, therefore I
choose the memory plugin. Not possible to access the box, but I will try to
reproduce on another system that is more open. With default settings and no
resets I end up with it slowly grinding to a maximum halt at about 36k
flows. Added more memory as you see and get to about 200k flow but in the
end same result. I have looked through the debuglogs
but I don't any errors.

I'll go for the print-plugin in the meantime.

Kind regards,

// David

**Comment by paololucente** [comment]
Hi David, I see. The approx 36k flows under default setting is ok due to the size of the memory table being built; what is not ok is the result you get in your original post with -m 0 where the table should grow indefinitely - is in that case maybe CPU pegging 100% then? That could give a lead. Also can you characterise what kind of flows you are wanting to detect? I'm thinking maybe with some tagging/filtering in place you can reduce the amount of flows making it in the memory structure or some other solution can pop to mind. Paolo

**Comment by sm3ulc** [comment]
Hi!

The CPU (4 cores) runs idle at about 95%. There´s about 10 pps flow with
the two host test setup. Will play with the print-plugin and aggregate
filters. One question though. Have been reading docs and some code and just
to verify. The flows are aggregated and cannot be filter out of the
aggregate at a later time. I.e like a sliding window where flows that ended
>x time ago can be deleted?

Kind regards,

// David

**Comment by paololucente** [comment]
Correct, no, that is not possible. Paolo
