### ISSUE TITLE
Negative Filter

### ISSUE THREAD

**Issue by aimdev** [pmacct/pmacct#157]
Hi
is it possible to filter, in pmacctd all traffic where the source and destination subnets are equal,
for example, I don't want 192.168.0.1 (src) to 192.168.0.2 (dst) to be included,
just want all the rest :)

Thanks

Aimee

**Comment by paololucente** [comment]
Yes, you could use pre_tag_map to, say, tag as '100' all traffic between the same subnets then have a 'pre_tag_filter[<plugin_name>]: -100'. The '-' is the negative filter you are looking for.

Depending on how many subnets you want to apply this to and how much traffic you have you could go down different paths in pre_tag_map. The simplest being (if traffic is VLAN-tagged or MPLS-labelled, adjust the filter accordingly):

set_tag=100     filter='src net 192.168.0.0/24 and dst net 192.168.0.0/24'

Paolo

**Comment by aimdev** [comment]
Hi

Sorry, been a bit distracted this week, thanks for the info

Aimee
