### ISSUE TITLE
nfacctd tee plugin fails when tee_transparent parameter is set to true

### ISSUE THREAD

**Issue by ashvanth48** [pmacct/pmacct#158]
Hi,
I'm getting the below error message if I enable tee_transparent parameter to true

ERROR ( a/tee ): raw send() from [x.x.x.x:50284] seqno [254179447] to [10.20.0.45:5000] failed (Message too long)

**Comment by paololucente** [comment]
Hi @ashvanth48 , the "message too long" error comes back from the kernel and you should look at packet sizes and configured MTU. When in non-transparent mode it may be things are just working because kernel fragments - you should check this too. Paolo

**Comment by ashvanth48** [comment]
Thanks Paolo.
