### ISSUE TITLE
Dynamically adding TEE receiver list

### ISSUE THREAD

**Issue by ashvanth48** [pmacct/pmacct#159]
I'm trying to figure out if there is a way to dynamically add receivers/filters to the TEE plugin, without having to restart the nfacctd daemon. 

If I start a new nfacctd daemon with the new receiver, then I see a new Core and TEE plugin process instantiated. I would like to know how costly this is when compared to having multiple receivers in a single tee plugin.

**Comment by paololucente** [comment]
Hi @ashvanth48 , yes. tee_receivers content can be reloaded at runtime.

Please see the relevant section from the QUICKSTART document on how to fill tee_receivers: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1378-L1435

Then, once you make changes to tee_receivers, you can reload the map at runtime sending a SIGUSR2 to the process, ie. "killall -USR2 nfacctd". In the logs you will get confirmation that the map is reloaded.

I reckon there may be a case of lack of documentation on the reloading at runtime part, i will add some later today.

Paolo
