### ISSUE TITLE
Can I use pmactt to measure consumption per program and month?

### ISSUE THREAD

**Issue by vemv** [pmacct/pmacct#16]
Hi,

I'm evaluating pmactt.

It's not super clear to me what its precise set of functionalities is. Maybe some examples, use cases or screenshots would help.

Anyway, I'm looking for a permanently-running monitor which can emit a monthly (or daily, etc) bandwidth report, in a per-program manner.

Example desired output:

```
Bandwidth consumption: last 30 days
==============
Program     Downloaded   Uploaded
/usr/bin/ssh  30MB       100MB
/usr/bin/java 9000MB     3000MB

```

I actually don't mind the output format (plain text or store to DB, etc), but those are the key metrics for me.

Can pmacct gather this data? So far I haven't found any such monitor so I'm suspecting this may not be possible under linux.

Any help appreciated!

Thanks - Victor

**Comment by paololucente** [comment]
Dear Victor: no, pmacct is not meant to count traffic per application on a system. It is an interesting case but i also can't help pointing you to an application able to do that. Cheers, Paolo

**Comment by vemv** [comment]
Alright Paolo, thanks so much in any case.

Victor
