### ISSUE TITLE
Underflow in NF_time_msecs_handler

### ISSUE THREAD

**Issue by dsgwork** [pmacct/pmacct#163]
In function src/pkt_handlers.c:NF_time_msecs_handler, default case for the packet version switch statement:
```
    pdata->time_start.tv_sec = ntohl(((struct struct_header_v5 *) pptrs->f_header)->unix_secs)-
      (ntohl(((struct struct_header_v5 *) pptrs->f_header)->SysUptime)-ntohl(((struct struct_export_v5 *) pptrs->f_data)->First));
    pdata->time_end.tv_sec = ntohl(((struct struct_header_v5 *) pptrs->f_header)->unix_secs)-
      (ntohl(((struct struct_header_v5 *) pptrs->f_header)->SysUptime)-ntohl(((struct struct_export_v5 *) pptrs->f_data)->Last));
```

Because SysUptime, First and Last are all unsigned, if SysUptime < First (or Last), there will be an underflow and packet time will be before NetFlow header unixtime.

We hit this issue because we have a bunch of historical NetFlow files generated with nfcapd that all have SysUptime=0. Trying to load these files into nfacctd with nfreplay results in all flows getting timestamps 49.7102 days in the past ((2^32)/1000/60/60/24).

If we change these lines to:
```
    pdata->time_start.tv_sec = ntohl(((struct struct_header_v5 *) pptrs->f_header)->unix_secs)-
    ((ntohl(((struct struct_header_v5 *) pptrs->f_header)->SysUptime))/1000)+
    ((ntohl(((struct struct_export_v5 *) pptrs->f_data)->First))/1000);

    pdata->time_end.tv_sec = ntohl(((struct struct_header_v5 *) pptrs->f_header)->unix_secs)-
    ((ntohl(((struct struct_header_v5 *) pptrs->f_header)->SysUptime))/1000)+
    ((ntohl(((struct struct_export_v5 *) pptrs->f_data)->Last))/1000);
```
then it gives us the right times.

**Comment by dsgwork** [comment]
I uploaded my patch at:
https://gist.github.com/dsgwork/b9741a01e7ae23dc933a6447d71abd7b

This needs to be sanity checked by someone more familiar with the codebase.

**Comment by paololucente** [comment]
Dear Davíð, thanks very much for reporting this; your patch makes sense. Can you please generate a PR against master code? Thanks, Paolo

**Comment by dsgwork** [comment]
Hi Paolo, no problem. I created pull request #164 for this work.

**Comment by paololucente** [comment]
Hi Davíð, thanks for your PR. Just merged it and going to close this issue. Thanks again, Paolo
