### ISSUE TITLE
pmacct and AS4 BGP capability issue/bug

### ISSUE THREAD

**Issue by cozonac** [pmacct/pmacct#167]
Hi,

I'm trying to use the bgp_daemon_as feature added in 1.6.2 in order to
do eBGP to pmacct, but the session doesn't go up until I disable AS4
capability on the other end. The other end is BIRD 1.6.3 and while the
AS4 capability is enabled, it complains "BGP Error: Bad peer AS".

Found this by capturing the packets:
Border Gateway Protocol - OPEN Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 73
    Type: OPEN Message (1)
    Version: 4
    My AS: 65533 <--- the configured bgp_daemon_as
    Hold Time: 240
    BGP Identifier: 1.2.3.4
    Optional Parameters Length: 44
    Optional Parameters
[other deleted stuff]
            Capability: Support for 4-octet AS number capability
                Type: Support for 4-octet AS number capability (65)
                Length: 4
                AS Number: 48112 <--- the AS echoed back as for iBGP
[other deleted stuff]

Relevant part of the config (tried both pmacct 1.6.2 and 1.7.0):

pmacctd_as: bgp
bgp_daemon: true
bgp_agent_map: /etc/pmacct/bgp_agent_map
bgp_daemon_ip: ::
bgp_daemon_port: 1790
bgp_daemon_as: 65533

Debug info from pmacct:

INFO ( default/core ): [/etc/pmacct/bgp_agent_map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/bgp_agent_map] map successfully
(re)loaded.
DEBUG ( default/core/BGP ): 1 thread(s) initialized
INFO ( default/core/BGP ): maximum BGP peers allowed: 2
INFO ( default/core/BGP ): waiting for BGP data on :::1790
INFO ( default/core/BGP ): [v6-neighbor-address] BGP peers usage: 1/2
INFO ( default/core/BGP ): [v6-neigh-router-id] Capability:
MultiProtocol [1] AFI [2] SAFI [1]
INFO ( default/core/BGP ): [v6-neigh-router-id] Capability: 4-bytes AS
[41] ASN [48112]
INFO ( default/core/BGP ): [v6-neigh-router-id] BGP_OPEN: Local AS:
65533 Remote AS: 48112 HoldTime: 240
INFO ( default/core/BGP ): [v6-neigh-router-id] BGP_NOTIFICATION
received (2, 2). Shutdown Message: ''
INFO ( default/core/BGP ): [v4-neighbor-address] BGP peers usage: 1/2
INFO ( default/core/BGP ): [v4-neigh-router-id] Capability:
MultiProtocol [1] AFI [1] SAFI [1]
INFO ( default/core/BGP ): [v4-neigh-router-id] Capability: 4-bytes AS
[41] ASN [48112]
INFO ( default/core/BGP ): [v4-neigh-router-id] BGP_OPEN: Local AS:
65533 Remote AS: 48112 HoldTime: 240
INFO ( default/core/BGP ): [v4-neigh-router-id] BGP_NOTIFICATION
received (2, 2). Shutdown Message: ''

**Comment by paololucente** [comment]
Thanks very much Radu for reporting this. The bug was related to multiple capabilities being grouped as part of the same optional parameter in the BGP OPEN. The fix to this issue has been successfully tested against BIRD, Quagga, ExaBGP, Cisco/XR and Juniper. Cheers, Paolo

**Comment by graf3net** [comment]
I can confirm that this bug affected Comware 7, HPE VSR 1000 as well. Thank you very much for the bugfix. Works perfect.
