### ISSUE TITLE
Unknown key: timestamps_rfc3339. Ignored.

### ISSUE THREAD

**Issue by coocla** [pmacct/pmacct#170]
Hi:
    When i started nfacctd daemon,  I ran into this error:
    ` Unknown key: timestamps_rfc3339. Ignored.`

    My Configure:
    `debug: true
syslog: daemon
daemonize: true
timestamps_rfc3339: true

nfacctd_ip: 0.0.0.0
nfacctd_port: 1234
nfacctd_net: netflow`

    My Environment:
    `# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.0-git (20170924-00)

Arguments:
 '--enable-plabel' '--enable-pgsql' '--enable-kafka' '--enable-geoip' '--enable-sqlite3' '--enable-jansson' '--enable-threads' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.4.0
PostgreSQL 90411
sqlite3 3.6.20
rdkafka 0.11.1
jansson 2.9

System:
Linux 2.6.32-642.6.1.el6.x86_64 #1 SMP Wed Oct 5 00:36:12 UTC 2016 x86_64

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.`

**Comment by paololucente** [comment]
Dear @coocla , timestamps_rfc3339 is a feature of pmacct 1.7.1 (which is the code in the master tree here on GitHub) hence it is expected that it's not being recognised if run against 1.7.0 (which is what you are doing, according to the output you posted). Please switch to 1.7.1. Regards, Paolo
