### ISSUE TITLE
nfacctd print_output_file timestamp_start before or in the future

### ISSUE THREAD

**Issue by coocla** [pmacct/pmacct#171]
I found that the value of the timestamp_start of the NetFlow data I collected was later than the current time or the future of the current time.

Example： I receive a data
```
{"event_type": "purge", "peer_ip_src": "172.16.1.1", "peer_ip_dst": "172.16.1.2","iface_in": 52, "iface_out": 17, "ip_src": "192.168.43.28 "port_src": 443, "port_dst": 16991, "tcp_flags": "24", "ip_proto": "tcp", "timestamp_start": "2017-11-28 14:11:25.0", "timestamp_end": "2017-11-28 14:11:25.0", "packets": 1, "bytes": 1458}
{"event_type": "purge", "peer_ip_src": "172.16.1.1", "peer_ip_dst": "172.16.1.2", "iface_in": 18, "iface_out": 17, "ip_src": "192.168.79.131", "ip_dst": "192.168.10.25", "port_src": 5665, "port_dst": 44460, "tcp_flags": "16", "ip_proto": "tcp", "timestamp_start": "2017-11-28 14:11:26.0", "timestamp_end": "2017-11-28 14:11:26.0", "packets": 1, "bytes": 52}
```
my system data:
```
# date +'%Y-%m-%d %H:%M:%S'
2017-11-28 20:31:02
```

I don't know why it's going to happen. Can you help me?

**Comment by paololucente** [comment]
Hi @coocla , timestamp_start and timestamp_end are both populated by the NetFlow exporter (ie. your router) and only decoded by pmacct as strings. Check that the date on your NetFlow exporter is in sync with the one of your collector system. Paolo

**Comment by coocla** [comment]
Thank you very much.
Our network engineer told me that the router time did not synchronize with NTP server。
