### ISSUE TITLE
Compiling with nDPI fails

### ISSUE THREAD

**Issue by vadimtk** [pmacct/pmacct#173]
I am doing (against nDPI 2.2.0)
`./configure --enable-mysql --enable-ndpi`
and make fails with
 
```
Making all in src
make[1]: Entering directory '/home/vadim/pmacct/pmacct/src'
Making all in nfprobe_plugin
make[2]: Entering directory '/home/vadim/pmacct/pmacct/src/nfprobe_plugin'
  CC       libnfprobe_plugin_la-nfprobe_plugin.lo
In file included from /usr/local/include/libndpi-2.2.0/libndpi/ndpi_main.h:30:0,
                 from ./../pmacct.h:93,
                 from common.h:30,
                 from nfprobe_plugin.c:53:
/usr/local/include/libndpi-2.2.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
```

**Comment by paololucente** [comment]
Hi Vadim, i suspect this may rather be something for the nDPI project. Travis does regression against nDPI 2.0 - and that works fine. I tested also 2.1 working fine. Then from 2.2 (and currently in master) ndpi_typedefs.h contains the following:

#ifndef __NDPI_TYPEDEFS_H__
#define __NDPI_TYPEDEFS_H__

#include "ndpi_define.h"
#include "../lib/third_party/include/libcache.h" <---

With such libcache.h header not being installed as part of the building process - which is in the end the complaint above when you go compiling pmacct sources.

Paolo

**Comment by paololucente** [comment]
Dear Vadim, All, the issue being still not resolved, i've added a piece of documentation in QUICKSTART that hope helps people compiling pmacct against nDPI: https://github.com/pmacct/pmacct/commit/edf192ca573d6ac6364775beefd367f3e3ddfa4a
