### ISSUE TITLE
pmacctd does not recognize -v option

### ISSUE THREAD

**Issue by vadimtk** [pmacct/pmacct#174]
https://github.com/pmacct/pmacct/blob/5950dc145996e8c4fce12d5b2e42e8e06ed747f8/sql/README.mysql#L196

**Comment by paololucente** [comment]
Dear Vadim, thanks for reporting this. I've now fixed documentation. The -v switch was removed some time ago since it allowed to configure only one aspect of the SQL tables - with all the others not being exposed via CL options, making it a bit of an exception.
