### ISSUE TITLE
Cannot run trigger scripts due to execv(3) usage

### ISSUE THREAD

**Issue by higgsd** [pmacct/pmacct#180]
I am playing with nfacctd 1.5.3 on OpenBSD and was unable to use the print_trigger_exec feature.  I traced it down to your usage of execv(3).  The args array passed to execv should have the filename as the first element.  On OpenBSD this causes execv to fail with errno=EFAULT.  This bug also applies to sql_trigger_exec.

Example fix:

```
 int P_trigger_exec(char *filename)
 {
-  char *args[1];
+  char *args[2] = { filename, NULL };
   int pid;
-
-  memset(args, 0, sizeof(args));
 
   switch (pid = vfork()) {
   case -1:
```

**Comment by paololucente** [comment]
Hi @higgsd , interesting. Why don't you submit this as a PR rather than issue? So that you are also clearly reckon on GitHub for your code contribution. Paolo

**Comment by higgsd** [comment]
Sorry, I didn't have a diff against 1.7.0 - I just patched my OpenBSD port of 1.5.3.

**Comment by paololucente** [comment]
I see, I will process the patch myself then. While @job can maybe try to make sure the OpenBSD port is updated to a some more current version? Paolo

**Comment by higgsd** [comment]
Looks like @job got the port updated, though I haven't tried it yet.

In the meantime, I made a PR: https://github.com/pmacct/pmacct/pull/181

**Comment by job** [comment]
Your testing is critical! :-)

**Comment by higgsd** [comment]
OK, confirmed that 1.7.0 plus my PR changes works on OpenBSD -current with my trivial config!

```
daemonize: true
syslog: daemon
nfacctd_ip: 127.0.0.1
nfacctd_port: 47399
aggregate: etype,src_host,dst_host,proto,src_port,dst_port,in_iface,out_iface,timestamp_start,timestamp_end
plugins: print
print_refresh_time: 30
print_num_protos: true
print_output: csv
print_output_file: /var/nfacctd/ipfix.csv
print_trigger_exec: /var/nfacctd/nf_to_es.py
```

**Comment by paololucente** [comment]
Fantastic, thanks much @higgsd and @job . Since we now have the PR open for this, i'm safely going to close this issue. Paolo
