### ISSUE TITLE
how to config pmacct output to kafaka or es?

### ISSUE THREAD

**Issue by dashng** [pmacct/pmacct#183]
Hi, All

We output the flows statics to csv files, then run an agent to analytic the file one by one, finally load to es for query.

It takes time to read I/O and seems not adapt to solve big flows scene.

Any suggtions on load to es, kafka or 3rd part cache system, would help us a lot.

Thanks again.

**Comment by paololucente** [comment]
Dear @dashng , to ingest in Kafka you can follow the relevant section of the QUICKSTART guide: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L661-L767 . Paolo
