### ISSUE TITLE
Support Cisco Model Driven Telemetry

### ISSUE THREAD

**Issue by numbnut** [pmacct/pmacct#184]
Hi there,
I try to setup a receiver for Cisco's "new" model driven telemetry and I considered pmacct, but it looks like it only supports  the "older" policy based telemetry. I wanted to ask, whether this is the case and if yes, whether it is on your roadmap or not to support model driven telemetry as well. My experience with cisco telemetry and the gpb format is that it is quite confusing, because of the many different versions (compact, self-describing, model driven, etc.) and the bad documentation. Hope this helps somehow to clarify pmaccts capabilities and maybe add a new feature for the model driven telemetry to the roadmap.
Thank you very much for the great project. I really appreciate it!

Resources:
- An interesting resource is the header of the following telemetry logstash plugin, which describes the different wire formats.  https://github.com/cisco/logstash-codec-bigmuddy-network-telemetry/blob/master/lib/logstash/codecs/telemetry.rb
- Some docs about model driven telemetry. https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/telemetry/b-telemetry-cg-ncs5500-61x/b-telemetry-cg-ncs5500-61x_chapter_011.html
- Some docs about policy based telemetry. https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/telemetry/b-telemetry-cg-ncs5500-61x/b-telemetry-cg-ncs5500-61x_chapter_0101.html
- Cisco telemetry receiver called pipeline. Seems to be not maintained anymore. https://github.com/cisco/bigmuddy-network-telemetry-pipeline
- Cisco proto files to parse the GPB messages. https://github.com/cisco/bigmuddy-network-telemetry-proto

**Comment by remingtonc** [comment]
@numbnut I can clarify some points on here, not related to pmacct however. The MDT tool that is typically being evangelized is still Pipeline as you referenced. The open source code has not been modified but is still functional for IOS-XR releases. Here is a [tutorial](https://xrdocs.github.io/telemetry/tutorials/2017-05-08-pipeline-with-grpc/) on its configuration. There are other tutorials in that site as well to export in to InfluxDB etc. and there will be a comprehensive dCloud demo available in the next several weeks (to months). If you would like to build your own collectors, we have also released some low level [libraries](https://github.com/cisco-grpc-connection-libs) to help enable that workflow.

**Comment by numbnut** [comment]
@remingtonc Thanks for the references. These three gRPC specific libraries are really new to me.

**Comment by remingtonc** [comment]
@numbnut If you have any request for programming language support please reach out.

**Comment by numbnut** [comment]
@remingtonc Thanks for the offer! We are still investigating which telemetry receiver solution to pick. Unfortunately the gRPC libs are most likely not flexible enough, since they only support gRPC.

**Comment by paololucente** [comment]
Dear @numbnut @remingtonc , there are some initial news on this thread. See commit https://github.com/pmacct/pmacct/commit/d30453aade056f43dd0cc4031ecf366e623a97e5 . I'm going to mark this issue as duplicate and close it so that we can continue conversation as part of issue #69 which is broader scope than Cisco & MDT. Paolo
