### ISSUE TITLE
Custom aggregation primitives with bits

### ISSUE THREAD

**Issue by analogic** [pmacct/pmacct#190]
I have simple problem - every our client have ipv6 /60 subnet and there is need to aggregate traffic by that subnets. Very elegant solution (instead of explicitly generating list of networks) would be read first 68 bits of dst/src ip at packet and aggregate accordingly but AFAIK right now it is possible only read bytes, right?

Or am I missing something what would work in same way?

**Comment by analogic** [comment]
Uh I've found networks_mask but no matter what I set it seems that it is not working for ipv6

**Comment by paololucente** [comment]
Hi @analogic, networks_mask could be one solution, yes. Another - finer grained if you have an IPAM - could be to define a networks_file with all your customer ranges (which may allow you in future to do grouping, guess a customer has two /60s or two customers should be handled as one, etc.). I will investigate the issue with networks_mask and come back to you. Paolo

**Comment by analogic** [comment]
my configuration:
```
imt_path[in6]: /tmp/pmacct_in6.pipe
networks_mask[in6]: 60
aggregate[in6]: dst_net
aggregate_filter[in6]: dst net AAAA:AA00:0100::/40 or (vlan and dst net AAAA:AA00:0100::/40)
```

```
# pmacct -s -p /tmp/pmacct_in6.pipe 
DST_NET                                        PACKETS               BYTES
::                                             176003300             330448319743

For a total of: 1 entries
```

networks_file will definitely work but I would rather to avoid dependency on external data source

**Comment by analogic** [comment]
@paololucente thanks! It is working as intended now, closing
