### ISSUE TITLE
IPFIX application name field size

### ISSUE THREAD

**Issue by zamog** [pmacct/pmacct#191]
The current application name field size seems to be 15 char.
Checking the required field size by running "show flow exporter templates details" on Cisco ASR1K (the output attached)
[templates.txt](https://github.com/pmacct/pmacct/files/1911930/templates.txt)

shows the need for 24 bytes/char.
the problem cause wrong statistics for some of application for example Cisco AVC has application names with the same prefix:
13:520  google-services           google-services, set of tools and apis used by google a
13:1061  google-services-audio     Google Services Audio
13:1071  google-services-media     Google Services Media
13:1062  google-services-video     Google Services Video
because the 15 char limit all the above application seems to be "google-services"

**Comment by paololucente** [comment]
Hi Gilad, i just committed a simple patch to address the issue. While simple, i had to do extensive regression to make sure to not break other things. Can you give it a try and confirm it working for you? Thanks, Paolo

**Comment by zamog** [comment]
The issue was fixed and all the application name display correctly
10x !
