### ISSUE TITLE
How to capture ingress VPN traffic 

### ISSUE THREAD

**Issue by zabudskyi** [pmacct/pmacct#193]
Hi. We use strongswan remote VPN. It doesn't have routed interfaces and it uses policy routing. I'm capturing traffic coming from server but how can I capture traffic coming to server with private IPs? 
It seems `post_nat` keys are not my case thing. 
```
{"event_type": "purge", "ip_src": "10.96.0.4", "ip_dst": "185.158.208.11", "post_nat_ip_src": "", "post_nat_ip_dst": "", "stamp_inserted": "2018-04-28 12:45:00", "stamp_updated": "2018-04-28 12:57:52", "packets": 11, "bytes": 1027}
{"event_type": "purge", "ip_src": "10.96.0.4", "ip_dst": "185.158.208.11", "post_nat_ip_src": "", "post_nat_ip_dst": "", "stamp_inserted": "2018-04-28 12:45:00", "stamp_updated": "2018-04-28 12:57:53", "packets": 2, "bytes": 196}
```
Will nflog and `uacctd` help me? 
Is there any `./configure` option I missed to install it?
```
uacctd -f /etc/pmacct/uacctd.conf 
bash: uacctd: command not found
```

**Comment by paololucente** [comment]
Hi @zabudskyi , yes, NFLOG / uacctd may come to the rescue perhaps with the POSTROUTING chain - you will have to test. Probably you will end up needing two instances of uacctd if you need pre- and post- NAT depending on the traffic direction.

You have to use the --enable-nflog switch in order to enable compiling of uacctd. I just realised this is currently not in the QUICKSTART doc, i will add it.

**Comment by zabudskyi** [comment]
Hi, @paololucente 
Thank you for your assistance. 
It seems `iptables -t mangle -I POSTROUTING -j NFLOG --nflog-group 5` and uacctd did the trick. And now I don't even need pmacctd as uacctd deals with interface based VPN as well. 
```
debug: false
daemonize: true
pidfile: /var/run/uacctd.pid
logfile: /var/log/uacctd.log
uacctd_group: 5

plugins: print[in], print[out]
aggregate[in]: dst_host
aggregate[out]: src_host
aggregate_filter[in]: dst net 10.0.0.0/8
aggregate_filter[out]: src net 10.0.0.0/8
timestamps_since_epoch: true 
timestamps_secs: true

print_refresh_time: 1
print_output: json
print_history: 15m
print_output_file[in]: /tmp/traffic_in.json
print_output_file[out]: /tmp/traffic_out.json
print_output_file_append: true
```

**Comment by paololucente** [comment]
Hi @zabudskyi , excellent news, very interesting. And thanks much for having shared your experience and config. Paolo
