### ISSUE TITLE
Real-time streaming : Plugin for Google PubSub 

### ISSUE THREAD

**Issue by sartaj10** [pmacct/pmacct#199]
Hi

The aim of my project is to perform real-time streaming of netflow data. I aim to collect netflow data via pmacct and send that raw data to Google Pub Sub (a fully-managed real-time messaging service that allows you to send and receive messages). Further, the processing would be achieved using the Google Cloud tools.

pmacct has a plugin for kafka / rabbitMQ. I was wondering if there's any work done regarding the integration with Google Cloud tools. If not, what would be the best way to proceed?

Thanks!

**Comment by paololucente** [comment]
Hi @sartaj10 , i can confirm there are no actual plans to build a plugin to integrate Google Cloud tools - of course i'd not oppose if one is written and contributed back for the community to benefit. Rationale being the several cloud vendors out there (ie. Google, AWS, Microsoft come to mind) and the impact of supporting one but not the other(s) or the effort involved to support them all (for a definition of all, of course). Paolo

**Comment by paololucente** [comment]
Hi @sartaj10 , i would recommend to write a new plugin using existing ones as example. All should be required is to replace calls of one API with those of a different one. Paolo
