### ISSUE TITLE
Is there any way to acquire sender IPs from output directly, without resorting to pre_tag_map?

### ISSUE THREAD

**Issue by withzestmn** [pmacct/pmacct#202]
Hello, 
Thank you for the great tool above all.
I've used pmacct for networking usage statistics.

I use pre_tag_map function to know sender IPs.
But, pre_tag_map management has been difficult as sender servers have been scaled up.

If sender IP is shown as output, I don't need to manage pre_tag_map.
Is there any way to acquire sender IPs from output directly, without resorting to pre_tag_map?

Thank you!

**Comment by paololucente** [comment]
Hi @withzestmn , are you using NetFlow/IPFIX or sFlow? And for sender IP you mean the IP address of the device exporting to pmacct? If so, sure, you can use the peer_src_ip primitive on your 'aggregate' line instead of the pre_tag_map. Paolo
