### ISSUE TITLE
Cisco ASA | v9 Flow - Flows/Packets/Bytes Columns are not coming

### ISSUE THREAD

**Issue by adhamelia** [pmacct/pmacct#205]
Hi @paololucente 

I have installed latest  NetFlow Accounting Daemon, nfacctd 1.7.2-git (20180606-00)
having fix of #182. Now if i use a memory plugin for debugging purpose then everything works fine but i use a print plugin then  Flows/Packets/Bytes Columns are not coming in the output file.

does it sound weird ??? 

Please find the sample output 

{"event_type": "purge", "tag": 1, "peer_ip_src": "192.168.10.1", "iface_in": 15, "iface_out": 8, "ip_src": "10.23.7.132", "ip_dst": "172.217.166.46", "port_src": 59913, "port_dst": 443, "ip_proto": 6, "sampling_rate": 0, "timestamp_start": "2018-06-07 14:31:47.220000", "timestamp_end": "1970-01-01 05:30:00.0", "export_proto_version": 9, "stamp_inserted": "2018-06-07 14:31:00", "stamp_updated": "2018-06-07 14:32:01"}
{"event_type": "purge", "tag": 1, "peer_ip_src": "192.168.10.1", "iface_in": 15, "iface_out": 9, "ip_src": "192.168.116.103", "ip_dst": "216.58.197.70", "port_src": 42537, "port_dst": 443, "ip_proto": 6, "sampling_rate": 0, "timestamp_start": "2018-06-07 14:31:23.619000", "timestamp_end": "1970-01-01 05:30:00.0", "export_proto_version": 9, "stamp_inserted": "2018-06-07 14:31:00", "stamp_updated": "2018-06-07 14:32:01"}
{"event_type": "purge", "tag": 1, "peer_ip_src": "192.168.10.1", "iface_in": 15, "iface_out": 9, "ip_src": "192.168.116.103", "ip_dst": "216.58.197.70", "port_src": 42537, "port_dst": 443, "ip_proto": 6, "sampling_rate": 0, "timestamp_start": "2018-06-07 13:27:09.408000", "timestamp_end": "1970-01-01 05:30:00.0", "export_proto_version": 9, "stamp_inserted": "2018-06-07 13:27:00", "stamp_updated": "2018-06-07 14:32:01"}
{"event_type": "purge", "tag": 1, "peer_ip_src": "192.168.10.1", "iface_in": 15, "iface_out": 8, "ip_src": "192.168.10.91", "ip_dst": "123.108.200.124", "port_src": 123, "port_dst": 123, "ip_proto": 17, "sampling_rate": 0, "timestamp_start": "2018-06-07 14:30:47.128000", "timestamp_end": "1970-01-01 05:30:00.0", "export_proto_version": 9, "stamp_inserted": "2018-06-07 14:30:00", "stamp_updated": "2018-06-07 14:32:01"}
{

nfacctd.conf 

plugins: print[NetFlow]
nfacctd_port:2055
aggregate[NetFlow]: src_host,dst_host,peer_src_ip, in_iface, out_iface, src_port, dst_port, proto,sampling_rate,export_proto_version,timestamp_start,timestamp_end,flows,tag
print_output_file[NetFlow]: NetFlow
print_output[NetFlow]: json
print_history[NetFlow]: 1m
print_history_roundoff[NetFlow]: m
print_refresh_time[NetFlow]: 60
print_num_protos: true
tmp_asa_bi_flow[NetFlow]: true

**Comment by paololucente** [comment]
Dear @adhamelia , thanks very much for getting in touch. This should be a bug and should be fixed by the code just committed - can you please give it a try and confirm it working for you? Thanks, Paolo

**Comment by adhamelia** [comment]
Thanks @paololucente  for the quick turn around :).

the fix is working now.
