### ISSUE TITLE
Filter for tee plugin

### ISSUE THREAD

**Issue by Gabalino** [pmacct/pmacct#207]
Hello!
I plan to replicate ipfix into mysql plugin and into another system, it needs to send packets concerning a particular network. Tell me, how in the tee plug-in filter out the data on the network source for a specific receiver?

**Comment by paololucente** [comment]
Hi @Gabalino , with code in master there are possibilities to do so (NetFlow/IPFIX catching up on this equivalent feature already existing for a while for sFlow). In short, this involves breaking an incoming IPFIX packet in singular flows and sending over to the recipient only those matching some criteria. How can you identify what you called "the network source"? For example: input and output interfaces, VLANs, source and destination MAC addresses and BGP next-hop are already all supported: would any of these help in your use-case? Source and destination IP addresses/prefixes are not supported (yet). Paolo

**Comment by Gabalino** [comment]
Hi @paololucente, there are several IP pools for NAT, I need to mirror the packets with src_host from the network 10.x.0.0/16.

**Comment by paololucente** [comment]
Hi @Gabalino , clear. As i was saying this is not supported today. I will mark this issue as an enhancement and will try to squeeze a small dev throughout the upcoming week. Paolo

**Comment by paololucente** [comment]
Hi @Gabalino , there is now some code in place for this. Please give it a try if you have a moment. Following a basic configuration for testing:

nfacctd_port: 2100
!
plugins: tee[foo]
!
tee_transparent: true
!
pre_tag_map[foo]: /path/to/tee_pretag.map
tee_receivers[foo]: /path/to/tee_receivers.lst

tee_pretag.map:
set_tag=100     ip=x.x.x.x        src_net=10.x.0.0/16
set_tag=100     ip=x.x.x.x        dst_net=10.x.0.0/16

tee_receivers.lst
id=1 ip=y.y.y.y:zzzz    tag=100

Paolo

**Comment by Gabalino** [comment]
Hi @paololucente, I checked, it works. Many thanks to you for such a wonderful project and operative response!

**Comment by paololucente** [comment]
Hi @Gabalino , wonderful, thank you for confirming. Paolo
