### ISSUE TITLE
timestamp_arrived fails to work for sfacctd

### ISSUE THREAD

**Issue by Jhors2** [pmacct/pmacct#21]
I am using a really basic configuration and trying to use the timestamp_arrived primitive.  It always produces a 0 value, either the start of epoch time or "0.0" if epoch timestamp is desired.  This only seems to happen with sfacctd.  Previously I was using timestamp_start in 1.5.2 and I do not see any issues with that aggregation primitive.

**Comment by paololucente** [comment]
Hi Jerred,

In 1.6.0 there has been already a fix around timestamp_arrival, see: https://github.com/pmacct/pmacct/commit/b733eb4f5cc4da733563da07e230775436bce955

Can you give a try to code in master and let me know if it works for you?

Cheers,
Paolo

**Comment by Jhors2** [comment]
Seems to be fixed!
Thanks
