### ISSUE TITLE
pmacct on Debian Stretch as Netflow probe - Multiple interfaces?

### ISSUE THREAD

**Issue by ph278** [pmacct/pmacct#211]
Hello,

i have installed pmacct on Debian Stretch using the [debian package](https://packages.debian.org/stretch/pmacct) to use it as a netflow probe.

But how can i configure pmacct to send netflow data for multiple interfaces? I've seen the INTERFACES option in the default file but it seems like that is deprecated ("SUPPORT FOR INTERFACES="" WAS REMOVED FROM THE INIT SCRIPT.")

Can anyone help me out?

Thanks!

**Comment by paololucente** [comment]
Hi @ph278 , the debian package is version 1.6.1 and that does not contain the feature. You can download latest stable, 1.7.1, from http://www.pmacct.net and compile, install and take advantage of the feature. Here you have a simple configuration snippet on how to configure it: https://github.com/pmacct/pmacct/blob/1.7.1/QUICKSTART#L387-L404

**Comment by ph278** [comment]
Hi @paololucente, thanks for your reply.

I've downloaded the Version 1.7.1 and tried to install it on a Debian Stretch with these steps:
**1. ./configure**
[Output on Gist](https://gist.github.com/ph278/11643e5f0f2f9b0b2bcd69c6b24406a4)
**2. make**
[Output on Gist](https://gist.github.com/ph278/d763e71c4260c7e073ee9c1c752edf9d)
**3. make check**
[Output on Gist](https://gist.github.com/ph278/9629e5c91160da4c45046dd90a2a88cb)
**4. make install**
[Output on Gist](https://gist.github.com/ph278/7e462ddf038424c14efcf9ca6bbbe676)

But after that pmacct not seemed to be installed, because /etc/pmacct and a init script does not exist.
When i try to run pmacct i get:
`ERROR: Unable to connect to '/tmp/collect.pipe'`

I've installed the packages build-essential and libpcap0.8-dev before compiling.

Is there anything I'm doing wrong?

Thank you!
