### ISSUE TITLE
 Discarded NetFlow v9/IPFIX packet (unkown template)

### ISSUE THREAD

**Issue by diyon4** [pmacct/pmacct#212]
Hello, 
I'm trying to get Netflow v9 packets to be processed and pumped into my mysql server. Unfortunately my Netflow template is not recognized? 

DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x.x.x.x:xxxx] version [9] seqno [816]
DEBUG ( default/core ): Discarded NetFlow v9/IPFIX packet (R: unknown template 256 [x.x.x.x:xxxx])

**Comment by paololucente** [comment]
Hi @diyon4 , is this issue lasting for long? The above is normal for the way NetfFlow v9/IPFIX template-based protocols work. Your router sends templates periodically and, once received by the collector, actual data can be decoded. Perhaps on your router you want to shorten the interval period with which templates are sent over. Paolo

**Comment by diyon4** [comment]
Hi Paolo,

I followed your recommendations and nfacctd was able to decode the template:

DEBUG ( default/core ): Received NetFlow/IPFIX packet from [X.X.X.X:XXXX] version [9] seqno [48890]
DEBUG ( default/core ): NfV9 agent         : X.X.X.X:XXXX
DEBUG ( default/core ): NfV9 template type : flow
DEBUG ( default/core ): NfV9 template ID   : 273
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
DEBUG ( default/core ): | 0          | IPv4 src addr      [8    ] |      0 |      4 |
DEBUG ( default/core ): | 0          | IPv4 dst addr      [12   ] |      4 |      4 |
DEBUG ( default/core ): | 0          | input snmp         [10   ] |      8 |      4 |
DEBUG ( default/core ): | 0          | 243                [243  ] |     12 |      2 |
DEBUG ( default/core ): | 0          | 254                [254  ] |     14 |      2 |
DEBUG ( default/core ): | 0          | L4 protocol        [4    ] |     16 |      1 |
DEBUG ( default/core ): | 0          | L4 src port        [7    ] |     17 |      2 |
DEBUG ( default/core ): | 0          | L4 dst port        [11   ] |     19 |      2 |
DEBUG ( default/core ): | 0          | 182                [182  ] |     21 |      2 |
DEBUG ( default/core ): | 0          | 183                [183  ] |     23 |      2 |
DEBUG ( default/core ): | 0          | 180                [180  ] |     25 |      2 |
DEBUG ( default/core ): | 0          | 181                [181  ] |     27 |      2 |
DEBUG ( default/core ): | 0          | first switched     [22   ] |     29 |      4 |
DEBUG ( default/core ): | 0          | last switched      [21   ] |     33 |      4 |
DEBUG ( default/core ): | 0          | in bytes           [1    ] |     37 |      8 |
DEBUG ( default/core ): | 0          | in packets         [2    ] |     45 |      8 |
DEBUG ( default/core ): | 0          | 85                 [85   ] |     53 |      8 |
DEBUG ( default/core ): | 0          | 86                 [86   ] |     61 |      8 |
DEBUG ( default/core ): -------------------------------------------------------------

Unfortunately the only thing it is identifying is the source/dest ipv4 add and the in bytes/packets.

DEBUG ( default_mysql/mysql ): INSERT INTO `acct_v2` (stamp_updated, stamp_inserted, vlan, ip_src, ip_dst, src_port, dst_port, ip_proto, agent_id, mac_src, mac_dst, packets, bytes) VALUES (FROM_UNIXTIME(1531852406), FROM_UNIXTIME(1531852200), 0, 'X.X.X.X', 'X.X.X.X', 0, 0, '0', 0, '0:0:0:0:0:0', '0:0:0:0:0:0', 1, 68)

I was hoping to get the vlan and port information as well. 


Thanks.

**Comment by paololucente** [comment]
Hi @diyon4 , as far as i can see the VLAN info (element 58 and 59) is not present in your NetFlow v9 message. If you are crafting the NetFlow content yourself (ie. a Flexible NetFlow platform), then you should add it; otherwise not much can be done. I'm proceeding to close this issue for now. Paolo
