### ISSUE TITLE
Formatting of microseconds in epoch timestamps

### ISSUE THREAD

**Issue by raymondrussell** [pmacct/pmacct#216]
Hi Paulo, I noticed that the microseconds field in epoch timestamps is not zero-padded.  For example, one millisecond past midnight UTC on 2018 August 1 gets rendered as "1533081600.1000"  The tools I'm using to parse the JSON output interpret this essentially as a floating point number, and end up reading it as 100ms past midnight.

Is this intentional?  If not, I can provide a patch that suggests how they might be zero-padded;  there are just four lines I've found that print the tv_usec field of timevals, two each in src/pmacct.c and in src/util.c.  Thanks, Raymond.

**Comment by paololucente** [comment]
Hi @raymondrussell , interesting and let me confirm this is not intentional. I'd look to your patch for this. Thanks, Paolo

**Comment by raymondrussell** [comment]
Sure - I've put the patch here:  https://gist.github.com/raymondrussell/8f58a3244385cd3fdeada9321437b2c3
Actually that includes another minor change: since both timeval members are signed longs on Linux, I've also taken the liberty of changing the %u spec to %ld.  Many thanks, Raymond.

**Comment by paololucente** [comment]
Hi Raymond, the patch looks good. How about we close this issue and you submit the patch via a PR to the master code? This would have the added benefit of correctly attributing the code to you. Paolo

**Comment by raymondrussell** [comment]
Hi Paulo, I'm sorry it took me so long to get around to doing that.  I've just created a pull request, let me know if you have any problems with it.  Many thanks for your quick responses on this query!  Raymond.
