### ISSUE TITLE
nfacctd gets crashed or stopped after 10-15 mins

### ISSUE THREAD

**Issue by adhamelia** [pmacct/pmacct#218]
Hey @paololucente 

I have been encountering a strange issue in one of my servers.  nfacctd process behaves weird while processing  NetFlow v5.

The  process runs for 10 -15 mins then it gets stopped working with following WARN

**nfacctd: plugin_common.c:442: P_cache_insert: Assertion `!cache_ptr->stitch' failed.**

The issue is random, it gets replicated on 2 servers and remaining works fine.

Any Guess ???

Syslog:

Aug 13 11:23:58 ubuntu kernel: [226577.973260] nfacctd[19533]: segfault at 7f24f903a330 ip 000000000046c6c4 sp 00007fff4e9bc8f0 error 6 in nfacctd[400000+fe000]
Aug 10 22:25:53 ubuntu kernel: [ 7093.181137] nfacctd[20657]: segfault at 7f08acfe4330 ip 000000000046c6c4 sp 00007ffd66792a60 error 6 in nfacctd[400000+fe000]
Aug 10 22:25:53 ubuntu kernel: [ 7093.181137] nfacctd[20657]: segfault at 7f08acfe4330 ip 000000000046c6c4 sp 00007ffd66792a60 error 6 in nfacctd[400000+fe000]

**Comment by paololucente** [comment]
Hi @adhamelia , can you please share your config and the version you are running (nfacctd -V)?

**Comment by adhamelia** [comment]
the latest 1.7.2 20180812

**Comment by paololucente** [comment]
Thanks. Still need the config.

**Comment by adhamelia** [comment]
plugins: print[NetFlow]
nfacctd_port:9996
snaplen: 65535
aggregate[NetFlow]: src_host,dst_host,peer_src_ip, in_iface, out_iface, src_port, dst_port, proto,sampling_rate,export_proto_version,timestamp_start,timestamp_end,flows,tag
print_output_file[NetFlow]: NetFlow
print_output[NetFlow]: json
print_history[NetFlow]: 1m
print_history_roundoff[NetFlow]: m
print_refresh_time[NetFlow]: 60
print_num_protos: true
pre_tag_map: /motadata/motadata/tag.rule

**Comment by adhamelia** [comment]
@paololucente  it works fine for v9 but v5 has some issues... any idea ???

**Comment by paololucente** [comment]
Got a second report of this issue. While a root cause could not be identified yet, it appears increasing print_cache_entries helps making the issue go away. Labelling this as workaround.

**Comment by adhamelia** [comment]
Yes @paololucente  I observed that when we forward flows and it takes more 30 mins to aggregate the flows it self. most of time exe gets crashed without processing any flows despite of running 30+ mins.

So, ideally what should be print_cache_entries size for temporary workaround ??? do you think so that would work ???

**Comment by paololucente** [comment]
Hi @adhamelia , not sure. It seemed to have worked for another user - please give it a try yourself, if you are still affected. I am myself unable to reproduce the issue (nor i have access to a system with the issue) so i can't establish a root cause.

**Comment by adhamelia** [comment]
@paololucente  can have a fix ??? what do you require from our side to fix the issue ??? we can provide the details like PCAP something.

**Comment by paololucente** [comment]
Hi @adhamelia , since i'm unable to reproduce the issue (i did try to let the daemon run for 30+ mins with your very same config) the ideal situation would be if i could get access to the box where the issue is arising - would that be possible? If not, we'll have to think to something else.

**Comment by adhamelia** [comment]
@paololucente  Thanks man !!! the work around rocks  :) :+1:
