### ISSUE TITLE
wrong classification with ndpi

### ISSUE THREAD

**Issue by rsolsn** [pmacct/pmacct#222]
We have some installations of pmacct 1.7.0 with ndpi 2.0 going fine since some months.

Starting from june we see that some packets classified correctly by ndpi (teamviewer) are classified as unknown/unknown in pmacct using plugin nfprobe,mysql.

We updated to pmacct 1.7.1 with nfdpi 2.2 and 2.4 thinking some changes on teamviewer protocol but with no results.

What sounds even more strange to me is that running: 
pmacctd -P print -r 5 -i eth0 -c class
It prints some packets classified correctly as teamviewer packets.

But changing in
pmacctd -P print -r 5 -i eth0 -c class, src_host,dst_host
Again are classified as unknown.

Adding sql_aggressive_classification to the config gives us this
WARN: [/etc/pmaccd.conf:25] Unknown key: sql_aggressive_classification. Ignored.

Any help appreciated 
Regards
Alessandro

**Comment by paololucente** [comment]
Hi Alessandro,

I was wondering: before updating to 1.7.1 and nDPI 2.2/2.4 things already started to be classified as unknown, true? Like, what was working fine at some point did start not working fine anymore - or did i get you wrong? If i got it correct, did anything change in your (pmacct) config or capturing infrastructure in the meanwhile?

I will try to do some testing at my end but i guess what may help is if you can provide me a capture of some of the mis-classified traffic by unicast email. On a separate note, i can confirm that  the sql_aggressive_classification knob does not apply to nDPI classification (and will be retired soon).

Paolo

**Comment by rsolsn** [comment]
Hi Paolo,
i'm going on on analysing this problem and i've done a couple of step forward.

What i wrote 2 days ago it's not completely true, in sense that pmacct/ndpi with sql plugin began, starting from june (i think), to classify teamviewer traffic from "SSL/Teamviewer" to "Unknown/Teamviewer".
The column class on my db was defined as char(16) and, as you can guess is too small to hold this string; so that's why those lines were not stored on db, giving me the false sensation there was a problem on pmacct or ndpi, because they disappeared.
This morning, resizing the column class to char(32) on db, solved this problem and the teamviewer traffic reapperared on db, as "Unknown/Teamviewer".

What i'm working on now, is to understand if the very high number of rows that are stored on db from pmacct classified as Unknown/Unknown 10-15% of all traffic that firewall handle, are classified in this way from ndpi or pmacct.
Trying to do this with some scripts using ndpireader like a tcpdump.....

I'll let you know.


Thx 
alessandro

**Comment by paololucente** [comment]
Hi Alessandro,

Thanks for the update, very much appreciated. And i'm definitely interested in the outcome of your troubleshooting effort.

Paolo

**Comment by rsolsn** [comment]
Hi Paolo, 
here is an update of what i've seen.

I confirm that ndpi sees less unkown traffic but what i see, going on as an example with teamviewer class, is that some traffic that ndpireader classify as teamviewer pmacct can classify in part as teamviewer and in part or totally as unknown.

Here an example of teamviewer traffic from one particular ip, one output come from the command  : 
ndpiReader -m 5 -i eth0 -v 2

        745     TCP 172.19.119.4:61617 <-> 213.227.186.138:5938 [proto: 148/TeamViewer][2 pkts/138 bytes <-> 1 pkts/78 bytes]
        1566    TCP 172.19.119.4:61617 <-> 213.227.186.138:5938 [proto: 148/TeamViewer][1 pkts/78 bytes <-> 1 pkts/54 bytes]

the other from command :
pmacctd -P print -r 30 -i eth0 -c timestamp_arrival,class,src_host,dst_host,src_port,dst_port -O csv -o /tmp/printdump.txt

Unknown/Unknown,172.19.119.4,213.227.186.138,61617,5938,2018-08-28 11:23:21.609510,1,64
Unknown/Unknown,213.227.186.138,172.19.119.4,5938,61617,2018-08-28 11:23:21.670857,1,64
Unknown/Unknown,172.19.119.4,213.227.186.138,61617,5938,2018-08-28 11:23:21.871419,1,40
Unknown/Unknown,172.19.119.4,213.227.186.138,61617,5938,2018-08-28 11:23:26.671830,1,64
Unknown/Unknown,213.227.186.138,172.19.119.4,5938,61617,2018-08-28 11:23:26.793281,1,40


In this case pmacct doesn't recognise the class.



Regards
alessandro

**Comment by paololucente** [comment]
Hi Alessandro,

Thanks for the troubleshooting. We should then progress to getting me a trace in libpcap format of some sample traffic. Once we are looking at the same packets and i'm able to reproduce the issue at my end, i can check the code.

Paolo

**Comment by rsolsn** [comment]
Paolo ,
you can find the pcap dumpfile here 
https://drive.google.com/file/d/17h1rvonTepKl21X8yVAotFHhIUv13M_N/view

With this dumpfile you can see the result from ndpi :
#1: ndpiReader -m 5 -i /root/sniff.pcap -v 2   | grep -i teamv | grep 172.19.119
#2:ndpiReader -m 5 -i /root/sniff.pcap -v 2   | grep -i ":5938 "

and from pmacct:
#1: pmacctd -P print  -c class,src_host,dst_host,src_port,dst_port -I /root/sniff.pcap   | grep 172.19.119.3
#2:pmacctd -P print  -c class,src_host,dst_host,src_port,dst_port -I /root/sniff.pcap   | grep " 5938 "


thx
alessandro

**Comment by paololucente** [comment]
Thank you, got the file. Please allow me some time to investigate and get back to you. Paolo

**Comment by paololucente** [comment]
Hi Alessandro,

I don't have a conclusive answer yet, but i spent a bit of time already to investigate the issue. I've tried a few settings given the available configuration knobs and i got the best results, ie. 30% more traffic is classified, with these:

classifier_num_roots: 5120000
classifier_giveup_proto_tcp: 5
classifier_giveup_proto_udp: 3
classifier_giveup_proto_other: 3

Can you please give them a try and share your thoughts? It would be great if you can confirm whether things look generally better or not and, taking a specific sample like the TeamViewer traffic, how things compare against ndpiReader.

This all said, there are for sure two odd things: 1) why more traffic is classified by lowering the give-up classification threshold? It is counter-intuitive; 2) how a greater amount of classifier_num_roots benefits classification. To answer these, i have still a bit of digging to do through the code. Keep you posted.

Paolo

**Comment by rsolsn** [comment]
Hi Paolo,
i've done some more tests, adding your suggested knobs to the config file and then trying to change them to see how it reflects on number of class detected and on the distributions of the number of rows with that class.

So the work done is this:
- collected a pcap file with tcpdump
- executed ndpireader on pcap file to count the number of class and distribution of class detected 
- changed the config knob a running a "benchmark script" for pmacct on pcap file

Here attached you will find the results of various runs of pmacct script and ndpi single execution.

[ndpiresult.txt](https://github.com/pmacct/pmacct/files/2360287/ndpiresult.txt)
[pmacctresult.txt](https://github.com/pmacct/pmacct/files/2360288/pmacctresult.txt)

 
alessandro

**Comment by rsolsn** [comment]
Hi Paolo,
after reading some docs in nDPI project, adding these lines to ndpi_util.c

30 struct pm_ndpi_workflow *pm_ndpi_workflow_init()
 31 {
+++++ 32   NDPI_PROTOCOL_BITMASK all;
 77
 +78   // enable all protocols
 +79   NDPI_BITMASK_SET_ALL(all);
 +80   ndpi_set_protocol_detection_bitmask2(workflow->ndpi_struct, &all);
81   return workflow;
82 }

And these settings in pmacc conf file:
classifier_proto_guess          : true
classifier_num_roots            : 4096
classifier_giveup_proto_tcp     : 1
classifier_giveup_proto_udp     : 1
classifier_giveup_proto_other   : 1

I'm passed to an average gf 15-18% of unknown/unknown flows to 4-7%.


Regards.
alessandro

**Comment by paololucente** [comment]
Hi Alessandro,

Thank you very much for this - the investigation and, even more importantly, sharing back the results.

I'd have two asks for you: 1) how does the resulting 4-7% compare with ndpiUtil? Is it in line with it or are you under the impression more work is needed? 2) would you mind submitting the patch via a Pull Request? I can of course take the lines in the code myself but it would be very nice that you are directly reckon for the patch.

Paolo

**Comment by rsolsn** [comment]
Hi Paolo,

i submitted the pull request, i hope this time correctly.

About what you asked to me  

> 1) how does the resulting 4-7% compare with ndpiUtil? Is it in line with it or are you under the impression more work is needed?

i will share with you my further analysis results.


regards 
alessandro

**Comment by paololucente** [comment]
Hi Alessandro,

Yes - thanks for the Pull Request. I just merged it. Thanks for sharing your further analysis results, look forward to them.

Paolo

**Comment by rsolsn** [comment]
Hi Paolo,
sorry in late answer.

I don’t have any further notice, for now.
Probably i have to work in next weeks again with ndpi  and if needed i will give you feedback in case of problems.


Thanks 
alessandro

**Comment by paololucente** [comment]
Thank you Alessandro. I will then go ahead and close this issue. We can re-open it at a later stage if there are news. Paolo
