### ISSUE TITLE
error compiling pmacct with ndpi 

### ISSUE THREAD

**Issue by rsolsn** [pmacct/pmacct#223]
I'm trying to compile pmacct with ndpi, both cloned from github (ndpi2.4 stable has a problem that doesn't create .so lib. Solved on 2.5 on GitHub):

Compile flags are these 
export NDPI_LIBS="-L/usr/local/src/nDPI/src/lib"
export NDPI_CFLAGS="-I/usr/local/src/nDPI/src/include"

Tried with both these:
./configure --enable-ndpi --with-ndpi-static-lib=/usr/local/src/nDPI/src/lib --enable-mysql
./configure --enable-ndpi --enable-mysql

With this result when doing make:

gmake[2]: Entering directory `/usr/local/src/pmacct/src/ndpi'
  CC       ndpi_util.lo
ndpi_util.c: In function 'pm_ndpi_export_proto_to_class':
ndpi_util.c:87:70: error: dereferencing pointer to incomplete type
   class_st_sz = sizeof(struct pkt_classifier) * workflow->ndpi_struct->ndpi_num_supported_protocols;
                                                                      ^
ndpi_util.c:91:50: error: dereferencing pointer to incomplete type
   for (idx = 0; idx < (int) workflow->ndpi_struct->ndpi_num_supported_protocols; idx++) {
                                                  ^
ndpi_util.c:92:30: error: dereferencing pointer to incomplete type
     if (workflow->ndpi_struct->proto_defaults[idx].protoId) {
                              ^
ndpi_util.c:94:37: error: dereferencing pointer to incomplete type
       css.id = workflow->ndpi_struct->proto_defaults[idx].protoId;
                                     ^
In file included from /usr/include/string.h:633:0,
                 from ../pmacct.h:36,
                 from ndpi_util.c:25:
ndpi_util.c:95:50: error: dereferencing pointer to incomplete type
       strncpy(css.protocol, workflow->ndpi_struct->proto_defaults[idx].protoName, MAX_PROTOCOL_LEN);
                                                  ^
gmake[2]: *** [ndpi_util.lo] Error 1
gmake[2]: Leaving directory `/usr/local/src/pmacct/src/ndpi'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/usr/local/src/pmacct/src'

**Comment by paololucente** [comment]
Hi Alessandro, i've just committed a fix. It seems some new definition was introduced and it is now required in order to compile properly against nDPI master/2.5 code. "At least it compiles", hence i'm going to close this issue. Thanks, Paolo
