### ISSUE TITLE
[sfacctd] Support vxlan?

### ISSUE THREAD

**Issue by withzest** [pmacct/pmacct#224]
Hello~!
I want to analyze sFlow data encapsuling by vxlan.
I can't find vxlan support on this pmacct document. 
I thought that the tunneled aggregation items(unnel_src_host, tunnel_dst_host, tunnel_proto, tunnel_tos) were related to vxlan.
But, I can't see anything. Could you some guide to me for vxlan?

Thanks.

**Comment by paololucente** [comment]
Hi @withzest , i can confirm VXLAN is not currently supported. If you could send me some sample data by unicast email, i can see what it is possible to do. Paolo

**Comment by withzest** [comment]
@paololucente , Thanks for your reply.
I have a text file by sflowtool.
If you want to the other type,  could you tell me how to get sample data?

**Comment by jackson-tim** [comment]
I too would be interested in VXLAN primitives being exposed.. Particularly the ability to extract the VNI and use the encapsulated information inside for the source/dest mac/ip/port/proto, etc. I can send you an additional sFlow capture with vxlan encapsulted samples.

**Comment by paololucente** [comment]
Hi @withzest , @jackson-tim ,

This is basically done. There is a new 'vxlan' primitive to capture VNI. Existing tunnel primitives are wired to VXLAN tunnels and new ones (as per @jackson-tim request) were made. Full list of currently supported tunnel primitives is: tunnel_src_mac, tunnel_dst_mac, tunnel_src_host, tunnel_dst_host, tunnel_proto, tunnel_tos, tunnel_src_port, tunnel_dst_port. I am going to close this feature request, please open new issues for bug reports.

Paolo
