### ISSUE TITLE
pmacctd - strip fabricpath header

### ISSUE THREAD

**Issue by sclark46** [pmacct/pmacct#226]
Cisco Nexus switches can encapsulate standard ip frames in a fabricpath header (type 0x8903). This preclude nfaccd nfprobe from reporting the netfow information contained in the encapsulated packet.

**Comment by paololucente** [comment]
Hi Steve, thanks for opening this for tracking this work. I will label this as enhancement, support for CFP. I will look into it soon. Paolo

**Comment by sclark46** [comment]
I made the following change to 1.6.2 and it seems to be working for us. It is pretty hacky.
$ diff nl.c.new nl.c
42d41
< #include "network.h"
50,51d48
<   struct ether_header *eth_header;
<   int offset = 0;
53,54d49
<   eth_header = (struct ether_header *) buf;
<   
60,65d54
<     if (ntohs(eth_header->ether_type) == 0x8903 )
<     {
<         offset = 20;
<  //       Log(LOG_INFO, "INFO ( %s/core ): packet read 0x8903 CFP\n",config.name );
<     }
<          
67c56
<     pptrs.packet_ptr = (u_char *) buf + offset;
---
>     pptrs.packet_ptr = (u_char *) buf;

**Comment by sclark46** [comment]
#include "network.h" should be
#include <net/ethernet.h>

**Comment by paololucente** [comment]
Hi Steve ( @sclark46 ), thank you very much for this. I was wondering: coding this in the pcap_cb() in nl.c assumes an ethernet header (bad!); coding this in eth_handler() in ll.c would correctly enable the feature to only for ethernet packets (what we want!): did you try this approach and it did not work for you? If not, any chance you could give it a try moving the code around? If all works out i can beautify it and move to master code. Thanks, Paolo

**Comment by sclark46** [comment]
Hi Paolo, no I didn't. But will certainly look at testing the code there. It should really check for CFP then look at +16 bytes to see if it is 1.q then +4 or if it is an ethernet frame. Since all the packets I saw in testing were 1.q after the CFP I just indexed +20 bytes, a real hack.

**Comment by paololucente** [comment]
Hi Steve, the patch is perfect for inclusion in the master branch - great work, thank you very much! I always recommend that authors of code are reckon for their work and hence would prefer you to do a pull request; if you instead prefer not to spend time with that, i'd understand, i'd patch master code myself and credit you in the commit description. Just let me know what you prefer. Paolo

**Comment by sclark46** [comment]
Hi Paolo, I would have go thru a learning experience to do the pull, etc. If you could just do the patch and credit me that would be fine.

**Comment by paololucente** [comment]
Hi Steve, sure will do and close this issue. Thanks again. Paolo

**Comment by paololucente** [comment]
Done! Closing this issue. @sclark46 , i'd appreciate very much if you could do a final round of testing and say whether anything is wrong. Paolo

**Comment by sclark46** [comment]
I'll test it next week.

**Comment by sclark46** [comment]
Hi Paolo,
I tested the master branch and the results looked good.
