### ISSUE TITLE
pipe capacity is too small

### ISSUE THREAD

**Issue by jushao** [pmacct/pmacct#227]
Hi paololucente. When I use nfacctd to get netflow data, I use plugins 'memory' to save the data in 'pmacct_in.pipe'. But pipe capacity is too small, my netflow data is quickly filled with pipe. There will be some data loss at this time. How to solve this problem？

**Comment by paololucente** [comment]
Hi @jushao, which pipe do you refer to? Do you have a log message? Is it the one between core process and plugin or between plugin and the client tool? Paolo
