### ISSUE TITLE
How to get source ip address string before insert statement in MySQL

### ISSUE THREAD

**Issue by Mehul2802** [pmacct/pmacct#23]
Hi,

I have added a new column in mysql as per my requirement.

I want to get Source IP address before Insert query is executed in MySQL.
Then, I will lookup for new column value from source IP adress. I need to append this value in Insert statement.
  
How to get source IP address from callback handlers ?

Regards,
Mehul

**Comment by paololucente** [comment]
Hi Mehul,

You mean you have a separate lookup table, say, mapping IP addresses to host names. And upon insert of IP accounting data from pmacct, somehow trigger a lookup so to link host names to flows? Or something around these lines?

**Comment by Mehul2802** [comment]
Hi Paololucente,

I want to get some id from source ip address. I have built custom API to get id from IP address.

However, I want to get source ip address string before INSERT query of MySQL. So, I can pass that string my custom API.

Regards,
Mehul
