### ISSUE TITLE
config-based interface remapping

### ISSUE THREAD

**Issue by pldubouilh** [pmacct/pmacct#233]
Hello,

I recently observed a difference in the `in_iface_index` and the `out_iface_index` on a port-channel interface ; `in` was reporting the port-channel index and `out` was reporting the physical member index. 

Pmacct is not the issue here - it's just how the switch behaves. Fortunately it's easy to know the port-channel members, so I wrote a quick remapping functionality on top of pmacct. 

Would it be of interest if I implement a sample interface remapping functionality ? A simple example would be to remap `out_iface: 1234` to `out_iface: 5678` based on a config file that would state `1234 out_remap_to 5678`.

Cheers, and thanks for the work on pmacct !

**Comment by paololucente** [comment]
Hi @pldubouilh , it is of interest especially if the feature is not tied specifically to the output interface but applies to both input and output. If it is and you don't want to take the extra time to generalise it, i'd understand and i may take it on at some later stage. Thanks, Paolo
