### ISSUE TITLE
Add support MariaDB 10.3

### ISSUE THREAD

**Issue by Gabalino** [pmacct/pmacct#237]
Hi, who to build pmacct with MariaDB 10.3 on CentOS 7?

configure: error: ERROR: missing MySQL client library

**Comment by Gabalino** [comment]
Paolo,

pmacct -V
pmacct IMT plugin client, pmacct 1.7.2-git (20180622-00)
 '--enable-mysql' '--disable-ipv6' '--disable-l2' '--enable-64bit' '--enable-traffic-bins' '--disable-bgp-bins' '--disable-bmp-bins' '--disable-st-bins'

ls -la /usr/lib64/ | grep mysqlclient
lrwxrwxrwx.  1 root root        26 Sep 11 11:05 libmysqlclient_r.so.15 -> libmysqlclient_r.so.15.0.0
-rwxr-xr-x.  1 root root   2052744 Aug 14 07:19 libmysqlclient_r.so.15.0.0
lrwxrwxrwx.  1 root root        26 Sep 11 11:05 libmysqlclient_r.so.16 -> libmysqlclient_r.so.16.0.0
-rwxr-xr-x.  1 root root   2029224 Aug 14 07:19 libmysqlclient_r.so.16.0.0
lrwxrwxrwx.  1 root root        35 Oct  3 16:24 libmysqlclient.so -> /usr/lib64/libmysqlclient.so.18.0.0
lrwxrwxrwx.  1 root root        24 Sep 11 11:05 libmysqlclient.so.15 -> libmysqlclient.so.15.0.0
-rwxr-xr-x.  1 root root   2043496 Aug 14 07:19 libmysqlclient.so.15.0.0
lrwxrwxrwx.  1 root root        24 Sep 11 11:05 libmysqlclient.so.16 -> libmysqlclient.so.16.0.0
-rwxr-xr-x.  1 root root   2016648 Aug 14 07:19 libmysqlclient.so.16.0.0
lrwxrwxrwx.  1 root root        24 Sep 11 11:05 libmysqlclient.so.18 -> libmysqlclient.so.18.0.0
-rwxr-xr-x.  1 root root   6782760 Aug 14 07:18 libmysqlclient.so.18.0.0
lrwxrwxrwx.  1 root root        23 Mar 17  2017 lmysqlclient.a -> /lib64/libmysqlclient.a
lrwxrwxrwx.  1 root root        25 Mar 17  2017 lmysqlclient_r.a -> /lib64/libmysqlclient_r.a
lrwxrwxrwx.  1 root root        26 Mar 17  2017 lmysqlclient_r.so -> /lib64/libmysqlclient_r.so
lrwxrwxrwx.  1 root root        24 Mar 17  2017 lmysqlclient.so -> /lib64/libmysqlclient.so


ls -la /usr/lib64/ | grep maria
-rw-r--r--.  1 root root    517932 Aug 14 07:19 libmariadbclient.a
-rw-r--r--.  1 root root  40941064 Aug 14 07:19 libmariadbd.a
lrwxrwxrwx.  1 root root        17 Sep 11 11:05 libmariadbd.so -> libmariadbd.so.19
-rwxr-xr-x.  1 root root 161519944 Aug 14 07:14 libmariadbd.so.19
lrwxrwxrwx.  1 root root        13 Oct  3 15:58 libmysqld.a -> libmariadbd.a
lrwxrwxrwx.  1 root root        17 Sep 11 11:05 libmysqld.so -> libmariadbd.so.19

rpm -qa | grep Maria
MariaDB-common-10.3.9-1.el7.centos.x86_64
MariaDB-test-10.3.9-1.el7.centos.x86_64
MariaDB-devel-10.3.9-1.el7.centos.x86_64
MariaDB-client-10.3.9-1.el7.centos.x86_64
MariaDB-server-10.3.9-1.el7.centos.x86_64
MariaDB-rocksdb-engine-10.3.9-1.el7.centos.x86_64
MariaDB-compat-10.3.9-1.el7.centos.x86_64

**Comment by paololucente** [comment]
Hi @Gabalino , i see. All seems in order. I have no access to such a setup. Can you offer access to yours to see what is wrong? As a workaround, to relief pressure on your issue, please try to use MariaDB 10.2 which, as i was saying, i'm successfully managing to compile against. Paolo

**Comment by Gabalino** [comment]
Hi @paololucente, I'm create test VM and send credetials to email

**Comment by paololucente** [comment]
Hi Alexander ( @Gabalino ), thank you for that. To summarize: the issue was related to a missing dependency of libmysqlclient - and not to pmacct itself. I have added some text to documentation in cases of issues at configure time: 535bb686f851507c46fa9d8bf88ce21c01f20070 . Going to close this issue. Paolo

**Comment by Gabalino** [comment]
Hi Paolo (@paololucente), i'm create link with command
` ln -s /usr/lib64/libmariadbd.so.19 /usr/lib64/libmariadb.so`
and configure completed successfully

make end with fail

```
Making all in examples/lg
gmake[1]: Entering directory `/root/pmacct/examples/lg'
gmake[1]: Nothing to be done for `all'.
gmake[1]: Leaving directory `/root/pmacct/examples/lg'
gmake[1]: Entering directory `/root/pmacct'
gmake[1]: *** No rule to make target `examples/lg/pmbgp', needed by `all-am'.  Stop.
gmake[1]: Leaving directory `/root/pmacct'
make: *** [all-recursive] Error 1
```
