### ISSUE TITLE
Nfacctd to RabbitMQ to Grafana

### ISSUE THREAD

**Issue by zaxeqaz** [pmacct/pmacct#238]
Hello Paolo,

I'm trying to get my Nfacctd to RabbitMQ working. I have my RabbitMQ running but nfacctd doesn't seem to connect. 

I've installed these dependencies:
git, pkgconfig, libtool, autoconf, automake, gcc, make, libstdc++-devel, openssl-devel, libpcap-devel, librabbitmq-devel, jansson-devel, librdkafka-devel, mysql-devel, vim, rabbitmq-c

Config:
![image](https://user-images.githubusercontent.com/43657922/46561969-dfd5de00-c8ae-11e8-97a5-837de1559f28.png)

Error:
![image](https://user-images.githubusercontent.com/43657922/46562010-0c89f580-c8af-11e8-9d0e-7bbe006cc8ad.png)

Thanks.

**Comment by zaxeqaz** [comment]
I also seem to get this error when running 
./configure --enable-rabbitmq \
            --with-rabbitmq-libs=/usr/local/rabbitmq/lib/ \
            --with-rabbitmq-includes=/usr/local/rabbitmq/include/ \
            --enable-jansson

![image](https://user-images.githubusercontent.com/43657922/46562092-6e4a5f80-c8af-11e8-81f2-65bf6570ebbf.png)

**Comment by paololucente** [comment]
Hi @zaxeqaz , i don't have myself a setup to reproduce your authentication issue - let me know if it is an option to get access to troubleshoot. With regards to the configure issue, not sure where the --with-rabbitmq-libs and --with-rabbitmq-includes come from: this is the relevant section from current docs: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L838-#L867 . Paolo
