### ISSUE TITLE
Let daemons exit if any plugin bails out

### ISSUE THREAD

**Issue by jushao** [pmacct/pmacct#239]
Hi, paololucente. When I use nfacctd print plugin to get netflow data, I printed two different paths. The conf like this:

pre_tag_filter[netflow]: 10000-19999
aggregate[netflow]: tag,in_iface,flow_direction, as_path
print_output_file[netflow]: /home/jushao/pmacct/netflow_data/raw/%Y%m%d%H%M.csv
print_latest_file[netflow]: /home/jushao/pmacct/netflow_data/raw/netflow.latest

pre_tag_filter[prefix]: 10000-19999
aggregate[prefix]: tag,in_iface,flow_direction, dst_net, dst_mask
print_output_file[prefix]: /home/jushao/pmacct/netflow_data/raw_prefix/%Y%m%d%H%M.csv
print_latest_file[prefix]: /home/jushao/pmacct/netflow_data/raw_prefix/netflow.latest

When nfacct was running, I saw the 'prefix' print connection closed in logfile because cannot allocate memory like this:

2018-10-01T02:27:01+08:00 WARN ( prefix/print ): Unable to fork writer: Cannot allocate memory
2018-10-01T02:27:52+08:00 WARN ( default/core ): connection lost to 'prefix-print'; closing connection.

The 'netflow' print was running normally.
Can pmacct configure automatic restart the 'prefix' print in this case?

**Comment by paololucente** [comment]
Hi @jushao , no. If 'prefix' was the only plugin defined, nfacctd would have exited (and perhaps you could have it restart with something like systemd, supervised or similar mechanisms); but since the other plugin 'netflow' keeps behaving well, the daemon won't bail out. Would you like a different behaviour implemented (via a config option) that if any of the plugins exits the daemon would exit too? That is 'any of the plugins exits' vs current 'all of the plugins exit'. Paolo

**Comment by jushao** [comment]
Hi, paololucente. I use supervised now. But like you said that since the other plugin 'netflow' keeps behaving well, the daemon won't bail out. Can pmacct configure 'all of the plugins exit'?

**Comment by paololucente** [comment]
Hi @jushao , no it is not possible. But it's an interesting feature to add. I will leave this issue open and mark it as feature enhancement. Hopefully i can add this soon. Paolo

**Comment by jushao** [comment]
Hi, Paolo. Many thanks for your help. This config is useful for me.

**Comment by EpiqSty** [comment]
I've tried to use such option with pmacctd, but w/o success:
```
plugin_exit_any: true
```
key was added to pmacctd configuration, but after 
```
WARN ( default/core ): connection lost to 'collector-nfprobe'; closing connection.
```
pmacctd process remains running w/o `pmacctd: Netflow Probe Plugin [collector]` plugin.

Is it an expected behavior or do I missed something?

ps: version info
```
$ sudo apt-cache policy pmacct 
pmacct:
  Installed: 1.7.2-3
  Candidate: 1.7.2-3
  Version table:
 *** 1.7.2-3 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ pmacct -V
pmacct IMT plugin client, pmacct 1.7.2-git (20181018-00+c3)
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pmacct-8WorSQ/pmacct-1.7.2=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

Thanks in advance!

**Comment by paololucente** [comment]
Hi @EpiqSty ,

The feature is part of 1.7.3 but you are running 1.7.2. Probably it even gives you an error at config parsing time.

Paolo
