### ISSUE TITLE
timestamps_secs does not working?

### ISSUE THREAD

**Issue by mikiT** [pmacct/pmacct#241]
Hi,

I have set up the time related setting of nfacct as follows.

```
timestamps_utc: true
timestamps_secs: true
timestamps_rfc3339: true
nfacctd_time_new: true
```

I have not changed the setting, but I noticed that the output format has been changed recently.

- nfacctd 1.7.2-git (20180520-00)

```
> jq '.timestamp_arrival' <flow-201810110951.json | head -3
"2018-10-11T09:51:00.0Z"
"2018-10-11T09:51:00.0Z"
"2018-10-11T09:51:00.0Z"
```

- nfacctd 1.7.2-git (20180817-01)

```
> jq '.timestamp_arrival' <flow-201810110925.json | head -3
"2018-10-11T09:25:06.000000Z"
"2018-10-11T09:25:27.000000Z"
"2018-10-11T09:25:43.000000Z"
```

Please let me know if you notice something.

**Comment by paololucente** [comment]
Hi @mikiT -san, the change was introduced as part of Pull Request #217 so it is expected. Is the new formatting is not working for you? Paolo

**Comment by mikiT** [comment]
Hi Mr. @paololucente,

ah, I'm sorry not be in detail explained.

I set `timestamps_secs` to true.

It seems that it should be: "2018-10-11T09:51:00Z"

https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L1424

```
KEY:		timestamps_secs
VALUES:		[ true | false ]
DESC:		Sets timestamps (ie. timestamp_start, timestamp_end, timestamp_arrival primitives) resolution
		to seconds, ie. prevents residual time fields like timestamp_start_residual to be populated.
		In nfprobe plugin, when exporting via NetFlow v9 (nfprobe_version: 9), allows to fallback
		to first and last swithed times in seconds.
DEFAULT:        false
```

**Comment by paololucente** [comment]
Hi @mikiT -san,

From the output you show, it seems everything is good to me. Let's check together: the feature timestamps_secs prevents residual time fields to be populated, that is, rounds time to the seconds resolution. This is precisely what you get with, for example, 2018-10-11T09:25:06.000000Z. 9 hour, 25 mins and 6 secs - with all the rest set to zero. Does something still look incorrect to you?

Paolo

**Comment by mikiT** [comment]
Hello, Mr. @paololucente,

I understood the timestamps_secs function.
I thought that this function was to truncate.

but, Is it intentional to change the format?

mikiT

**Comment by paololucente** [comment]
Hi @mikiT -san, 

Yes, it was intentional. See the comment here: https://github.com/pmacct/pmacct/pull/217/commits/3ccd868c3dac250174222dfb6b925c070a5341f9 . The previous way of encoding was generally working OK but limited and could potentially lead to incorrect results.

Paolo

**Comment by mikiT** [comment]
Hi, @paololucente,

I'm wondering if you could share me where is the changelog?

mikiT

**Comment by paololucente** [comment]
Hi @mikiT -san,

1.7.2 code was freezed and forked less than 24 hours ago. So ChangeLog is available here:

https://github.com/pmacct/pmacct/blob/1.7.2/ChangeLog

And the relevant lines for this change are here:

https://github.com/pmacct/pmacct/blob/1.7.2/ChangeLog#L125-#L127

Release 1.7.2 will be out between 2 and 4 weeks (depending if anything serious pops up).

Paolo
