### ISSUE TITLE
sFlow MPLS Extended Data

### ISSUE THREAD

**Issue by johanek** [pmacct/pmacct#242]
Hi,

Is it possible to aggregate on sFlow MPLS extended data, such as vc_name? 

Thanks!

**Comment by paololucente** [comment]
Hi Johan ( @johanek ), some MPLS extended data is supported, like MPLS labels. VC name specifically is not. While NetFlow/IPFIX and raw data sniffing (libpcap / NFLOG) allow to leverage the aggregate_primitives framework to define custom primitives, unfortunately the structure of sFlow does not allow for that. You may send over a capture and which fields you would be interested into and take it from there. Paolo
