### ISSUE TITLE
master will not build with psql enabled on CentOS 6.

### ISSUE THREAD

**Issue by sclark46** [pmacct/pmacct#243]
In trying to build pmacct on latest CentOS 6 it fails.
  CCLD   pmacctd
./.libs/libdaemons.a(libdaemons_la-pgsql_plugin.o): In function `PG_postgresql_get_version':
/var/lib/pgsql/Download/pmacct/src/pgsql_plugin.c:979: undefined reference to `PQlibVersion'

CentOS 6 ships with postgresql 8.4 the above PQlibVersion function was introduced in 9.1. It appears the only use of the function PG_postgresql_get_version() is to print out the postgresql version.

**Comment by paololucente** [comment]
Hi Steve,

Actually master configure script checks for a PostgreSQL install >= 9.3 and should bail out if negative. Interesting with a PostgreSQL 8.4 you even manage to get to compile phase. Is this the case? If so, let me know as there would be something to fix at my end.

This said, according to https://www.postgresql.org/support/versioning/ PostgreSQL 9.3 is from 2013 and being updated up to 2018; whereas 8.4 is a 2009-2014 kind of thing. Perhaps worth a bump out of what is packaged with the OS?

Paolo

**Comment by paololucente** [comment]
Hi Steve, you were able to compile it by removing the line calling PQlibVersion()? If so, of course i'd be happy to find a way around it (for the reasons you mention). I was worried a cascade of other issues would pop up. If you can briefly confirm, i will add to the todo list for today / the weekend. Paolo

**Comment by sclark46** [comment]
Hi Paolo, yes I commented out the line and changed the printf to print 8.4.20;
void PG_postgresql_get_version()
{
  //printf("PostgreSQL %u\n", PQlibVersion());
  printf("PostgreSQL 8.4.20\n");
}

I only could find this function referenced in src/utils.c
#ifdef WITH_PGSQL
  PG_postgresql_get_version();
#endif

**Comment by paololucente** [comment]
Hi Steve, just committed a patch to address this issue. And i did manage to find a CentOS 6 for testing - so all good. Going to close this issue. As always, if you can give a try yourself and confirm it working for you, it would be wonderful. Thanks for your comments and support. Paolo

**Comment by sclark46** [comment]
Hi Paolo, just did a pull and it compiles OK. Thanks for your quick response.
