### ISSUE TITLE
pmacctd with pcap_interfaces_map does not export any flows

### ISSUE THREAD

**Issue by Skeletrox** [pmacct/pmacct#251]
Hello

I've compiled pmacct 1.17.1 from source on **Linux Mint 19 [Based on Ubuntu 18.04]**. pmacct and pmacctd are verified to be at the correct versions:

`pmacct -V`:  `pmacct IMT plugin client, pmacct 1.7.1-git (20180331-00+c3)`

and

`pmacctd -V`: `Promiscuous Mode Accounting Daemon, pmacctd 1.7.1-git (20180331-00+c3)`

Here's my configuration file [`/etc/pmacct/pmacctd.conf`]:

```
daemonize: true
pidfile: /var/run/pmacctd.pid
syslog: daemon
aggregate: src_host,dst_host,timestamp_start,timestamp_end,src_port,dst_port,proto
pcap_interfaces_map: /etc/pmacct/pcap_interfaces.map
```
The `/etc/pmacct/pcap_interfaces.map` file refered at `pcap_interfaces_map` is:
```
ifname=enp1s0
ifname=wlp2s0
```

Running the pmacct daemon by invoking `sudo pmacctd -f /etc/pmacct/pmacctd.conf` does not capture/export any flows on either of these interfaces. However, commenting out the `pcap_interfaces_map` line (or using `pcap_interface` for a single interface) and running the application works fine.

It doesn't seem like there is any issue with loading the `.map` file as the `syslog` output is as follows:

```
Nov 21 12:27:45 neuromancer pmacctd[20516]: INFO ( default/core ): [/etc/pmacct/pcap_interfaces.map] (re)loading map.
Nov 21 12:27:45 neuromancer pmacctd[20516]: INFO ( default/core ): [/etc/pmacct/pcap_interfaces.map] map successfully (re)loaded.
Nov 21 12:27:45 neuromancer pmacctd[20518]: OK ( default_memory/memory ): waiting for data on: '/tmp/collect.pipe'

```

Is there any error in either of the files? I've followed [this](https://github.com/pmacct/pmacct/blob/1.7.1/QUICKSTART#L387-L404) as much as possible for my use case.

Thanks

**Comment by paololucente** [comment]
Hi @Skeletrox ,

Thanks for reporting this. It should be an issue with documentation, which is now fixed. Or at least with the new piece of doc, i see master code working OK. Can you please give it a try? Essentially in the map put the following lines:

```
ifindex=100  ifname=enp1s0
ifindex=200  ifname=wlp2s0
```

Paolo

**Comment by Skeletrox** [comment]
Hi @paololucente 

It is working now, thanks!

**Comment by paololucente** [comment]
Thanks for confirming, closing issue.
