### ISSUE TITLE
memory plugin output corruption

### ISSUE THREAD

**Issue by pawmal** [pmacct/pmacct#253]
Hello,

`pmacct -p foo.pipe ...` may occasionally report corrupted data from nfacctd/sfacctd memory backend.

Typical corruption result:
- zero bytes or packtes counters
- extremely high counter value
- some of aggregation criterias may be not present or corrupted, e.g. empty IP address string, binary characters as country code

As problem is not persistent, daemons' in-memory counters are probably correct and data gets corrupted "in transit".

How to reproduce:
1. Start nfacctd/sfacctd with multiple memory plugins exposed over separate pipes
2. Run: `while true; do  pmacct -s -p /tmp/foo.pipe -l -O json | grep -A2 -B2 'dst": 0' && date; sleep 0.1 ; done`
3. Wait 1-60 minutes.

Example outputs:
```
{"tag": 30, "tag2": 0, "net_dst": "x.x.x.0", "mask_dst": 24, "tcp_flags": "0", "ip_proto": "icmp", "packets": 2500, "bytes": 390000}
{"tag": 30, "tag2": 0, "net_dst": "x.x.x.0", "mask_dst": 24, "tcp_flags": "22", "ip_proto": "tcp", "packets": 816000, "bytes": 33332000}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
[...cut...]
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 0, "tag2": 0, "net_dst": "", "mask_dst": 0, "tcp_flags": "0", "ip_proto": "0", "packets": 0, "bytes": 0}
{"tag": 139750420661192, "tag2": 139750420661192, "net_dst": "", "mask_dst": 0, "tcp_flags": "32538", "ip_proto": "0"}
Thu Dec 13 13:19:41 CET 2018
```

or:
```
# pmacct -s -p /tmp/bar.pipe
TAG         TAG2        DST_NET                                        PROTOCOL    PACKETS               BYTES
0           0           0                                              0           0                     0
[...cut...]
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           0           0                                              0           0                     0
0           1041        0                                              0           2314885530818453536   2314885530818453552
```

pmacct version in use: official Debian testing (10) package.
```
# pmacct -V
pmacct, pmacct client 1.7.0 (20170924-00+c1)
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pmacct-1.7.0=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'
```

Config file excerpt:
```
aggregate[foo]: tag, tag2, proto, dst_host, tcpflags, dst_as, sampling_rate, peer_src_ip

aggregate[foo]: tag, tag2, proto, dst_net
pre_tag_filter[foo]: 40-49
! etc.
networks_file: /etc/pmacct/networks.lst
sfacctd_net: file
sfacctd_as: file
maps_refresh: true
pre_tag_map: /etc/pmacct/pretag.map
sfacctd_renormalize: true
sampling_map: /etc/pmacct/sampling.map

plugins: memory[foo], memory[bar]

plugin_pipe_size: 40960000
plugin_buffer_size: 40960

imt_path[foo]: /tmp/foo.pipe
imt_path[bar]: /tmp/bar.pipe
```

**Comment by paololucente** [comment]
Hi Pawel,

Can you try again performing a lock of the table when querying? Like 'pmacct -s -l -p /tmp/bar.pipe'? 

Paolo

**Comment by pawmal** [comment]
But I already do add `-l` option. :)

**Comment by paololucente** [comment]
Hi Pawel,

Sorry i originally missed you were using -l in one of the two outputs you posted. In the past few days i did try to reproduce the issue in my testbed - without joy, unfortunately. Perhaps this is due to a combination of rate of input (not much in my case) vs rate of querying; or something being exposed in Debian 10 / gcc8.   

I'd then have a few questions for you: 1) does the issue present only when instantiating multiple (memory) plugins? In other words: if you simplify the config to the bare minimum set of features involved / lines of config - can you still reproduce the issue? 2) If answer to the previous question is yes, ignore this point. Otherwise: can you please re-introduce features / lines of config one by one so to determine which one feature may be responsible? 3) If you change the sleep interval from 0.1 to, say, 1 second - do you still experience the issue? 4) Guess nothing of this helps determining something conclusive, would remote access to your box be a possibility?

Paolo

**Comment by pawmal** [comment]
> I'd then have a few questions for you: 1) does the issue present only when instantiating multiple (memory) plugins? In other words: if you simplify the config to the bare minimum set of features involved / lines of config - can you still reproduce the issue? 2) If answer to the previous question is yes, ignore this point. Otherwise: can you please re-introduce features / lines of config one by one so to determine which one feature may be responsible? 3) If you change the sleep interval from 0.1 to, say, 1 second - do you still experience the issue? 4) Guess nothing of this helps determining something conclusive, would remote access to your box be a possibility?

1. Not sure, but very likely (this setup is fairly old and worked OK, I recently added more memory plugins, upgraded package and enabled GeoIP).
2. I will try to narrow it down but it will take some time.
3. Yes, I use 10-20 s delay it hit the problem, 0.1s was just for faster reproduction.
4. Not at this time.

In the meantime I grabbed [strace excerpt from pmacct client](https://github.com/pmacct/pmacct/files/2725517/pmacct.client.strace.txt) to illustrate a problem from syscall perspective (what is received from server via pipe/what is displayed).
`# strace -f -s 81920 pmacct -p /tmp/xx_dst.pipe -s -l -O json 2>&1 | less`
I also noticed `strace` overhead/slowdown makes it easier to trigger a problem (same command without strace produces sane output). :santa:

**Comment by paololucente** [comment]
Hi @pawmal , several compiler-assisted code fixes were carried out recently as part of PR 301, 302 and 306 (also named 'nuclear blast'). Any chance you could give this issue another try and see if anything has changed meanwhile? Thanks, Paolo
