### ISSUE TITLE
examples directory contains architecture dependant files

### ISSUE THREAD

**Issue by bzed** [pmacct/pmacct#257]
The examples are being installed into /usr/share/pmacct/examples, which is a directory for architectoure independant files only. As it contains ELF binaries, it needs to be moved to /usr/lib/pmacct/examples.

**Comment by paololucente** [comment]
Hi @bzed , thanks for reporting this. I just committed a fix. Can you see if it works for you? Thanks, Paolo

**Comment by bzed** [comment]
Did not have the time to test it, but your patch looks fine! Thanks a lot!
