### ISSUE TITLE
mysql_plugin: fails to buidl with recent mariadb

### ISSUE THREAD

**Issue by bzed** [pmacct/pmacct#258]
Hi,

to build against the recent maria db version in debian, I need this patch:

https://salsa.debian.org/debian/pmacct/blob/master/debian/patches/fix-build-with-recent-mariadb

not sure what a backward compatible way is here unfortunately.

Thanks,
Bernd

**Comment by paololucente** [comment]
Hi Bernd, i essentially incorporated your patch after having verified it working against MariaDB 10.2 and MySQL 5.5 and 5.6. What MariaDB version are you compiling against? Do you have any chance to try against MySQL 8 or any MySQL shipped with Debian? Paolo

**Comment by bzed** [comment]
@paololucente sorry for being slow in replying :) Just checked a mysql 5.1 installation, it ships with mysql_version.h, so the fix should be just fine. They just stopped including mysql_version.h into mysql.h at some point.

**Comment by paololucente** [comment]
Hi Bernd, no worries and actually thanks very much for checking! Paolo
