### ISSUE TITLE
Kafka Error: Failed to produce to topic pmacct-raw partition -1: Local: Queue full

### ISSUE THREAD

**Issue by johanek** [pmacct/pmacct#261]
Hello,

I upgraded pmacct to latest master and I'm now receiving this error:

`ERROR ( default_kafka/kafka ): ERROR ( default_kafka/kafka ): Failed to produce to topic pmacct-raw partition -1: Local: Queue full`

Based on https://github.com/edenhill/librdkafka/issues/210 I tried increasing queue.buffering.max.messages - see https://github.com/sohonet/pmacct/commit/1267bdc8dc96790e3576882c07fed508e95a3278. With the higher setting everything works correctly, so it looks like I hit this when sending >100k records when flushing. But of course the number of records being sent could be even higher in the future.

So I also looked at calling `rd_kafka_poll()` with a minimum timeout value to prevent the queue length getting too big, and this also worked: https://github.com/sohonet/pmacct/commit/8bb4493cc5a2ee7a4d72c40888df0aebabc357ce

I'm not sure what the best way to address this problem, but maybe it's possible to  allow configuration of queue.buffering.max.messages via pmacct config, as well as calling `rd_kafka_poll()` to reduce the queue when at or near the maximum? I'm sure it's possible to do this in a better way than I tried.

Thanks!

**Comment by paololucente** [comment]
Hi Johan, with kafka_config_file pmacct configuration directive you can pass config parameters to librdkafka, including queue size. I have myself around 100K messages/sec and these do for me:

global, queue.buffering.max.messages, 8000000
global, batch.num.messages, 100000

Paolo

**Comment by johanek** [comment]
Hi Paolo,

I tested this out and it works great. 👍 Thanks for pointing out this config to me.

One question: is the config also used for sending sflow counters to kafka?

Thanks again

**Comment by paololucente** [comment]
Nice! Every Kafka producer in pmacct can be configured with its own config file to pass to librdkafka. So kafka_config_file applies to the Kafka plugin; sfacctd_counter_kafka_config_file applies to the sFlow counters part, which is distinct and does not leverage the Kafka plugin.

**Comment by johanek** [comment]
Gotcha. Thanks for the clarification.
