### ISSUE TITLE
bgp_table_dump stops pmbgpd process

### ISSUE THREAD

**Issue by njgarfield** [pmacct/pmacct#266]
When configuring bgp_table_dump the pmbgpd process dies:

INFO ( default/core ): *** Dumping BGP tables - START (PID: 25002) ***
INFO ( default/core ): *** Dumping BGP tables - END (PID: 25002, TABLES: 1 ET: 0) ***

[1]+  Killed                  /usr/local/sbin/pmbgpd -f /etc/pmacct/pmacctd.conf

Same behavior for both files and kafka.

Other features work fine when table dumping is not activated.

File based config:
bgp_table_dump_file: /root/pm-eval/bgp-$peer_src_ip-%H%M.log
bgp_table_dump_refresh_time: 60

or kafka based config:
bgp_table_dump_kafka_config_file: /etc/pmacct/bgp_table_kafka
bgp_table_dump_refresh_time: 60
bgp_table_dump_output: json
bgp_table_dump_kafka_broker_host: a.host.com
bgp_table_dump_kafka_topic: pmacct.bgp

Compilation options:

# /usr/local/sbin/pmbgpd -V
pmacct BGP Collector Daemon, pmbgpd 1.7.2-git (20181018-00+c3)

Arguments:
 '--enable-mysql' '--enable-zmq' '--enable-kafka' '--enable-jansson' 'ZMQ_CFLAGS=-I/usr/local/zeromq/include' 'ZMQ_LIBS=-L/usr/local/zeromq/lib -lzmq' 'KAFKA_CFLAGS=-I/usr/local/kafka/include' 'KAFKA_LIBS=-L/usr/local/kafka/lib -lrdkafka' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
MySQL 5.5.60-MariaDB
rdkafka 0.11.4
jansson 2.10
ZeroMQ 4.1.4

System:
Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
#

**Comment by paololucente** [comment]
Hi Nick ( @njgarfield ), this should have already been fixed in master code. Can you please give it a try? Paolo

**Comment by njgarfield** [comment]
no longer crashing.

bgp_table_dump to file looks good.

Kafka bgp table dump seems to be ordering strangely, but that might be my kafka client. Debug output from pmbgpd sometimes writes in the correct order, other times it's writing dump_close first, the a dump message, then dump_init, then another dump message. Maybe a buffer flushing issue?

# /usr/local/sbin/pmbgpd -V
pmacct BGP Collector Daemon, pmbgpd 1.7.3-git (20190221-00)

Arguments:
 '--enable-mysql' '--enable-zmq' '--enable-kafka' '--enable-jansson' 'ZMQ_CFLAGS=-I/usr/local/zeromq/include' 'ZMQ_LIBS=-L/usr/local/zeromq/lib -lzmq' 'KAFKA_CFLAGS=-I/usr/local/kafka/include' 'KAFKA_LIBS=-L/usr/local/kafka/lib -lrdkafka' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
MySQL 5.5.60-MariaDB
rdkafka 0.11.4
jansson 2.10
ZeroMQ 4.1.4

System:
Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64

Compiler:
gcc 4.8.5

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

**Comment by paololucente** [comment]
Where are you collecting the debug? Reading from Kafka? If so, if the topic is partitioned that may explain and to fix you could look in one of the pmacct kafka_partition configuration keys.

**Comment by njgarfield** [comment]
the debug is from the daemon standard output running use daemonize: false and debug: true in the config file. I'll take a look into the kafka configuration options. I don't see any re-ordering in the kafka stream for the msglog stream.

**Comment by paololucente** [comment]
I see. Please let me know how things look like once consumed from Kafka; debug on standard output may not be 100% accurate, as you were saying, due to buffering for example.

**Comment by njgarfield** [comment]
Tuning up the table dump configuration has fixed the issue.

timestamps_rfc3339: true
kafka_markers: true
timestamps_secs: true
kafka_partition_dynamic: true
bgp_table_dump_kafka_partition_key: $peer_src_ip

Thanks for the support.

**Comment by paololucente** [comment]
Thank you for the feedback. I am going to close this issue.
