### ISSUE TITLE
Need to send IPFIX streams using pmacct based on specific templates and read using nfdump/nfcapd

### ISSUE THREAD

**Issue by nishantambastha** [pmacct/pmacct#267]
Hi All,

I need to test a scenario where I've to export IPFIX streams using pmacct based on some specific template and collect using nfdump/nfcapd based on the same template.

I have already tested a simple scenario where i exported IPFIX using pmacct but without specifying any kind of template anywhere.

my pmacctd.conf file:

daemonize: true
#daemonize: false
interface: br0
aggregate: src_host, dst_host, src_port, dst_port, proto, tos
plugins: nfprobe
nfprobe_receiver: *ip-address*:2055		# ip address.. by default the port number is 2055
! Do IPFIX:
nfprobe_version: 10
nfprobe_timeouts: tcp=30:maxlife=60

I was able to see the data while reading using nfdump.

**Could you please guide me on how can I test with some specific template**. 
Please let me know if any question/concern. Thanks.

Cheers
Nishant

**Comment by paololucente** [comment]
Hi Nishant, can you say what is your final use-case and/or make an example? What are you missing in the auto-generated template? Or what kind of information you would like to add to the exported IPFIX packet? Paolo

**Comment by nishantambastha** [comment]
Hey Paolo,

Actually I want to understand how to use IPFIX templates: where do templates reside on the filesystem, how to edit them to emit different IPFIX data etc..

Cheers
Nishant

**Comment by paololucente** [comment]
Templates are auto-generated for you. You can choose what to send by selecting primitives: 'aggregate' (for built-in primitives) and 'aggregate_primitives' (for custom primitives). You could also add tags and/or labels in some cases to carry external info.
