### ISSUE TITLE
nfacctd crashing on high load with kafka plugin

### ISSUE THREAD

**Issue by numbnut** [pmacct/pmacct#268]
Hi Paolo,

I am facing an issue which leads to a crash of the nfacctd when the following conditions are met.

1. Exceeding a certain load threshold (Output of minimum 150k data points per interval, which is in our case 5 minutes)
2. Using the Kafka plugin
3. Aggregation on a custom netflow field (name=mpls_dst_ip field_type=47 len=4 semantics=ip)

To say this up front. This bug isn't reproducable with the current master code. I also read carefully your guideline about contributing bug reports, but I thought this could be a valuable information for other users and maybe you as well.

The affected version is the following
```
NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)

Arguments:
 '--enable-zmq' '--enable-kafka' '--enable-jansson' '--enable-ipv6' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
rdkafka 0.11.6
jansson 2.9
ZeroMQ 4.3.1

System:
Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```
I was able to reproduce this also in my development environment, but depending on the shape of the netflow data with two different kinds of errors. The first one looked the same as in production, which means seg faulting, but the second one was an unmet assertion, which terminated the process.

First the seg fault
```
dmesg -T | grep seg [Thu Feb 21 10:52:29 2019] nfacctd[70373]: segfault at 29c ip 00007fe9548dee6b sp 00007ffcf5533998 error 6 in libc-2.24.so[7fe9547b6000+195000]
```
```
INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)
INFO ( default/core ): '--enable-zmq' '--enable-kafka' '--enable-jansson' '--enable-ipv6' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bi ns' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/etc/pmacct/pmacctd.conf'.
INFO ( default/core ): [/etc/pmacct/primitives.lst] (re)loading map.
INFO ( default/core ): [/etc/pmacct/primitives.lst] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( netflow/kafka ): cache entries=16411 base cache memory=54878384 bytes
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
INFO ( default/core ): waiting for NetFlow/IPFIX data on :::2100
INFO ( netflow/kafka ): JSON: setting object handlers.
INFO ( netflow/kafka ): *** Purging cache - START (PID: 13) ***
INFO ( netflow/kafka ): *** Purging cache - END (PID: 13, QN: 20878/20878, ET: 1) ***
WARN ( default/core ): connection lost to 'netflow-kafka'; closing connection.
WARN ( default/core ): no more plugins active. Shutting down.
```

Second the unmet assertion
```
INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)
INFO ( default/core ):  '--enable-zmq' '--enable-kafka' '--enable-jansson' '--enable-ipv6' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/etc/pmacct/pmacctd.conf'.
INFO ( default/core ): [/etc/pmacct/primitives.lst] (re)loading map.
INFO ( default/core ): [/etc/pmacct/primitives.lst] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( netflow/kafka ): cache entries=16411 base cache memory=54878384 bytes
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
INFO ( default/core ): waiting for NetFlow/IPFIX data on :::2100
INFO ( netflow/kafka ): JSON: setting object handlers.
INFO ( netflow/kafka ): *** Purging cache - START (PID: 14) ***
INFO ( netflow/kafka ): *** Purging cache - END (PID: 14, QN: 37128/37128, ET: 1) ***
nfacctd: plugin_common.c:442: P_cache_insert: Assertion `!cache_ptr->stitch' failed.
WARN ( default/core ): connection lost to 'netflow-kafka'; closing connection.
WARN ( default/core ): no more plugins active. Shutting down.
```
A verification, whether the current head of master doesn't crash in the production environment is still outstanding and will hopefully be done during the next days or weeks. I didn't create a core dump or any further debug information, since I can't reproduce it with the current head of master. Nevertheless I thought it is worth sharing, since I weren't able to find a related issue. Feel free to directly close this or if you want any further information, please let me know.
Thank you very much for pmacct and kind regards.

**Comment by paololucente** [comment]
Hi @numbnut , thank you for reporting this, much appreciated. This is same as issue #218 and, as explained there, it is something fixed in mid December 2018, post 1.7.2. I will therefore close this issue. Paolo

**Comment by numbnut** [comment]
Hi Paolo,
thanks for pointing me to the issue. I wasn't aware of that one. One last question. What do you recommend to work around this issue in a production environment?
1. Applying the related patch to the version1.7.2? Would that be safe?
2. Using the current head of master?
3. Waiting for the next release? How long would that probably take? Weeks or even months?
Thank you once more!

**Comment by paololucente** [comment]
You could definitely apply the patch to 1.7.2, it is a very isolated code change. But perhaps i may recommend to use 1.7.3-rc1 over all the other options you mentioned. It is packaged here: https://github.com/pmacct/pmacct/releases/tag/1.7.3-rc1
