### ISSUE TITLE
pmbmpd segfault

### ISSUE THREAD

**Issue by ccakes** [pmacct/pmacct#274]
I'm having an issue with pmbmpd segfaulting, usually pretty quicky after starting (within seconds). I've trimmed the configuration down to the bare minimum:
```
bmp_daemon_ip: 0.0.0.0
bmp_daemon_port: 11019
bmp_daemon_max_peers: 200
bmp_daemon_msglog_file: /dev/null
bmp_daemon_msglog_output: json
```

I followed the advice in the QUICKSTART file and grabbed a core dump to generate a backtrace.

<details>
<summary>gdb output</summary>

```
root@aca04338d2c7:/build# gdb target/sbin/pmbmpd pmbmpd.core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/sbin/pmbmpd...done.
[New LWP 1015]

warning: Unexpected size of section `.reg-xstate/1015' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `                                      '.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/1015' in core file.
#0  0x000055ebb219954a in bgp_nlri_parse (bmd=<optimized out>, attr=<optimized out>,
    info=0x7ffcc755e580) at bgp_msg.c:1048
1048	bgp_msg.c: No such file or directory.
(gdb)
(gdb)
(gdb) bt
#0  0x000055ebb219954a in bgp_nlri_parse (bmd=<optimized out>, attr=<optimized out>,
    info=0x7ffcc755e580) at bgp_msg.c:1048
#1  0x00000402000f000f in ?? ()
#2  0x0624000000380400 in ?? ()
#3  0x00be0000000300b9 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) quit
```
</details>

This particular trace is from a binary compiled using the 1.7.3-rc1 tarball however I've had the same issue on 1.7.2 as well. In case it matters, I'm compiling and running on an up-to-date Debian stable with `--enable-jansson --enable-zmq`

I tried running tcpdump to see if any of the routers were sending malformed messages but it all looks ok - Wireshark had no issues decoding them at least. Let me know if I can provide any extra details

Cheers

**Comment by ccakes** [comment]
To clarify - there are a number of clients already configured so within the few seconds it takes to segfault, it'll usually gain between 1-4 sessions up.

**Comment by paololucente** [comment]
Hi Cameron, 

Thanks for reporting this. From the GDB output it seems this is related to some label-unicast prefix being advertised via BMP. This could be slightly harder to reproduce on my own; any chance you could share (by unicast email perhaps) a brief capture of your BMP packets for me to replay and reproduce the issue? Should i find you positive, this is the route i'd recommend: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2681-#L2691 .

Paolo

**Comment by paololucente** [comment]
Hi Cameron,

To say this should be fixed in master code. I took a moment to revisit a couple other things not directly related to the issue. It would be great if you could test it working (that is, not crashing and returning meaningful output) for you. By the way, the router is really sending zero-length label-unicast prefixes (whereas minimum length should be 3 bytes, that is, one label), i got it confirmed also with Wireshark. Will provide you further info via unicast email.

Paolo

**Comment by paololucente** [comment]
Hi Cameron, i will close this issue for now. We can re-open it if it turns something else must be fixed related to this or open a new issue in case of unrelated problems. Paolo
