### ISSUE TITLE
why 100 peer limit for pmbgpd?

### ISSUE THREAD

**Issue by njgarfield** [pmacct/pmacct#277]
#define MAP_BGP_PEER_AS_SRC  100  /* bgp_peer_src_as_map */

What is the impact of setting this number an order of magnitude higher?

**Comment by FvDxxx** [comment]
Hi Nick,

this has nothing to do with the size of the map - it's just the map type 
... are you looking for bgp_daemon_max_peers?

Markus

/* map type */
#define MAP_TAG                 0       /* pre_tag_map */
#define MAP_BGP_PEER_AS_SRC     100     /* bgp_peer_src_as_map */
#define MAP_BGP_TO_XFLOW_AGENT  101     /* bgp_to_agent_map */
#define MAP_BGP_SRC_LOCAL_PREF  102     /* bgp_src_local_pref_map */
#define MAP_BGP_SRC_MED         103     /* bgp_src_med_map */
#define MAP_FLOW_TO_RD          104     /* flow_to_rd_map */
#define MAP_SAMPLING            105     /* sampling_map */
#define MAP_TEE_RECVS           106     /* tee_receivers */
#define MAP_IGP                 107     /* igp_daemon_map */
#define MAP_CUSTOM_PRIMITIVES   108     /* aggregate_primitives */
#define MAP_BGP_XCS             109     /* bgp_xconnect_map */
#define MAP_PCAP_INTERFACES     110     /* pcap_interfaces_map */



Am 03.04.2019 um 12:51 schrieb Nick Garfield:
>
> #define MAP_BGP_PEER_AS_SRC  100  /* bgp_peer_src_as_map */
>
> What is the impact of setting this number an order of magnitude higher?
>
>

**Comment by njgarfield** [comment]
ah yes, i see it's a config item. Is 100 just a recommendation or is there any particular constraint?

**Comment by paololucente** [comment]
Hi Nick, as @FvDxxx was explaining that is simply a type ID. As such it should not really of much interest to you (as user) to which value it is set. What i am curious, though, is how you ended up there: did you hit some limits and were trying to perform some troubleshooting? Paolo

**Comment by FvDxxx** [comment]
Hi Nick,

bgp_daemon_max_peers defaults to 10 (according to the doc, in the source 
I read somewhere 4). The upper limit depends on the size of the tables 
(AFI/SAFI, multi-path), your CPU speed (no MT), memory and so on. It's 
an int, but I almost doubt it will scale reasonable beyond a few 
hundreds active peers ... and if you try larger scaling, you might want 
to check other BGP related settings as well ...

Markus


Am 03.04.2019 um 14:46 schrieb Nick Garfield:
>
> ah yes, i see it's a config item. Is 100 just a recommendation or is 
> there any particular constraint?
>

**Comment by njgarfield** [comment]
Hi Paolo, good question. Hypothetically, we have a requirement for ~500 peerings, most of which have maybe 100 prefixes advertised, a few with full tables. We are wondering how the system scales. Is this just a case of more cpu and memory, or if the system is single threaded what's the best approach to distributed pmbgp?

**Comment by paololucente** [comment]
In a few setup I personally reached in the order of 200-300 BGP peerings in a single instance with no issues. Of course the number can get reduced depending on features enabled. Good news is things can be scaled out pretty easily. Please see here the approach that i would recommend, the SO_REUSEPORT: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1735-#L1781 : essentially you can bind to the very same 179/TCP port as many daemons as you wish. You can also review conversation in Issue #272. This is effectively a multi-processing approach.

**Comment by njgarfield** [comment]
Thanks for the suggestion of SO_REUSEPORT. I'll test this feature out, looks like a good solution.
