### ISSUE TITLE
Finding long open TCP connections

### ISSUE THREAD

**Issue by zerocarbthirty** [pmacct/pmacct#278]
Is there any way using the information in v9 flow record to find long lasting TCP connections? I believe that because sflow expires the records that there is really no way to do this but perhaps there is a way to aggregate multiple connections with the same src_mac dst_mac into single continuous record?

I am using MySQL as my storage. Any thoughts?

**Comment by paololucente** [comment]
Hi @zerocarbthirty , could the stitching feature documented here ( https://github.com/pmacct/pmacct/blob/1.7.2/CONFIG-KEYS#L1684-#L1694 ) be what you are looking for? Paolo
