### ISSUE TITLE
nfacctd tee plugin fail forwarding netflow when tee_receivers is set to true

### ISSUE THREAD

**Issue by zhxgigi** [pmacct/pmacct#280]
Hi,

I found nfacctd failed forwarding NetFlow pkts to remote collector when tee_receivers is true, when I disable it, it works.

Using following setup, the flow pckts can be recieved at id=1 and id=2 no matter tee_receivers true or false, but for id=4, can only recieve flow when tee_receivers=false.

At the same server, sfacctd working perfect using almost same config.
I tested the 1.7.1, 1.7.2, 1.7.3-rc2 versions which results are the same.

Any suggestion? 
Thanks

`
# cat pmacctd.conf

daemonize: true
logfile: /var/log/pmacct/pmacct.log
interface: eno1
aggregate: src_host, dst_host, src_port, dst_port, proto, tos
plugins: nfprobe
nfprobe_receiver: 127.0.0.1:3055

! Do IPFIX:
nfprobe_version: 10
nfprobe_timeouts: tcp=30:maxlife=60
#nfprobe_sampling_rate: 1

# cat nfacctd.conf
daemonize: false
nfacctd_port: 3055
nfacctd_ip: 0.0.0.0
pidfile: /var/run/nfacctd.pid
logfile: /var/log/pmacct/nfacctd.log

!
plugins: tee[a]
tee_receivers[a]: tee_nflow_receivers.lst
tee_transparent: true

# cat tee_nflow_receivers.lst
id=1    ip=127.0.0.1:3056
id=2    ip=10.6.5.88:3057
id=4    ip=54.67.86.xxx:2056

# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.3-git (20190409-00)

Arguments:
 '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1

System:
Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64

Compiler:
gcc 7.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

# ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.6.5.88  netmask 255.255.255.0  broadcast 10.6.5.255
        inet6 fe80::baca:3aff:feba:c530  prefixlen 64  scopeid 0x20<link>
        ether b8:ca:3a:ba:c5:30  txqueuelen 1000  (Ethernet)
        RX packets 16710138  bytes 5266038726 (5.2 GB)
        RX errors 0  dropped 94288  overruns 0  frame 0
        TX packets 17431446  bytes 10649642818 (10.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7100000-f7120000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 25793740  bytes 3937348427 (3.9 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25793740  bytes 3937348427 (3.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by paololucente** [comment]
Hi @zhxgigi , can you please show the log of nfacctd tee at start up when tee_receivers is enabled? Is there any warning or error message? Like file not found since tee_nflow_receivers.lst does not have an absolute path? Paolo

**Comment by zhxgigi** [comment]
hi @paololucente , I'm not in office now, will post tmr. I'm sure tee_nflow_receivers.lst is loaed since I do pcap at the same time and I can see the traffic at localhost.
No warning message with -d flag.

**Comment by paololucente** [comment]
Hi @zhxgigi , i see. Keep me posted then. Another aspect you may want to look at (since you say all works good for localhost but not for remote hosts) is making sure packets are not filtered out due to policies or RPF checks, ie. https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2627-#L2632

**Comment by zhxgigi** [comment]
@paololucente Just did a quick check in one of staging servers, I think it's very likely the reason as you mentioned, filtered out by RPF checks.
`
$ cat /proc/sys/net/ipv4/conf/eth0/rp_filter
1
`
I will check this tmr and update the result here,  thank you very much.

**Comment by zhxgigi** [comment]
Hi @paololucente , I found the reason, we are using AWS, it seems they don't allow src IP spoofing.

https://aws.amazon.com/answers/networking/vpc-security-capabilities/

>  Network Traffic Control
> Network Address Spoofing
> Network MAC addresses are dynamically assigned to Amazon Elastic Compute Cloud (Amazon EC2) instances by the AWS network infrastructure. IP addresses are either dynamically assigned by the AWS network infrastructure or statically assigned by an EC2 administrator through authenticated API requests. The AWS network only allows EC2 instances to send traffic from IP and MAC addresses specifically assigned to them, or the traffic will be dropped.
> 
> By default, AWS also protects EC2 instances by treating an instance as a standalone network host, not a router or network gateway, and drops any traffic not specifically addressed to the instance. Customers who need EC2 network appliances to run network address translation, routing, or firewall services can change this default behavior by disabling the Source/Destination Check attribute and configuring VPC route tables to send outbound traffic through the network appliance.
>

**Comment by paololucente** [comment]
Thank you @zhxgigi , brilliant. I have also added a note of this in the docs. I will close this issue then. Paolo
