### ISSUE TITLE
sfprobe: export of non-standard information (ie. class, tag)

### ISSUE THREAD

**Issue by arbaldin** [pmacct/pmacct#281]
I tried to use pmacct to export sFlow and found two possible problems:

i. I can't see IPv6 traffic when exporting with sfprobe, if the export is using nfprobe instead, the collector show IPv6 traffic, but with sfprobe it doesn't;

ii. The collector keeps logging a warning messages like this:
`Unknown record entreprise 43874, format 3`
`Unknown record entreprise 43874, format 2`
I captured some packets from the sfprobe machine and even Wireshark is complaining of the packet, indicating it is malformed (pcap file attached)

[capture.zip](https://github.com/pmacct/pmacct/files/3075132/capture.zip)

**Comment by paololucente** [comment]
Hi @arbaldin , out of curiosity, what collector are you using for sFlow? The sFlow capture you attached does actually contain a few IPv6 packets, for example. Also those unknown records are tag and class: there is no standard way to pass them via sFlow and hence to collect them back you should use sfacctd, the pmacct sFlow collector; in NetFlow/IPFIX there is a commonly accepted way to pass classification information so you may have better chances at your NetFlow/IPFIX collector of choice (if that is not nfacctd) to be able to parse them. Paolo

**Comment by arbaldin** [comment]
@paololucente , I'm using ashangit/logstash-codec-sflow. What are the tag and class records? By class should I understand the information that ndpi is sending? In case I don't  compile with ndpi option, is this information still sent?

**Comment by paololucente** [comment]
@arbaldin , correct. Wrt the tag, is it possible you have a pre_tag_map directive defined in your config?

**Comment by arbaldin** [comment]
So, if I compile without the ndpi (it´s not working) and not use a tag_map (I bellieve I was) I should not receive those information anymore. I will try.

**Comment by arbaldin** [comment]
Confirmed, I compile pmacct without ndpi option and the conf file don't have tag_map, an there were no errors in the collectors log, but it still does not process IPv6 traffic. If I use nfprobe export (ipfix) it works.

**Comment by paololucente** [comment]
Great, thank you. In parallel i committed a small piece of code to add a conditional to enable/disable sending of classification info via sfprobe/sFlow (this plugin was unique in not providing a conditional if nDPI was compiled in). I am hence going to close this issue. Thank you for the quick feedback.
