### ISSUE TITLE
Using nDPI plugin with kafka Plugin

### ISSUE THREAD

**Issue by KunwarAkanksha** [pmacct/pmacct#282]
I want to send the data to Kafka cluster, but how to use nDPI with this . Kafka cluster is getting the data , but I want to explore the layer 7 protocols as well, is it possible using nDPI?

**Comment by paololucente** [comment]
Hi @KunwarAkanksha ,

Did you already read the relevant section in the QUICKSTART guide, ie.:

https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1100-#L1172

If so, please tell me where things go wrong.

Paolo

**Comment by KunwarAkanksha** [comment]
Thanks for the prompt reply.
I have gone through the docs and enabled the ndpi without any error. As my nDPI version
is 2.9 i have set the pkg_conf_file path as well. All the NDPI_CFLAGS and NDPI_LIBS are
correctly set but I am not sure that it is enabled correctly.


ccsm@ccsm:~/pmacct$ echo $PKG_CONFIG_PATH
/usr/local/libdata/pkgconfig
ccsm@ccsm:~/pmacct$ echo $NDPI_CFLAGS
-I/usr/local/nDPI/src/include
ccsm@ccsm:~/pmacct$ echo $NDPI_LIBS
-L/usr/local/nDPI/src/lib
ccsm@ccsm:~/pmacct$ sudo pmacctd -P print -f ndpi.conf
WARN: [ndpi.conf:9] Unable to handle key: plugins. Ignored.
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.2-git
(20181018-00+c3)
###################################################################################
INFO ( default/core ):  '--enable-kafka' '--enable-jansson'
'KAFKA_CFLAGS=-I/usr/local/kafka/include' 'KAFKA_LIBS=-L/usr/local/kafka/lib -lrdkafka'
'JANSSON_CFLAGS=-I/usr/local/jansson/include' 'JANSSON_LIBS=-L/usr/local/jansson/lib
-ljansson' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-traffic-bins'
'--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'    
 (###### here ndpi plugin is not shown)
##################################################################################
INFO ( default/core ): Reading configuration file '/home/ccsm/pmacct/ndpi.conf'.
INFO ( default_print/print ): plugin_pipe_size=4096000 bytes plugin_buffer_size=280 bytes
INFO ( default_print/print ): ctrl channel: obtained=212992 bytes target=117024 bytes

###############################################################################
ndpi.conf

daemonize: false
debug: true
pcap_interface: nt3g0
snaplen: 700
!
plugins: print
!
aggregate: class, src_host, dst_host, src_port, dst_port, proto                                                                                                                                                                                       
############################################################################

And one more doubt ,
As we have generated the flow from some other Flow Generation Tool, we are getting less
accumulative traffic flow count in pmacctd this is because there are many packets of
size one byte in flows (aggregation is : src_port,dst_port, src_add, dst_add, proto,tos ).

**Comment by paololucente** [comment]
Hi @KunwarAkanksha ,

About the nDPI part:
* pmacct 1.7.2 works against nDPI 2.2 and 2.4. Master code works against nDPI 2.4, 2.6, 2.8
* you can remove "-P print" from your command-line, since that is specified already in the config

About the flow aggregation part: you can get flows count by adding the 'flows' keyword to the 'aggregate' directive - which i recommend. Alternatively, you can de-aggregate and get one entry per flow by adding 'timestamp_start, timestamp_end' to the 'aggregate' directive - which i do not recommend unless you have a specific use-case for it.

Paolo

**Comment by KunwarAkanksha** [comment]
Hi @paololucente ,
 I have downgraded the nDPI version to 2.4 , 2.2 and then to 2.2.2, but again in all the cases ndpi-plugin is not shown.

ccsm@ccsm:~/pmacct/pmacct-1.7.2$ ndpiReader -h
Welcome to nDPI 2.2.2
.
.
.
ccsm@ccsm:/pmacct$ sudo pmacctd -f ndpi.conf
WARN: [ndpi.conf:9] Unable to handle key: plugins. Ignored.
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.2-git
(20181018-00+c3)
###################################################################################
INFO ( default/core ): '--enable-kafka' '--enable-jansson'
'KAFKA_CFLAGS=-I/usr/local/kafka/include' 'KAFKA_LIBS=-L/usr/local/kafka/lib -lrdkafka'
'JANSSON_CFLAGS=-I/usr/local/jansson/include' 'JANSSON_LIBS=-L/usr/local/jansson/lib
-ljansson' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-traffic-bins'
'--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
(###### here again  ndpi plugin is not shown)

**Comment by paololucente** [comment]
You are compiling the package yourself, true? Are you following instructions in https://github.com/pmacct/pmacct/blob/master/README.md ? Plus instructions in QUICKSTART specific to any switch you may want to enable (ie. Jansson, Kafka, nDPI, etc.)? How do you configure the package for compiling? Do you append --enable-ndpi to the list of arguments you may already be providing for other purposes? For example: "./configure --enable-kafka --enable-jansson --enable-ndpi"?

**Comment by KunwarAkanksha** [comment]
Yes , I am compiling the package myself. And I have gone through the QUICKSTART instructions line by line. jansson, kafka are configured correctly, as I can get Kafka messages in my Kafka Cluster. 
for nDPI I have configured the nDPI package first and set all the variables of NDPI_CFLAGS, NDPI_LIBS and PKG_CONFIG_PATH as per the instructions in QUICKSTART. 
"./configure --enable-kafka --enable-jansson --enable-ndpi --with-ndpi-static-lib=DIR"   (with and without static lib ) 
I can see the plugin after ./configure :

PLATFORM ..... : x86_64
OS ........... : Linux 4.4.0-131-generic (ccsm)
COMPILER ..... : gcc
CFLAGS ....... : -O2 -g -O2 
LIBS ......... :  -ldl -L/usr/local/lib -lpfring -lpcap -lrt -lnuma -lpthread
LDFLAGS ...... : -Wl,--export-dynamic 
PLUGINS ...... :  kafka
SUPPORTS ..... :  jansson ndpi          ###############here ndpi is showing######################
Now type 'make' to compile the source code.

**Comment by KunwarAkanksha** [comment]
Hello @paololucente Sir,
 I am now using pmacct-master code with nDPI 2.8, but issue remain same for this case as well. I cannot see --enable-ndpi switch although I have configured it correctly without any error or warnings.
######################################################################################
sudo pmacctd -f print.conf 
WARN: [print.conf] Class aggregation not possible due to missing --enable-ndpi   
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.4-git (20190429-00)
INFO ( default/core ):  'KAFKA_CFLAGS=-I/usr/local/kafka/include' 'KAFKA_LIBS=-L/usr/local/kafka/lib -lrdkafka' 'JANSSON_CFLAGS=-I/usr/local/jansson/include' 'JANSSON_LIBS=-L/usr/local/jansson/lib -ljansson' 'NDPI_CFLAGS=-I/usr/local/nDPI/src/include' 'NDPI_LIBS=-L/usr/local/nDPI/src/lib' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/home/ccsm/pmacct-master/tmp/print.conf'.
INFO ( ipfix/print ): plugin_pipe_size=81920000 bytes plugin_buffer_size=10240 bytes
INFO ( ipfix/print ): ctrl channel: obtained=212992 bytes target=64000 bytes
INFO ( ipfix/print ): cache entries=16411 base cache memory=54878384 bytes
INFO ( default/core ): [ntxs0,0] link type is: 1
WARN ( default/core ): ntxs0: no IPv4 address assigned

######################################################################################
./configure --enable-ndpi --enable-kafka --enable-jansson LDFLAGS="-L/opt/napatech3/lib -lntapi -lntos" CFLAGS=-I/opt/napatech3/include --prefix=/opt/napatech3 --with-pcap-libs=/opt/napatech3/lib --with-pcap-includes=/opt/napatech3/include
##################################################################################

**Comment by KunwarAkanksha** [comment]
In Config.log I can see this - 
####3
..
..
..
configure:16419: gcc -o conftest -O2 -g -O2  -Wl,--export-dynamic  conftest.c -lndpi   -ldl -L/usr/local/lib -lpfring -lpcap -lrt -lnuma -L/usr/local/nDPI/src/lib >&5
configure:16419: $? = 0
configure:16428: result: yes
configure:16442: checking libndpi/ndpi_main.h usability
configure:16442: gcc -c -O2 -g -O2 -I/usr/local/nDPI/src/include  conftest.c >&5
conftest.c:67:31: fatal error: libndpi/ndpi_main.h: No such file or directory
compilation terminated.
..
...
..
####

**Comment by paololucente** [comment]
Hi @KunwarAkanksha , i wonder: is nDPI actually installed in /usr/local/nDPI? If not then those settings are not correct. Also see where libndpi.pc is installed. If in /usr/local/lib/pkgconfig/ then you may also skip the PKG_CONFIG_PATH.

**Comment by KunwarAkanksha** [comment]
ccsm@PROBE3:~/pmacct-master$ whereis nDPI
nDPI: /usr/local/nDPI
ccsm@PROBE3:~/pmacct-master$ cd /usr/local/nDPI/src/
ccsm@PROBE3:/usr/local/nDPI/src/lib$ ls
libndpi.a     libndpi.so.2.8.0  ndpi_content_match.c.inc  protocols
libndpi.so    Makefile          ndpi_main.c               third_party
libndpi.so.2  Makefile.in       ndpi_main.o
ccsm@PROBE3:/usr/local/nDPI/src/lib$ cd /usr/local/nDPI/src/include/
ccsm@PROBE3:/usr/local/nDPI/src/include$ ls
Makefile.am       ndpi_define.h     ndpi_protocol_ids.h  ndpi_win32.h
ndpi_api.h        ndpi_define.h.in  ndpi_protocols.h     stamp-h1
ndpi_config.h     ndpi_includes.h   ndpi_typedefs.h
ndpi_config.h.in  ndpi_main.h       ndpi_unix.h
ccsm@PROBE3:/usr/local/nDPI/src/include$ ndpiReader -r
ndpiReader - nDPI (2.8.0-1457-003547a)
ccsm@PROBE3:/usr/local/lib/pkgconfig$ ls
libndpi.pc  rdkafka.pc  rdkafka++.pc

I have installed it in correct path.
