### ISSUE TITLE
Support elasticsearch as a output plugin

### ISSUE THREAD

**Issue by netixx** [pmacct/pmacct#284]
Elasticsearch is a scalable storage/query solution that is well suited for network trafic (eg. it has the type for ip addresses). Other solution currently leverage ELK, such as [elastiflow](https://github.com/robcowart/elastiflow), but the logstash component does not scale and is not able to perform any temporal or spatial aggregation. The ELK suite already provides a GUI (Kibana) which enables immediate dashboarding, temporal and spacial, easily customisable to the many different needs of the user. Also the whole suite is open source, with optional support contract which makes it a good choice for many companies.

I think it would be a very nice addition to the output plugins of pmacct, enabling users to immediately leverage the value of the network data, without having to do any development of any sort, as opposed to the current situation (at least if dashboards are the goal).

This could apply to network, BGP and telemetry data as well.

**Comment by paololucente** [comment]
Hi @netixx ,

There are a couple of aspects to consider for the why there is not an ES plugin:

1) the space of noSQL databases is vibrant and every few months - for some years now - there is a great new product being rolled out; each product comes with its own API, its peculiarities, etc. As you may imagine it is difficult to track them all down. This is why currently pmacct outputs to brokers like Kafka and RabbitMQ (and, just for completeness, there is on the way a plugin to output to ZeroMQ) from where it is easy to pick up data from pretty much any noSQL database;

2) regardless of logstash, one may wonder whether ES is at all a good solution for data that is already well structured; in my personal opinion it is not and comparing numbers for some deployments at scale that was obvious (like ES may take twice the resources of other databases). I only acknowledge ES has a good ecosystem around it. To expand a bit my thoughts on this you may read https://imply.io/post/kappa-architecture-at-ntt . 

This all said, are you aware of the https://github.com/pierky/pmacct-to-elasticsearch project to facilitate your ingestion in ES? I am sure the super-good @pierky will be super happy to hear if you hit any scalability issues using his code.

Hopefully you don't mind if i close this issue. Super happy if you would like to continue conversation on this very interesting topic, please hit me by unicast email. 

Paolo

**Comment by netixx** [comment]
Thank you for you insights. I will definitely look at druid (which I never heard of before).

Basically my point of view about pmacct is that it's an efficient and very powerfull tool, however, it is complicated to push because it lacks a complete ecosystem (such as storage and visualisation).

I think proposing/documenting an end-to-end solution that scales (with pmacct at it's base) would be great to increase the reach of the tool (and why not use druid/superset if it's more suited).

**Comment by paololucente** [comment]
Hi @netixx ,

What you say is very true and i am with you: there are only spare efforts at a documentation that covers things end-to-end; pity, since these days building such a pipeline is way easier (and with several good options) than 10 years ago when relational databases were not a precise fit for flow analytics and seamless integration with frontend was lacking.

I would go even one step further than docs: provide a containerized low-touch demo.

Would you be willing to help with any of this?

Paolo
