### ISSUE TITLE
pmbmpd segmentation fault when kafka is down

### ISSUE THREAD

**Issue by netixx** [pmacct/pmacct#287]
I was testing the bmp server and I forgot to restart zookeeper and got the following trace:
```
# pmbmpd -f pmbmpd.conf
INFO ( default/core ): pmacct BMP Collector Daemon, pmbmpd 1.7.4-git (20190505-00)
INFO ( default/core ):  '--enable-kafka' '--enable-jansson' '--enable-plabel' '--enable-geoipv2' '--enable-zmq' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/xx/pmbmpd.conf'.
INFO ( default/core ): maximum BMP peers allowed: 4
INFO ( default/core ): waiting for BMP data on :::1790
INFO ( default/core ): [X.X.X.X] BMP peers usage: 1/4
ERROR ( default/core ): Failed to produce to topic pmacct.bmp.msglogs partition -1: Local: Queue full
ERROR ( default/core ): Connection failed to Kafka: p_kafka_close()
[1]    81893 segmentation fault  pmbmpd -f pmbmpd.conf
```

I am using this config: 
```
bmp_daemon: true
bgp_daemon_lg: true

bmp_daemon_msglog_kafka_topic: pmacct.bmp.msglogs
```

After I restarted the service correctly (zookeeper and kafka), the problem went away.

**Comment by paololucente** [comment]
Hi @netixx , i am unsuccessful reproducing the issue. Can you please check whether master code still exposes the issue? Can you also confirm what OS and OS version you are running pmacct? Finally, if the code still crashes can you please send over a gdb output? If unfamiliar with gdb, please follow instructions here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2601-#L2630 . Thanks, Paolo

**Comment by paololucente** [comment]
Hi @netixx , i did finally manage to reproduce the issue with a recent librdkafka (v1.0.0). I hence committed 8a8e5379e18a3d0b6457d8b2f349467215c532c4 and that solved the issue for me. Let me know if the fix appears to work for you too. Paolo

**Comment by netixx** [comment]
I was using `librdkafka` version `0.11.5` when I stumbled upon this issue.

I can confirm that the latest version from master fixes the issue.

Thank you!
