### ISSUE TITLE
pre tag map filter not matching in some cases

### ISSUE THREAD

**Issue by pgnuta** [pmacct/pmacct#290]
Hi there,

I'm using a pre tag map to match based on a filter expression so that i can later filter them out of the output plugin.  I'm finding that sometimes flows are not matching and being tagged.

This is the nfacctd version i'm using:
```
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20190519-00)

Arguments:
 '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
jansson 2.10

System:
Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 17:35:45 PDT 2019 x86_64

Compiler:
gcc 4.8.5
```

My config is here:
```
debug: false
daemonize: false
pidfile: /var/run/nfacctd.pid

print_cache_entries: 1000000

#nfacctd_pipe_size: 2048000000
#nfacctd_disable_checks: true

plugin_pipe_size: 10240000
plugin_buffer_size: 10240

plugins: print[nfacct]
aggregate [nfacct]: tag,tcpflags,tos,proto,src_host,dst_host,src_as,dst_as,src_port,dst_port,in_iface,out_iface,peer_src_ip
print_output_file[nfacct]: /tmp/nfacctd.json
print_output[nfacct]: json
print_history[nfacct]: 1m
print_history_roundoff[nfacct]: m
print_refresh_time[nfacct]: 60
print_trigger_exec[nfacct]: /usr/local/bin/nfacct-clickhouse-import
pre_tag_map[nfacct]: /etc/pmacct/pretag.map
#pre_tag_filter[nfacct]: !666

#aggregate [nfacct-ip]: src_host,dst_host,peer_src_ip
#print_output_file[nfacct-ip]: /tmp/nfacctd-ip.json
#print_output[nfacct-ip]: json
#print_history[nfacct-ip]: 1m
#print_history_roundoff[nfacct-ip]: m
#print_refresh_time[nfacct-ip]: 60
#print_trigger_exec[nfacct-ip]: /usr/local/bin/nfacct-ip-clickhouse-import
#
#aggregate [nfacct-as]: src_as,dst_as,peer_src_ip
#print_output_file[nfacct-as]: /tmp/nfacctd-as.json
#print_output[nfacct-as]: json
#print_history[nfacct-as]: 1m
#print_history_roundoff[nfacct-as]: m
#print_refresh_time[nfacct-as]: 60
#print_trigger_exec[nfacct-as]: /usr/local/bin/nfacct-as-clickhouse-import

timestamps_since_epoch: true
timestamps_secs: true
#timestamps_rfc3339: true
```

And here is my pre tag map file:
`set_tag=666 filter='proto 17 and (port 53 or port 123)'`

This is the example output from two aggregates, one that matched and one that didn't:
```
{"event_type": "purge", "tag": 666, "as_src": 56030, "as_dst": 133075, "peer_ip_src": "10.0.0.1", "iface_in": 1248, "iface_out": 1291, "ip_src": "114.23.98.23", "ip_dst": "103.242.68.68", "port_src": 60100, "port_dst": 123, "tcp_flags": "0", "ip_proto": "udp", "tos": 0, "stamp_inserted": "1559095020", "stamp_updated": "1559095142", "packets": 1, "bytes": 76}
{"event_type": "purge", "tag": 0, "as_src": 4826, "as_dst": 133075, "peer_ip_src": "10.0.0.6", "iface_in": 863, "iface_out": 552, "ip_src": "95.90.232.182", "ip_dst": "103.242.68.68", "port_src": 53608, "port_dst": 123, "tcp_flags": "0", "ip_proto": "udp", "tos": 0, "stamp_inserted": "1559094600", "stamp_updated": "1559095142", "packets": 2, "bytes": 152}
```

Any help would be appreciated.

**Comment by pgnuta** [comment]
In one sample file for destination port 123, ~157000 aggregate records had the '666' tag and ~25000 had a '0' tag.
destination port 53 meanwhile was 105000 records marked with tag '666' and 9000 with '0'.

**Comment by paololucente** [comment]
Hi @pgnuta , is it possible some traffic is vlan-tagged or MPLS-labelled? If so then you may want to pay attention to https://github.com/pmacct/pmacct/blob/1.7.3/QUICKSTART#L2639-#L2644 (and of course your filter should be slightly more complex to take into account both traffic, say, tagged and untagged; if it's all confirmed we can bake the filter together no problem). Let me know. Paolo

**Comment by pgnuta** [comment]
Hi Paolo,

I thought that you might be right and there were probably MPLS labels on the traffic but adding additional pre tag filters thus caught no additional aggregates:

```
set_tag=666 filter='proto 17 and (port 53 or port 123)'
set_tag=667 filter='mpls proto 17 and (port 53 or port 123)'
set_tag=668 filter='vlan proto 17 and (port 53 or port 123)'
```

I'd imagine that we're on the right track and there is some combination of libpcap filter that will match but i'm only guessing what it would be at this stage.  Is there a way to debug these IPFIX packets, dump their contents temporarily to see whats in them?

**Comment by paololucente** [comment]
Any chance you can send me a capture of relevant traffic data by unicast email?

**Comment by paololucente** [comment]
Summary: the issue was manifesting on a Ubuntu 18.04 container. Switching to bare metal and then to a Debian 9 container all worked well. We think something in the ecosystem of the first container may have caused the issue. Closing for now. Paolo
