### ISSUE TITLE
Failed to enable nfacctd_disable_checks

### ISSUE THREAD

**Issue by zhxgigi** [pmacct/pmacct#291]
Hi,
I just found nfacctd failed to enable nfacctd_disable_checks: false.
Any suggestion? 
Thanks.

nfacctd -f nfacctd-seqn.conf -d
DEBUG: [nfacctd-seqn.conf] plugin name/type: 'default'/'core'.
DEBUG: [nfacctd-seqn.conf] plugin name/type: 'default_print'/'print'.
DEBUG: [nfacctd-seqn.conf] daemonize:false
DEBUG: [nfacctd-seqn.conf] nfacctd_port:3057
DEBUG: [nfacctd-seqn.conf] nfacctd_ip:0.0.0.0
DEBUG: [nfacctd-seqn.conf] pidfile:/var/run/nfacctd-seqn.pid
DEBUG: [nfacctd-seqn.conf] logfile:/var/log/pmacct/nfacctd-seqn.log
DEBUG: [nfacctd-seqn.conf] aggregate:export_proto_seqno, flows, peer_src_ip
DEBUG: [nfacctd-seqn.conf] print_refresh_time:60
DEBUG: [nfacctd-seqn.conf] print_history:1m
DEBUG: [nfacctd-seqn.conf] print_output:csv
DEBUG: [nfacctd-seqn.conf] print_output_file:/data/flowseq/netflows-%Y%m%d-%H%M.txt
DEBUG: [nfacctd-seqn.conf] print_output_file_append:true
DEBUG: [nfacctd-seqn.conf] print_history_roundoff:m
DEBUG: [nfacctd-seqn.conf] nfacctd_pipe_size:2048000000
DEBUG: [nfacctd-seqn.conf] nfacctd_disable_checks:false
WARN: [nfacctd-seqn.conf:23] Invalid value. Ignored.
DEBUG: [nfacctd-seqn.conf] debug:true

cat nfacctd-seqn.conf

daemonize: false
nfacctd_port: 3057
nfacctd_ip: 0.0.0.0
pidfile: /var/run/nfacctd-seqn.pid
logfile: /var/log/pmacct/nfacctd-seqn.log

!
plugins: print
!
aggregate: export_proto_seqno, flows, peer_src_ip
!aggregate: src_host, dst_host, src_port, dst_port, export_proto_seqno, flows, peer_src_ip
!
print_refresh_time: 60
print_history: 1m
print_output: csv
print_output_file: /data/flowseq/netflows-%Y%m%d-%H%M.txt
print_output_file_append: true
print_history_roundoff: m
!

nfacctd_disable_checks: false

:/mnt/pmacct# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.3-git (20190418-00+c4)

Arguments:
 '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
jansson 2.11

System:
Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64

Compiler:
gcc 7.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

**Comment by paololucente** [comment]
Hi @zhxgigi , thank you for reporting this issue. It should be solved now, can you try master code working for you? Thanks, Paolo

**Comment by zhxgigi** [comment]
Hi @paololucente , 
Build failed using master branch.

./.libs/libdaemons.a(libpmfilters_la-bloom.o): In function `bloom_init':
/root/pmacct/src/filters/bloom.c:96: undefined reference to `log'
collect2: error: ld returned 1 exit status
Makefile:769: recipe for target 'pmacctd' failed
make[2]: *** [pmacctd] Error 1
make[2]: Leaving directory '/root/pmacct/src'
Makefile:1234: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/pmacct/src'
Makefile:726: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


~/pmacct# git log -p -1
commit 6e29a6a6aa76dc8fce251d9e4d1b027e2b22296b (HEAD -> master, origin/master, origin/HEAD)
Author: Paolo Lucente <pl+github@pmacct.net>
Date:   Tue Jun 4 17:04:03 2019 +0000

    * fix, cfg_handlers: [sn]facctd_disable_checks and nfacctd_disable_opt_scope_check could not be properly set to false. To solve Issue #291.

**Comment by zhxgigi** [comment]
I patched to branch 1.7.3 and it works, thanks.

2019-06-05T06:32:01Z INFO ( default_print/print ): *** Purging cache - START (PID: 7871) ***
2019-06-05T06:32:01Z INFO ( default_print/print ): *** Purging cache - END (PID: 7871, QN: 0/0, ET: X) ***
2019-06-05T06:32:01Z INFO ( default/core ): expecting flow '777445' but received '777452' collector=0.0.0.0:3057 agent=10.6.5.88:0
2019-06-05T06:32:01Z INFO ( default/core ): expecting flow '777452' but received '777460' collector=0.0.0.0:3057 agent=10.6.5.88:0
2019-06-05T06:32:01Z INFO ( default/core ): expecting flow '777460' but received '777468' collector=0.0.0.0:3057 agent=10.6.5.88:0

**Comment by paololucente** [comment]
Hi @zhxgigi, Thank you for confirming. I will close this issue then. Will look into the log() issue. Paolo
