### ISSUE TITLE
pgsql plugin "Abnormal exit status detected"

### ISSUE THREAD

**Issue by nansenat16** [pmacct/pmacct#298]
I try to upgrade an old pmacct to last version and postgresql-11
OS CentOS  7.6.1810
Postgresql 11 install from official site
But don't have not row insert to Postgresql

[root@tflow-new ~]# rpm -qa postgresql11*
postgresql11-libs-11.4-1PGDG.rhel7.x86_64
postgresql11-11.4-1PGDG.rhel7.x86_64
postgresql11-server-11.4-1PGDG.rhel7.x86_64
postgresql11-devel-11.4-1PGDG.rhel7.x86_64

pmacctd.conf
aggregate:src_host, dst_host, src_port, dst_port, proto
plugins:pgsql
interface:ens19
interface_wait:true
sql_history:1m
sql_locking_style:row
sql_refresh_time:60
sql_table:acct_v6_%Y%m%d
sql_table_schema:/var/tflow/etc/pmacct-create-dynamic-table_v6.pgsql
sql_table_version:6
sql_host:127.0.0.1
sql_user:pmacct
sql_passwd:sianit

[root@tflow-new bin]# /var/tflow/bin/pmacctd -d -f /var/tflow/etc/pmacctd.conf
DEBUG: [/var/tflow/etc/pmacctd.conf] plugin name/type: 'default'/'core'.
DEBUG: [/var/tflow/etc/pmacctd.conf] plugin name/type: 'default_pgsql'/'pgsql'.
DEBUG: [/var/tflow/etc/pmacctd.conf] aggregate:src_host, dst_host, src_port, dst_port, proto
DEBUG: [/var/tflow/etc/pmacctd.conf] interface:ens19
DEBUG: [/var/tflow/etc/pmacctd.conf] interface_wait:true
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_history:1m
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_locking_style:row
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_refresh_time:60
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_table:acct_v6_%Y%m%d
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_table_schema:/var/tflow/etc/pmacct-create-dynamic-table_v6.pgsql
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_table_version:6
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_host:127.0.0.1
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_user:pmacct
DEBUG: [/var/tflow/etc/pmacctd.conf] sql_passwd:pmacct
DEBUG: [/var/tflow/etc/pmacctd.conf] debug:true
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.3-git (20190418-00+c4)
INFO ( default/core ):  '--enable-pgsql' '--enable-geoipv2' '--disable-shared' '--with-pcap-libs=/root/libpcap-1.9.0' '--with-pcap-includes=/root/libpcap-1.9.0' 'PGSQL_CFLAGS=-I/usr/pgsql-11/include/' 'PGSQL_LIBS=-L/usr/pgsql-11/lib -lpq' 'GEOIPV2_CFLAGS=-I/usr/local/geoipv2/include' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/var/tflow/etc/pmacctd.conf'.
INFO ( default_pgsql/pgsql ): plugin_pipe_size=4096000 bytes plugin_buffer_size=344 bytes
INFO ( default_pgsql/pgsql ): ctrl channel: obtained=212992 bytes target=95248 bytes
INFO ( default/core ): [ens19,0] link type is: 1
WARN ( default/core ): ens19: no IPv4 address assigned
INFO ( default_pgsql/pgsql ): cache entries=32771 base cache memory=13648736 bytes
INFO ( default_pgsql/pgsql ): *** Purging cache - START (PID: 10393) ***
INFO ( default_pgsql/pgsql ): *** Purging cache - END (PID: 10393, QN: 0/0, ET: X) ***
INFO ( default_pgsql/pgsql ): *** Purging cache - START (PID: 10394) ***
WARN ( default_pgsql/pgsql ): Abnormal exit status detected for child PID 10394
INFO ( default_pgsql/pgsql ): *** Purging cache - START (PID: 10397) ***
WARN ( default_pgsql/pgsql ): Abnormal exit status detected for child PID 10397
INFO ( default_pgsql/pgsql ): *** Purging cache - START (PID: 10399) ***

**Comment by nansenat16** [comment]
i try rollback old release on same host
the pgsql plugin is broken on pmacctd 1.7.1-git (20180331-00+c3) or newer

this is working for me:
Promiscuous Mode Accounting Daemon, pmacctd 1.7.0-git (20170924-00)

Arguments:
 '--enable-pgsql' '--enable-geoipv2' '--disable-shared' '--with-pcap-libs=/root/libpcap-1.9.0' '--with-pcap-includes=/root/libpcap-1.9.0' 'PGSQL_CFLAGS=-I/usr/include/pgsql/' 'PGSQL_LIBS=-L/usr/lib64/pgsql -lpq' 'GEOIPV2_CFLAGS=-I/usr/local/geoipv2/include' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
PostgreSQL 90224
MaxmindDB 1.3.2

System:
Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64

**Comment by paololucente** [comment]
Hi @nansenat16 ,

Thank you for reporting this. I am puzzled on where the issue may be because two things at a time were changed: first you have pmacct 1.7.3 against PostgreSQL 11 and then you have pmacct 1.7.0 with PostgreSQL 9 (90224). So is it the PostgreSQL release or the pmacct version?

I sense there is a process crash. Can you please follow instructions here: https://github.com/pmacct/pmacct/blob/1.7.3/QUICKSTART#L2578-#L2593 and then re-run pmacct 1.7.3 against PostgreSQL 11? Inspecting the core dump file may give useful info on what is going on.

Paolo

**Comment by nansenat16** [comment]
Hi @paololucente ,

My old pmacct is 0.14.3( 20130503-00) with postgresql 8.

1. First time i try to use postgresql-11 with pmacct 1.7.4(from git) => not work
2. i try to downgrade postgresql10/9.6/9.2(CentOS included) with pmacct 1.7.3 => not work
3. i try to dongrade pmacctd 1.6.0-git (20160112-02) with postgresql 9.2(distro version) => work
4. upgrade to pmacctd 1.7.0-git (20170924-00) with postgresql 9.2 => work
5. upgrade to pmacctd 1.7.1-git (20180331-00+c3) wthi postgresql 9.2 => not work

I have no time use pmacct 1.7.0 with postgresql-11 on yesterday
The next few day ,i  wil try it

**Comment by nansenat16** [comment]
@paololucente 

I get core dump.
Does it mean execute extended command path argument failed

(gdb) bt
#0  0x000000000042d37c in handle_dynname_internal_strings (
    new=0x7ffc05be1f30 "--\r\n-- # su - postgres  (or whatever your database runs as ... usually postgres)\r\n-- $ psql -d pmacct -f pmacct-create-table_v6.pgsql \r\n--\r\n\r\n-- Tables \r\n-- DROP TABLE acct_v6_%Y%m%d;\r\nCREATE TABLE ac"..., newlen=8224,
    old=0x7ffc05be3f50 "--\r\n-- # su - postgres  (or whatever your database runs as ... usually postgres)\r\n-- $ psql -d pmacct -f pmacct-create-table_v6.pgsql \r\n--\r\n\r\n-- Tables \r\n-- DROP TABLE acct_v6_%Y%m%d;\r\nCREATE TABLE ac"..., prim_ptrs=0x7ffc05be6120, type=5) at util.c:527
#1  0x000000000042e75a in handle_dynname_internal_strings_same (
    s=0x7ffc05be3f50 "--\r\n-- # su - postgres  (or whatever your database runs as ... usually postgres)\r\n-- $ psql -d pmacct -f pmacct-create-table_v6.pgsql \r\n--\r\n\r\n-- Tables \r\n-- DROP TABLE acct_v6_%Y%m%d;\r\nCREATE TABLE ac"..., max=8224,
    tmp=0x7ffc05be1f30 "--\r\n-- # su - postgres  (or whatever your database runs as ... usually postgres)\r\n-- $ psql -d pmacct -f pmacct-create-table_v6.pgsql \r\n--\r\n\r\n-- Tables \r\n-- DROP TABLE acct_v6_%Y%m%d;\r\nCREATE TABLE ac"..., prim_ptrs=0x7ffc05be6120, type=5) at util.c:863
#2  0x00000000004b6ca5 in sql_create_table (db=0x8e95a0 <p>, basetime=0x7f159ecb7e50,
    prim_ptrs=0x7ffc05be6120) at sql_common.c:3399
#3  0x000000000049740f in PG_cache_purge (queue=0x7f15a43d9010, index=4, idata=0x7ffc05be6da0)
    at pgsql_plugin.c:493
#4  0x000000000049d90d in sql_exit_gracefully (signum=2) at sql_common.c:1070
#5  <signal handler called>
#6  0x00007f15a31ca370 in __poll_nocancel () from /lib64/libc.so.6
#7  0x0000000000495ddc in pgsql_plugin (pipe_fd=3, cfgptr=0x150abb8, ptr=0x858be0 <channels_list>)
    at pgsql_plugin.c:115
#8  0x000000000043527d in load_plugins (req=0x7ffc05c03590) at plugin_hooks.c:289
#9  0x000000000042a3a6 in main (argc=4, argv=0x7ffc05c03878, envp=0x7ffc05c038a0) at pmacctd.c:922

**Comment by nansenat16** [comment]
I fixed the issue. This problem occurs when the contents of the external SQL script contain $ char (0x24).

**Comment by paololucente** [comment]
Hi @nansenat16 , thank you very much for sharing your results. I have updated documentation to encourage not to include unnecessary stuff (comments, strings, characters) besides just the SQL statement. Paolo
