### ISSUE TITLE
/bin/ld: cannot find -lz  collect2: error: ld returned 1 exit status error while sudo make install

### ISSUE THREAD

**Issue by shinojpremaraj** [pmacct/pmacct#300]
Hi,
I am getting following issue "**/bin/ld: cannot find -lz**"  while issuing command "make install" for pmacct installation steps. This is the complete error I am getting while make. I am installing pmacct on Centos 7. And this is for configuring pmacct for bgp data analytics.

/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
gmake[2]: *** [pmacctd] Error 1
gmake[2]: Leaving directory `/home/shinu/pmacct/src'
gmake[1]: *** [install-recursive] Error 1
gmake[1]: Leaving directory `/home/shinu/pmacct/src'
make: *** [install-recursive] Error 1
Thank you for your help in advance.

**Comment by paololucente** [comment]
Hi @shinojpremaraj ,

It should be because you don't have zlib (dev) package installed. Can you please have it installed for your system and try again?

Paolo

**Comment by shinojpremaraj** [comment]
Thanks a million Paolo. It works for me after installing # yum install zlib-devel.
