### ISSUE TITLE
pmtelemetryd error : telemetry_decode_zmq_peer(): invalid telemetry node JSON received: '[' or '{' expected

### ISSUE THREAD

**Issue by Trasmontinho** [pmacct/pmacct#303]
Hello, 

First of all Congratulation for a such great tool. 

I'm trying to use pmacctd solution in order to collect telemetry datas from huawei equipment and modelise the data collected by telemetry on Kibana (I've attached an Image of what I'm trying to build).

In my case I've commented in pmgrpcd script all functions related to Cisco as I haven't the Cisco dialout protos. 

I'v launched in my case pmtelemetryd with the config file attached (you will find also th pmgrpcd file modified) 

After launching pmgrpcd.py file, I see on debug  of pmtelemetryd the message below : 
" telemetry_decode_zmq_peer(): invalid telemetry node JSON received: '[' or '{' expected."

I've been looking a bit the subject (but not an expert in development) without any answer on it. 

could you help me please ?

Just for your information, the v1 works well for me.
Thanks, 

Regards, 
![trial pmacctd](https://user-images.githubusercontent.com/53441739/62063202-b9f93b80-b22a-11e9-80af-9d757ccf0227.JPG)
[telemetry_configs.zip](https://github.com/pmacct/pmacct/files/3443258/telemetry_configs.zip)

Sam

**Comment by paololucente** [comment]
Hi @Trasmontinho ,

Thank you very much for your kind words. I was looking for some more info to see how i can help you better.

The output files in 'spool' are produced by pmtelemetryd, true? Are they produced with the 'v1' setup? Or is the error you mention intermittent, ie. some elements are received correctly by pmtelemetryd and some others are not?

Also, but this is a different point, are you mono-vendor with Huawei? If so, you may very well keep using 'v1' if it works well for you since the 'v2' effort is precisely aimed at multi-vendor setups. 

Paolo

**Comment by Trasmontinho** [comment]
Hi @paololucente,

Thank you for your quick answer. I've got so manny question for you lol :-)

Actually I work for a SP and try your tool for Huawei equipment but the idea after that is to try it in a few months with Nokia & Cisco that's why the generic fashion of the v2 is interesting in term of testing and try to sell this tool internally as the best swiss knife :-P.

You're right spool has been created just to try the v1 with flat files. My idea right now is to send the data collected by the v2 and forward it directly to the zookeper which is based in the second server. I would have appreciated to do both flat files with zmq & kafka but I haven't found how have seen in the differents exchanges on Github that is not possible right ? 

Below the step by step of my testing : 
I've started first pmtelemetryd with the pmtelemetryd.conf (in the zip file)
I've started then the pmgrpcd.py.

At the difference with the v1, I've never seen in the session where pmtelemetryd is started, the number of peers incremented.

few seconds after the start of the python script  I've got directly the message below. I've tried to make some debug on the python script but I'm not sure of my results of debugging.

pmtelemetryd -f /opt/collector/telemetry/pmtelemetryd.conf 
INFO ( (null)/core ): Streaming Network Telemetry Daemon, pmtelemetryd 1.7.3-git (20190418-00+c4)
INFO ( (null)/core ):  '--enable-zmq' '--enable-kafka' '--enable-jansson' '--enable-avro' 'AVRO_CFLAGS=-I/include' 'AVRO_LIBS=-L/lib -lavro' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/opt/collector/telemetry/pmtelemetryd.conf'.
INFO ( default/core ): maximum telemetry peers allowed: 100
INFO ( default/core ): telemetry peers timeout: 300
INFO ( default/core ): reading telemetry data from ZeroMQ tcp://127.0.0.1:50001
WARN ( default/core ): telemetry_decode_zmq_peer(): invalid telemetry node JSON received: '[' or '{' expected.
WARN ( default/core ): telemetry_decode_zmq_peer(): invalid telemetry node JSON received: '[' or '{' 
.....

**Comment by paololucente** [comment]
Hi @Trasmontinho ,

Thank you for the extra insight, it also makes sense why you are aiming to v2 instead of v1. Let me say a reviewed version of v2 collector is in the works with many bug fixes and performances improvements. This said, i've just made a commit where, if you set 'debug: true' in pmtelemetryd config, you should get a print out of the JSON object that fails to parse:

https://github.com/pmacct/pmacct/commit/347f37821956487c30de59f3085d4436a9ef9f92

It's a very simple patch, feel free to just apply it to the code you are currently running or download master code here from GitHub. Please return me (here or by unicast email if there is any sensible info) the output as it would give us a hint of what is going on. I'd not exclude we may be simply in presence of an empty object that failed to transform correctly inside the Python code. 

Paolo

**Comment by Trasmontinho** [comment]
Hello @paololucente.

I've do so. 

Below the output of the debug.I've just modified deleted the name & IP address of the equipment to put it as generic as possible ;-). By default the activation of the telemetry datas on the equipment are for all the interfaces. I've just picked one of the different debug messages. 

DEBUG ( default/core ): "{\n  \"collector\":{\n    \"data\":{\n      \"collection_end_time\":\"1564563963954\",\n      \"collection_id\":\"68006\",\n      \"collection_start_time\":\"1564563963954\",\n      \"collection_timestamp\":1564563963789,\n      \"current_period\":10000,\n      \"except_desc\":\"OK\",\n      \"msg_timestamp\":\"1564563964026\",\n      \"node_id_str\":\"TOTO\",\n      \"product_name\":\"NE40E\",\n      \"sensor_path\":\"huawei-ifm:ifm\\/interfaces\\/interface\\/ifStatistics\\/ethPortErrSts\",\n      \"subscription_id_str\":\"testsamadherent\",\n      \"timestamp\":\"1564563963954\"\n    },\n    \"grpc\":{\n      \"grpcPeer\":\"A.B.C.D\",\n      \"ne_vendor\":\"Huawei\"\n    }\n  },\n  \"interfaces\":{\n    \"interface\":[\n      {\n        \"ifAdminStatus\":0,\n        \"ifIndex\":0,\n        \"ifName\":\"GigabitEthernet0\\/4\\/0\",\n        \"ifStatistics\":{\n          \"ethPortErrSts\":{\n            \"rxAlignment\":\"0\",\n            \"rxCRC\":\"0\",\n            \"rxFragment\":\"0\",\n            \"rxInrangeLen\":\"0\",\n            \"rxJabber\":\"0\",\n            \"rxJumboOctets\":\"0\",\n            \"rxLong\":\"0\",\n            \"rxOverrun\":\"0\",\n            \"rxPause\":\"0\",\n            \"rxSymbol\":\"0\",\n            \"rxUndersize\":\"0\",\n            \"txJumboOctets\":\"0\",\n            \"txLost\":\"0\",\n            \"txOverrun\":\"0\",\n            \"txPause\":\"0\",\n            \"txSystem\":\"0\",\n            \"txUnderrun\":\"0\"\n          },\n          \"rcvBroadPacket\":\"0\",\n          \"rcvMutiPacket\":\"0\",\n          \"rcvUniPacket\":\"0\",\n          \"receiveByte\":\"0\",\n          \"receivePacket\":\"0\",\n          \"sendBroadPacket\":\"0\",\n          \"sendByte\":\"0\",\n          \"sendMutiPacket\":\"0\",\n          \"sendPacket\":\"0\",\n          \"sendUniPacket\":\"0\"\n        }\n      }\n    ]\n  }\n}"

**Comment by Trasmontinho** [comment]
@paololucente, 

After a quick look into the json message (not sure of what I've found is the right root cause). It seems that the json decoding is based on a RFC which is not the RFC format message of Huawei. Trying to check the conformity of the message on https://jsonformatter.curiousconcept.com/, I've seen that depending on the RFC standard the message is well formated or not. In the case of Huawei it seems that the RFC supported is the 7159

**Comment by Trasmontinho** [comment]
@paololucente 

For your information, I've tried with mitigation activated in the telemetry.conf. The error disapeared but still without any data in the zmq.

**Comment by paololucente** [comment]
Hi @Trasmontinho , 

Thank you for the debug output. The JSON object itself looks proper, I then have a tragic suspect: we may have extra trailing and ending quotes in the message making it not parseable by the JSON library.

Can you please edit lines 461 and 475 of pmgrpcd.py. They both are:

`zmqSock.send_json("%s" % jsonTelemetryData)`

Can you change them to:

`zmqSock.send_json(jsonTelemetryData)`

And see if it works?

Thanks,
Paolo

**Comment by Trasmontinho** [comment]
Hello  @paololucente ,

Tried it and there's no change on the result. I've tried with the stable version of the script (1.7.3) and the one in github.

Below the debug results :

DEBUG ( default/core ): "{\n  \"collector\":{\n    \"data\":{\n      \"collection_end_time\":\"1564749455256\",\n      \"collection_id\":\"86554\",\n      \"collection_start_time\":\"1564749455256\",\n      \"collection_timestamp\":1564749454866,\n      \"current_period\":10000,\n      \"except_desc\":\"OK\",\n      \"msg_timestamp\":\"1564749455323\",\n      \"node_id_str\":\"HOSTNAME\",\n      \"product_name\":\"NE40E\",\n      \"sensor_path\":\"huawei-ifm:ifm\\/interfaces\\/interface\",\n      \"subscription_id_str\":\"testsamadherent\",\n      \"timestamp\":\"1564749455256\"\n    },\n    \"grpc\":{\n      \"grpcPeer\":\"A.B.C.D\",\n      \"ne_vendor\":\"Huawei\"\n    }\n  },\n  \"interfaces\":{\n    \"interface\":[\n      {\n        \"ifAdminStatus\":1,\n        \"ifIndex\":155,\n        \"ifName\":\"Virtual-Ethernet0\\/7\\/1\"\n      }\n    ]\n  }\n}"
WARN ( default/core ): telemetry_decode_zmq_peer(): invalid telemetry node JSON received: '[' or '{' expected.
DEBUG ( default/core ): "{\n  \"collector\":{\n    \"data\":{\n      \"collection_end_time\":\"1564749455256\",\n      \"collection_id\":\"86554\",\n      \"collection_start_time\":\"1564749455256\",\n      \"collection_timestamp\":1564749454867,\n      \"current_period\":10000,\n      \"except_desc\":\"OK\",\n      \"msg_timestamp\":\"1564749455323\",\n      \"node_id_str\":\"HOSTNAME\",\n      \"product_name\":\"NE40E\",\n      \"sensor_path\":\"huawei-ifm:ifm\\/interfaces\\/interface\",\n      \"subscription_id_str\":\"testsamadherent\",\n      \"timestamp\":\"1564749455256\"\n    },\n    \"grpc\":{\n      \"grpcPeer\":\"A.B.C.D\",\n      \"ne_vendor\":\"Huawei\"\n    }\n  },\n  \"interfaces\":{\n    \"interface\":[\n      {\n        \"ifAdminStatus\":1,\n        \"ifIndex\":156,\n        \"ifName\":\"Virtual-Ethernet0\\/7\\/1.4078\"\n      }\n    ]\n  }\n}"

**Comment by Trasmontinho** [comment]
By the way, If you want help for the testing of your different enhancement on Telemetry, with the tool, I would be happy to do my best for the progress of it ;-)

Thanks again for your help.

Sam

**Comment by paololucente** [comment]
Hi @Trasmontinho , just an interim update: there is some testing ongoing at our side and, in parallel, some new code that will effectively become v3 (and will make us retire v2; v1 will stay instead). Just to say we are on it but will need a bit more time (days / week(s)). Would love if you could help us testing the new code once it's out. Paolo

**Comment by Trasmontinho** [comment]
Hi @paololucente ,

No problem it would be a pleasure keep me posted, I'll be out for 3 weeks but it would be a pleasure to help on it as I'll be back to work. ;-)

Sam

**Comment by Trasmontinho** [comment]
Hi @paololucente, 

I've integrated all the Huawei protos in the v1 code . If you would like, it would be a pleasure to share it for the v1.

By the way, I'm using of the Huawei Protos. In my case an IP address is transmitted in UINT32 format by GRPC, by default the decoder is acting well and make the treatment on it as an integer value. I would like to know if there's a way from your opinion to convert it in IP address before sending it in the ZMQ.

Don't hesitate to consult me if you need some testing on th e V3 for huawei :-)

Thanks for your answer :)

Regards, 

Samuel CAMELO

**Comment by paololucente** [comment]
Hi Sam ( @Trasmontinho ), thanks very much for the feedback and the tip wrt the IP address. About v3 testing, which we'd love you to be part of, would you mind moving this thread to unicast email? Then we can summarize things back for the general public at the end. Paolo

**Comment by Trasmontinho** [comment]
Hi @paololucente , 

Just for your information, I've sent you an unicast mail directly on the mail found in your website ;-)
