### ISSUE TITLE
Problem with timestamps

### ISSUE THREAD

**Issue by utepnetlab** [pmacct/pmacct#305]
Hello,

I am using pmacctd to generate NetFlow to a CSV file using the following config:

daemonize: false
pcap_interface: ens33
snaplen: 70000
print_output: csv
print_output_file_append: true
timestamps_utc: true
timestamps_since_epoch: true
!
plugins: print
!
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, timestamp_start, timestamp_end

Problem 1: The timestamp_end field in the output CSV is always 0.
Problem 2: The output lines are packets, not flow records; the PACKETS field is always 1.

If I do not include timestamp_start in the aggregate list then the output lines are flow records with multiple packets.

What am I doing wrong?

Thanks for any help!

**Comment by paololucente** [comment]
Hi @utepnetlab ,

To generate NetFlow out of data collected with libpcap you should use the nfprobe plugin, here is how to configure it: https://github.com/pmacct/pmacct/blob/1.7.3/QUICKSTART#L1175-L1310 . You can export locally on the loopback interface where nfacctd, the NetFlow collector daemon, listens for NetFlow and writes to a file in CSV format (pretty much with the same config you have got above, you can remove 'snaplen' and 'pcap_interface').

Paolo

**Comment by utepnetlab** [comment]
Paolo,

Thank you for taking the time to help us with this. It looks like it is working.

Best wishes!
