### ISSUE TITLE
Unknown column 'timestamp_min' in 'where clause' ERROR ( c/mysql ): while running pmacctd

### ISSUE THREAD

**Issue by shinojpremaraj** [pmacct/pmacct#307]
Hi,
I am getting the following error while running pmacctd, also no items are displayed on the mysql table "acct". 

DEBUG ( c/mysql ): FAILED query follows:
UPDATE `acct` SET packets=packets+2, bytes=bytes+212 WHERE ip_src='fe80::fc7f:7532:4e7e:8c88' AND ip_dst='ff02::fb' AND ip_proto='udp' AND timestamp_min=FROM_UNIXTIME(1565178175) AND timestamp_max=FROM_UNIXTIME(1565178218)
**ERROR ( c/mysql ): Unknown column 'timestamp_min' in 'where clause'**
And the messages are same for all IPs I configured on the interfaces.

Thank you in advance for your help in this.

**Comment by paololucente** [comment]
Hi @shinojpremaraj , i was wondering if you did add the column when creating the table 'acct'. See: https://github.com/pmacct/pmacct/blob/master/sql/README.timestamp and more in general see https://github.com/pmacct/pmacct/blob/master/sql/README.mysql . Paolo

**Comment by shinojpremaraj** [comment]
Hi @paololucente The error goes off after adding those columns on tablle "acct" but it gives me another error.
DEBUG ( c/mysql ): FAILED query follows:
INSERT INTO `acct` (ip_src, ip_dst, ip_proto, timestamp_min, timestamp_max, packets, bytes) VALUES ('fe80::fc7f:7532:4e7e:8c88', 'ff02::1:2', 'udp', FROM_UNIXTIME(1565274661), FROM_UNIXTIME(1565274702), 6, 858)
**ERROR ( c/mysql ): Field 'mac_src' doesn't have a default value**
-Shinoj

**Comment by shinojpremaraj** [comment]
Hi @paololucente That issue has been resolved.

-Thanks
Shinoj

**Comment by paololucente** [comment]
Hi @shinojpremaraj , thank you for confirming.
