### ISSUE TITLE
Compilation fail - Make error 1

### ISSUE THREAD

**Issue by DaveSimmo** [pmacct/pmacct#310]
Hi

I am trying to compile pmacct from the current source, cloned from GIT, on Ubuntu 18.04.2 LTS, and I get the following error log:-

~/pmacct$ sudo make install

Making install in src
make[1]: Entering directory '/home/user1/pmacct/src'
Making install in nfprobe_plugin
make[2]: Entering directory '/home/user1/pmacct/src/nfprobe_plugin'
make[3]: Entering directory '/home/user1/pmacct/src/nfprobe_plugin'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/nfprobe_plugin'
make[2]: Leaving directory '/home/user1/pmacct/src/nfprobe_plugin'
Making install in sfprobe_plugin
make[2]: Entering directory '/home/user1/pmacct/src/sfprobe_plugin'
make[3]: Entering directory '/home/user1/pmacct/src/sfprobe_plugin'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/sfprobe_plugin'
make[2]: Leaving directory '/home/user1/pmacct/src/sfprobe_plugin'
Making install in bgp
make[2]: Entering directory '/home/user1/pmacct/src/bgp'
make[3]: Entering directory '/home/user1/pmacct/src/bgp'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/bgp'
make[2]: Leaving directory '/home/user1/pmacct/src/bgp'
Making install in tee_plugin
make[2]: Entering directory '/home/user1/pmacct/src/tee_plugin'
make[3]: Entering directory '/home/user1/pmacct/src/tee_plugin'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/tee_plugin'
make[2]: Leaving directory '/home/user1/pmacct/src/tee_plugin'
Making install in isis
make[2]: Entering directory '/home/user1/pmacct/src/isis'
make[3]: Entering directory '/home/user1/pmacct/src/isis'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/isis'
make[2]: Leaving directory '/home/user1/pmacct/src/isis'
Making install in bmp
make[2]: Entering directory '/home/user1/pmacct/src/bmp'
make[3]: Entering directory '/home/user1/pmacct/src/bmp'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/bmp'
make[2]: Leaving directory '/home/user1/pmacct/src/bmp'
Making install in telemetry
make[2]: Entering directory '/home/user1/pmacct/src/telemetry'
make[3]: Entering directory '/home/user1/pmacct/src/telemetry'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/telemetry'
make[2]: Leaving directory '/home/user1/pmacct/src/telemetry'
Making install in rpki
make[2]: Entering directory '/home/user1/pmacct/src/rpki'
make[3]: Entering directory '/home/user1/pmacct/src/rpki'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/rpki'
make[2]: Leaving directory '/home/user1/pmacct/src/rpki'
Making install in filters
make[2]: Entering directory '/home/user1/pmacct/src/filters'
make[3]: Entering directory '/home/user1/pmacct/src/filters'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/user1/pmacct/src/filters'
make[2]: Leaving directory '/home/user1/pmacct/src/filters'
make[2]: Entering directory '/home/user1/pmacct/src'
  CC       libdaemons_la-net_aggr.lo
net_aggr.c: In function ‘load_networks4’:
net_aggr.c:151:23: warning: pointer targets in passing argument 1 of ‘strlcpy’ differ in signedness [-Wpointer-sign]
               strlcpy(tmpt->table[eff_rows].plabel, plabel, PREFIX_LABEL_LEN);
                       ^~~~
In file included from net_aggr.c:23:0:
pmacct.h:410:8: note: expected ‘char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 size_t strlcpy(char *, const char *, size_t);
        ^~~~~~~
net_aggr.c:139:28: error: unused variable ‘endptr’ [-Werror=unused-variable]
             char *plabel, *endptr;
                            ^~~~~~
net_aggr.c: In function ‘search_src_host_label’:
net_aggr.c:963:54: warning: pointer targets in passing argument 1 of ‘label_to_addr’ differ in signedness [-Wpointer-sign]
     if (res && res->plabel[0] != '\0') label_to_addr(res->plabel, &p->src_ip, PREFIX_LABEL_LEN);
                                                      ^~~
In file included from net_aggr.c:28:0:
addr.h:61:21: note: expected ‘const char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 extern unsigned int label_to_addr(const char *, struct host_addr *, int);
                     ^~~~~~~~~~~~~
net_aggr.c:967:56: warning: pointer targets in passing argument 1 of ‘label_to_addr’ differ in signedness [-Wpointer-sign]
     if (res6 && res6->plabel[0] != '\0') label_to_addr(res6->plabel, &p->src_ip, PREFIX_LABEL_LEN);
                                                        ^~~~
In file included from net_aggr.c:28:0:
addr.h:61:21: note: expected ‘const char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 extern unsigned int label_to_addr(const char *, struct host_addr *, int);
                     ^~~~~~~~~~~~~
net_aggr.c: In function ‘search_dst_host_label’:
net_aggr.c:979:54: warning: pointer targets in passing argument 1 of ‘label_to_addr’ differ in signedness [-Wpointer-sign]
     if (res && res->plabel[0] != '\0') label_to_addr(res->plabel, &p->dst_ip, PREFIX_LABEL_LEN);
                                                      ^~~
In file included from net_aggr.c:28:0:
addr.h:61:21: note: expected ‘const char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 extern unsigned int label_to_addr(const char *, struct host_addr *, int);
                     ^~~~~~~~~~~~~
net_aggr.c:983:56: warning: pointer targets in passing argument 1 of ‘label_to_addr’ differ in signedness [-Wpointer-sign]
     if (res6 && res6->plabel[0] != '\0') label_to_addr(res6->plabel, &p->dst_ip, PREFIX_LABEL_LEN);
                                                        ^~~~
In file included from net_aggr.c:28:0:
addr.h:61:21: note: expected ‘const char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 extern unsigned int label_to_addr(const char *, struct host_addr *, int);
                     ^~~~~~~~~~~~~
net_aggr.c: In function ‘load_networks6’:
net_aggr.c:1459:21: warning: pointer targets in passing argument 1 of ‘strlcpy’ differ in signedness [-Wpointer-sign]
             strlcpy(tmpt->table6[eff_rows].plabel, plabel, PREFIX_LABEL_LEN);
                     ^~~~
In file included from net_aggr.c:23:0:
pmacct.h:410:8: note: expected ‘char *’ but argument is of type ‘u_char * {aka unsigned char *}’
 size_t strlcpy(char *, const char *, size_t);
        ^~~~~~~
net_aggr.c:1453:28: error: unused variable ‘endptr’ [-Werror=unused-variable]
             char *plabel, *endptr;
                            ^~~~~~
cc1: all warnings being treated as errors
Makefile:960: recipe for target 'libdaemons_la-net_aggr.lo' failed
make[2]: *** [libdaemons_la-net_aggr.lo] Error 1
make[2]: Leaving directory '/home/user1/pmacct/src'
Makefile:1245: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/user1/pmacct/src'
Makefile:727: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

The goal is to set up something like this:-

https://afenioux.fr/blog/article/pmacct-sfacct-influxdb-grafana

I am attempting to compile from a Githib clone from today - 12/08/2019 - approx 4pm

**Comment by paololucente** [comment]
Hi @DaveSimmo , thank you for reporting this. I just made a commit to resolve the issue. Paolo

**Comment by DaveSimmo** [comment]
Hi @paololucente - that compiled - thank you!
