### ISSUE TITLE
issue with custom primitives

### ISSUE THREAD

**Issue by carlos-alcan** [pmacct/pmacct#319]
I am running pmacctd and nfacctd with the intent of labeling the exported flows with custom primitives, specifically from IPFIX packtes, but I am unable to add custom primitives. I have followed the Quickstart guide but found no success. I have attached the pmacctd and nfacctd config files along with the custom list.

- pmacctd config file:
`interface: enp2s0`
`aggregate_primitives: /home/netlab/custom.lst`
`aggregate: src_host, dst_host, src_port, dst_port, proto, tos, class, sumofsq, minIPTotalLen`
`plugins: nfprobe`
`nfprobe_receiver: 127.0.0.1:2100`
`nfprobe_version: 10`

- nfacctd config file:
`!`
`plugins: print`
`!`
`aggregate_primitives: /home/netlab/custom.lst`
`aggregate: src_host, dst_host, src_port, dst_port, proto, tos, class, timestamp_start, timestamp_end, timestamp_arrival, sumofsq, minIPTotalLen`
`nfacctd_ip: 127.0.0.1`
`nfacctd_port: 2100`
`print_refresh_time: 300`
`print_output: csv`
`print_output_file: /home/netlab/netflow.txt`
`print_history: 1m`
`print_output_file_append: true`

- custom primitive file:
`name=sumofsq	field_type=198	len=8	semantics=u_int`
`name=minIPTotalLen	field_type=25	len=8	semantics=u_int`

**Comment by paololucente** [comment]
Hi @carlos-alcan ,

What version are you using (an output of 'nfacctd -V' would suffice)?

The definition of custom primitives in your example is OK for nfacctd, that is, for decoding (take a certain field type, of a certain length and interpret it in a certain way). But it is not sufficient for pmacctd to encode the wanted info: where to pick the wanted information from? So you should have two separate definitions, one for pmacctd, one for nfacctd. The one for nfacctd is fine as-is; the one for pmacctd should be augmented with a packet_ptr instruction instead.

Paolo

**Comment by carlos-alcan** [comment]
Hey Paolo, thanks for your quick response!

nfacctd version: 1.7.4-git

Could you possibly provide an example of this or point me in the right direction to see how to augment with the packet_ptr instruction

**Comment by paololucente** [comment]
Thanks for confirming the version. And, sure, you can find some examples here: https://github.com/pmacct/pmacct/blob/master/examples/primitives.lst.example#L79-#L98 . You could start from one of them and get it working so to assure the basics are right. Then move to what is of interest. Paolo
