### ISSUE TITLE
Issue with aggregate config key

### ISSUE THREAD

**Issue by hemachandray** [pmacct/pmacct#321]
Hi Paolo

When I am running pmacctd, only for the attributes src_host, dst_host, src_port, dst_port, proto, tos the values are shown. If I add other supported attributes it is showing the value 0 only. I tried running it multiple times by adding different set of attributes but the result is same.

My configuration is as follows:
pmacctd.conf
daemonize: false
interface: enp0s31f6
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, class, mpls_label_bottom, mpls_label_top, in_iface, out_iface,
plugins: nfprobe, print
nfprobe_receiver: 192.168.144.28:4740
nfprobe_version: 10

Output:
WARN: [pmacctd.conf] Class aggregation not possible due to missing --enable-ndpi
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.4-git (20190912-00)
INFO ( default/core ):  '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/home/hema/pmacct/pmacctd.conf'.
INFO ( default_nfprobe/nfprobe ): NetFlow probe plugin is originally based on softflowd 0.9.7 software, Copyright 2002 Damien Miller <djm@mindrot.org> All rights reserved.
INFO ( default_nfprobe/nfprobe ):           TCP timeout: 3600s
INFO ( default_nfprobe/nfprobe ):  TCP post-RST timeout: 120s
INFO ( default_nfprobe/nfprobe ):  TCP post-FIN timeout: 300s
INFO ( default_nfprobe/nfprobe ):           UDP timeout: 300s
INFO ( default_nfprobe/nfprobe ):          ICMP timeout: 300s
INFO ( default_nfprobe/nfprobe ):       General timeout: 3600s
INFO ( default_nfprobe/nfprobe ):      Maximum lifetime: 604800s
INFO ( default_nfprobe/nfprobe ):       Expiry interval: 60s
INFO ( default_nfprobe/nfprobe ): Exporting flows to [192.168.144.28]:4740
INFO ( default_print/print ): cache entries=16411 base cache memory=54878384 bytes
WARN ( default_print/print ): no print_output_file and no print_output_lock_file defined.
INFO ( default/core ): [enp0s31f6,0] link type is: 1
INFO ( default_print/print ): *** Purging cache - START (PID: 4263) ***
IN_IFACE    OUT_IFACE   SRC_IP                                         DST_IP                                         SRC_PORT  DST_PORT  PROTOCOL    TOS    MPLS_LABEL_TOP  MPLS_LABEL_BOTTOM  PACKETS               BYTES
0           0           192.168.144.1                                  224.0.0.10                                     0         0         eigrp       192    0               0                  10                    600
0           0           140.82.113.26                                  192.168.144.28                                 443       57800     tcp         0      0               0                  2                     128
0           0           192.168.144.28                                 140.82.113.26                                  57800     443       tcp         0      0               0                  1                     80
0           0           140.82.113.26                                  192.168.144.28                                 443       57802     tcp         0      0               0                  2                     128
0           0           192.168.144.28                                 140.82.113.26                                  57802     443       tcp         0      0               0                  1                     80
0           0           140.82.113.26                                  192.168.144.28                                 443       57804     tcp         0      0               0                  2                     128
0           0           192.168.144.28                                 140.82.113.26                                  57804     443       tcp         0      0               0                  1                     80
0           0           192.30.253.125                                 192.168.144.28                                 443       47816     tcp         0      0               0                  2                     128
0           0           192.168.144.28                                 192.30.253.125                                 47816     443       tcp         0      0               0                  1                     80

Any help will be appreciated
Thanks,
Hema

**Comment by paololucente** [comment]
Hi @hemachandray ,

For the 'class' primitive you get a warning "WARN: [pmacctd.conf] Class aggregation not possible due to missing --enable-ndpi"; for input and output interfaces, i guess you are missing a part of the config: specifically https://github.com/pmacct/pmacct/blob/1.7.3/QUICKSTART#L1243-#L1295 but please read the whole "Quickstart guide to setup a NetFlow/IPFIX agent/probe" in the QUICKSTART document. For the MPLS labels i am not sure - is the traffic MPLS-labelled?

Paolo
