### ISSUE TITLE
Docker port issue

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#322]
We are create a docker container for pmacct, and that is expose a port but we can't access that port from other network. Can you give some idea to resolve this issue

**Comment by claudio-ortega** [comment]
Hi Ananth,
What you need to do is very a common need.
Here's an explanation on how you do it:
https://www.bitcoininsider.org/article/32223/dockerfile-expose-how-define-ports-docker-containers
Good luck
Claudio

**Comment by paololucente** [comment]
@AnanthGopal : plus you can see Claudio's docs on dockerizing pmacct: https://github.com/pmacct/pmacct/tree/master/docs/docker . Paolo
