### ISSUE TITLE
pgsql plugin incompatible with pg12

### ISSUE THREAD

**Issue by mmlb** [pmacct/pmacct#329]
Came across this when working on some new configs:
```
server_1  | INFO ( all/pgsql ): *** Purging cache - START (PID: 183) ***
server_1  | ERROR ( all/pgsql ): ERROR:  function abstime(integer) does not exist
server_1  | LINE 1: ...to, tag, class_id, packets, bytes, flows) VALUES (ABSTIME(15...
server_1  |                                                              ^
server_1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
server_1  |
server_1  |
```
The PG12 release notes states [1]:
> * Remove data types abstime, reltime, and tinterval (Andres Freund)
>   These are obsoleted by SQL-standard types such as timestamp.

Happy to try out a PR if you have a way you'd like to see this implemented.

[1]: https://www.postgresql.org/docs/12/release-12.html

**Comment by paololucente** [comment]
Hi Manueal ( @mmlb ),

Thank you for reporting this and, yes, if you could put together a PR that would be fantastic. Addressing this requires checking the PostgreSQL server version; this is not done in pmacct so far but i found this snippet of code doing it: https://github.com/postgres/postgres/blob/master/contrib/postgres_fdw/connection.c#L358-#L388 . In short, apparently, there is a convenient function to retrieve the server version: PQserverVersion(). Done that, if version is less than 12 behave as today; if equal or greater then behave in a new way.

Paolo

**Comment by mmlb** [comment]
@paololucente whats the minimum version of PG you want to support? `to_timestamp` looks to be an equivalent function, I've gone back checking for it all the way back to 9.0 and just stopped there.
I've checked with
```
~> echo 'select to_timestamp(1) AS "1", to_timestamp(1571420312) AS "1571420312"; select(ABSTIME(1)) as "abs 1", ABSTIME(1571420312) AS "abs 1571420312";' | docker exec -i pg su -l postgres -c psql
           1            |       1571420312
------------------------+------------------------
 1970-01-01 00:00:01+00 | 2019-10-18 17:38:32+00
(1 row)

         abs 1          |     abs 1571420312
------------------------+------------------------
 1970-01-01 00:00:01+00 | 2019-10-18 17:38:32+00
(1 row)
```
I shall proceed with that unless you really want the conditional on PG version.

**Comment by paololucente** [comment]
Hey @mmlb ,

In configure.ac currently there is a check to ensure the PostgreSQL version is >= 8.4. Now, 8.4 was originally released in 2009 and supported up to 2014; 9.0 is the following major release and supported up to 2015.

We can review the check in configure.ac no problem and make 9.0 the minimum supported release and avoid conditionals in the actual code.

Thank you very much for your effort!

Paolo

**Comment by sclark46** [comment]
Postgresql 8.4.x is the supported version on RHEL 6 and CentOS 6. These releases don't go EOL until Nov. 2020. I would still like 8.4 to be supported til then.
Regards,
Steve

**Comment by sclark46** [comment]
I just ran a test and got:
psql (8.4.20)
Type "help" for help.

postgres=# select to_timestamp(1) AS "1", to_timestamp(1571420312) AS "1571420312";
           1            |       1571420312       
------------------------+------------------------
 1969-12-31 19:00:01-05 | 2019-10-18 13:38:32-04

**Comment by sclark46** [comment]
So to me it looks like the to_timestamp function is in 8.4.

**Comment by paololucente** [comment]
Hey Steve ( @sclark46 ), good point & thanks for the test. Manuel ( @mmlb ) so it appears it's very simple: configure.ac tests already for PostgreSQL >= 8.4. The function is supported there as well so all is cool: new code and no conditionals, the way we like it 👍 Paolo
