### ISSUE TITLE
Kafka-Plugin: Support Failover

### ISSUE THREAD

**Issue by JonasGroeger** [pmacct/pmacct#33]
# Problem
As far as I can tell, if I currently use the Kafka plugin and my configured [`kafka_broker_host`](https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L645) is going down or has some other issues, I am losing data.

Is that correct or am I missing something?

# Solution
If it is correct, there are several ways to solve this issue as far as I can tell:

- Run pmacct twice with different `kafka_broker_host` values. This will create duplicates that need to be removed.
- Add failover support to pmaccts Kafka plugin. I guess this is the cleanest and most value-adding version for the Open Source community.
- (Maybe: Run a Kafka broker locally that we expect **NOT** to go down? If its running on the same host then we at least have control over the broker.)

**Comment by paololucente** [comment]
Hi Jonas, in SQL plugins there is such a builtin failover mechanism where essentially one can define a backup SQL server where to dump data to in case the primary is found dead. Are you thinking along the same lines for a Kafka broker? Or you more thinking to leverage some feature offered by Kafka in this sense (in which case i'd like to know more about it)?

**Comment by JonasGroeger** [comment]
> Hi Jonas, in SQL plugins there is such a builtin failover mechanism where essentially one can define a backup SQL server where to dump data to in case the primary is found dead.
> Are you thinking along the same lines for a Kafka broker?

Absolutely.

I would like to have the following modification work:

```
- kafka_broker_host: kafka1.example.com
- kafka_broker_port: 1234
+ kafka_brokers: kafka1.example.com:1234 kafka2.example.com:4321 kafka3.example.com:5555
```

[`librdkafka`](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#brokers) already supports adding multiple brokers with [`rd_kafka_brokers_add`](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#brokers).

I took a peek at the code but unfortunately I'm a C++ novice :frowning:

**Comment by paololucente** [comment]
Hi Jonas, this is now implemented. You can now specify something like "broker1:10000,broker2" as argument for kafka_broker_host. If no comma-separated list, it reverts to the original/legacy syntax and expect the port be specified as part of kafka_broker_port. It would be great if you can verify it working for you and confirm.

Additionally, i so far found not enough documentation on the behaviour to expect when multiple brokers are defined, ie. is it failing over, is it balancing, is it writing in parallel to all of them? There is only one case that i found well described "If a broker name resolves to multiple addresses (and possibly address families) all will be used for connection attempts in round-robin fashion.".

**Comment by JonasGroeger** [comment]
I'm using that now but I didn't do any tests yet as to how reliable librdkafka is in that regard.

**Comment by paololucente** [comment]
Hi Jonas, perfect. Let me close this for now then. You feel free to re-open or open a different one if you find an issue while you progress testing stuff.
