### ISSUE TITLE
is it possible to get unique flow data?

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#336]

**Comment by AnanthGopal** [comment]
We are listening to PMMACT data by using RabbitMQ. RabbitMQ received the 400 flow data per second. So that we received 1lakhs flow data within half an hour. Then we checked those 1lakhs records have many duplicate records.

**Comment by paololucente** [comment]
To totally disaggregate flows you can typically specify an aggregation method a-la "aggregate: peer_src_ip, in_iface, out_iface, src_host, dst_host, src_mask, dst_mask, tos, src_port, dst_port, proto, tcpflags, peer_dst_ip, timestamp_start, timestamp_end". If your flow records contain more fields (you can verify with Wireshark && CFLOW decoder, for example), you should add them too.
