### ISSUE TITLE
Sub seconds timestamps

### ISSUE THREAD

**Issue by carlos-alcan** [pmacct/pmacct#339]
I could not find anything on using timestamps at any level below seconds in the CONFIG-KEYS file and was wondering if there is a way to enable anything smaller than that, specifically at the microseconds level?

Thanks in advance

**Comment by paololucente** [comment]
Hi @carlos-alcan , in general if the collection method (be it libpcap, NetFlow, etc.) supports finer-grained resolutions, you should be get that (out of the box); there is one knob to prevent that from happening and set granularity to seconds level, ie. 'timestamps_secs: true', but by default this is set off. How are you collecting data? What daemon are you using? What version of pmacct are you using? Paolo

**Comment by paololucente** [comment]
Conversation continued via unicast emails. Adding "enhancement" label. Paolo
