### ISSUE TITLE
pmacctd looses connection each day at 1:25 o'clock

### ISSUE THREAD

**Issue by MichiFr** [pmacct/pmacct#340]
Hi,

I'm running pmacctd with this command on my Linux firewall IPFire:
```
pmacctd -f /etc/pmacct/pmacct_green_print.conf -D
```
The content of the configuration file is, shotend since there are two more pinrt plugins running as you might see in the log below:
```
syslog: daemon
promisc: true
interface: green0
plugins: print[green_full]
print_output_file[green_full]: /root/metrics/traffic_green_full.csv
print_output[green_full]: csv
print_history[green_full]: 1m
print_history_roundoff[green_full]: m
print_refresh_time[green_full]: 60
print_trigger_exec[green_full]: /root/metrics/traffic_trigger_green_full.sh
aggregate_filter[green_full]: src net 192.168.0.0/16 and not dst net 192.168.0.0/16 and not ether multicast and not ip broadcast and ip
aggregate[green_full]: src_host, dst_host, dst_host_country, dst_host_coords
/geoip2/geolite2/ to below path
geoipv2_file: /usr/share/pmacct/geoip/GeoLite2-City.mmdb
```

This runs perfectly well until 1:25 each day at night. pmacctd shuts down with those lines in /var/log/messages:

```
Nov 10 01:25:07 ipfire pmacctd[11359]: WARN ( default/core ): connection lost to 'green_ports-memory'; closing connection. 
Nov 10 01:25:08 ipfire pmacctd[11359]: WARN ( default/core ): connection lost to 'green_basic-memory'; closing connection. 
Nov 10 01:25:09 ipfire pmacctd[11359]: WARN ( default/core ): connection lost to 'green_full-memory'; closing connection. 
Nov 10 01:25:09 ipfire pmacctd[11359]: WARN ( default/core ): no more plugins active. Shutting down. 
Nov 10 01:25:09 ipfire kernel: device green0 left promiscuous mode
Nov 10 01:25:11 ipfire pmacct: GeoIP database has been updated
```
Nothing more and IMO nothing special. There is no memory shortage at this time or a reboot of the system. I could image that there is no traffic at the green0 interface at his point of time, but I tend to say that this is nearly impossible since at least one of the NAS on green0 is still running 24/7.

I guess a possible solution would be to restart pmacctd via cron at 1:28 for example, however, it would be better to understand what's going on and find a correct solution.

Any idea what's happening here?
Michael

**Comment by paololucente** [comment]
Hi @MichiFr ,

The time synchronization is indeed interesting. Any chance an UNIX signal is sent to the process(es)? Let's one moment follow the lead that this could be a process crash - not sure though. Can you follow this https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2714-#L2743 and see if we get one or multiple core dump files? 

Paolo

**Comment by MichiFr** [comment]
Paolo, 
thanks for your reply! 

With the help of a friend, I could now solve this riddle: at 1:25 a cron job updates the GeoIPv2 database and stops pmacctd after the job successfully downloaded the new database. 
Right after this the script tries to restart the pmacctd daemon but uses the default pmacct.conf file and fails while restarting because I'm using a differently named configuration file. 

Hence the daemon stops correctly but restart istn't possible anymore. Simple, eh? If one knows the difference.

Anyway - case solved successfully. Thanks for this great tool, Paolo!
Michael

**Comment by paololucente** [comment]
Wonderful, thanks for the update. Closing this up. Paolo
