### ISSUE TITLE
Issues aggregating basic ipfix information using nfacctd and custom defined primitives.

### ISSUE THREAD

**Issue by pawandhakal** [pmacct/pmacct#341]
While aggregating IPFIX information using nfacct and custom defined primitives, elements like OctetDeltaCount (id = 1), packetDetaCount (id = 2), ingressInterface (id = 10) and many more collects value 0 when semantics = u_int, instead the raw value shows nonzero content (for example: collected value when semantics=u_int is 0 and is 00-00-00-C2 when semantics=raw.

Is there any other semantics that gives the correct value.

**Comment by paololucente** [comment]
Hi @pawandhakal , what pmacct version are you using for this? Can you share your config and aggregate_primitives map? Paolo

**Comment by pawandhakal** [comment]
Hi Paolo,  the version of my pmacct is pmacct-1.7.3.

Here is the config:
!
! nfacctd configuration example
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys supported ?
!
! General configs
!
debug_internal_msg: true
debug: true
daemonize: true
!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: 2055
nfacctd_time_secs: true
nfacctd_time_new: true
nfacctd_net: netflow
nfacctd_as: netflow
! ..
plugins: print
!
aggregate:  octetDeltaCount, packetDeltaCount flowStartMilliSec
!
aggregate_primitives: primitives.lst
print_refresh_time: 10
print_output_file: /tmp/pmacct/flow_%s


**And** here is the aggregate primitives map
!
!
!
! Custom defined for IPFIX primitives
!
!
!
name=octetDeltaCount   field_type=01   len=8     semantics=u_int
!
name=packetDeltaCount  field_type=02   len=8     semantics=raw
!
name=flowStartMilliSec field_type=152 len=8     semantics=u_int

Thanks

**Comment by paololucente** [comment]
Hi @pawandhakal , 

Can you please try with master code? I just tried and all seems to work fine for me:

```
{"event_type": "purge", "octetdeltacount": "864", "packetdeltacount": "9", "flowstartmillisec": "1574483562279", "packets": 9, "bytes": 864}

{"event_type": "purge", "octetdeltacount": "868", "packetdeltacount": "14", "flowstartmillisec": "1574483562279", "packets": 14, "bytes": 868}
```

I found a minor issue with your config, ie. a missing comma "packetDeltaCount flowStartMilliSec"; but i'm sure this is not the nature of the issue because with that it won't start as it would complain that the primitive 'packetDeltaCount flowStartMilliSec' is not defined anywhere.

Paolo

**Comment by pawandhakal** [comment]
Hi @paololucente,

I tried with the master code and still, the problem is not solved. BTW, the exporter in my case is IPFIXCOL2 (https://github.com/CESNET/ipfixcol2/blob/master/doc/sphinx/configuration.rst). Does it change anything? I believe not. And some of the fields are correctly decoded and collected however some are not.

Pawan

**Comment by paololucente** [comment]
Hi @pawandhakal , 

I also think the exporter should not make any difference. To be extra sure you could send me by unicast email a trace captured with tcpdump that i can reply at my end. Since we experience such difference in behaviour, would it be possible for me to troubleshoot the issue on your box?

Paolo

**Comment by pawandhakal** [comment]
Hi @paololucente,

I have sent you the tcpdump trace in your email (paolo@pmacct.net). I think it is not possible to troubleshoot the issue on my box as it is in the cloud. However, IPFIXcol2 is also an opensource collector/exporter which can be easily configured to generate IPFIX flows.

Thanks
Pawan

**Comment by paololucente** [comment]
It was determined that the issue was lying in specifying primitives with different sizes compared to how they were specified in the actual template.
