### ISSUE TITLE
strcpy -> strncpy

### ISSUE THREAD

**Issue by jaredmauch** [pmacct/pmacct#346]
strcpy is used in several places where strncpy should be used

**Comment by paololucente** [comment]
Hey Jared ( @jaredmauch ), i saw you had a patch there for this and then reverted (as it was out of context for BMP I/O). Look forward to a separate PR, if you had the time. Paolo

**Comment by jaredmauch** [comment]
Yes, I have it but also reverted it back out because it wasn't in the right branch.  I'll post much of it soon.  There's several places that should just be snprintf() as well where it does strcpy+strcat

**Comment by paololucente** [comment]
In agreement with Jared ( @jaredmauch ), closing this for now.
