### ISSUE TITLE
Do we have the  aggregate filter with TCP flags in nfacctd ?

### ISSUE THREAD

**Issue by Krishjs** [pmacct/pmacct#350]
Hi @paololucente ,

Thanks for the wonderful tool,
Need to know whether the nfacctd aggregate filter supports the tcpflags filter ?
I have filter like this
tcp[tcpflags] & (tcp-syn|tcp-fin) != 0

I checked a question 9 years ago 
https://pmacct-discussion.pmacct.narkive.com/0xdnPvXz/nfacctd-aggregate-filter
That it is not supported and it can be added quickly is it available now ?

**Comment by paololucente** [comment]
Hi @Krishjs , i just gave a try to put the expression 'tcp[tcpflags] & (tcp-syn|tcp-fin) != 0' as part of an aggregate_filter and it works. Please next time i appreciate if you first try by yourself and - only if not working - open an issue. Thanks, Paolo

**Comment by Krishjs** [comment]
Hi @paololucente 
Thanks for the quick reply and I tried it and it was not working as expected for me. Let me check what I might have done wrong.
