### ISSUE TITLE
BPS question

### ISSUE THREAD

**Issue by blackmetal1** [pmacct/pmacct#354]
Hello,
We have many Juniper EX4200 switches and we send their sflow to pmacct but pmacct store only packets and bytes in mysql, so how can we check BPS ?
for example we want to see in the past month how much BPS we had towards a specific country, 
THank you.

**Comment by paololucente** [comment]
Hello @blackmetal1 , you may calculate / derive it very simply. SUM(Bytes Counter) * 8 / Time Interval. The * 8 is for Bytes to Bits conversion. This way you can still dump data, say, every 5 minutes to your storage of preference but calculate daily, weekly, monthly, etc. Bps. Paolo
