### ISSUE TITLE
memory leak since upgrade in 1.7.4

### ISSUE THREAD

**Issue by beufanet** [pmacct/pmacct#356]
I upgraded pmacctd from source yesterday (+dist-upgrade the machine), and since then, I see lot of memory leak from nfacctd processes.

[nfacctd mem leak](http://imgur.com/a/QWm4Scr)

Could you let me know how I can help troubleshoot this ?

**Comment by paololucente** [comment]
Hi Fabien, thanks for reporting this. Can you please share (here or via unicast email) your config and an output of 'nfacctd -V'? Ideally this last one from 1.7.4 but if 1.7.3 was compiled the same way that can do too. Paolo

**Comment by beufanet** [comment]
Sent privately ;)

**Comment by paololucente** [comment]
Closing for now due to missing information. We can re-open at a later time.
