### ISSUE TITLE
NetFlow packets when using nDPI have garbage in them

### ISSUE THREAD

**Issue by sclark46** [pmacct/pmacct#360]
I have been testing 1.7.4 with nDPI 2.8. If I just run pmacctd and write the output to a file it looks great. But if I send it to nfacctd the number of bytes and packets seem to be bogus. I captured the output of pmacctd netflow packets and looked at them in wireshark and see values that can't be true.

output directly from pmacctd:
CLASS             SRC_IP                                         DST_IP                                         SRC_PORT  DST_PORT  PROTOCOL    TOS    PACKETS               BYTES
Unknown/Unknown   172.24.109.252                                 172.24.109.246                                 52031     3000      tcp         0      10                    520
Unknown/Unknown   172.24.109.252                                 172.24.109.246                                 52032     3000      tcp         0      12                    624
Unknown/Unknown   172.24.109.252                                 172.24.110.40                                  1194      56312     udp         0      560                   302542
Unknown/Unknown   172.24.110.71                                  172.24.10.138                                  53016     445       tcp         0      284                   58489
Unknown/Unknown   172.24.110.40                                  172.24.109.252                                 56312     1194      udp         0      592                   89082
Unknown/Unknown   172.24.109.252                                 172.24.109.246                                 52030     3000      tcp         0      6                     312
Unknown/HTTP      172.24.109.246                                 172.24.109.252                                 3000      52033     tcp         0      11                    11640

output from sending pmacctd netflow packets to nfacctd:
CLASS             SRC_IP                                         DST_IP                                         SRC_PORT  DST_PORT  PROTOCOL    TOS    PACKETS               BYTES
RTP               172.24.103.60                                  208.89.110.171                                 2228      21532     udp         0      1216000               3548202565
RTP               208.89.110.171                                 172.24.103.60                                  21532     2228      udp         184    1216400               3548202565
RTP               172.24.103.41                                  208.89.110.171                                 2258      20082     udp         184    1216400               3548202566
RTP               208.89.110.171                                 172.24.103.41                                  20082     2258      udp         0      1216400               3548202566
RTP               172.21.64.113                                  208.89.110.80                                  8514      19008     udp         0      1149800               3548202566
RTP               208.89.110.80                                  172.21.64.113                                  19008     8514      udp         184    1216400               3548202566
RTP               172.24.103.71                                  208.89.110.171                                 2224      17992     udp         0      1143000               3548202566
RTP               208.89.110.171                                 172.24.103.71                                  17992     2224      udp         184    1216400               3548202566
^Q^?                52.96.29.82                                    172.21.64.58                                   443       8497      tcp         104    865418                3548202649
^Q^?                172.21.64.58                                   52.96.29.82                                    8497      443       tcp         0      1154844               3548202649
^Q^?                172.24.106.9                                   172.24.106.60                                  4323      42404     tcp         0      40                    3548202564
^Q^?                172.24.106.9                                   172.24.106.60                                  1236      41850     tcp         0      40                    3548202564

pmacctd config:
daemonize: true
pidfile: /var/run/pmacctd.pid
interface: p4p1
pcap_filter: not net 172.24.106.0/24
snaplen: 700
!
!plugins: print
!print_refresh_time: 60
!print_history: 60
!print_output_file:/var/lib/pgsql/sclark/pmacct_output.txt
!
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, class
plugins: nfprobe[p4p1]
pcap_filter[p4p1]: not net 172.24.106.0/24
!aggregate_filter[p4p1]: not host $IP
aggregate_filter[p4p1]: not net 172.24.106.0/24
plugin_buffer_size: 10240
plugin_pipe_size: 819200000
!nfprobe_receiver: 127.0.0.1:2055
nfprobe_receiver: 172.24.109.247:2055
nfprobe_version: 9
nfprobe_maxflows: 131072
nfprobe_direction[p4p1]: in
nfprobe_ifindex[p4p1]: 2
nfprobe_maxflows: 131072
nprobe_source_ip: 172.24.109.246
!pre_tag_map: /etc/pmacct_netwolves/pretag.map
nfprobe_timeouts: expint=5:general=60:tcp=60:tcp.rst=60:tcp.fin=60:udp=60:maxlife=60

nfacctd config:
!
! nfacctd configuration example
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys supported ?
!
! General configs
!
! debug: true
daemonize: false
!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: 5679
! nfacctd_time_secs: true
nfacctd_time_new: true
!
! Plugins definitions
!
plugins: print[foo] 
!
! 'foo' plugin configuration
!
aggregate[foo]: src_host, dst_host, src_port, dst_port, proto, tos, class
print_output_file:/var/lib/pgsql/sclark/nfacct_output.txt

Also when I sent the netflow packets to SolarWinds I got huge figures.

**Comment by sclark46** [comment]
Here is a wireshark dump of one of the packets - notice the time seems screwy also:
No.     Time            Source                Destination           Protocol Length Info
     29 13:10:43.027709 172.24.109.246        172.24.109.247        CFLOW    554    total: 8 (v9) records

Frame 29: 554 bytes on wire (4432 bits), 554 bytes captured (4432 bits)
Ethernet II, Src: LannerEl_22:58:a0 (00:90:0b:22:58:a0), Dst: LannerEl_21:db:99 (00:90:0b:21:db:99)
Internet Protocol Version 4, Src: 172.24.109.246 (172.24.109.246), Dst: 172.24.109.247 (172.24.109.247)
User Datagram Protocol, Src Port: 52790 (52790), Dst Port: iop (2055)
Cisco NetFlow/IPFIX
    Version: 9
    Count: 8
    SysUptime: 66003
    Timestamp: Jan 23, 2020 13:10:43.000000000 EST
    FlowSequence: 26
    SourceId: 0
    FlowSet 1
        FlowSet Id: (Data) (1024)
        FlowSet Length: 492
        Flow 1
            [Duration: -3550038.791000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.023000000 EST
                EndTime: Dec 13, 2019 11:03:24.232000000 EST
            Octets: 3549979405
            Packets: 1320000
            IPVersion: 04
            InputInt: 2
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 172.24.103.103 (172.24.103.103)
            DstAddr: 208.89.110.171 (208.89.110.171)
            SrcPort: 2240                                                                                                           
            DstPort: 22284                                                                                                          
            IP ToS: 0x00                                                                                                            
            TCP Flags: 0x00                                                                                                         
            Protocol: 17                                                                                                            
            ApplicationID: NBAR Application ID: 87:0 (type:id)                                                                      
        Flow 2                                                                                                                      
            [Duration: -3550038.791000000 seconds]                                                                                  
                StartTime: Jan 23, 2020 13:10:43.023000000 EST                                                                      
                EndTime: Dec 13, 2019 11:03:24.232000000 EST                                                                        
            Octets: 3549979405                                                                                                      
            Packets: 1320000
            IPVersion: 04
            InputInt: 0
            OutputInt: 2
            Direction: Ingress (0)
            SrcAddr: 208.89.110.171 (208.89.110.171)
            DstAddr: 172.24.103.103 (172.24.103.103)
            SrcPort: 22284
            DstPort: 2240
            IP ToS: 0xb8
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 3
            [Duration: -3550038.787000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.019000000 EST
                EndTime: Dec 13, 2019 11:03:24.232000000 EST
            Octets: 3549979405
            Packets: 1319600
            IPVersion: 04
            InputInt: 0
            OutputInt: 2
            Direction: Ingress (0)
            SrcAddr: 172.24.103.101 (172.24.103.101)
            DstAddr: 208.89.110.171 (208.89.110.171)
            SrcPort: 2232
            DstPort: 19752
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 4
            [Duration: -3550038.789000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.019000000 EST
                EndTime: Dec 13, 2019 11:03:24.230000000 EST
            Octets: 3549979405
            Packets: 1134800
            IPVersion: 04
            InputInt: 2
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 208.89.110.171 (208.89.110.171)
            DstAddr: 172.24.103.101 (172.24.103.101)
            SrcPort: 19752
            DstPort: 2232
            IP ToS: 0xb8
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 5
            [Duration: -3550039.713000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.019000000 EST
                EndTime: Dec 13, 2019 11:03:23.306000000 EST
            Octets: 3549979405
            Packets: 1319600
            IPVersion: 04
            InputInt: 0
            OutputInt: 2
            Direction: Ingress (0)
            SrcAddr: 172.24.103.73 (172.24.103.73)
            DstAddr: 208.89.110.80 (208.89.110.80)
            SrcPort: 2224
            DstPort: 18132
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 6
            [Duration: -3550038.789000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.019000000 EST
                EndTime: Dec 13, 2019 11:03:24.230000000 EST
            Octets: 3549979405
            Packets: 1320000
            IPVersion: 04
            InputInt: 2
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 208.89.110.80 (208.89.110.80)
            DstAddr: 172.24.103.73 (172.24.103.73)
            SrcPort: 18132
            DstPort: 2224
            IP ToS: 0xb8
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 7
            [Duration: -3550038.793000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.025000000 EST
                EndTime: Dec 13, 2019 11:03:24.232000000 EST
            Octets: 3549979406
            Packets: 1235200
            IPVersion: 04
            InputInt: 2
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 172.24.103.71 (172.24.103.71)
            DstAddr: 208.89.110.171 (208.89.110.171)
            SrcPort: 2224
            DstPort: 17992
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)
        Flow 8
            [Duration: -3550039.217000000 seconds]
                StartTime: Jan 23, 2020 13:10:43.025000000 EST
                EndTime: Dec 13, 2019 11:03:23.808000000 EST
            Octets: 3549979406
            Packets: 1320000
            IPVersion: 04
            InputInt: 0
            OutputInt: 2
            Direction: Ingress (0)
            SrcAddr: 208.89.110.171 (208.89.110.171)
            DstAddr: 172.24.103.71 (172.24.103.71)
            SrcPort: 17992
            DstPort: 2224
            IP ToS: 0xb8
            TCP Flags: 0x00
            Protocol: 17
            ApplicationID: NBAR Application ID: 87:0 (type:id)

**Comment by paololucente** [comment]
Hey Steve ( @sclark46 ),

So the problem seems to be on export from nfprobe since both Wireshark and nfacctd see the same thing. Allow me a bit of time to try to reproduce the issue at my end. One question meanwhile for you: if you remove 'class' (so essentially you put away the nbar part), does it all work ok? Or you still see the time / counters issues? 

Paolo

**Comment by sclark46** [comment]
Yes I still see the same problem. I did a comparison between the current version we are using 1.6.2 and 1.7.4 using the same configuration file without the class agregator. the 1.6.2 version is fine the 1.7.4 netflow packet have bad values for the duration, bytes and packets. Below is the config I used and the version information for 1.7.4.
$ sudo new/pmacct-1.7.4/src/pmacctd -f pmacctd.conf
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.4-git (20191126-01+c5)
INFO ( default/core ):  '--enable-ndpi' 'LIBS=' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/var/lib/pgsql/sclark/pmacctd.conf'.
INFO ( p4p1/nfprobe ): plugin_pipe_size=819200000 bytes plugin_buffer_size=10240 bytes
WARN ( p4p1/nfprobe ): ctrl channel: obtained=249856 bytes target=640000 bytes
INFO ( p4p1/nfprobe ): NetFlow probe plugin is originally based on softflowd 0.9.7 software, Copyright 2002 Damien Miller <djm@mindrot.org> All rights reserved.
INFO ( p4p1/nfprobe ):           TCP timeout: 600s
INFO ( p4p1/nfprobe ):  TCP post-RST timeout: 60s
INFO ( p4p1/nfprobe ):  TCP post-FIN timeout: 60s
INFO ( p4p1/nfprobe ):           UDP timeout: 600s
INFO ( p4p1/nfprobe ):          ICMP timeout: 300s
INFO ( p4p1/nfprobe ):       General timeout: 600s
INFO ( p4p1/nfprobe ):      Maximum lifetime: 3600s
INFO ( p4p1/nfprobe ):       Expiry interval: 60s
INFO ( p4p1/nfprobe ): Exporting flows to [172.24.109.247]:iop
INFO ( default/core ): [p4p1,0] link type is: 1
^CWARN ( p4p1/nfprobe ): Shutting down on user request.
WARN ( default/core ): connection lost to 'p4p1-nfprobe'; closing connection.
WARN ( default/core ): no more plugins active. Shutting down.

$ cat pmacctd.conf 
!
! pmacctd configuration example
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys
! supported by 'nfacctd' and 'pmacctd' ?
!
! debug: true
debug: false
pidfile: /var/run/pmacctd.pid
!syslog: daemon
!daemonize: true
interface: p4p1
pcap_filter: not net 172.24.106.0/24
aggregate: src_host, dst_host, src_port, dst_port, proto, tos
plugins: nfprobe[p4p1]
!aggregate_filter[p4p1]: not host $IP
plugin_buffer_size: 10240
plugin_pipe_size: 819200000
nfprobe_receiver: 172.24.109.247:2055
nfprobe_version: 9
!nfprobe_maxflows: 32768
nfprobe_maxflows: 131072
nfprobe_direction[p4p1]: in
nfprobe_ifindex[p4p1]: 2
nfprobe_source_ip:
!pre_tag_map: /etc/pmacct_netwolves/pretag.map
!nfprobe_timeouts: expint=60:general=300:tcp=300:tcp.rst=60:tcp.fin=60:udp=300:maxlife=600
nfprobe_timeouts: expint=60:general=600:tcp=600:tcp.rst=60:tcp.fin=60:udp=600:maxlife=3600
!
! networks_file: /path/to/networks.lst
! classifiers: /path/to/classifiers/
snaplen: 700

**Comment by paololucente** [comment]
Great Steve, thanks for confirming. One last super quick question that slipped out of my mind in my previous message: if you change nfprobe_version from 9 to 10 (IPFIX) in 1.7.4, does the problem persist? Paolo

**Comment by sclark46** [comment]
Yes it still does - I used the same config file only change: nfprobe_version: 10
wireshark output:
Frame 27: 518 bytes on wire (4144 bits), 518 bytes captured (4144 bits)
Ethernet II, Src: LannerEl_22:58:a0 (00:90:0b:22:58:a0), Dst: LannerEl_21:db:99 (00:90:0b:21:db:99)
Internet Protocol Version 4, Src: 172.24.109.246 (172.24.109.246), Dst: 172.24.109.247 (172.24.109.247)
User Datagram Protocol, Src Port: 46602 (46602), Dst Port: iop (2055)
Cisco NetFlow/IPFIX
    Version: 10
    Length: 476
    Timestamp: Jan 24, 2020 09:12:01.000000000 EST
    FlowSequence: 196
    Observation Domain Id: 0
    Set 1
        FlowSet Id: (Data) (1024)
        FlowSet Length: 460
        Flow 1
            [Duration: -3622046.963000000 seconds]
            Octets: 3622046910
            Packets: 80
            IPVersion: 04
            InputInt: 0
            OutputInt: 2
            Direction: Ingress (0)
            SrcAddr: 172.24.111.126 (172.24.111.126)
            DstAddr: 172.217.15.195 (172.217.15.195)
            SrcPort: 45096
            DstPort: 443
            IP ToS: 0x00
            TCP Flags: 0x04
            Protocol: 6
        Flow 2
            [Duration: -3622046.963000000 seconds]
            Octets: 3622046910
            Packets: 104
            IPVersion: 04
            InputInt: 2
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 172.217.15.195 (172.217.15.195)
            DstAddr: 172.24.111.126 (172.24.111.126)
            SrcPort: 443
            DstPort: 45096
            IP ToS: 0x00
            TCP Flags: 0x11
            Protocol: 6

**Comment by sclark46** [comment]
Also I tried adding the class agregator with ipfix and nfprobe sends the template packets then it starts using 100% cpu and doesn't output anymore flow packets.

**Comment by sclark46** [comment]
Hi Paolo, just tried master with ipfix and class sitll got junk in time, octets and packets, but at least nfprobe didn't lockup.

**Comment by paololucente** [comment]
Hey Steve,

We have a bit of an issue: i took master code, i loaded your config - just changed IP addresses - and all works fine, that is, i can't reproduce the issue. That is both on a Debian 8 and a Debian 9. What OS (and if Linux what distribution and version) are you using? 

Also, can you slim down the config to the bare bones as follows and confirm you still have the issue:

interface: p4p1
pcap_filter: not net 172.24.106.0/24
plugins: nfprobe[p4p1]
nfprobe_version: 9
nfprobe_receiver: 172.24.109.247:2055

Paolo

**Comment by sclark46** [comment]
Same results with the slimmed down config. 
$ cat /etc/redhat-release 
CentOS release 6.10 (Final)
Linux P301002.netwolves.com 2.6.32-504.3.3.el6.x86_64 #1 SMP
pfring-6.4.1-1034.x86_64

NetFlow v9 packets are perfect using 1.6.2 and the same config.

I just tried v5 netflow with 1.7.5 and your config and was perfect.
Also this traffic is coming to from a span port on a cisco switch - probably makes no difference.

**Comment by sclark46** [comment]
I am going to try building it on CentOS 7 without ndpi and see if that works for me.

**Comment by sclark46** [comment]
built on CentOS 7 without nDPI - capturing data from standard port looks OK. Will now rebuild with nDPI and keep you informed.

**Comment by sclark46** [comment]
Just tested with nDPI with and without classification and it looks good. Don't have any idea why it didn't work correctly on my C6 dev box. I'll do some more investigation. Sorry for the noise.
