### ISSUE TITLE
Connection failed to Kafka: p_kafka_check_outq_len()

### ISSUE THREAD

**Issue by Slepwin** [pmacct/pmacct#361]
Hi, I am running a nfacctd (1.7.5) on my server and get the following output:
```
2020-01-24T14:18:42Z ERROR ( netflow/kafka ): Connection failed to Kafka: p_kafka_check_outq_len()
2020-01-24T14:18:42Z ERROR ( netflow/kafka ): Connection failed to Kafka: p_kafka_close()
```
Also can see few workers in systemctl status nfacctd:
```
 CGroup: /system.slice/nfacctd.service
           ├─30670 nfacctd: Core Process [default]
           ├─30671 nfacctd: Kafka Plugin [netflow]
           ├─30883 nfacctd: kafka Plugin -- Writer (urgent) [netflow]
           ├─30890 nfacctd: kafka Plugin -- Writer (urgent) [netflow]
           ├─30904 nfacctd: kafka Plugin -- Writer (urgent) [netflow]
           └─30926 nfacctd: kafka Plugin -- Writer (urgent) [netflow]
```
On Kafka side i don't see any errors and JSON data populated from Kafka to ELK.

Configuration below:

```
NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200113-01)

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-avro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
rdkafka 0.9.3
jansson 2.11
avro-c

System:
Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64

Compiler:
gcc 4.8.5
```
nfacctd.conf:

```
! debug: true
daemonize: false
!
pidfile: /var/run/nfacctd.pid
logfile : /var/log/nfacctd/nfacct.log
!
! returns warning messages in case of data loss
! look at CONFIG-KEYS for details
! bufferization of data transfers between core process and active plugins (default 4MB)
plugin_pipe_size: 10240000
!
! The value has to be <= the size defined by 'plugin_pipe_size' and keeping a ratio < 1:1000 between the two
! Once a buffer is filled, it is delivered to the plugin
plugin_buffer_size: 10240
!
kafka_output[netflow]: json
kafka_topic[netflow]: netflow
kafka_broker_host[netflow]: x.x.x.x, y.y.y.y
kafka_broker_port[netflow]: 9092
kafka_refresh_time[netflow]: 300
kafka_history[netflow]: 5m
kafka_history_roundoff[netflow]: m
kafka_config_file[netflow]: /etc/pmacct/librdkafka.conf
!
plugins: kafka[netflow]
!
nfacctd_ip: z.z.z.z
nfacctd_port: 2055
nfacctd_time_new: true
!
aggregate[netflow]: peer_src_ip, out_iface, in_iface, src_as, dst_as, src_host,  dst_host, src_port, dst_port, proto, tcpflags, flows, tos, timestamp_start, timestamp_end, timestamp_arrival
```

librdkafka.conf

```
global, queue.buffering.max.messages, 8000000
global, batch.num.messages, 100000
```

**Comment by paololucente** [comment]
Hi Alexander ( @Slepwin ),

The error message is generated in this section of code:

https://github.com/pmacct/pmacct/blob/master/src/kafka_common.c#L579-#L602

If you see, the error message is triggered after 3 times the output queue is found in the same state (like, not being emptied up successfully). So this would point to your Kafka broker being probably congested?

Your output brings to attention a different - but perhaps related issue - see the "Writer (urgent)" processes: your plugin cache is too little for the amount of tuples generated by the configured aggregation method (well de-aggregation method in your case :)). While it is all being taken care for you by those out-of-schedule (or "urgent") writers, you may want to shorten the refresh time to 60 secs or perhaps even less, 30 or 10. I guess the pressure of all the tuples being generated is making your Kafka broker cripple (you should perhaps add more threads and/or more resources to your host).

Paolo

**Comment by Slepwin** [comment]
Hi Paolo,

I have found this issue related with RTT (>150ms) between nfacctd and kafka broker.
I checked with broker in the same location and all looks good. I think it's something on librdkafka side.

**Comment by paololucente** [comment]
Wonderful, thank you Alexander for the feedback - very informative. Paolo
