### ISSUE TITLE
BMP/BGP Packets are being discarded because peer_up not seen.

### ISSUE THREAD

**Issue by bcavns01** [pmacct/pmacct#363]
**Description**
Packets are being discarded because no peer_up seen, but peer_up has already been seen.

Seeing this in debugging:
```
INFO ( default/core ): [x.x.x.x] [route] packet discarded: missing peer up BMP message for peer_ip: y.y.y.y
```

Packets are indeed being discarded and not reaching the log file; however, there _are_ peer-up messages.  In some cases, this is even happening after a peer up has been seen and some packets have been accepted.  I.e., peer-up comes in, route-monitor packets come in and are accepted, and then later route-monitor packets are discarded because "missing peer up BMP message".

In one case, I was able to confirm that `pm_tsearch` was correctly inserting the peer and an immediate call to `pm_tfind` was looking it up successfully; but state is somehow, sometimes, lost between the call to `bmp_process_msg_peer_up` and `bmp_process_msg_route_monitor`.

I'm still poking around, but maybe someone more familiar with the codebase will be able to make sense of that.

**Version**

pmacct BMP Collector Daemon, pmbmpd 1.7.5-git (20200128-00)

Arguments:
 '--enable-debug' '--enable-bmp-bins' '--enable-jansson' '--enable-pgsql' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
PostgreSQL 100010
jansson 2.12

System:
Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64

Compiler:
gcc 7.4.0

**Comment by paololucente** [comment]
Hi @bcavns01 ,

Thank you very much for reporting this, interesting. I myself never ran in such a case - not myself, not in a few deployments i have been following. Perhaps it's a data specific issue, perhaps a platform specific one. As a way forward for troubleshooting: may i ask you to create a trace where you do experience the issue and share it via unicast email with me? https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2873-#L2883 . It should allow me to reproduce the issue at my end - and i'd be more than happy to have a look into this for you.

Paolo

**Comment by bcavns01** [comment]
Sure, sent one along.

**Comment by paololucente** [comment]
Hi @bcavns01 , the commit referenced above should resolve the issue. Can you give it a try and confirm (or not) it working for you? I tested it working against your trace successfully. Paolo

**Comment by bcavns01** [comment]
Hi @paololucente,

It looks like that commit fixed the issue.

**Comment by paololucente** [comment]
Thanks for confirming @bcavns01 , i'm going to close this issue.
