### ISSUE TITLE
PMBMPD Kafka feeds do not reflect upstream timestamp from BGP Update messages

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#364]
The timestamp in the PMBMPD Kafka feeds appear to reflect the current time and not the timestamp found in the Per-Peer Header of BGP Update found within the received Route Monitoring messages.

It would be great if two epoch's were added to the JSON logged data
     - epoch at time message was received
     - epoch from the Per-Peer Header of the BGP Update

PMBMPD version 1.7.4

**Comment by paololucente** [comment]
Hi @pothier-peter , thanks for bringing this up. You are right about the Route Monitoring message; the others appear to carry the correct timestamp - i'll fix that asap.

One question on your other point: when dumping at regular time intervals, you have the time of the dump and the time of the event - precisely as you were saying (this motivated by the fact a dump can take place minutes after the event). For real-time logging: would you stilll see the need of the double timestamping? And, i'm curious, are you using dumping, logging or both?

Paolo

**Comment by pothier-peter** [comment]
Hello Paolo,

Thank you for your quick response. We are utilizing both bmp_dump_kafka_broker_host and bmp_daemon_msglog_kafka_broker_host in our configuration. For real-time logging, I guess we would not need double timestamps, however, in our code-base, it might be nice to have both for consistency. 

Peter P

**Comment by paololucente** [comment]
Hi Peter,

The bug part of it (incorrect timestamps in Route Monitoring log messages) should be solved - can you confirm it works for you? I will handle the feature request part (get event + log timestamps) separately.

Paolo

**Comment by pothier-peter** [comment]
upstream epoch 1579788923
... "log_type": "update", "timestamp": "2020-01-23 14:15:23.000000"...

Looks good. Thank You.
