### ISSUE TITLE
pmacct with kafka schema registry subject name 

### ISSUE THREAD

**Issue by hinoryo** [pmacct/pmacct#371]
**Description**
i would like to use nfacctd as a producer of kafka topic and use schema registry with it so i configure it with the following configuration : 
`nfacctd_port: xxxx
nfacctd_ip: x.x.x.x
! ..
plugins:kafka
!
kafka_output:avro
aggregate: dst_mac,cos,etype,src_mac,vlan,src_host,dst_host,src_mask,dst_mas$
kafka_topic: pmacct-topic
kafka_refresh_time: 1
kafka_broker_host: kafka1:9092,kafk2:9092,kafka3:9092
kafka_avro_schema_registry: http://x.x.x.x:8081`

nfacctd create a topic and send messages but on the schema registry he create 3 subject with the name : 
[pmacct-topic-acct-data-value","pmacct-topic-acct-close-value","pmacct-topic-acct-init-value]
and i think this default name causing me a problem when iam traying to use kafka sink connector he gives me error 40401 subject not found 

so can i manually specify the subject name ?  

**Version**
`NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191126-01+c5)

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-avro' '--enable-serdes' 'KAFKA_CFLAGS=-I/usr/include/librdkafka' 'KAFKA_LIBS=-L/usr/lib/x86_64-linux-gnu -lrdkafka' 'JANSSON_CFLAGS=-I/usr/local/include/' 'JANSSON_LIBS=-L/usr/local/lib -ljansson' 'AVRO_CFLAGS=-I/usr/local/include/' 'AVRO_LIBS=-L/usr/local/lib -lavro' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
rdkafka 1.3.0
jansson 2.12
avro-c
serdes

Compiler:
gcc 7.4.0`

thanks!!

**Comment by paololucente** [comment]
Hi Faycal ( @hinoryo ), thanks for getting in touch. Let me confirm that at the moment it is not possible to choose the name of those subjects. Did you try to remove the trailing "-value" when trying to consume from / access the subjects though? Paolo

**Comment by hinoryo** [comment]
Hey paolo (@paololucente) i solve this by creating manually a schema subject with the name of "subject-value" using schema registry REST API  and then its worked fine ; it would be relly cool if we could choose the name of subject ie (topicName-value)

**Comment by paololucente** [comment]
Hi Faycal ( @hinoryo ), i am a bit puzzled - can you please elaborate more? The subject name depends on the kafka_topic set, it's just that the topic name gets a "-value" string appended to it (which apparently is conforming to what Confluent Platform expects). Paolo
