### ISSUE TITLE
wrong direction in the flow sent by uacctd in certain scenario

### ISSUE THREAD

**Issue by maplewf** [pmacct/pmacct#372]
Hi,

I'm using uacctd in my debian linux to collect data via netflow v9, but recently, I met a wired problem about direction in the flow. Here is version of uacctd I'm using:

### Version
```
Linux NetFilter NFLOG Accounting Daemon, uacctd 1.7.2-git (20181018-00+c3)

Arguments:
 '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pgsql' '--enable-mysql' '--enable-sqlite3' '--enable-ipv6' '--enable-64bit' '--enable-threads' '--enable-jansson' '--enable-geoip' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.6.2
MySQL 5.5.60
PostgreSQL 90424
sqlite3 3.8.7.1
jansson 2.7
netfilter_log

System:
Linux 4.19.54-amd64 #1 SMP Sun Jun 23 20:05:03 CEST 2019 x86_64
```

### Description
I usually start two uacctd processes for monitoring ingress and egress traffic separately like following:
```
root      1640     1  0 15:09 ?        00:00:00 uacctd: Core Process [default]               
root      1641  1640  0 15:09 ?        00:00:00 uacctd: IMT Plugin [memory-ingress]          
root      1643  1640  0 15:09 ?        00:00:00 uacctd: Netflow Probe Plugin [192.168.1.1-2055-nfprobe-ingress]
root      1644     1  0 15:09 ?        00:00:00 uacctd: Core Process [default]               
root      1646  1644  0 15:09 ?        00:00:00 uacctd: IMT Plugin [memory-egress]           
root      1651  1644  0 15:09 ?        00:00:00 uacctd: Netflow Probe Plugin [192.168.1.1-2055-nfprobe-egress
```
Normally it works fine. But recently I found there is problem in certain traffic scenario that wrong direction is included in the flow by uacctd or its nfprobe plugin more specifically. 

Here is wrong direction in the flow:
![image](https://user-images.githubusercontent.com/18524415/74848189-68ed9800-5372-11ea-8b5d-a78da935aafb.png)

As you see in the flow, the direction is ingress, but the interface index is `OutputInt`, it's conflict, how come the ingress flow has output interface index? here is correct flow as reference:
![image](https://user-images.githubusercontent.com/18524415/74848925-1c568c80-5373-11ea-9be8-fb6777b537eb.png)

But this problem doesn't happen all the time, it only occur in certain scenario which took me a lot of time to find out:
![image](https://user-images.githubusercontent.com/18524415/74852215-3db97780-5377-11ea-9d75-ab5e867699ba.png)

In the chart above, `A` send request to `B` through the system where uacctd locate, `B` reply with response to `A` though the system either. If the traffic match that pattern and uacctd monitor the `eth0` and `eth1` at same time, then the problem will happen on the response traffic flow in `eth0`,  it should be egress traffic, but uacctd count it with ingress direction in the flow.

I checked memory plugin, it's counted correctly, so I guess there may be problem in netflow probe plugin? Could you please help to look into it? Here is my configuration for reference:

##### Ingress
- uacctd-i.conf
```
daemonize: true
promisc:   false
pidfile:   /var/run/uacctd-i.pid
imt_path:  /tmp/uacctd-i.pipe
imt_mem_pools_number: 169
uacctd_group: 2
uacctd_nl_size: 2097152
snaplen: 4096
timestamps_secs: true
refresh_maps: true
pre_tag_map: /etc/pmacct/int_map-i
aggregate: tag,src_mac,dst_mac,vlan,src_host,dst_host,src_port,dst_port,proto,tos,flows
plugin_pipe_size: 10485760
plugin_buffer_size: 10240
syslog: daemon
plugins: memory[memory-ingress],nfprobe[192.168.1.1-2055-nfprobe-ingress]
nfprobe_receiver[192.168.1.1-2055-nfprobe-ingress]: 192.168.1.1:2055
nfprobe_version[192.168.1.1-2055-nfprobe-ingress]: 9
nfprobe_direction[192.168.1.1-2055-nfprobe-ingress]: in
```
- int_map-i
```
id=4	in=4
id=5	in=5
```
- nflog in iptables
```
iptables -t raw -A PREROUTING -i eth0 -j NFLOG --nflog-group 2 --nflog-range 64 --nflog-threshold 10
iptables -t raw -A PREROUTING -i eth1 -j NFLOG --nflog-group 2 --nflog-range 64 --nflog-threshold 10
```
##### egress
- uacctd-e.conf
```
daemonize: true
promisc:   false
pidfile:   /var/run/uacctd-e.pid
imt_path:  /tmp/uacctd-e.pipe
imt_mem_pools_number: 169
uacctd_group: 5
uacctd_nl_size: 2097152
snaplen: 4096
timestamps_secs: true
refresh_maps: true
pre_tag_map: /etc/pmacct/int_map-e
aggregate: tag,src_mac,dst_mac,vlan,src_host,dst_host,src_port,dst_port,proto,tos,flows
plugin_pipe_size: 10485760
plugin_buffer_size: 10240
syslog: daemon
plugins: memory[memory-egress],nfprobe[192.168.1.1-2055-nfprobe-egress]
nfprobe_receiver[192.168.1.1-2055-nfprobe-egress]: 192.168.1.1:2055
nfprobe_version[192.168.1.1-2055-nfprobe-egress]: 9
nfprobe_direction[192.168.1.1-2055-nfprobe-egress]: out
```
- int_map-e
```
id=4	out=4
id=5	out=5
```
- nflog in iptables
```
iptables -t mangle -A POSTROUTING -o eth0 -j NFLOG --nflog-group 5 --nflog-range 64 --nflog-threshold 10
iptables -t mangle -A POSTROUTING -o eth1 -j NFLOG --nflog-group 5 --nflog-range 64 --nflog-threshold 10
```

best regards

**Comment by paololucente** [comment]
Hey @maplewf ,

Thanks for reporting this.

There has been recently a commit (still 1.7.5 master code) that may correct the behavior you are seeing, https://github.com/pmacct/pmacct/commit/977faeee8e794e24b85beaf5b33e1c4be9f3fb6f . Can you please give the patch (or, better, either master code or 1.7.4p1 + the patch) a try and see if that works for you?

Thanks, Paolo

**Comment by maplewf** [comment]
hi Paolo,

I will check this patch as soon as possible and come back to you, thanks for help.

best regards

**Comment by maplewf** [comment]
Hi Paolo,

After applying this path to pmacct 1.7.2, the problem is gone, thanks very much for help.

best regards.

**Comment by paololucente** [comment]
Thank you for confirming, closing the issue. Paolo
