### ISSUE TITLE
bgp_attr_parse_origin appears to update wrong attribute within struct bgp_attr

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#373]
**Description**
Within PMACCT 1.7.4, I believe the code in
     bgp/bgp_msg.c: bgp_attr_parse_origin()
should be changed from
     memcpy(&attr->local_pref, ptr, 1);
to
     memcpy(&attr->origin, ptr, 1);

**Version**
1.7.4

**Comment by paololucente** [comment]
Dear Peter ( @pothier-peter ), thank you very much for raising this: your comment makes total sense and I've just committed a patch following your input. Paolo
