### ISSUE TITLE
Is this still available for IPFire

### ISSUE THREAD

**Issue by MMitsialis** [pmacct/pmacct#375]
**Description**
I found this project via this discussion on the IPFire forum: https://forum.ipfire.org/viewtopic.php?t=14699 

I however cannot find it in PakFire. It is still avaialble for IPFire (IPFire 2.25 (x86_64) - Core Update 141)

**Comment by paololucente** [comment]
Hi @MMitsialis , I have no idea of what IPFire is. Not myself not anybody i am in touch with / i am aware of is maintaining a package for IPFire. I am going to close this issue and i invite you to post to that forum again; if you find anybody maintaining a package for pmacct please invite him/her to get in touch with me. Paolo
