### ISSUE TITLE
pgsql bgp no store flow to table

### ISSUE THREAD

**Issue by prozaklob** [pmacct/pmacct#377]
hi
sorry for me ENG :)

i try settings up config for save v9flow with BGP and store to pgsql from my mikrotik ( mikrotik cant send asn in flow ).

im try config without BGP - its ok,work fine and store flow to acct table.
now, im add BGP settings. bgp link is up,bt acct_bgp table is empty.

```
INFO ( default_pgsql/pgsql ): *** Purging cache - START (PID: 1505) ***
WARN ( default_pgsql/pgsql ): Abnormal exit status detected for child PID 1505
```

What am I doing wrong with my config?
thanks

import dumps
```
pmacct-create-db
pmacct-create-table_v1
pmacct-create-table_bgp_v1
```

config:
```
bgp_daemon: true
bgp_daemon_ip: 10.99.9.9
bgp_daemon_as: 65553
bgp_daemon_max_peers: 1

nfacctd_port: 9993
nfacctd_as_new: bgp
nfacctd_net: bgp
nfacctd_time_new: true

plugins: pgsql 
aggregate: src_as, dst_as
sql_host: 10.99.9.9
sql_db: pmacct
sql_table: acct_bgp
sql_table_version: 1 
sql_table_type: bgp
sql_passwd: arealsmartpwd
sql_user: pmacct
sql_refresh_time: 60
sql_history: 1m 
sql_history_roundoff: mh
``


```
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191126-01+c6)
 '--enable-pgsql' 'PKG_CONFIG_PATH=/usr/local/postgresql/pkgconfig/' 'PGSQL_CFLAGS=-I/usr/local/postgresql/include' 'PGSQL_LIBS=-L/usr/local/postgresql/lib -lpq' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
Libs:
libpcap version 1.8.1
PostgreSQL 11
System:
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64
Compiler:
gcc 8.3.0
```

**Comment by prozaklob** [comment]
issue
wrong config
:)

sql_host: 10.99.9.9
```
sql_db: pmacct
sql_table: acct_v9
sql_table_version: 9 
sql_passwd: arealsmartpwd
sql_user: pmacct
sql_refresh_time: 60
sql_history: 1m 
sql_history_roundoff: mh
```

**Comment by paololucente** [comment]
Thank you @prozaklob for auto-solving this issue, i am going to close it then. Paolo
