### ISSUE TITLE
ESP protocol displayed as ipv6-crypt in ip_proto field

### ISSUE THREAD

**Issue by Slepwin** [pmacct/pmacct#379]
**Description**
ESP protocol displayed as ipv6-crypt in `ip_proto` field nfacctd

**Version**
```
NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200312-00)

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-avro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
rdkafka 0.11.5
jansson 2.11
avro-c
```

**Comment by paololucente** [comment]
Thank you Alexander ( @Slepwin ) for pointing this. Effectively protocol descriptions were behind compared to latest IANA assignments, to some pre-2010 status. Fortunately, of the defined ones, only two did change. Paolo
