### ISSUE TITLE
4761d67 : failed assert BMP_MSG_TYPE_MAX < BMP_LOG_TYPE_LOGINIT

### ISSUE THREAD

**Issue by tbearma1** [pmacct/pmacct#380]
Ciao paolo
I updated the pmacctd on our lab and i detected a problem. I can no longer launch pmbmpd.
The following Error occurs.
I removed the port 1790 on my server FW.... still the same problem.
Therefor no BMP Traffic can be the trigger of the coredump happened.
It was able for me to isolate the problem to the commit 4761d677eb8e0df583282fea90d3b77b19b12059 from Wed Mar 25.
The following error is from the "journalctl -u pmbmpd01". It represents the STDOUT.
This error is not visible on the logfile of pmbmpd.
----------------
Apr 03 12:51:49 daisy64 systemd[1]: pmbmpd01.service: Service RestartSec=5s expired, scheduling restart.
Apr 03 12:51:49 daisy64 systemd[1]: pmbmpd01.service: Scheduled restart job, restart counter is at 8.
Apr 03 12:51:49 daisy64 systemd[1]: Stopped BMP-Collector.
Apr 03 12:51:49 daisy64 systemd[1]: Started BMP-Collector.
Apr 03 12:51:49 daisy64 pmbmpd[67801]: pmbmpd: bmp.c:352: skinny_bmp_daemon: Assertion `BMP_MSG_TYPE_MAX < BMP_LOG_TYPE_LOGINIT' faile>
Apr 03 12:51:50 daisy64 systemd[1]: pmbmpd01.service: Main process exited, code=dumped, status=6/ABRT
Apr 03 12:51:50 daisy64 systemd[1]: pmbmpd01.service: Failed with result 'core-dump'.
Apr 03 12:51:55 daisy64 systemd[1]: pmbmpd01.service: Service RestartSec=5s expired, scheduling restart.
Apr 03 12:51:55 daisy64 systemd[1]: pmbmpd01.service: Scheduled restart job, restart counter is at 9.
Apr 03 12:51:55 daisy64 systemd[1]: Stopped BMP-Collector.
Apr 03 12:51:55 daisy64 systemd[1]: Started BMP-Collector.
Apr 03 12:51:55 daisy64 pmbmpd[67817]: pmbmpd: bmp.c:352: skinny_bmp_daemon: Assertion `BMP_MSG_TYPE_MAX < BMP_LOG_TYPE_LOGINIT' faile>
Apr 03 12:51:56 daisy64 systemd[1]: pmbmpd01.service: Main process exited, code=dumped, status=6/ABRT
Apr 03 12:51:56 daisy64 systemd[1]: pmbmpd01.service: Failed with result 'core-dump'.
------------------
Thanks to solve the bug.

**Comment by paololucente** [comment]
Hi Matthias ( @tbearma1 ), thanks for raising this. This is now fixed. Paolo

**Comment by tbearma1** [comment]
ciao Paolo
For me still something is not working. Maby it is only my setup.
I launched the daemon from the bash and get the following error.
See also below the current version and the configfile i am using.
Tanks for your help.
...and have a good day
Matthias


root@daisy64: [/opt/daisy/pkg/pmacct]# /usr/local/sbin/pmbmpd -f /etc/pmacct/pmbmpd01.conf
pmbmpd: bmp.c:353: skinny_bmp_daemon: Assertion `BMP_LOG_TYPE_MAX < MAX_AVRO_SCHEMA' failed.
Aborted (core dumped)

root@daisy64: [/opt/daisy/pkg/pmacct]# cat /etc/pmacct/pmbmpd01.conf
interface: eno2
core_proc_name: daisy64bmp01c
daemonize: false
debug: false
logfile: /var/log/pmacct/pmbmpd01.log
!
bmp_daemon_ip: 138.187.58.12
bmp_daemon_port: 1790
bmp_daemon_max_peers: 255
bmp_daemon_msglog_kafka_broker_host: kafka.sbd.corproot.net
bmp_daemon_msglog_kafka_broker_port: 9093
bmp_daemon_msglog_kafka_topic: daisy.dev.control-bmp-avro-raw
bmp_daemon_msglog_kafka_config_file: /etc/pmacct/librdkafka.conf
!
timestamps_secs: false
timestamps_since_epoch: true
!
!bmp_daemon_allow_file: /etc/pmacct/pmbmpd01_allow.lst
bmp_daemon_pipe_size: 4096000
!bmp_daemon_msglog_file: /var/log/pmacct/tmp/bmp-msglog01$peer_src_ip.log
!
bmp_daemon_msglog_avro_schema_file: /var/log/pmacct/bmp01_avroschema.avsc
bmp_daemon_msglog_kafka_avro_schema_registry: https://schema-registry.sbd.corproot.net
bmp_daemon_msglog_output: avro

root@daisy64: [/opt/daisy/pkg/pmacct]# pmbmpd -V
pmacct BMP Collector Daemon, pmbmpd 1.7.5-git (20200405-00)

Arguments:
 '--enable-zmq' '--enable-kafka' '--enable-jansson' '--enable-avro' '--enable-serdes' 'AVRO_CFLAGS=-I/include' 'AVRO_LIBS=-L/usr/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
rdkafka 1.3.0-14-g1f3f46
jansson 2.11
ZeroMQ 4.3.3
avro-c
serdes

System:
Linux 4.18.0-168.el8.x86_64 #1 SMP Fri Jan 10 22:15:08 UTC 2020 x86_64

Compiler:
gcc 8.3.1

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
root@daisy64: [/opt/daisy/pkg/pmacct]#
