### ISSUE TITLE
Traffic separation based on direction

### ISSUE THREAD

**Issue by prozaklob** [pmacct/pmacct#391]
hi!
How can packets and bytes be divided into in and out types in the logs? In each entry in the database, the total amount of bytes and packets is written. Thus, it is difficult to determine the amount of incoming and outgoing traffic.
im not see its in aggregate functions.
thx

**Comment by paololucente** [comment]
Hi @prozaklob , this is a basic example on how you can achieve what you want: https://github.com/pmacct/pmacct/blob/1.7.4/QUICKSTART#L486-#L500 . You should indeed customize to your needs depending what primitives are of interest, how you can discriminate in vs out and how you are capturing data. Paolo

**Comment by prozaklob** [comment]
This is not quite right.
I am using bgp and a full-view table with ASN persistence.
I guess this is not exactly the solution that I need

**Comment by paololucente** [comment]
Ok, closing this issue until you can elaborate on the details and provide more specific information. The current detail resolution is not helpful.
