### ISSUE TITLE
Flow sequence numbers issue

### ISSUE THREAD

**Issue by mhercek** [pmacct/pmacct#392]
Running multiple pmacct (version 1.7.4-git (20191126-01+c6)) on FreeBSD 11.3 (pfSense) like this:

_daemonize: true
interface: igb1.10
aggregate: src_mac, dst_mac, src_host, dst_host, src_port, dst_port, proto, tos
plugins: nfprobe
nfprobe_receiver: xxx.xxx.xxx.xxx:dddd
nfprobe_version: 9_

and experiencing wrong flow sequence numbers at remote site running nprobe & ntopng as collector (https://github.com/ntop/ntopng/issues/3864).

I did packet captures on both sides (exporter and collector) and number of captured packets is almost identical. So I assume the problem is within the host running pmacct.

I've checked UDP drops, there are 70,500 dropped packets due to no socket (after activation of  net.inet.udp.log_in_vain, system log showed some issues about Google DNS UDP packets.)

**Comment by paololucente** [comment]
Hi @mhercek ,

Thanks for reaching out. You may share a capture of the NetFlow traffic by unicast email so to look into sequence numbers. Two questions for you meanwhile: 1) did you try to switch to IPFIX (nfprobe_version: 10)? Does the issue persist? 2) the "number of captured packets is almost identical" between NetFlow exporter and collector so, disregarding any possible sequence number warning, do the figures (or shapes of the figures) look close to reality?

Paolo

**Comment by mhercek** [comment]
Apparent wrong flow numbers were caused by running multiple pmacct daemons. Solved by switching to IPFIX and adding 'nfprobe_engine: <number>' to my config.
