### ISSUE TITLE
Will nfacct tee detect a failed receiver?

### ISSUE THREAD

**Issue by mirsblog** [pmacct/pmacct#393]
**Description**
My setup consists of a tee and multiple receivers with a round-robin balancing scheme. What will happen if one of the receivers goes down? Will the data destined to the failed receiver keeps getting lost until the receiver comes back up?

**Version**
nfacctd 1.7.2

**Comment by paololucente** [comment]
Hi @mirsblog ,

Let me break my answer in two parts:

1) NetFlow, IPFIX, sFlow replication is all UDP-based so - being the underlying protocol not session aware - the replicator won't notice whether a collector goes down; one may rely on the chance of receiving ICMP Port Unreachable messages back but that is aleatory; so, as of today, realistically i'd encourage you towards an own solution that checks whether the local collector is running and if not edit the map on the replicator with some backup logics. I'd say: easy, doable but perhaps not a weekend project.

2) pmacct 1.7.5 brings in the picture Redis, a key-value cache store, for cluster management. So far, as documentation says, this is for pmacct elements (replicators, collectors, etc.) to be aware that there is a cluster and which elements are part of it for cluster health monitoring / management purposes only. By extending this scheme further it is possible (and it is in the  plans for this year!) to reckon wheter a collector went down (for example to adjust replication as in your case; but think rolling upgrades or elastic upgrade of the cluster too).

Paolo

**Comment by mirsblog** [comment]
Thanks Paolo. That confirms my understanding too. I will look towards implementing a solution in the meantime.
