### ISSUE TITLE
Build Errors with GCC 10

### ISSUE THREAD

**Issue by kkoning** [pmacct/pmacct#394]
Attempting to build pmacct on Arch produces a substantial number of `multiple definition of ...` errors.

It looks like pmacct is affected by [this issue](https://gcc.gnu.org/gcc-10/porting_to.html), where GCC changed the default from `-fcommon` to `-fno_common`  As a workaround, `pmacct` does build properly if `CFLAGS=-fcommon` is added to `configure`.

**Comment by paololucente** [comment]
Hi Kendall ( @kkoning ),

Thank you very much for reporting this. Please allow me to study the issue a bit in the forthcoming days to understand what would be the proper due course of action here. Whether it is testing compiler version in configure.ac or testing compiler features; or just pragmatically append -fcommon no matter the compiler (version).

Paolo

**Comment by msune** [comment]
@paololucente in case you need it, you can try this trick to have newer compilers in travis:

https://www.ogre.com/node/519

**Comment by paololucente** [comment]
Hi Kendall ( @kkoning ),

I should have nailed it with the commit above without the need of passing -fcommon to the compiler; now if i pass -fno-common to my humble gcc8 compiler it does compiler just fine. Can you please give it a try working for you with gcc10? 

Paolo

**Comment by kkoning** [comment]
Yep, just did a  `git reset --hard && git pull && ./configure && make` and make completes successfully again.  Nice!

**Comment by paololucente** [comment]
Wonderful, thanks for confirmng. Closing.
