### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by abdalians** [pmacct/pmacct#40]
hi 

I am getting the following error while running make

/usr/local/lib/libpcap.a(bpf_filter.o): In function `bpf_validate':
(.text+0x0): multiple definition of `bpf_validate'
./.libs/libdaemons.a(libdaemons_la-bpf_filter.o):/root/pmacct/src/bpf_filter.c:528: first defined here
/usr/local/lib/libpcap.a(bpf_filter.o): In function `bpf_filter':
(.text+0x590): multiple definition of `bpf_filter'
./.libs/libdaemons.a(libdaemons_la-bpf_filter.o):/root/pmacct/src/bpf_filter.c:201: first defined here
collect2: ld returned 1 exit status
gmake[2]: *** [pmacctd] Error 1
gmake[2]: Leaving directory `/root/pmacct/src'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/root/pmacct/src'
make: *** [all-recursive] Error 1

using this for confiure
./configure --enable-rabbitmq --enable-jansson

Release: CentOS release 6.6 (Final)

**Comment by paololucente** [comment]
Are you using libpcap and libpcap-devel packages or a self-compiled version of libpcap? With the packaged version i'm unable to reproduce your issue on a CentOS 6.5. It seems like if the following check in configure.ac is failing:

AC_CHECK_LIB([pcap], [bpf_filter], [ AC_DEFINE(PCAP_NOBPF, 1) ], [])

But actually libpcap is somehow there. If you can offer remote-access to look into this issue, please get in touch privately via email.

Cheers,
Paolo
