### ISSUE TITLE
sFlow agent error: sfl_agent_sysError: receiver: socket sendto error (errno = 22 - Invalid argument)

### ISSUE THREAD

**Issue by andrejzverev** [pmacct/pmacct#403]
**Description**
hello, i made simple config. As i'm understand in must capture via pcap local traffic and convert in to sFlow and send to collector, but something is wrong. 

`debug: true
daemonize: false

pcap_interface: em0
plugins: sfprobe
sfprobe_agentsubid: 1402
sfprobe_receiver: 10.11.12.250:6343
sampling_rate: 20
`

**Version**
`INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.4-git (20191126-01+c6)
INFO ( default/core ):  '--disable-mysql' '--disable-pgsql' '--disable-sqlite3' '--enable-l2' '--enable-ipv6' '--disable-plabel' '--disable-threads' '--disable-mongodb' '--disable-nflog' '--enable-64bit' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd12.1' 'build_alias=amd64-portbld-freebsd12.1' 'CC=cc' 'CFLAGS=-pipe -g  -g -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS= -L/usr/local/lib -fstack-protector-strong ' 'LIBS=' 'CPPFLAGS=-I/usr/local/include' 'CPP=cpp' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/usr/local/etc/pmacct.cfg'.
INFO ( default_sfprobe/sfprobe ): plugin_pipe_size=4096000 bytes plugin_buffer_size=416 bytes
INFO ( default_sfprobe/sfprobe ): ctrl channel: obtained=78768 bytes target=78768 bytes
INFO ( default/core ): [em0,0] link type is: 1
DEBUG ( default_sfprobe/sfprobe ): Creating sFlow agent.
INFO ( default_sfprobe/sfprobe ): Exporting flows to [10.11.12.250]:6343
INFO ( default_sfprobe/sfprobe ): Sampling at: 1/20
ERROR ( default_sfprobe/sfprobe ): sFlow agent error: sfl_agent_sysError: receiver: socket sendto error (errno = 22 - Invalid argument)

ERROR ( default_sfprobe/sfprobe ): sFlow agent error: sfl_agent_sysError: receiver: socket sendto error (errno = 22 - Invalid argument)

DEBUG ( default_sfprobe/sfprobe ): 600308a421ba -> ffffffffffff (len = 174, captured = 128)
ERROR ( default_sfprobe/sfprobe ): sFlow agent error: sfl_agent_sysError: receiver: socket sendto error (errno = 22 - Invalid argument)`

**Comment by andrejzverev** [comment]
I did put abort() into sfl_agent_sysError to crash app for debug.

[trace.txt](https://github.com/pmacct/pmacct/files/4742009/trace.txt)

**Comment by paololucente** [comment]
H Andrej ( @andrejzverev ),

Thank you for having raised this issue and also for the precious detailed insight which allowed me to proceed quicker. Effectively sendto() on FreeBSD seems to have an issue with the sockaddr_storage size - whereas on Linux that works OK. So, since an underlying sockaddr_storage is needed, i sophisticated the length calculation a bit. I tested it working fine for both v4 and v6 export on both Linux and FreeBSD. Here the patch:

https://github.com/pmacct/pmacct/commit/f723f16fe075fd8d469c034e302611807a0e03f6

Paolo

**Comment by andrejzverev** [comment]
@paololucente thank you for a quick fix, i'm also did a quick test and it works.

**Comment by paololucente** [comment]
Thanks for confirming @andrejzverev . Closing then. Paolo
