### ISSUE TITLE
Active health monitoring

### ISSUE THREAD

**Issue by pratheekbangera** [pmacct/pmacct#410]
Hi,

First of all thank you for providing a great tool to the opensource community. 
I had a question regarding the using the Nfacctd as Tee service. Does Nfacctd support health monitoring for the nodes to which the data/ packets get forwarded ? 

Thanks.

**Comment by paololucente** [comment]
Hi @pratheekbangera ,

Thank you for your kind words. Please look at Issue #393 as pretty much the same question was asked.

Paolo

**Comment by pratheekbangera** [comment]
Thank you for Sharing the duplicate issue @paololucente . Appreciate it.
