### ISSUE TITLE
1.7.5 ndpi error

### ISSUE THREAD

**Issue by sclark46** [pmacct/pmacct#411]
sudo src/pmacctd -f ../paolo.conf 
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.5-git (20200510-00+c1)
INFO ( default/core ):  '--enable-ndpi' '--with-ndpi-static-lib=/usr/local/lib' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/var/lib/pgsql/sclark/paolo.conf'.
INFO ( eth5/nfprobe ): NetFlow probe plugin is originally based on softflowd 0.9.7 software, Copyright 2002 Damien Miller <djm@mindrot.org> All rights reserved.
INFO ( eth5/nfprobe ):           TCP timeout: 3600s
INFO ( eth5/nfprobe ):  TCP post-RST timeout: 120s
INFO ( eth5/nfprobe ):  TCP post-FIN timeout: 300s
INFO ( eth5/nfprobe ):           UDP timeout: 300s
INFO ( eth5/nfprobe ):          ICMP timeout: 300s
INFO ( eth5/nfprobe ):       General timeout: 3600s
INFO ( eth5/nfprobe ):      Maximum lifetime: 604800s
INFO ( eth5/nfprobe ):       Expiry interval: 60s
INFO ( eth5/nfprobe ): Exporting flows to [172.24.109.247]:iop
INFO ( default/core ): [eth5,0] link type is: 1
[ndpi_main.c:6207] [NDPI] Internal error: please call ndpi_finalize_initalization()
[ndpi_main.c:6207] [NDPI] Internal error: please call ndpi_finalize_initalization()
[ndpi_main.c:6207] [NDPI] Internal error: please call ndpi_finalize_initalization()
[ndpi_main.c:6207] [NDPI] Internal error: please call ndpi_finalize_initalization()
[ndpi_main.c:6207] [NDPI] Internal error: please call ndpi_finalize_initalization()**Description**
What's the issue? Did something go wrong? Would you like something new to exist?

, pmacctd 1.7.5-git (20200510-00+c1)

**Comment by paololucente** [comment]
Hi Steve ( @sclark46 ),

Thanks for getting in touch. I suspect you ended up in an unsupported pairing of pmacct version & nDPI version. nDPI is under active development and the API is changing over time; probably you are trying to use nDPI 3.2 (or greater) against pmacct 1.7.5. Please use master code for that as ndpi_finalize_initalization() has been introduced in mid-May: https://github.com/pmacct/pmacct/commit/abab332942481c165cac6911b42b8e9fb8853a4b . Or downgrade nDPI to pre 3.2, ie. 3.0. 

I will follow-up shortly on the issues on the mailing-list.

Paolo

**Comment by sclark46** [comment]
Hi Paolo - I am using nDPI 3.2 stable from git
/sclark/nDPI
$ git status
# On branch 3.2-stable

**Comment by sclark46** [comment]
Don't know why it bolded the status - I not yelling.

**Comment by sclark46** [comment]
P703406:~/sclark
$ ldd pmacct/src/pmacctd
        linux-vdso.so.1 =>  (0x00007fff0952f000)
        libndpi.so.3 => /usr/local/lib/libndpi.so.3 (0x00007f75f7175000)

P703406:~/sclark
$ ls -al /usr/local/lib/
total 22656K
drwxr-xr-x  4 root root     4096 Jun 23 10:46 .
drwxr-xr-x 18 root root     4096 Nov  8  2018 ..
drwxr-xr-x  2 root root     4096 Nov  8  2018 daq
-rw-r--r--  1 root root 11406472 Jun 23 10:46 libndpi.a
lrwxrwxrwx  1 root root       16 Jun 23 10:46 libndpi.so -> libndpi.so.3.2.0
lrwxrwxrwx  1 root root       16 Jun 23 10:46 libndpi.so.3 -> libndpi.so.3.2.0
-rwxr-xr-x  1 root root  3524792 Jan 24 12:36 libndpi.so.3.0.0
-rwxr-xr-x  1 root root  4238056 Jun 23 10:46 libndpi.so.3.2.0

**Comment by paololucente** [comment]
No worries, Steve. Then you must use master code (1.7.6) for 3.2.0.

**Comment by sclark46** [comment]
Hi Paolo - I started using 3.0 but 1.7.5 would not build got compile errors - looked in Changelog for 1.7.5 and it said I needed 3.2 
I'll try pmacct master branch now. Also I would like to build against the static libndpi.a library but can't seem to figure out the correct configuration options. Do you have any hints?

**Comment by paololucente** [comment]
Hey Steve, ack, let me know about if you manage to compile and run pmacct master code against nDPI 3.2 stable. On the static part, let me handle that in the mailing-list since it was raised there first. Please allow me a few hours. Paolo

**Comment by sclark46** [comment]
Ok - going to start now with master and 3.2 - and thanks for such a great product and support.

**Comment by sclark46** [comment]
Hi Paolo, haven't seen any ndpi errors with master and 3.2 - gonna let it run for while.

**Comment by sclark46** [comment]
Well I don't see any errors now and I am getting data at nfacctd - so I am closing this issue.

**Comment by paololucente** [comment]
Wonderful Steve, thanks for confirming. I am labeling it as workaround since we were able to get you going with 1.7.6 code. I will see if it makes sense to add a note in the docs. Paolo
