### ISSUE TITLE
Add support for Proxy Protocol Header

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#412]
Hello Paolo,

We are running PMACCT 1.7.4 and would like to front-end PMBMPD with an HAProxy.
Would it be feasible for PMBMPD to support the presence of a Proxy Protocol Header during connection?
Section 9 of the Proxy Protocol documentation contains sample code
     http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

The idea being that the peer->adds_str is obtained from the source IP address in the header rather than from the socket.

Thank You,
Peter P

**Comment by paololucente** [comment]
Hi Peter ( @pothier-peter ),

Interesting. It is certainly a feature that i can add to the todo list (labeling in fact this as 'enhancement') and it seems useful. 

May i ask you also a couple of questions: 1) is this Proxy Protocol anything standardized or specific to HAProxy? Reading the page you sent it seems it's no standard; 2) what is the bigger picture: HAProxy managing a sort of VIP to which the BMP export from the network is pointed to, true? Then how would the distribution of the sessions work downstream? And is HAProxy able to do any magics like detect that one collector is down and hence distribute to a backup one or anything similar? 

Paolo

**Comment by pothier-peter** [comment]
Hello Paolo,

1) Proxy Protocol appears to be a "defacto" standard, implemented by such load balancers/servers as Apache, HAProxy, NGINX, and Amazon.

2) Yes, you understand the big picture. HAProxy can present a VIP to monitored routers and manage the distribution and resiliency of BMP connections/messages to a farm of machines running PMBMPD.

Would you like assistance/contribution implementing this feature?

Peter P

**Comment by paololucente** [comment]
Hi Peter,

Thank you for taking the time to educate me, appreciate it a lot. I support the idea and, totally, any assistance / contribution would be very much welcome as i may not have the bandwidth to converge onto it short-term.

I was also wondering one thing: as part of the Peer Up message we do have a reference to the BMP exporter in the form of a BGP Router-ID. As of today this is saved but not visualized as part of the BMP data; but, bear with me one second with the reasoning, the tmp_bgp_lookup_compare_ports config knob (meant for BGP x-connects, NAT scenarios, etc. so very similar to your scenario), does enable to show the remote BGP Router-ID for BGP data, see for example. here: https://github.com/pmacct/pmacct/blob/master/src/bgp/bgp_logdump.c#L124-#L127 . We may do something very similar for BMP by extending this mechanism and it would be matter of a couple extra conditionals - would this work for you?

Paolo

**Comment by pothier-peter** [comment]
Hello Paolo,

I did notice from Wireshark that the Source IP Address was available within the Sent OPEN Message of the BMP Peer Up Notification. However, this information is limiting since the BGP ID is restricted to 32 bits and the source port is not provided. Furthermore, could we rely on all routers being properly configured to provide this information?
 
The Proxy Protocol support seems more flexible (e.g. under out control, future IPv6, etc..) and doesn't rely on routers (that may or may not be in our control) embedding the correct information.

Peter P

**Comment by paololucente** [comment]
Hi Peter,

> Furthermore, could we rely on all routers being properly configured to provide this information?
No, you are right. But BGP monitoring in my experience - in any incarnation of it -  has been useful to straighten such situations up.

Regardless of the above commend, I see and i agree with you. One example for all, thinking deeper about it, is that the BGP Router-ID is known when parsing the Peer Up message; at that point several things already happened before: TCP session went established, BMP Init message, etc. meaning all init functions have already been called. So adding such a key piece of information while in-flight is not a good idea. 

How do we take it from here? It would be really cool if you guys could spend some cycles on it 🤩

Paolo

**Comment by pothier-peter** [comment]
Hi Paolo,

I forked PMACCT, created a branch, and committed a first pass implementation of Proxy Protocol headers in BMP
     https://github.com/pothier-peter/pmacct/commit/736a708689c23540bb216a3386cab28514cd0d58

There are three parts to the code:
      - a new parse_proxy_header configuration
      - the parsing of the header in network.[ch], replacing addr/port
      - looking for the header in bmp.[ch] on the first packet of a new connection
I am hesitant to add IPv6 support as I am only testing IPv4.

What are the appropriate next steps? Should I have created a Pull Request at this point in time to better review the code?
Thanks,
Peter P

**Comment by paololucente** [comment]
Hi Peter, 

I had a first review of the code and i think it's great material for a PR, yes.

I would probably propose a couple minor changes / additions to it on top of your code a-la: 1) make log messages compliant to the rest of pmacct, 2) rename parse_proxy_header config option into bmp_daemon_parse_proxy_header so that - if proxy support is added in other parts at a later stage - it can be enabled/disabled with the right granularity and 3) add a few liners of documentation in CONFIG-KEYS. These you can do them if you have time to or i can do them no problem.

So, yeah, send a PR over and thanks once again for this great contribution!

Paolo

**Comment by paololucente** [comment]
Hi Peter,

Thank you very much for having contributed the code via PR #416 . Much-much appreciated. While closing this Issue, may i ask you one last favor on this? (And this comes from some interest your PR already generated) Would you have a sample config for HAProxy for this? I would just embed it in CONFIG-KEYS if it's a few liners kind of stuff or, if longer, i'd put a sample config in the examples/ directory (perhaps in a sub-directory haproxy/) and reference it from CONFIG-KEYS.

Paolo

**Comment by pothier-peter** [comment]
Hi Paolo,

I added a simple HAProxy config into CONFIG-KEYS. Here's the Pull request:
https://github.com/pmacct/pmacct/pull/418

Peter P

**Comment by paololucente** [comment]
Thank you Peter, fantastic stuff. I just merged it. Paolo
