### ISSUE TITLE
Unable to read next Data Flowset (incomplete NetFlow v9/IPFIX packet)

### ISSUE THREAD

**Issue by ixodis** [pmacct/pmacct#413]
Hello Paolo!

A large amount of fragmented traffic is being sent to the nfacctd from some network device. MTU on nfacctd RHEL server is 9000. Kafka plugin is activated.

This error occurs and very small amount of aggregates passes to Kafka: 

> 2020-06-25T14:07:28+03:00 DEBUG ( default/core ): Received NetFlow/IPFIX packet from [10.2.2.2:40000] version [10] seqno [17117037]
> 2020-06-25T14:07:20+03:00 INFO ( default/core ): unable to read next Data Flowset (incomplete NetFlow v9/IPFIX packet): nfacctd=0.0.0.0:2055 agent=10.1.2.3:40000 seq=17117037

The config file is:
 
> plugins: kafka
> kafka_broker_host: s1:9092,s:9092,s3:9092,s7:9092,s8:9092
> kafka_topic: nfacct
> kafka_refresh_time: 10
> kafka_cache_entries: 1000000
> kafka_max_writers: 10
> 
> interface: eth0
> nfacctd_port: 2055
> 
> nfacctd_templates_file: 
> 
> aggregate_primitives: 
> aggregate: 
> 
> #debug: true
> #debug_internal_msg: true
> logfile: /var/log/nfacctd

Could you explain how to solve the problem?

**Comment by paololucente** [comment]
Hello @ixodis ,

Send me a sample of your data via unicast email. If it's fragmented UDP then i'm afraid there are good chances that, at least as things stand, there is not much that can be done. 

Paolo

**Comment by paololucente** [comment]
Hi @ixodis ,

Thanks very much for the data - looked into it. I confirm my initial assessment: at an increased risk, one may try to get smarter and decode a flowset as much as poossible - but i think it's not the best idea. Then for the remaining fragments (all fragments except the very first one) they would go lost anyway as there is no built-in UDP re-assembly mechanism in nfacctd. If the source of fragmentation can't be avoided you may look in some TCP tunneling technolog; or perhaps use a different transport than UDP for IPFIX; or distribute collectors locally throughout the network, decode IPFIX in-situ and then export decoded data to a central location using Kafka protocol. Just some ideas.

Paolo

**Comment by ixodis** [comment]
Paolo, 

I found that these errors disappear if I change  PKT_MSG_SIZE 10000 to 65535 in network.h. How does it affect functionality?

IPFIX exporter sends UDP packets of 65535 bytes – it is hardcoded in firmware and I can’t change it.

Will UDP re-assembly mechanism released in nfacctd in future?

**Comment by paololucente** [comment]
Happy you found a workaround, i may see how it can potentially work although how it could also be based on coincidences (ie. no out-of-order packets): that parameter tunes the size of the receiving buffer used. To be frank implementing an UDP re-assembly mechanism is not in the cards. I would propose to close this with a workaround tag; maybe in parallel you want also to drop a note to your vendor about sending 65535 bytes UDP packets.
