### ISSUE TITLE
heap corruption in nfacctd (likely ecommunity_ecom2str)

### ISSUE THREAD

**Issue by cdanis** [pmacct/pmacct#414]
**Description**
As of a few hours ago today, we started seeing many segfaults in one of our `nfacctd` daemons.

The daemon in question is deployed at Wikimedia Foundation's datacenter in the Dallas TX area, and receives netflow from & BGP peers with three Juniper MX-series routers, all of which have a full routing table view.

Here are a selection of several different backtraces we saw, all within skinny_bgp: https://phabricator.wikimedia.org/P11715

I reran nfacctd under valgrind and caught a few invalid writes happening, all from within `ecommunity_ecom2str`: https://phabricator.wikimedia.org/P11716

However it hasn't actually crashed again under valgrind.  I'll leave it running this way for a while and let you know.

Please let me know if any other details or data would be helpful!

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)

Arguments:
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pmacct-8WorSQ/pmacct-1.7.2=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'            

Libs:
libpcap version 1.8.1
MariaDB 10.3.12
PostgreSQL 110007
sqlite3 3.27.2
rabbimq-c 0.9.0
rdkafka 0.11.6
jansson 2.12
MaxmindDB 1.3.2
ZeroMQ 4.3.1
netfilter_log

System:
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64

The system itself is running Debian Buster (stable).

**Appreciation**
Thanks so much for pmacct!  nfacctd + the Kafka plugin has made a lot of our work much easier.

**Comment by paololucente** [comment]
Dear Chris,

Thanks very much for reporting this. Given the nature of the issue, the failing within the malloc(), a super hot fix to not run things under valgrind could be to set the MALLOC_CHECK_ environment variable. You could set it to 2. This should lead to the daemon stable again but may hide some root cause issue. Let me meanwhile check through your traces to nail a possible root cause.

Paolo

**Comment by cdanis** [comment]
Thanks Paolo!

Let me know if anything else would be helpful (like packet dumps of the BGP traffic).

**Comment by paololucente** [comment]
Hi Chris,

We should have resolution: https://github.com/pmacct/pmacct/commit/9bc7a1543791405baa9eff00ca67bef0be298e9b . Can you give it a try and see if it works for you? The patch is very small so you could safely apply it to the version you are running; but indeed if you feel ambitious today you could switch to master code :-) Please keep me posted. 

Paolo

**Comment by cdanis** [comment]
Thanks very much!  I'll try the patch tomorrow.

**Comment by cdanis** [comment]
Works great, thank you!

* Restarted nfacctd outside valgrind; segvs within a minute
* Installed patched version; runs for several minutes just fine
* Restarted with unpatched version; segvs within a minute
* Reinstalled patched version; still running fine.

**Comment by paololucente** [comment]
Wonderful Chris, thank you for confirming. Paolo

**Comment by cdanis** [comment]
Oh BTW, I also submitted this to the Debian package maintainer: https://bugs.debian.org/964083
