### ISSUE TITLE
sql database via proxy

### ISSUE THREAD

**Issue by gklpnd** [pmacct/pmacct#419]
Hello,

When postgres database is behind proxy (haproxy or nginx), nfacctd cannot connect to it.

In logs:
Jul 17 16:44:01 flow nfacctd[122936]: ERROR ( ip/pgsql ): The SQL server says: Failed connecting to dbname=pmacct user=pmacct password=pass port=8432

In postgres logs - nothing. 

connection via cli like "psql -U pmacct -h 10.98.8.17 -p 8432 pmacct" - passed successfully.

config of nfacctd:
daemonize: false
pidfile: /var/run/nfacctd.pid
syslog: daemon
plugins: pgsql[ip]
nfacctd_port: 2100
sql_optimize_clauses[ip]: true
sql_table[ip]: nfacctd_ip_%Y%m%d
sql_table_schema[ip]: /etc/pmacct/pgsql_nfacctd_ip.schema
sql_db[ip]: pmacct
sql_passwd[ip]: pass
sql_user[ip]: pmacct
sql_host[ip]: 10.98.8.17
sql_port[ip]: 8432
sql_refresh_time[ip]: 120
sql_history[ip]: 120
sql_history_roundoff[ip]: m
bgp_daemon: true
bgp_daemon_ip: 10.200.0.21
bgp_daemon_max_peers: 100
bgp_daemon_id: 10.98.2.18
bgp_daemon_as: 65534
bgp_daemon_msglog_file: /home/pnd/pm/bgp_nf-$peer_src_ip.txt
bgp_daemon_msglog_output: json
nfacctd_as: bgp
bgp_peer_src_as_type: map
bgp_peer_src_as_map: /etc/pmacct/peers.map
aggregate[ip]: tag, class, src_mac, dst_mac, vlan, in_iface, out_iface, src_host, dst_host, src_port, dst_port, tcpflags, proto, tos, timestamp_start, timestamp_end, timestamp_arrival, int_descr
aggregate_primitives: /etc/pmacct/primitives.lst
pre_tag_map: /etc/pmacct/pretag.map

config of haproxy:
listen postgres5
    bind *:8432
    #bind 127.0.0.1:5432
    mode tcp
    #option  dontlognull
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s
    option httpchk OPTIONS /master
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server postgresql1 10.98.8.17:5432 maxconn 1000 check port 8008
    server postgresql2 10.98.8.18:5432 maxconn 1000 check port 8008
    server postgresql3 10.98.8.19:5432 maxconn 1000 check port 8008

or via nginx:
stream {
 server {
  listen 8432;
  proxy_pass 10.98.8.17:5432;
 }
}

I tried it with pmacct-1.7.2, pmacct-1.7.3, pmacct-1.7.4, pmacct-1.7.5, pmacct-1.7.6 - result is the same.
root@flow:/home/pnd# /usr/sbin/nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)

Arguments:
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pmacct-8WorSQ/pmacct-1.7.2=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'

Libs:
libpcap version 1.8.1
MariaDB 10.3.12
PostgreSQL 110007
sqlite3 3.27.2
rabbimq-c 0.9.0
rdkafka 0.11.6
jansson 2.12
MaxmindDB 1.3.2
ZeroMQ 4.3.1
netfilter_log

System:
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64

Maybe i missed something?

**Comment by paololucente** [comment]
Hi @gklpnd , 

I can confirm that this is not a tested scenario and i can't easily test it myself. Can you check what happens on the wire? Is a connection even established between where pmacct lies and one of the PostgreSQL servers? Can you turn on some sort of debugging for PostgreSQL logs?

In theory what you can do with the 'psql' command you should be able to do via libpq - which is what pmacct uses to interface with PostgreSQL. Both browsing library docs and checking on the web i can't find any specific reference to / issue among the use of proxy & libpq.

Paolo

**Comment by gklpnd** [comment]
Thanks for reply.

Something strange:)

I moved all to the localhost, for simplifier.... Nginx as proxy at 127.0.0.1:8432 proxying to 127.0.0.1:5432.

In postgresql i enabled debug logs:
root@flow:/home/pnd/pmacct# grep log /etc/postgresql/11/main/postgresql.conf  | grep -v "^#"|egrep -v "(^$|^\s*#)"
logging_collector=on                                    # into log files. Required to be on for
log_min_messages=debug5
log_min_error_statement=debug5
log_connections=on
log_disconnections=on
log_line_prefix = '%m [%p] %q%u@%d '            # special values:
log_statement='all'
log_timezone = 'Europe/Kiev'
default_text_search_config = 'pg_catalog.english'

When i connecting via cli psql in logs i see:
2020-07-20 10:37:38.473 EEST [134650] [unknown]@[unknown] LOG:  connection received: host=[local]
2020-07-20 10:37:38.473 EEST [134650] postgres@postgres DEBUG:  postgres child[134650]: starting with (
2020-07-20 10:37:38.473 EEST [134650] postgres@postgres DEBUG:          postgres
2020-07-20 10:37:38.473 EEST [134650] postgres@postgres DEBUG:  )
2020-07-20 10:37:38.473 EEST [134650] postgres@postgres DEBUG:  InitPostgres
2020-07-20 10:37:38.474 EEST [134650] postgres@postgres DEBUG:  my backend ID is 3
2020-07-20 10:37:38.474 EEST [134650] postgres@postgres DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
2020-07-20 10:37:38.474 EEST [134650] postgres@postgres LOG:  connection authorized: user=postgres database=postgres

From nfacctd no connections.

I added logs at nginx:
stream {
    log_format basic '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time';
    log_format basic2 '$remote_addr [$time_local] ' '$protocol $status ';

    access_log  /var/log/nginx/accessstr.log basic2;
    error_log  /var/log/nginx/errorstr.log debug;

  server {
    listen 8432;
    proxy_pass 127.0.0.1:5432;
 }
}

Also no logs at nginx access\error logs.

I have tried tcpdump (tcpdump -n -nn -vvv -i lo 'port 5432 or port 8432'), but output is empty .

At Haproxy logs also no connection from nfacctd.

What is the next step?

Thanks!

p.s. I don't understand why there is nothing in the proxy logs about connecting from nfacctd :(

**Comment by paololucente** [comment]
Shall you further simplify the scenario and remove the proxy from the middle alltogether, so nfacctd would connect directly to one of the PostgreSQL servers, does it work? Consider nfacctd does not establish a permanent connection to the database: every sql_refresh_time time interval (120 secs according to your config) it connects to dump flow data (if there is flow data do dump; ie. if no data, it does not try to connect).

**Comment by gklpnd** [comment]
Yes, without proxy it works (something it write to tables).

**Comment by paololucente** [comment]
I see. Would it be possible to access your setup for troubleshooting? If positive, let's follow-up by unicast email. If negative then we can keep this issue open until i'll find a way to replicate your setup and reproduce the issue.

**Comment by paololucente** [comment]
@gklpnd kindly confirmed the fix working. Closing.
