### ISSUE TITLE
pmacct: installation via apt in Ubuntu 18

### ISSUE THREAD

**Issue by maddog-nn** [pmacct/pmacct#421]
Hello, 
I've installled pmacct client 1.7.0 (20170924-00+c1) using apt in Ubuntu 18.04
Could you tell me please - how can I run pmacct with mySQL and Grafana or where I can find information about this?

Thank you in advance!

**Comment by paololucente** [comment]
Hello,

Iam not aware of any tutorial covering the specific setup you are looking for. If you are looking to build a data pipeline please look at the good https://github.com/neptune-networks/flow-exporter project for inspiration. There you have pmacct -> Kafka -> Prometheus -> Grafana. If you are convinced about MySQL then you should just replace the Prometheus bit with MySQL (and of course perhaps the data you are looking to save may be different).

I will close this Issue. 

Paolo

**Comment by maddog-nn** [comment]
Hello Paolo, I'll be wery grateful to you if you help me - i've installed pmacct + mysql server + grafana. /etc/pmacct/nfacctd.conf I've configured like from your examples and run it like nfacctd.conf -f /etc/pmacct/nfacctd.conf but I'm not seeing data im mysql database...

```
[dd@ub01:/usr/local/share/pmacct/sql]$ nfacctd -f /etc/pmacct/nfacctd.conf
INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200510-00)
INFO ( default/core ):  '--enable-mysql' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/etc/pmacct/nfacctd.conf'.
INFO ( default/core ): waiting for NetFlow/IPFIX data on :::5678
INFO ( foo/mysql ): cache entries=32771 base cache memory=11727392u bytes
INFO ( foo/mysql ): *** Purging cache - START (PID: 5919) ***
INFO ( foo/mysql ): *** Purging cache - END (PID: 5919, QN: 0/0, ET: X) ***
INFO ( foo/mysql ): *** Purging cache - START (PID: 5942) ***
INFO ( foo/mysql ): *** Purging cache - END (PID: 5942, QN: 0/0, ET: X) ***
INFO ( foo/mysql ): *** Purging cache - START (PID: 5946) ***
INFO ( foo/mysql ): *** Purging cache - END (PID: 5946, QN: 0/0, ET: X) ***
```
Thank you in advance.

**Comment by maddog-nn** [comment]
Here is /etc/pmacct/nfacctd.conf

```
[dd@ub01:~]$ sudo vim /etc/pmacct/nfacctd.conf
daemonize: false
nfacctd_time_new: true
nfacctd_port: 5678
plugins: mysql[foo]
aggregate[foo]: src_host
sql_db[foo]: pmacct
sql_table[foo]: acct_v4
sql_table_version[foo]: 4
sql_passwd[foo]: face2face
sql_user[foo]: root
sql_refresh_time[foo]: 120
sql_history[foo]: 10m
sql_history_roundoff[foo]: mh
```
