### ISSUE TITLE
Support ICMP/ICMP6 types and codes

### ISSUE THREAD

**Issue by indyprime** [pmacct/pmacct#422]
**Description**
There doesn't seem to be support for recording the ICMP/ICMP6 types and codes in generated flows that are exported to collectors. Could this be added to provide missing information on these protocols? This is important for IPv4, but even more so for IPv6.

Some flow generators have placed them in the Destination Port (otherwise unused for ICMP/ICMP6) in the format "type.code"; for example, "3.1" would represent ICMP type 3 (Destination Unreachable), code 1 (Host Unreachable). That would be fine, or placing them in their own fields.

**Version**
nfacctd 1.7.6-git (as synced from github on 7/29)

**Comment by paololucente** [comment]
Hey Indy / Ken, @indyprime ,

Thank you for opening an issue here and checking up. Adding Enhancement label and i was targeting next week for this dev. We should have convergence pretty soon!  

Paolo

**Comment by paololucente** [comment]
Hey Indy / Ken, @indyprime ,

Thanks for your patience with this. This is now done & tested, it would be great if you could give a test yourself. I went for the common practice of encoding ICMP code/type in the destination port field. For one moment i thought to do go for the cleaner approach but than that would constrain you in using nfacctd as a collector. Shall a need to be cleaner ever emerge, i will be more than happy to tackle this issue with perhaps a config knob. 

Paolo

**Comment by indyprime** [comment]
I updated from github a few hours after your message and started tested on my current flows.  IPv4 looks good, with the ICMP Type and Code appearing in the dest port as expected. However, all ICMP6 Types/Codes are still set to zeros, which isn't correct for any of them.

Do the changes require any additional configuration for IPv6 (which aren't required for IPv4)?

**Comment by indyprime** [comment]
[pmacct-config.conf.txt](https://github.com/pmacct/pmacct/files/5307894/pmacct-config.conf.txt)

**Comment by paololucente** [comment]
Wonderful to have your attention on this & apologies for the time it took to converge. I did push a patch that should solve the issue (my bad). Can you give a new try to latest & greatest code?

**Comment by indyprime** [comment]
With the updates and the same config file, I get an error now:
**ERROR ( default/core ): Unknown primitive 'icmp_type'**

I noticed that the icmp_type and icmp_code primitives aren't listed with the command **pmacctd -a**

**Comment by paololucente** [comment]
Yes - there has never been an icmp_type primitive (not sure why you were not getting that before): you should include 'dst_port' in the list of your aggregation primitives and the magic happens.

**Comment by indyprime** [comment]
Sorry, I seem to have mixed up config files with the ones I had been unsuccessfully testing for creating aggregate primitives for the types/codes.

This works well for ICMP6 now, and continues to work for ICMP. Thank you! This will be great to have for flows going forward.

**Comment by paololucente** [comment]
Fantastic. Thank you for your bearing with this, much appreciated. Closing the issue. Paolo
