### ISSUE TITLE
timestamp primitive didn't work

### ISSUE THREAD

**Issue by cyrilhokage** [pmacct/pmacct#424]
**Description**
Hello, my issue is quite simple (i hope).
I use pmacct to collect sflow datagrams from a switch and send them to a kafka broker. Everything works fine, unless one issue in the aggregation. I would like to have all these primitives : src_host, dst_host,in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, tcpflags

but when i launch my sfacctd.conf file, i see somme of them, but neither the timestamp_start, not the timestamp_end primitive.
Here is my sfacctd.conf file 

`kafka_topic: <tpic_name>
kafka_broker_host: <**.**.**.**>
kafka_broker_port: XXXX
kafka_refresh_time: 1
!pcap_interface: *<local interface to listen for netflow packets on>*

plugins: kafka

aggregate: src_host, dst_host,in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, tcpflags`

? Did something go wrong? 

**Version**
Flow Accounting Daemon, sfacctd 1.7.2-git

Libs:
libpcap version 1.5.3
rdkafka 0.9.2-RC1
jansson 2.12

System:
Linux 4.13.16-3.el7.x86_64 #1 SMP Fri Oct 18 09:11:26 UTC 2019 x86_64

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi @cyrilhokage , 

timestamp_end is not populated because sFlow captures individual samples (it does not have the NetFlow caching mechanism that attempts at building flows); but timestamp_start should be populated fine and i just tested it working as expected against master code on GitHub. Although not much changed in that specific section of the code, do you want to give a try to master code to see if it helps?

Paolo

**Comment by paololucente** [comment]
Hi @cyrilhokage ,

A quick note to say that if you consider giving a try to master code, see the commit above. timestamp_start was effectively aliased over timestamp_arrival; i've polished this up. Please use timestamp_arrival instead. More detailed explanation is in the UPGRADE file.

Paolo

**Comment by cyrilhokage** [comment]
HI @paololucente , 

Thank you i've tried it but it still can't have a timestamp primitive? May be i have to uninstall an re-install pmacct ?

**Comment by paololucente** [comment]
@cyrilhokage ,

Try an higher kafka_refresh_time. Say 60 secs and see if it helps. It may also be a symptom that the Kafka broker is unable to process the amount of data you are throwing at it (maybe needs some tuning, maybe it needs a scale out): check if the Kafka broker is pegging 100% CPU.

Paolo

**Comment by cyrilhokage** [comment]
@paololucente ,

Thanks, i changed the kafka_refresh_time to 60 seconds, and the error disapeared ! But now everything seems ok, but i don't receive any flows.  When i run `**sfacctd -f safcctd.conf**` i have this :

![image](https://user-images.githubusercontent.com/43598248/93098113-c054ac00-f6a6-11ea-8bf2-cda9b0a88706.png)


But when i try to print received flows with pmacct i have nothing, and my kafka topic is empty.

Here are the sfacctd logs when i launch it in debug mode.

![image](https://user-images.githubusercontent.com/43598248/93097783-49b7ae80-f6a6-11ea-9613-85e34213f0a7.png)

Do you know the origin of this error please ?

P.S : At the begining i pmacct worked fine, i just missed timestamp information, but i stoped received flows when i cloned the latest version of pmacct on github, and restart the installation process. 

Thanks,
