### ISSUE TITLE
Can't receive sflow data

### ISSUE THREAD

**Issue by cyrilhokage** [pmacct/pmacct#425]
**Description**
Hello, i have an issue or a bug with pmacct. I have properly installed pmacct, and configured it. I have also configured **sflow** on a switch (ARISTA) to send sflow datagrams to the pmacct server. I start sfacct with `sfacctd -f sfacctd.conf`, and i have this :  
![image](https://user-images.githubusercontent.com/43598248/93190041-2727a300-f743-11ea-8751-4016b4e1e3c8.png)

But when i try to see received datagrams, i have nothing `pmacct -p /tmp/collect.pipe -s`. 
I also want to send data to kafka, and even in kafka i have nothing ...

Here is my sfacctd.conf file : 

`debug: false
! for this example, I wan to run sfacctd by hand and look at the output
!daemonize: true
pidfile: /path/to/pid

plugin_pipe_size: 10240000

plugin_buffer_size: 10240

plugins: kafka, memory

sfacctd_port: 6343
kafka_topic: <topic_name>
kafka_broker_host: XX.XX.XX.XX
kafka_broker_port: 9092
kafka_refresh_time: 1

aggregate: src_host, dst_host,in_iface, out_iface, timestamp_arrival, src_port, dst_port, proto, tos, tcpflags`

Do someone know what can i do, and how can i fix this error please ?

Thanks

**Version**
Here is the version of sfacctd 

![image](https://user-images.githubusercontent.com/43598248/93190607-d95f6a80-f743-11ea-9441-7e19116aa539.png)

**Comment by paololucente** [comment]
Hi @cyrilhokage , i suggest for a start you review https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2887-#L2926 : specifically points 1, 2 and 4. Paolo
