### ISSUE TITLE
Unable to compile pmacct with ndpi support

### ISSUE THREAD

**Issue by tbard1** [pmacct/pmacct#427]
**Description**
Tried to compile pmacct with ndpi support (./configure --enable-ndpi), got an error : 

  CCLD     libdaemons.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     pmacct
/usr/bin/ld: ./.libs/libdaemons.a(libdaemons_la-util.o): in function `version_daemon':
/root/pmacct/src/util.c:1903: undefined reference to `ndpi_revision'
/usr/bin/ld: ./.libs/libdaemons.a(libdaemons_la-print_plugin.o): in function `P_cache_purge':
/root/pmacct/src/print_plugin.c:597: undefined reference to `ndpi_get_proto_name'
/usr/bin/ld: /root/pmacct/src/print_plugin.c:597: undefined reference to `ndpi_get_proto_name'
/usr/bin/ld: /root/pmacct/src/print_plugin.c:883: undefined reference to `ndpi_get_proto_name'
/usr/bin/ld: /root/pmacct/src/print_plugin.c:883: undefined reference to `ndpi_get_proto_name'
/usr/bin/ld: ./.libs/libdaemons.a(ndpi.o): in function `pm_ndpi_free_flow_info_half':
/root/pmacct/src/ndpi/ndpi.c:39: undefined reference to `ndpi_flow_free'
/usr/bin/ld: /root/pmacct/src/ndpi/ndpi.c:44: undefined reference to `ndpi_free'
/usr/bin/ld: /root/pmacct/src/ndpi/ndpi.c:49: undefined reference to `ndpi_free'
/usr/bin/ld: ./.libs/libdaemons.a(ndpi.o): in function `pm_ndpi_get_flow_info':
/root/pmacct/src/ndpi/ndpi.c:224: undefined reference to `ndpi_flow_malloc'
/usr/bin/ld: /root/pmacct/src/ndpi/ndpi.c:230: undefined reference to `ndpi_malloc'
/usr/bin/ld: /root/pmacct/src/ndpi/ndpi.c:236: undefined reference to `ndpi_malloc'
/usr/bin/ld: ./.libs/libdaemons.a(ndpi.o): in function `pm_ndpi_node_guess_undetected_protocol':
/root/pmacct/src/ndpi/ndpi.c:443: undefined reference to `ndpi_guess_undetected_protocol'
/usr/bin/ld: ./.libs/libdaemons.a(ndpi.o): in function `pm_ndpi_packet_processing':
/root/pmacct/src/ndpi/ndpi.c:357: undefined reference to `ndpi_detection_process_packet'
/usr/bin/ld: /root/pmacct/src/ndpi/ndpi.c:376: undefined reference to `ndpi_detection_giveup'
/usr/bin/ld: ./.libs/libdaemons.a(ndpi.o): in function `pm_ndpi_idle_flows_cleanup':
/root/pmacct/src/ndpi/ndpi.c:493: undefined reference to `ndpi_free'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:835: pmacct] Error 1
make[3] : on quitte le répertoire « /root/pmacct/src »
make[2]: *** [Makefile:1341: all-recursive] Error 1
make[2] : on quitte le répertoire « /root/pmacct/src »
make[1]: *** [Makefile:680: all] Error 2
make[1] : on quitte le répertoire « /root/pmacct/src »
make: *** [Makefile:729: all-recursive] Error 1

**Version**
pmacct 1.7.6
ndpi 3.2 stable
Debian GNU/Linux 10 \n \l

Any idea ?

**Comment by paololucente** [comment]
Hi Thomas,

Is it possible that after you compiled nDPI, you missed to slap in a 'ldconfig'? Summary of all the errors is that the linker can't find the nDPI library.

Paolo

**Comment by tbard1** [comment]
you're right ! thanks a lot for your support. 

Thomas
