### ISSUE TITLE
Wrong timestamp values 

### ISSUE THREAD

**Issue by ixodis** [pmacct/pmacct#432]
Hi Paolo!

Running nfacctd 1.7.4 with configuration:

> plugins: kafka[out]
> ...
> interface: eth0
> nfacctd_port: 3070
> ...
> timestamps_utc: true
> nfacctd_time_new: true
> 

I receive wrong timestamp_start and timestamp_end values from Palo Alto (netflow 9) firewall device:

> "timestamp_start": "2020-08-17 21:32:16.000000"
> "timestamp_end": "2020-08-17 21:32:16.000000"
> "timestamp_arrival": "2020-10-06 14:35:02.973186"

Changing nfacctd_time_new to false didn't help. I'll send you pcap file via email, please help me to resolve this problem

**Comment by paololucente** [comment]
Hi Roman ( @ixodis ), 

Got your trace, thank you. I did replay it with a simple:

`nfacctd -I palo07.pcap -c timestamp_start,timestamp_end,src_host,dst_host,src_port,dst_port,proto -W` 

And then checked stats with `pmacct -s -O json`. I can say that all timestamp_start / timestamp_end are in order, ie. are from the day of today, Oct 6th. Would you have your full config to share? It almost appears you may have `timestamps_secs: true`.

Paolo

**Comment by ixodis** [comment]
I forgot to say that not all entries have invalid dates, some of them are correct. Also I can't find wrong dates today - that's strange.

Configs: [nfacctd.conf.txt](https://github.com/pmacct/pmacct/files/5339020/nfacctd.conf.txt)
[primitives_pa.txt](https://github.com/pmacct/pmacct/files/5339022/primitives_pa.txt)
[ssl.property_lz4.txt](https://github.com/pmacct/pmacct/files/5339024/ssl.property_lz4.txt)
[template_common.txt](https://github.com/pmacct/pmacct/files/5339025/template_common.txt)

Partial output from Kafka with wrong dates:
[palo06_kafka.txt](https://github.com/pmacct/pmacct/files/5339021/palo06_kafka.txt)

If you look at the record with FlowSequence: 2637928426 & Flow Id: 72715490 in pcap file:
[2637928426.txt](https://github.com/pmacct/pmacct/files/5339035/2637928426.txt)

and in Kafka:
{"event_type": "purge", "peer_ip_src": "10.42.51.113", "iface_in": 500021243, "iface_out": 500010243, "ip_src": "10.63.179.25", "ip_dst": "172.29.24.107", "port_src": 443, "port_dst": 56005, "tcp_flags": "18", "ip_proto": "tcp", "tos": 0, "sampling_rate": 0, "post_nat_ip_src": "", "post_nat_ip_dst": "", "post_nat_port_src": 0, "post_nat_port_dst": 0, "nat_event": 0, "timestamp_start": "2020-08-17 21:32:16.000000", "timestamp_end": "2020-08-17 21:32:16.000000", "timestamp_arrival": "2020-10-06 14:35:02.973196", "export_proto_seqno": 2637928426, "export_proto_version": 9, "export_proto_sysid": 16908288, "firewallevent": "1", "nf_f_ingress_acl_id": "", "nf_f_egress_acl_id": "", "nf_f_fw_ext_event": "0", "observationtimemilliseconds": "0", "flowid": "72715490", "in_bytes": "70", "in_pkts": "1", "initiatoroctets": "0", "responderoctets": "0", "initiatorpackets": "0", "responderpackets": "0", "icmp_type": "0", "icmptypeipv4": "0", "icmpcodeipv4": "0", "nf_f_username": "", "app_id": "", "user_id": "", "packets": 1, "bytes": 70, "writer_id": "out/23411"}

you can see that dates are incorrect

**Comment by paololucente** [comment]
Hi Roman ( @ixodis ),

Oh, i see, easy peasy: timestamps are overflowing, you should point this issue to your vendor. I have just passed a commit ( https://github.com/pmacct/pmacct/commit/a942bc48fb1a6d2a39784cc4b4f1b8a541514bd4 ) that, when debug is enabled, warns about such condition (you can point your vendor to this specific commit / check to show them what is wrong). Output of pmacct would be something a-la:

`DEBUG ( default/core ): Received NetFlow/IPFIX packet from [10.42.51.113:51704] version [9] seqno [2637895287]`
`DEBUG ( default/core ): [2637895287] firstSwitched > sysUptime timestamp. Overflow detected.`
`DEBUG ( default/core ): [2637895287] lastSwitched > sysUptime timestamp. Overflow detected.`
`DEBUG ( default/core ): [2637895287] firstSwitched > sysUptime timestamp. Overflow detected.`
`DEBUG ( default/core ): [2637895287] lastSwitched > sysUptime timestamp. Overflow detected.`

Hope this helps and i'd proceed to close this issue.

Paolo

**Comment by ixodis** [comment]
Paolo, thank you! I will create a ticket to vendor
