### ISSUE TITLE
selective netflow exporter

### ISSUE THREAD

**Issue by obla4ko** [pmacct/pmacct#433]
**Description**
Good day!
This ticket  is not really a problem, but rather a performance and architecture issue.

I have a large stream of information from cisco switches. Unfortunately, my monitoring system cannot process all incoming flow. I thought that it would be possible to put a pmacct utility between the switch and the monitoring system, which would cut out unnecessary subnets from the stream and send only the necessary ones. For example below i tried to display this

Model now:
-=many switches=---=netflow v9=---=monitoring system=-

Model after:
-=many switches=---=netflow v9=--=pmacct netflow daemon + filter=--=netflow v9=---=monitoring system=

Netflow now:
10.0.0.0/24.      <->10.200.0.0/24
100.100.0.0/16 <->15.100.0.0/16
1.1.1.1/32<->8.8.8.8/32
4.4.4.4/32<5.5.5.5/32>
..... and many other networks

Netflow after add pmacct
1.1.1.1/32<->8.8.8.8/32
4.4.4.4/32<5.5.5.5/32>

I tried 2 configuration for this.
1. configuration with pmacctd (libpcap). In this case pmacct put eth0 to promiscuous mode and sended only netflow information  about incoming packets. As far as I understand, if I need to analyze a netflow, this mode doesnt work
2. configuration with nfacctd. In this case pmacct listen interface eth0(and i check it through ss -tapnu). But i don't understand, will the aggregation rules work in this configuration?

Total:
1. Can i use second configuration for my task?
2. Is it possible to somehow make the first configuration in flow analysis mode? (not packet)

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191126-01+c6)

Arguments:
 '--sysconfdir=/etc/pmacct' '--prefix=/usr' '--disable-bgp-bins' '--disable-bmp-bins' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1

System:
Linux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64

Compiler:
gcc 7.5.0

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi @obla4ko ,

Thanks for getting in touch. It should be that you are looking for using the 'nfacctd' daemon with the 'tee' plugin to replicate data. You can read more here: https://github.com/pmacct/pmacct/blob/1.7.5/QUICKSTART#L2043-#L2200 . Specifically, you are interested in the "XVa. Splitting and dissecting data while replicating" section. Replicating and dissecting brings some limitations but should achieve what you want.

Paolo

**Comment by obla4ko** [comment]
Paolo, thanks for the answer.
After reading, I had a few questions about thread splitting.
1. Suppose the switch has sent a set of information, in which there are 5 flows. of all the flows, I only need 1 and 3 flows. Will nfacctd re-create a flow, with only 2 flows, or will it create 2 new flows, each containing information one by one?
![image](https://user-images.githubusercontent.com/4190324/95481443-acdeed00-0995-11eb-9c44-42e8b44e58ef.png)

**Comment by paololucente** [comment]
Hi @obla4ko ,

> Will nfacctd re-create a flow set, with only 2 flows, or will it create 2 new flow set, each containing information one by one?

The poor man solution, that is, the second you mention. Once things are unpacked they are not re-packed optimally.  

Paolo
