### ISSUE TITLE
[QUESTION] IPFIX record export with BGP Next Hop added

### ISSUE THREAD

**Issue by kabraet** [pmacct/pmacct#435]
Hello,

Just wanted to know if it is possible to use PMACCT to import IPFIX records and BGP data. After this determine the BGP Next Hop the router has selected for the IP destination in the IPFIX record using the BGP information.

Then use this information to create an updated version of the IPFIX record with the BGP Next Hop as added field and export this to other IPFIX collectors while having the source IP address in the IP header of the UDP IPFIX packet set to the router of the original IPFIX record was created.

Kind Regards,
Kamiel Braet

**Comment by paololucente** [comment]
Answered on the pmacct-discussion mailing-list:

`Unfortunately, no, this scenario (take IPFIX, massage it & spit it out) is not supported.`

Paolo
