### ISSUE TITLE
Valgrind detected a memory leak in bgp_aspath.c

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#436]
**Description**
Valgrind reported the following memory leak
==29599== 27,553 bytes in 27,553 blocks are definitely lost in loss record 160 of 194
==29599==    at 0x4C2DC0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29599==    by 0x4CF0FA: aspath_make_empty (bgp_aspath.c:484)
==29599==    by 0x4CF489: aspath_make_str_count.isra.4 (bgp_aspath.c:506)
==29599==    by 0x4CF4FE: aspath_str_update (bgp_aspath.c:603)

Appears the function aspath_make_empty() allocates 1 byte that's returned in str_buf,
yet another malloc on line 522 to str_buf results in the 1 byte leak.

Should the code
     if (!as->segments) str_buf = aspath_make_empty();
be modified to return?
     if (!as->segments) { str_buf = aspath_make_empty(); return str_buf; }

**Version**
v1.7.4

**Appreciation**
Thank You!

**Comment by paololucente** [comment]
Hi Peter ( @pothier-peter ),

That seems indeed to be the case, thanks for catching this. Would you like the honor to submit a PR? I like the full attribution part - so my preference would be for you to do it. If not, of course, i will take care of it myself.

Paolo

**Comment by pothier-peter** [comment]
Hello Paolo,

I'll make the change in my code, do some testing, and then get a PR going, hopefully today.

Thank You,
Peter P

**Comment by pothier-peter** [comment]
https://github.com/pmacct/pmacct/pull/437
