### ISSUE TITLE
Something wrong with collector aggregation filters

### ISSUE THREAD

**Issue by RomkaKharkov** [pmacct/pmacct#445]
**Description**
Seems nfacctd aggregation have problem, not sure , but need check this anyway. I will copy two "rules" from my config for show situation.

> plugins: print[smtp], print[full]

> aggregate[full]: src_host, dst_host, dst_port, timestamp_arrival
> print_refresh_time[full]: 300
> print_output_file[full]: /opt/dev-ddos/pipes/%Y/%m/%d/%H.full
> print_output_file_append[full]: true

> aggregate[smtp]: src_host, dst_host, dst_port, timestamp_arrival
> aggregate_filter[smtp]: dst port 25
> print_refresh_time[smtp]: 300
> print_output_file[smtp]: /opt/dev-ddos/pipes/%Y/%m/%d/smtp.stat
> print_output_file_append[smtp]: true

Like you see, both of my aggregate have same aggregate parameters "src_host, dst_host, dst_port, timestamp_arrival" (maybe problem there). By my logic , i should have "full stats" into "%H.full" files and stats with "dst port 25" into daily "smtp.stat" file.

But !

```
# cat 10.full |grep 45.142.xxx.xxx (hide from other)
8
# cat smtp.stat |grep 45.142.xxx.xxx|wc -l
0

```
So, data with IP "45.142.xxx.xxx" collected just in "Full" aggregate. In same "full" aggregate i see 25 port usage like this:
`45.142.xxx.xxx                                 xxx.xxx.xxx.xxx                                   25        2020-11-15 10:01:44.579161     13                    752`

But nothing in "smtp" aggregate.....

Maybe i do something wrong ? or maybe aggregate "smtp" rewrited by  "full" because have same aggregation rules ? 

In my case i just have two same aggregation rules but one of them have additional filter for "dst port 25".

So, this is bug? or i should do this another way?

**Version**
```
NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200510-00)
Arguments:
 '--enable-mysql' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
Libs:
libpcap version 1.5.3
MySQL 5.5.65-MariaDB
System:
Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64
Compiler:
gcc 4.8.5
For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

```

**Comment by paololucente** [comment]
Hi @RomkaKharkov ,

Is it possible the traffic is VLAN-tagged? If so, filters are 'sensible' to that, see here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2942-#L2947 .

Paolo

**Comment by RomkaKharkov** [comment]
Hi Paolo,

Its a magic, seems it working now, i will check this next few days and will report there again. 
But this mean now my filter not match "untagged" traffic, right ? Should i build two aggregations ?

Thank you!!!
> 
> 
> Hi @RomkaKharkov ,
> 
> Is it possible the traffic is VLAN-tagged? If so, filters are 'sensible' to that, see here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2942-#L2947 .
> 
> Paolo

**Comment by paololucente** [comment]
Hi @RomkaKharkov ,

You can do two aggregations - so instantiate two plugins - sure. You can make the expression also slightly more complex to catch both, ie. "( vlan and port 25 ) or port 25". The syntax of the filter expression is in libpcap format, that is, exact same as tcpdump: any examples you can find online and/or test working against tcpdump, it should work as well as part of 'aggregate_filter'.

Paolo

**Comment by RomkaKharkov** [comment]
Hi Paolo,

Thanks a lot, works perfect. One more question , just can't understand from DOCs.

Can i do something like "network lists" for my aggregations ?

For example:
MYNET=1.1.1.1/24
MYNET=2.2.2.2/24

then aggregate[xxxx]: src_ip MYNET

Its possible some way ? just let me know needed parameter i will check itself.

T.Y

**Comment by paololucente** [comment]
Hi @RomkaKharkov ,

1) If you want only to filter in certain subnets, you can append "src net x.x.x.x or src_net y.y.y.y or .." to the aggregate filter.

2) If you want to aggregate ie. you don't want to report on the singular IP addresses but on some subnets, you can use a 'networks_file' (see CONFIG-KEYS) to list the subnets and have 'src_net' or 'dst_net' primitive on your 'aggregate' config directive. 

3) If you want to filter and aggregate, you can follow point 2 above plus set 'networks_file_filter: true' in the config. This can be also an alternative method - less optimal but equivalent - to point 1.

Paolo

**Comment by RomkaKharkov** [comment]
Hi @paololucente

> 
> 
> Hi @RomkaKharkov ,
> 
>     1. If you want only to filter in certain subnets, you can append "src net x.x.x.x or src_net y.y.y.y or .." to the aggregate filter.
> 
>     2. If you want to aggregate ie. you don't want to report on the singular IP addresses but on some subnets, you can use a 'networks_file' (see CONFIG-KEYS) to list the subnets and have 'src_net' or 'dst_net' primitive on your 'aggregate' config directive.
> 
>     3. If you want to filter and aggregate, you can follow point 2 above plus set 'networks_file_filter: true' in the config. This can be also an alternative method - less optimal but equivalent - to point 1.
> 
> 
> Paolo

I think i mean other one, i want something like list of ranges for filtering and aggregation.

For example i have 2 subnets like 1.1.1.0/24 and 1.1.2.0/24 (sure each list will be less then 1 subnet), then i want use name of this list for filtering.
LIST1=1.1.1.0/24
LIST1=x.x.x.x/24

LIST2=1.1.2.0/24
LIST2=y.y.y.y/24

Then i was use links to this lists for filtering for example:
plugin[XXX]
aggregate[XXX]: src_ip LIST2

plugin[YYY]
aggregate[YYY]: src_ip LIST2

I hope i use nfacctd right ;) 

Thnk you for your time Paolo!

**Comment by paololucente** [comment]
Cool, then i think you want 2 + 3 from my previous message:

In your nfacctd config:
```
aggegate: src_net, [ .. ]
networks_file: /path/to/networks.lst
networks_file_filter: true
```

In networks.lst:
```
1.1.1.0/24
1.1.2.0/24
```

Paolo

**Comment by RomkaKharkov** [comment]
Hi @paololucente,

Thank you, will try very soon.!
