### ISSUE TITLE
Netflow/IPFIX enrichment in nfacctd

### ISSUE THREAD

**Issue by ixodis** [pmacct/pmacct#448]
Hi Paolo!

My installation of nfacctd receives netflow/ipfix (no BGP) with Kafka output plugin. Also I have SQL DB with IP addresses of internal hosts, their hostnames, users logged on it, type of their OS, etc. Is it possible to enrich the nfacctd output matching src_ip/dst_ip with data from this DB (or some text file with the same data if it's not possible to work with SQL DBs)?

**Comment by paololucente** [comment]
Hi Roman ( @ixodis ),

Nice one. pmacct comes with an infrastructure to tag data, pre_tag_map. It has some potential but of course it could be improved and made more powerful. It essentially can match one or more conditions (ie. 'src_net', 'dst_net' or 'filter' to provide a full fledged filter in libpcap format) and output a tag (positive number) or a label (string). tags are more efficient, labels are prettier and can be stacked easily (ie. multiple labels per one packet / flow). Full info here: https://github.com/pmacct/pmacct/blob/master/examples/pretag.map.example 

With the above said and taking in consideration i seem to understand the context here is NetFlow / IPFIX / nfacctd (from some previous issue that you opened): with a script, at regular intervals, you could compose a pre_tag_map like this from the DB:

set_label='OS_X|hostname_Y|<any other info>' src_net=Z.Z.Z.Z/32
set_label='OS_X|hostname_Y|<any other info>' dst_net=Z.Z.Z.Z/32

Call this map from the config `pre_tag_map: /path/to/pretag.map`. For better efficiency (if not using the 'filter' keyword) you could index the map with `maps_index: true`. You can make pmacct reload updated content with a `killall -USR2 nfacctd`. The above example assumes you have two plugins, one for ingress traffic, one for egress traffic.

Hope this helps for a start. Of course the alternative would be to do the enrichment as part of your post-processing in the data pipeline.

Paolo
