### ISSUE TITLE
Issue with sfacctd for sFlow collecting 

### ISSUE THREAD

**Issue by strahinjalalic** [pmacct/pmacct#449]
Hello, I have problem with sFlow collecting data. FIrstly, I want to output anything on screen with print plugin, using standard sFlow 6343 port, binding to IP address of server I am working on. I have one source address, because of NATing sFlow packets, and basically I put that one IP address in network_file configuration file. With debuging set to true, only output on screen is "Daemonizing. Bye Bye Screen". Am I making some big mistake? Maybe not setting some config? 

Best regards

**Comment by paololucente** [comment]
Hi @strahinjalalic ,

It would help to see the log. Do not daemonize sfacctd with '-d' so that you can read the logs and perhaps spot some useful (warning / error) there. And also because otherwise you will not be able to see the output on the screen with the print plugin.

Paolo
