### ISSUE TITLE
Problem in writing sFlow data to database

### ISSUE THREAD

**Issue by NMili997** [pmacct/pmacct#452]
Hello , 
I use latest version of `sfacctd = 1.7.6-git`, and I have problem with writing sflow data in mySQL database. In first try with configuration that i will paste bellow this text, i managed to write data in database, but when I killed all `sfacctd` processes and try again it doesn't work. My database is empty and process that described `sfacctd: --DB Writer [acct]`  doesn't show anymore.

### My configuration is
```
daemonize: true
syslog: daemon
pidfile: /var/run/sfacctd.pid

sfacctd_port: 6343

plugins: mysql[acct]
sql_table[acct]: acct

sql_refresh_time[acct]: 120
sql_history[acct]: 1m
sql_history_roundoff[acct]: m


aggregate[acct]: src_mac,dst_mac,src_host,dst_host,src_port,dst_port,proto
```
### My database is _v1 in examples

**Comment by paololucente** [comment]
Hi @NMili997 ,

Check logs for any hint why it may not be working - see if you spot any error / warning message. Also, one clarification: did you manage to write data to the DB or is the DB empty (so you never managed to write data to it)? 

Paolo

**Comment by NMili997** [comment]
Hi @paololucente ,
As I say, in first try i manage data in DB (if I go in mysql and type select * from acct; I got data src_host, dst_host & more as in aggregate type). After that i delete DB and create new one(same as previous) and killed processes of `sfacctd` so I can try all processes again. After these steps my DB is empty... Weird problem since I do twice same thing.
Can you please help me with logs, where I can find them? 

Thanks for answer, 
NM

**Comment by paololucente** [comment]
You are apparently sending logs over to the 'daemon' facility of syslog so wherever that is logged, there you will find the info. Alternatively, comment out 'syslog: daemon', set a 'logfile: /tmp/sfacctd.log', try to start the daemon then browse that file for more info.

**Comment by NMili997** [comment]
Hi @paololucente ,
I found logs in /var/log/syslog, error was `ERROR ( acct/mysql ): Data too long for column 'ip_proto' at row 319#012`. I fixed this up with length extension for field named in error. 
Thanks for answers! 
Best regards,
NM

**Comment by paololucente** [comment]
Wonderful @NMili997 , thanks for confirming! Paolo
