### ISSUE TITLE
Unable to add both tag and label to packet

### ISSUE THREAD

**Issue by SanderDelden** [pmacct/pmacct#453]
**Description**
Hi,

We are trying to add tags to traffic from specific IPs in our network, the aim is to make it so that we can create traffic insights for our customers (based on their IPs). We want to add a tag to a packet based on the src_net, currently our pretag.map looks as follows:

```
! Set tag 1 for our own AS (as we want to ignore this)
!
set_tag=1       dst_as=0
! 
! Set tag 100 for customer IP
set_tag=100     src_net=1.1.1.1
!
! Define all netflow sending devices and label them
!
set_label=router1       ip=xx.xx.xx.250
set_label=router2       ip=xx.xx.xx.254
set_label=router3       ip=xx.xx.xx.243
set_label=router4       ip=xx.xx.xx.244
set_label=router5       ip=xx.xx.xx.255
set_label=router6       ip=xx.xx.xx.252
set_label=router7       ip=xx.xx.xx.246
set_label=router8       ip=xx.xx.xx.247
set_label=router9       ip=xx.xx.xx.240
```

Packets not matched by tag 100:
`{"event_type": "purge", "tag": 0, "label": "router3", "as_dst": 12345, "iface_out": 1000020, "ip_src": "2.2.2.2", "stamp_inserted": "2020-12-14 16:05:00", "stamp_updated": "2020-12-14 16:06:02", "packets": 10000, "bytes": 15220000}`

Packets matched by tag 100:
`{"event_type": "purge", "tag": 100, "label": "", "as_dst": 67890, "iface_out": 1000012, "ip_src": "1.1.1.1", "stamp_inserted": "2020-12-14 16:05:00", "stamp_updated": "2020-12-14 16:06:01", "packets": 10000, "bytes": 700000}`

As you can see the label is not present on packets matched by tag 100. 

**Version**
1.7.2

**Comment by paololucente** [comment]
Hi @SanderDelden ,

Let's say you put first all tags in your pre_tag_map file, like in your example. You should add a 'jeq=labels_section' (for example), that is, jump on equal to the 'labels' section. Then being the entry with 'set_label=router1' the first of the labels, you should add a 'label=labels_section', then labels will be evaluated.

In general, pre_tag_map is a first match wins kind of map. Should you want to do any more specific kind of evaluation, ie. some sections of it, then you should instruct the flow with JEQs.

Paolo

**Comment by SanderDelden** [comment]
Hi @paololucente ,

That makes a lot of sense, thank you for taking your time to explain this!
