### ISSUE TITLE
SSL librdkafka

### ISSUE THREAD

**Issue by dashng** [pmacct/pmacct#455]
I am librdkafka to populdate netflow data to kafka.

The kafka broker url is ssl://ip:port,ssl://ip:port, and 3 cert files provided from kakfa side:

ssl_cafile: ../ssl/CARoot.pem
  | ssl_certfile: ../ssl/certificate.pem
  | ssl_keyfile: ../ssl/key.pem

The password required also, I didnot find any related steps to setup the configuration for ssl kakfa consumer.

Please help to comment, Apprecicated.

Thanks.

**Comment by dashng** [comment]
My current config file

```
nfacctd_time_new: true
nfacctd_account_options: true
nfacctd_ip: xx.xx.xx.xx
nfacctd_port: 9995
nfacctd_renormalize: true
dtls_path: /opt/certs/
nfprobe_dtls: true
! ..
plugins: kafka
!
aggregate: tag, in_iface, flow_direction, dst_host
kafka_output: json
kafka_topic: netflow_data
kafka_broker_host: ssl://ip:port,ssl://ip:9093
kafka_broker_port: 9093
kafka_refresh_time: 10
kafka_history: 5m
kafka_history_roundoff: m
aggregate_primitives: /etc/pmacct/primitives.lst
pre_tag_map: /etc/pmacct/pretag.map
maps_refresh: true
!
debug:true
logfile: /var/log/pmacct/netflow.log
~                                      
```

**Comment by dashng** [comment]
![Uploading image.png…]()

**Comment by dashng** [comment]
![image](https://user-images.githubusercontent.com/13565116/102953496-66b51680-450c-11eb-8462-52ca4fc803be.png)

**Comment by paololucente** [comment]
Hi @dashng ,

Did you check out this part of the documentation? https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1144-#L1163

Paolo

**Comment by dashng** [comment]
yes, I saw this part. But honstely is hard for me understand how to config the ssl for librdkafka. I have no knowledge about c, from the documeentattion, I didnot find a properway on how to configure the ssl file.

**Comment by dashng** [comment]
Does the pmacct supports call external api to pass the traffic data to the api directly. then the api funciton can do the filter and populate to the kafka broker or database.

**Comment by dashng** [comment]
@paololucente 

I follow the document.
1. instatlled openssl and libssl-dev  package.
2. create a folder certs in the librdkafka root path.
3. re-build the librdkafka with command ./configure --reconfigure && make.
4. copy  the ssl files to the created certs folder. three files totally. ca-certificates.crt  cert.pem  key.pem
```
[root@alpha-kafka-1 librdkafka]# cd certs/
[root@alpha-kafka-1 certs]# ls
ca-certificates.crt  cert.pem  key.pem
```
But the issue still existing.

**Comment by paololucente** [comment]
Just to make sure we are aligned:

1) add `kafka_config_file: /path/to/librdkafka.conf` to your pmacct confg;

2) you created all needed files with OpenSSL. This seems to be the case from your last message;

3) you fill the `librdkafka.conf` with the relevant SSL config knobs to pass to the librdkafka API, ie.:

global, security.protocol, ssl
global, ssl.ca.location, ca-cert
global, ssl.certificate.location, /path/to/client_?????_client.pem
global, ssl.key.location, /path/to/client_?????_client.key
global, ssl.key.password, abcdefgh
