### ISSUE TITLE
enable plugins in 'yum install pmacct'

### ISSUE THREAD

**Issue by cyrilhokage** [pmacct/pmacct#456]
**Description**
Hello, my problem is more a question than an issue. I used to work with a compiled version of pmacct, where during the installation, i can enable plugins i want to use (like kafka) with a command line like `(./configure --enable-kafka' '--enable-jansson' '--enable-ipv6'`). 

But now, i can install it on my os (CentOs 7) with a ``yum install pmacct --enable-repo=<personal_repo>``. But with this king of installation i would like to know how i can enable needed plugins. Is there a way please ?

**Version**
Centos 7 
Latest pmacct stable version

**Comment by paololucente** [comment]
Hi @cyrilhokage ,

You can check which plugins are enabled a bit indirectly with, say, 'nfacctd -V'. It tells you which library pmacct is compiled against and that gives you a hint of whether a plugin is compiled-in or not. Like, you see it compiled against librdkafka and jansson then you know the Kafka plugin is in but, say, the AMQP (RabbitMQ) one is not.

Good input for me to make this a bit more explicit as part of the -V command.

Paolo

**Comment by cyrilhokage** [comment]
Hello @paololucente ,

Thanks for your response, here is the ourput of `sfacctd -V` . I use sfacctd daemon.

`
sFlow Accounting Daemon, sfacctd 1.7.6-git (20200628-01)

Arguments:
 '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-static' '--enable-jansson' '--enable-kafka' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
rdkafka 0.11.5
jansson 2.10

System:
Linux 5.4.70-1.el7.x86_64 #1 SMP Tue Oct 13 12:15:00 UTC 2020 x86_64

Compiler:
gcc 4.8.5

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

`

**Comment by paololucente** [comment]
Cool, so this essentially says that sfacctd is compiled with the Kafka plugin in. Plus you can output JSON. I guess should you need any other plugin, you should compile it yourself. If i am not mistaken this does answer your original question, true?

**Comment by cyrilhokage** [comment]
Hello @paololucente , Yes, it is the answer to my original question . Thank you !
