### ISSUE TITLE
Traffic aggregation counters

### ISSUE THREAD

**Issue by AlexProfi** [pmacct/pmacct#459]
**Description**
after some test ( send file with scp) get results ( make filter for get only data from sender by 22 port)
```
-rwxr-x---.  1 root       root        440414208 дек 16 01:20 VTS_01_3.VOB
[root@mon02 ~]# scp VTS_01_1.VOB root@mon01.11.ru:~/
```

on the pmacct get following
DEBUG ( click/amqp ): publishing to RabbitMQ: p_amqp_publish_string() [E=pmacct RK=acct DM=2]: `{"event_type": "purge", "ip_src": "10.10.5.98", "ip_dst": "10.10.5.97", "port_dst": 22, "country_ip_src": "", "ip_proto": "tcp", "stamp_inserted": "1609874700", "stamp_updated": "1609875001", "packets": 178569, "bytes": 484610265, "writer_id": "click/16"}`
Is it correct? Size of transferred data more by 40 Mb than file source size

**Version**
pmacct:bleedeing-edge

**Comment by paololucente** [comment]
Hi @AlexProfi ,

That's the file size. Then add encryption - since you used scp - and add network headers. It seems reasonable to me.

Paolo

**Comment by AlexProfi** [comment]
Ok thanks for comment.

**Comment by AlexProfi** [comment]
sometimes get this result
DEBUG ( click/amqp ): publishing to RabbitMQ: p_amqp_publish_string() [E=pmacct RK=acct DM=2]: `{"event_type": "purge", "ip_src": "10.10.5.98", "ip_dst": "10.10.5.97", "port_dst": 22, "country_ip_src": "O1", "ip_proto": "tcp", "stamp_inserted": "1609876500", "stamp_updated": "1609876561", "packets": 119046, "bytes": 335837337, "writer_id": "click/11"}`
