### ISSUE TITLE
Possible Memory Leak bgp_peers_free

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#463]
Running PMACCT 1.7.4 I am seeing the following Valgrind stack

     ==11551== 732,720 bytes in 645 blocks are definitely lost in loss record 129 of 130 
     ==11551==    at 0x4C2DC0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
     ==11551==    by 0x43AA99: pm_tsearch (util.c:1607)
     ==11551==    by 0x489290: bmp_process_msg_peer_up (bmp_msg.c:376) 
     ==11551==    by 0x48A544: bmp_process_packet (bmp_msg.c:89)
     ==11551==    by 0x484786: skinny_bmp_daemon (bmp.c:838)
     ==11551==    by 0x436F12: main (pmbmpd.c:272)

I am wondering whether the empty function

     void bgp_peer_free(void *a)
     {
     }

is causing a leak in the pm_tdestroy_recurse() function, here

  (*freefct) ((void *) root->key);

where the key, malloced in pm_tsearch() is orphaned. Should there be a call to free() within the bgp_peer_free() function?

**Comment by paololucente** [comment]
Hey Peter ( @pothier-peter ),

Happy New Year! You are indeed (and as always) very right. Can you please give it a try and submit a PR?

Paolo

**Comment by pothier-peter** [comment]
Hello Paolo. Thank You, let's hope 2021 is a good year.

I made the change locally and ran overnight. Memory usage looks much better. I'll get a PR going.

Peter P

**Comment by pothier-peter** [comment]
Pull Request:
https://github.com/pmacct/pmacct/pull/464
