### ISSUE TITLE
post_nat_src_ip, post_nat_dst_ip etc in nfprobe plugin

### ISSUE THREAD

**Issue by rpravm** [pmacct/pmacct#465]
When using nfprobe plugin to generate NetFlow v9 or v10 data on Linux host, 
pmacctd do not fill the post_nat_src_ip, post_nat_dst_ip fields.

Can this be fixed somehow? 

Or maybe nfprobe can generate NEL events?

**Comment by paololucente** [comment]
Hi @rpravm ,

Let's make one step back: how this information can be possibly determined using pmacctd / libpcap?

I may imagine that if you were running uacctd (as opposed to pmacctd), you could let the daemon get data from different points of the chain so to achieve desired results (or even run multiple daemons getting data from different parts of the chain so to get pre-NAT and post-NAT flows). 

Let me know your thoughts.

Paolo
