### ISSUE TITLE
timestamp_end always 0 for IPFIX

### ISSUE THREAD

**Issue by bugdealer** [pmacct/pmacct#47]
Hi,

I'm using nfacctd to collect IPFIX datagram from OVS for traffic logging. I've tried timestamp_start and timestamp_end primitives but timestamp_end always seemed to be 0 (1970-01-01 08:00:00.0 ).

IPFIX datagrams captured by wireshark shows that there actually is a flowEndDeltaMicroseconds value in the flow data (and this value will be eventually parsed as timestamp_end).

I've traced to NF_timestamp_end_handler function in  pkt_handlers.c but the code looks fine.

Can anyone tell me what the problem might be?

Thanks.
Neo

**Comment by paololucente** [comment]
Hi,

I'm assuming you are using a recent code (1.5.3, 1.6.0 or master on GitHub) so to rule out it's some old stuff. Can you get in touch by private email and send a sample of the IPFIX packets (template plus data) to look into it and eventually reproduce in lab?

**Comment by paololucente** [comment]
Enhancement addressed by: https://github.com/pmacct/pmacct/commit/f0bdefdf1e4e94de3d2745b2fe91c09c71f73ca0
