### ISSUE TITLE
WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID

### ISSUE THREAD

**Issue by DocMAX** [pmacct/pmacct#474]
**Description**
I compiled a newer version on Debian 10 (old was 1.7.2). But i get this error. (No issue with Debian verison)
How can i debug this? With debug enabled there is not more info.
```
Feb 27 04:40:01 server nfacctd[9850]: WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID 10242
Feb 27 04:43:01 server nfacctd[9850]: WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID 10875
Feb 27 04:44:01 server nfacctd[9850]: WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID 11197
Feb 27 04:45:01 server nfacctd[9850]: WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID 11456
```

**Version**
```
NetFlow Accounting Daemon, nfacctd 1.7.7-git [20210226-2 (8fb94f03)]

Arguments:
 '--enable-mysql' '--enable-geoipv2' '--enable-debug' '--prefix=/usr/local/' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'                                                                  

Libs:
cdada 0.3.4
libpcap version 1.9.1 (with TPACKET_V3)
MariaDB 10.3.27
MaxmindDB 1.3.2

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql

System:
Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64

Compiler:
gcc 8.3.0
```

**Comment by DocMAX** [comment]
Just compiled a few versions. The last working version is 1.7.3!

**Comment by DocMAX** [comment]
This piece of software is full of bugs! With 1.7.5:
```
Feb 27 14:45:01 server nfacctd[17768]: DEBUG ( default_mysql/mysql ): FAILED query follows:
                                       UPDATE `acct` SET packets=packets+1, bytes=bytes+54, stamp_updated=NOW() WHERE FROM_UNIXTIME(1614433440) = stamp_inserted AND ip_src='192.168.1.2' AND ip_dst='192.168.1.1' AND src_port=48193 AND dst_port=53 AND ip_proto='udp' AND country_ip_src='O1' AND lat_ip_src='0.000000' AND  AND lon_ip_src='0.000000'
Feb 27 14:45:01 server nfacctd[17768]: ERROR ( default_mysql/mysql ): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND lon_ip_src='0.000000'' at line 1

```

**Comment by paololucente** [comment]
Dear @DocMAX ,

I am sorry to find you in such a bad mood today and if `This piece of software is full of bugs!` was true then, given the extended software user base, yours would not be the only single one bug issue open at this one point in time. This said, let's get to business:

1) With regards to the `Abnormal exit status` issue: that message indicates a crash in the child (the database writer) so it is normal to not find more info in the logs - even at debug level. You could provide me useful information could you please provide me the output of gdb (preferrably) or valgrind? https://github.com/pmacct/pmacct/blob/1.7.6/QUICKSTART#L2864-#L2884 . If this does not apply to more recent versions of code, we can forget about it and leave history behind us.

2) I see that 'AND AND' issue. The latest commit 2ec83acd338b61c8726c5f155295fcf71ae7faba should address it. Please let me know if you get a chance to give it a try.

Paolo

**Comment by DocMAX** [comment]
i allready gave you the gdb output of latest master... what do you mean?

**Comment by paololucente** [comment]
Cool, can you confirm you do not include a `sql_host` directive in the config? If so, situation would be pretty clear and i'd have a fix for this right away.

**Comment by DocMAX** [comment]
My current config working with 1.7.5 is this:
```
daemonize: false
#debug_internal_msg: true
#debug: true
pidfile: /var/run/nfacctd.pid
nfacctd_ip: 0.0.0.0
syslog: daemon
#geoip_ipv4_file: /usr/share/GeoIP/GeoIP.dat
#geoipv2_file: /var/lib/GeoIP/GeoLite2-ASN.mmdb
geoipv2_file: /var/lib/GeoIP/GeoLite2-City.mmdb
#geoipv2_file: /var/lib/GeoIP/GeoLite2-Country.mmdb
aggregate: src_mac, dst_mac, src_host, dst_host, proto, src_port, dst_port, src_host_country, src_host_pocode, src_host_coords, flows
plugins: mysql
sql_table: acct
sql_refresh_time: 60
sql_optimize_clauses: true
sql_history: 1m
sql_history_roundoff: m

```

**Comment by paololucente** [comment]
Cool, so most probably 1922062277d87da024938cc3057df9a4c3725e76 would solve the `Abnormal exit status` issue you were experiencing. So, in short, please give a try to master code and let me know what works and what does not work still.

**Comment by DocMAX** [comment]
didn't help
```
Feb 28 04:00:39 server nfacctd[17967]: INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.7-git (20210226-2 (8fb94f03))                                                                                          
Feb 28 04:10:01 server nfacctd[17968]: WARN ( default_mysql/mysql ): Abnormal exit status detected for child PID 20160
```

**Comment by DocMAX** [comment]
everything is working now. thank you!
