### ISSUE TITLE
Propagate signals to plugin child processes

### ISSUE THREAD

**Issue by toreanderson** [pmacct/pmacct#478]
**Description**

It would be nice if signals sent to the core process are propgagated to the child processes.

In my use case, I am running `sfacctd` in a Podman container (official `docker.io/pmacct/sfacctd` image). I have separate plugins for `in` and `out` traffic, which runs in separate child processes.

I need to periodically update the `networks.lst` file and make `sfacctd` reload it. The intuitive way to do that would be:

```console
$ podman kill --signal 12 sfacctd_container
```

However, that does not work – the `USR2` signal is only sent to the core process (i.e. the container's entrypoint). The child processes never receive the signal, so they do not reload the `networks.lst` file.

As I workaround, I can instead do:

```console
$ podman exec sfacctd_container killall5 12
```

This works, but is a bit ugly, in my opinion.

**Version**

```
sFlow Accounting Daemon, sfacctd 1.7.7-git [20210303-1 (5534d4f5)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.4
libpcap version 1.8.1
MariaDB 10.3.27
PostgreSQL 110010
sqlite3 3.27.2
rabbimq-c 0.11.0-pre
rdkafka 1.6.1
jansson 2.13.1
MaxmindDB 1.5.2
ZeroMQ 4.3.2
Redis 1.0.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.4.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64

Compiler:
gcc 8.3.0
```

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi Tore ( @toreanderson ),

Thanks for reaching out about this. What you say makes sense. Please allow me a little bit of time to reproduce the scenario and resolve the situation. Keep you posted.

Paolo

**Comment by paololucente** [comment]
Hi Tore ( @toreanderson ),

I added a new `propagate_signals` config directive. See 5397a32d64dfb8ace7bf0e60a978c9e13adaf3d4 , 619cfdfef912719a593fe65782f8619ae9a5ad97 and 7e27a8d618164dd306fb5a67b60b7ffc624fa091. Let me know if you get a moment to give it a try and confirm it working for you. I went for a new knob for two reasons: 1) backward compatibility and 2) perhaps even more importantly, retain the flexibility of targeting individual pieces of the daemon (or all of them via a killall) like it is today (perhaps for who does not run containers but VMs or bare metal). 

Paolo

**Comment by toreanderson** [comment]
I am very sorry for the delay in getting back to you. I tried this now, but either I'm doing something wrong, or it doesn't work. My `sfacctd.conf` contains the following:

```
aggregate[in]: dst_as
aggregate[out]: src_as
imt_path[in]: /etc/pmacct/in.pipe
imt_path[out]: /etc/pmacct/out.pipe
networks_file: /etc/pmacct/networks.lst
plugins: memory[in], memory[out]
pre_tag_filter[in]: 1
pre_tag_filter[out]: 2
pre_tag_map: /etc/pmacct/pretag.map
sfacctd_as: longest
sfacctd_net: longest
sfacctd_port: 6344
sfacctd_renormalize: true
propagate_signals: true
```

When running `sfacctd:bleeding-edge` (which identifies itself as `sfacctd 1.7.7-git (20210509-1 (37477553))` on startup) from Docker Hub in Podman, this are the created processes (seen from outside the container):

```
3489650 ?        Ssl    0:00 /usr/bin/conmon --api-version 1 -c 5523240db7f0968803870c1511c0de18e87ebdeeb173951133947d0cb80ff333 -u 
3489668 ?        Ss     0:00  \_ sfacctd: Core Process [default]
3489682 ?        S      0:00      \_ sfacctd: IMT Plugin [in]
3489683 ?        S      0:00      \_ sfacctd: IMT Plugin [out]
```

If I now do `kill -USR2 3489668`, the following is logged to stdout:

```
INFO ( default/core ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/pretag.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/pretag.map] map successfully (re)loaded.
```

No similar messages from the plugins appear. Shouldn't they have?

If I do `kill -USR2 3489682`, a message from the plugin appear as expected:

```
INFO ( in/memory ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
```

Also as expected, after `kill -12 3489683` this is logged:

```
INFO ( out/memory ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
```

**Comment by paololucente** [comment]
Hi Tore ( @toreanderson ),

Apologies for the late answer, this feel in the cracks. I verified you were indeed correct and just committed a corrective patch. Please let me know if you see it working for you.

Paolo

**Comment by toreanderson** [comment]
LGTM! :+1:
