### ISSUE TITLE
dns resolver?

### ISSUE THREAD

**Issue by DocMAX** [pmacct/pmacct#480]
can you add a feature where we have an extra collum of resolved ip's? like ip_src_resolved and ip_dst_resolved?

**Comment by paololucente** [comment]
Hi @DocMAX ,

This topic was approached on the mailing-list some time ago, please see this thread: https://www.mail-archive.com/pmacct-discussion@pmacct.net/msg03270.html .  The key message on that thread is the one from Bill Nash which essentially does justify why this feature is not present (nor on the roadmap) of pmacct. I'd still recommend to perform this kind of lookup down in your data pipeline where things are less time sensitive. 

Paolo
