### ISSUE TITLE
kafka partition polarization

### ISSUE THREAD

**Issue by Slepwin** [pmacct/pmacct#488]
**Description**
Hi Paolo, i've deployed nfacctd with kafka plugin in production environment but faced with partition polarization: some partition overloaded and some underloaded. I've tried to configure:
```
kafka_partition_dynamic[netflow]: true
kafka_partition_key[netflow]: $peer_src_ip
```
But this did not lead to any drastic changes, also i've tried to configure in librdkafka.conf:
`global, partitioner, murmur2_random`
but still no luck.

Maybe you have any recommendations how i can fix it or which nfacctd/librdkafka configuration knob may affect this.
Thank in advance!

**Version**
nfacctd 1.7.6

**Comment by paololucente** [comment]
Hi Alexander ( @Slepwin ),

Did you try, say, `kafka_partition_key[netflow]: $peer_src_ip-$in_iface` so to spread data among partitions basing on their exporter IP address and input interface. Strange though even the random partitioner, ie. `murmur2_random`, did not yield any luck.

Paolo

Paolo
