### ISSUE TITLE
Monitor BGP connection state = establish   - #Help  # Support  #Tip

### ISSUE THREAD

**Issue by toggit** [pmacct/pmacct#497]
Hello guys,

i need help to monitor BGP peers to check that all peers state = establish
i have diffren  private networks with mix of devices  foritgate , arista , hp comware that use private p2p lines with  bgp peers between them.
how can i monitor the peers state? does pmacct can help to do that? or its overkill for my needs?

can you give me tips ? where should i look?

i am using  prometheus + telegraf + grafana for my monitoring system

**Comment by SanderDelden** [comment]
Hi @toggit 

When a BGP peer from PMACCT becomes disconnected PMACCT will log the following entry:
`INFO ( default/core/BGP ): [x.x.x.x] BGP_NOTIFICATION received (6, 3). Shutdown Message: ''`

If you are for instance pushing logs to a Elastic you could create some alerts based on this, however I think you would be best of by monitoring this on the router side. You can monitor this using your setup (Prometheus + Telegraf + Grafana) or for instance use something like Zabbix or Observium to achieve BGP monitoring on your routers using SNMP.

Kind regards,
Sander

**Comment by paololucente** [comment]
Hi @toggit ,

If you are really only interested in peers up/down, as @SanderDelden  said, i'd recommend you towards SNMP. using BGP / BMP streams gives you tons more information than you may be interested into.

Paolo
