### ISSUE TITLE
nfacctd not catching anything, and not creating .csv file?

### ISSUE THREAD

**Issue by Willbound** [pmacct/pmacct#498]
**Description**
it seems like nfacctd is not catching anything on the network, nor it is but not outputting to a specified .csv file

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)
Promiscuous Mode Accounting Daemon, pmacctd 1.7.2-git (20181018-00+c3)

nfacctd config:
`daemonize: false
nfacctd_ip: 127.0.0.1
nfaccttd_port: 5800
!
plugins: print
print_output_file: netflow_data.csv
print_output: csv
print_refresh_time: 30
aggregate: src_host, dst_host, src_port, dst_port, proto, timestamp_start, timestamp_end`

pmacctd config:
`daemonize: false
timestamps_utc: true
timestamps_since_epoch: true
!
plugins: nfprobe
nfprobe_receiver: 127.0.0.1:5800
nfprobe_version: 9
nfprobe_tstamp_usec: true
!
aggregate: src_host, dst_host, src_port, dst_port, proto, timestamp_start, timestamp_end
pcap_interface: enp0s3`

below are screenshots 
![Screenshot from 2021-04-19 21-22-25](https://user-images.githubusercontent.com/51217197/115323749-a7d5d400-a156-11eb-9fd8-6ca03cf821ef.png)
![Screenshot from 2021-04-19 21-22-40](https://user-images.githubusercontent.com/51217197/115323765-ad331e80-a156-11eb-897e-75cffad6da61.png)

**Comment by paololucente** [comment]
Hi @Willbound ,

As the log says the `nfaccttd_port` is not recognized - one 't' too much :) I bet you fix that and all will magically start working.

Paolo

**Comment by Willbound** [comment]
> Hi @Willbound ,
> 
> As the log says the `nfaccttd_port` is not recognized - one 't' too much :) I bet you fix that and all will magically start working.
> 
> Paolo

That worked thank you
The config arguments were given to me by my professor so I just took it as it is without thinking there would be any misspellings
