### ISSUE TITLE
bytes always 0 when exporter uses IPFIX

### ISSUE THREAD

**Issue by hyberdk** [pmacct/pmacct#499]
**Description**
for some reason the bytes field is always 0 when exporting from some of my devices. It seems to be the case with Cisco 9300/9500, ASA firewalls and Cisco 4500X

It works just fine on my ISR/ASR routers.. I think the reason is that the other devices are using Flexible Netflow (IPFIX) and the ISR/ASR are using Netflow v9.. 

I can see in a tcpdump that it uses the octetDeltaCount when its not working.

**Version**

```
flowapp01:/opt/nfacct# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.6-git (20200608-01)

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.9.1 (with TPACKET_V3)
rdkafka 1.2.1
jansson 2.12

System:
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64

Compiler:
gcc 9.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

```

My config looks like this:

```
flowapp01:/opt/nfacct# cat nfacctd.conf
!
!
! AUTOGENERATED FILE @ Wed Mar 31 09:55:51 UTC 2021 - PLEASE EDIT TEMPLATE INSTEAD
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys supported ?
!
! General configs
!
debug: false
daemonize: false
!logfile: nfacct.log

aggregate_primitives: /opt/nfacct/primitives.lst

!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: 3016
! nfacctd_time_secs: true
! nfacctd_time_new: true
!

plugins: kafka
!
aggregate: dscp,direction,appid,proto,src_host,dst_host,src_port,dst_port,in_iface,out_iface,peer_src_ip
kafka_output: json
kafka_topic: netflow-collector
kafka_refresh_time: 60
kafka_history: 1m
kafka_history_roundoff: m
kafka_broker_host: flowapp01
kafka_broker_port: 9092
kafka_cache_entries: 160000
```

**Appreciation**
done ages ago :-)

**Comment by paololucente** [comment]
Hi Esben ( @hyberdk ),

Can you send me by unicast email a sample of the non-working packets (along with their template) so that i can reproduce the issue at my end? octetDeltaCount (IE 1) and layer2OctetDeltaCount (IE 352) are supported (also octetDeltaCount should be what your ISR/ASR is using). Probably is some different <bla>DeltaCount? As there are several defined.

Paolo

**Comment by hyberdk** [comment]
Hi Paolo (@paololucente), 

thanks for the quick reply and "you got mail"..

Let me know if you need additional information, I will be more than happy to supply..

Esben

**Comment by paololucente** [comment]
hi Esben,

Got to look at the pcap, thanks. I see the `bytes` counter just fine, what remains to zero is the `packets` counter - are we looking at the same issue? If so, while your `NETFLOW_MONITOR` instance includes the packet count, your `FLOW_MONITOR_IN` and `FLOW_MONITOR_OUT` do not and that should be the issue (ie. fix template and we should be back in business).

Look forward to your thoughts.

Paolo

**Comment by hyberdk** [comment]
Hi Paolo,

> what remains to zero is the `packets` counter - are we looking at the same issue?

We are not collecting the number of packets, we dont really use that. 

the data looks fine coming into nfacctd

![image](https://user-images.githubusercontent.com/3530739/116195080-02ac9400-a732-11eb-9669-75ede90c0435.png)

question is of course if they are mapped to a different field than "bytes"

Esben

**Comment by paololucente** [comment]
Hi Esben,

Can you give a try to latest master code or apply the one-liner patch in 24b8650df2ef1ba0eb4c48b677a5d7acbf7a62be to 1.7.6 code and see if it works for you? It does for me. Our disconnect was that you were using JSON output (due to the Kafka plugin) and i was testing string-formatted output. 

Paolo

**Comment by hyberdk** [comment]
It seems to work..

```
SELECT
    stamp_updated,
    exporter,
    sum(bytes)
FROM min1_test2
WHERE (stamp_updated >= (now() - 1200)) AND (exporter = IPv4StringToNum('10.9.16.1'))
GROUP BY
    stamp_updated,
    exporter
ORDER BY stamp_updated ASC

Query id: 441d79ee-d15b-4659-996b-2039adb3c289

┌───────stamp_updated─┬─exporter──┬─sum(bytes)─┐
│ 2021-04-29 10:10:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:11:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:12:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:13:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:14:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:15:00 │ 10.9.16.1 │          0 │
│ 2021-04-29 10:17:00 │ 10.9.16.1 │  529973075 │
│ 2021-04-29 10:18:00 │ 10.9.16.1 │  612715881 │
│ 2021-04-29 10:19:00 │ 10.9.16.1 │  662002538 │
│ 2021-04-29 10:20:00 │ 10.9.16.1 │  719098109 │
│ 2021-04-29 10:21:00 │ 10.9.16.1 │  846589152 │
│ 2021-04-29 10:22:00 │ 10.9.16.1 │  550624609 │
│ 2021-04-29 10:23:00 │ 10.9.16.1 │  624934979 │
│ 2021-04-29 10:24:00 │ 10.9.16.1 │  619461803 │
│ 2021-04-29 10:25:00 │ 10.9.16.1 │  582310562 │
│ 2021-04-29 10:26:00 │ 10.9.16.1 │  469310524 │
│ 2021-04-29 10:27:00 │ 10.9.16.1 │  551609192 │
│ 2021-04-29 10:28:00 │ 10.9.16.1 │  619046701 │
│ 2021-04-29 10:29:00 │ 10.9.16.1 │  509397643 │
└─────────────────────┴───────────┴────────────┘

19 rows in set. Elapsed: 0.021 sec. Processed 409.60 thousand rows, 6.55 MB (19.76 million rows/s., 316.22 MB/s.) 

822f67d8ee92 :) 
```

thanks a lot!

Esben
