### ISSUE TITLE
not all IP Protocols are translated to known names.

### ISSUE THREAD

**Issue by hyberdk** [pmacct/pmacct#500]
**Description**
It seems like there are missing a lots of names for the IP Protocols. I assume that its missing from here: https://github.com/pmacct/pmacct/blob/7f4db42a1f7b9768b88387f184694c86c95ab35d/src/pmacct-data.h#L136

Question is can I turn off the "translations" and just get the "raw" numbers via the configuration.. or is the only way to update it from https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml and do a pull request?

Esben

**Comment by paololucente** [comment]
Hi Esben ( @hyberdk ),

From your other issue i understand you are using the `kafka` plugin. Then what you are looking for should be to add `kafka_num_protos: true` to your config.

Paolo

**Comment by hyberdk** [comment]
Hi Paolo (@paololucente),

thanks a lot, I did search the config_keys, but I did not realize that it was bound to the output plugin.

I will test it a little later as I need to build a new container with a new configuration template for my docker containers...

Esben

**Comment by hyberdk** [comment]
Hi Paolo (@paololucente),

I just confirmed that it works as expected.. thanks for the quick help and awesome product!

Esben
