### ISSUE TITLE
configure: error: Could not find libcdada in pmacct 1.7.6

### ISSUE THREAD

**Issue by MUsman1992** [pmacct/pmacct#501]
I am facing this issue #11 19.82 configure: error: Could not find libcdada when i try to run the following command in the Dockerfile

pmacct-1.7.6   && ./autogen.sh   && ./configure --enable-zmq --enable-ndpi --enable-kafka --enable-jansson --enable-ipv6   && make   && make install

The issue occurs with pmacct 1.7.6. Can anyone help me how to solve this. Thanks

I have also attached the image of the logs.
<img width="1280" alt="Screenshot 2021-04-28 at 22 14 09" src="https://user-images.githubusercontent.com/62036653/116466653-10b3ff00-a86f-11eb-9cf7-51ade74f7586.png">

**Comment by msune** [comment]
You are using the tarball, correct? I could reproduce it:

```
root@c38e86aa24a0:/# wget https://github.com/pmacct/pmacct/archive/refs/tags/v1.7.6.tar.gz
...
root@c38e86aa24a0:~# tar xvf v1.7.6.tar.gz 
pmacct-1.7.6/
pmacct-1.7.6/.github/
...
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for a valid C++ compiler... yes
checking for cdada_get_ver in -lcdada... no
configure: error: Could not find libcdada
root@c38e86aa24a0:~/pmacct-1.7.6# 
```

@paololucente seems a problem with the packaging. Let's discuss.

**Comment by msune** [comment]
For completion, I took the tarball from here: https://github.com/pmacct/pmacct/releases/tag/v1.7.6

**Comment by paololucente** [comment]
Thanks Marc ( @msune ) for having looked into this - that tarball definitely has to go away to avoid confusions.

@MUsman1992 please use the official pmacct tarball from the pmacct.net website: http://www.pmacct.net/pmacct-1.7.6.tar.gz . Or one of the officially supported Docker containers at: https://hub.docker.com/u/pmacct

Paolo

**Comment by skinfrakkiirid** [comment]
I have the same error from both GitHub and tarball

**Comment by skinfrakkiirid** [comment]
![image](https://github.com/pmacct/pmacct/assets/120418829/0c7bbf66-e79e-479b-8766-f3b4fb2c3f92)
