### ISSUE TITLE
Reloading maps causes infinite increase in memory usage

### ISSUE THREAD

**Issue by SanderDelden** [pmacct/pmacct#511]
**Description**
I'm using a dynamic pretag map which is reloaded every 5 minutes using `killall -USR2 sfacctd`. When reloading the map it seems that the old map is not destroyed / removed properly as the memory usage is constantly increasing.

When all memory is consumed sfacctd is not able to print anymore nor reload maps and gives the following error messages:
```
WARN ( CUSTOMER/print ): Unable to fork writer: Cannot allocate memory
WARN ( CUSTOMER/print ): Unable to fork writer: Cannot allocate memory
WARN ( CUSTOMER/print ): Unable to fork writer: Cannot allocate memory
WARN ( CUSTOMER/print ): Unable to fork writer: Cannot allocate memory
WARN ( CUSTOMER/print ): Unable to fork writer: Cannot allocate memory
INFO ( default/core ): [/etc/pmacct/mappings/bgp.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/mappings/bgp.map] map successfully (re)loaded.
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] (re)loading map.
ERROR ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] malloc() failed.
```

For reference, a succesfull reload of the map looks as follows:
```
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] (re)loading map.
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] maps_index: creating index 40000000 (9 entries).
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] maps_index: creating index 1000 (2 entries).
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] maps_index: creating index 800000000 (69064 entries).
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] pretag_index_report(): index=40000000 entries=9
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] pretag_index_report(): index=1000 entries=1
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] pretag_index_report(): index=800000000 entries=34532
INFO ( default/core ): [/etc/pmacct/api/output/customer_pretag.map] map successfully (re)loaded.
```

I believe that in the past I would also see log entries pertaining to the destruction (that sounds quite dramatic) of the maps_index, this seems to be missing here.

A screenshot to show the increase of memory usage over time:
![memory](https://user-images.githubusercontent.com/38953576/122759281-0d9b2500-d29a-11eb-9fb2-136ce86eafd2.png)

**Version**
sfacctd 1.7.7-git (20210617-0 (bc145b34))

**Comment by paololucente** [comment]
Hi Sander ( @SanderDelden ),

Thanks very much for reporting this - good that this leak will not make to an actual release. I think i have just addresses the problem, which i was able to reproduce. Can you please give it a try and confirm it working for you?

Paolo

**Comment by SanderDelden** [comment]
Hi Paolo,

I've been testing with this and everything looks good. As always thank you very much for your quick reply and fix, much appreciated!

Kind regards,
Sander
