### ISSUE TITLE
pmacct performance

### ISSUE THREAD

**Issue by maplewf** [pmacct/pmacct#512]
@paololucente,

First of all, I want to address that this is not issue but query, I'm just not sure where to put this question. After searching document in project, I have not seen any information about pmacct performance. For example:

- how much throughput the pmacct can handle? 
- how many flows the pmacct can do the accounting?
- pmacct can reach what kind of capacity with how many resources? 
- etc.

I'm searching solution for data collection in my project, pmacct seems suitable from perspective of functionality, but what i'm concerning is its performance and capacity, is there any performance data for pmacct as reference? BTW, I especially focus on components of pmacctd(libpcap) and uacctd(NFLOG).

thanks

**Comment by paololucente** [comment]
Hi @maplewf ,

Being daemons with an extremely modular feature set, stuff that can be enabled / disabled depending on the use-case, the scalability can vary (think correlation with BGP or performing DPI). So perhaps the only generic answer i may give is: give it a try with your intended feature set and consider that you can perform some hardware or software hashed balancing should you reach some CPU-bound limits ( see https://www.ntop.org/guides/pf_ring/rss.html ) and hence scale horizontally.

I may also add that perhaps within the Gbps you should be fine. Within the 10's of Gbps you should be also fine most probably by scaling horizontally. More than that it may depend on the specific feature set or you may probably want to look at some software that is optimized for the specific use-case.

Paolo

**Comment by maplewf** [comment]
Hi @paololucente,

Thanks for your reply, I'm trying it in my environment to probe its limit. Maybe it will back to you, thanks again.

Best regards
