### ISSUE TITLE
IPv6 sflow not mapping to BGP fields (net_dst, net_mask)

### ISSUE THREAD

**Issue by floatingstatic** [pmacct/pmacct#513]
**Description**
My setup is as follows:

- sfacctd running in docker configured for bgp and a print plugin as a backend (have also verified the same behavior with kafka and pgsql plugins)

- sflow packets sent by arista switches (native sflow implementation). All flows are sent over IPv4 to sfacctd (`192.0.2.1` is the anonymized agent IP and source IP of sflow packets).

- A single external "route collector" running gobgp that gets ADD-PATH routes from multiple arista switches in a point-of-presence (POP). The routers are running bird1.6.x so we have a two distinct ipv4 and ipv6 sessions for each switch. We take the best path routes from all sources and send those to sfacctd simply to do `net_dst` and `mask_dst` aggregations on flows. Without going into great detail there is a reason we are not peering the aristas directly with pmacct in this setup.

- I have confirmed that pmacct is getting a full feed of ipv4 and ipv6 routes from the route collector (src ip `203.0.113.1`[anonymized], router id `172.16.10.100`) by both checking per-address-family route exports from the route collector and configuring a periodic rib dump within sfacctd to a json file.

Crude diagram of the topology:

![image](https://user-images.githubusercontent.com/5504449/125101802-9e4e6f00-e0a8-11eb-94e6-3ad630d0efc0.png)

The problem I am seeing is that all ipv6 flows are being associated to `::/0` even though we have a full rib of ipv6 routes loaded in sfacctd/pmacct.

For example we see this purge message in one of the print plugin dumps:

```
{"event_type": "purge", "peer_ip_src": "192.0.2.1", "iface_out": 1000001, "ip_dst": "2603:6080:2408:9c00:a503:249a:ea28:dcc3", "net_dst": "::", "mask_dst": 0, "sampling_rate": 32768, "stamp_inserted": "2021-07-09 14:30:00", "stamp_updated": "2021-07-09 14:31:01", "packets": 2, "bytes": 1616}
```

This should resolve to `2603:6080::/28` which I see in a rib dump from sfacctd:

```
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 2, "safi": 1, "ip_prefix": "2603:6080::/28", "bgp_nexthop": "2001:2000:3080:1fb6::1", "as_path": "1299 7843 11426", "comms": "1299:35000", "ecomms": "SoO:2:3 SoO:3:1 ?", "origin": "i", "local_pref": 50, "med": 99}
```

Oddly IPv4 routes are being correctly associated to prefixes in the rib, for example:

```
{"event_type": "purge", "peer_ip_src": "192.0.2.1", "iface_out": 1000003, "ip_dst": "72.74.62.184", "net_dst": "72.74.0.0", "mask_dst": 16, "sampling_rate": 32768, "stamp_inserted": "2021-07-09 14:30:00", "stamp_updated": "2021-07-09 14:31:01", "packets": 3, "bytes": 4374}
```

ALL IPv6 flows are being mapped to `::/0`.

I suspect this has something to do with my `bgp_agent_map` configuration but I cannot seem to figure out why it may not be working as intended or if this is some kind of bug. Perhaps I am simply misunderstanding how the agent mappings are intended to work with a multiprotocol peer.

The relevant config files are below:

/etc/pmacct/sfacctd.conf

```
!
daemonize: false
sfacctd_port: 6343
sfacctd_net: bgp
sfacctd_as: bgp
!
print_cache_entries: 65536
!
plugin_pipe_size: 10240000
plugin_buffer_size: 10240
!
bgp_daemon: true
bgp_daemon_max_peers: 4
bgp_daemon_as: 65534
bgp_agent_map: /etc/pmacct/bgp.map
!
bgp_table_dump_file: /tmp/bgp-%s.json
bgp_table_dump_output: json
bgp_table_dump_refresh_time: 300
!
plugins: print[debugging]
aggregate[debugging]: peer_src_ip, dst_host, dst_net, dst_mask, out_iface, sampling_rate
!
print_output_file[debugging]: /tmp/sfacctd-%s.json
print_output[debugging]: json
print_history[debugging]: 1m
print_history_roundoff[debugging]: m
print_refresh_time[debugging]: 60
!
```

/etc/pmacct/bgp.map

```
bgp_ip=172.16.10.100 ip=0.0.0.0/0
```

On the `bgp_agent_map` the idea is that the route collector will be the source of all BGP routing information for all sflow agents. We just want to use it to get an up-to-date list of prefixes for a pop and aggregate on the destination prefix (`dst_net` and `dst_mask`), however you will note for debugging I added `dst_host` so i could validate we actually have a route that the destination IP resolves to in our bgp rib. I suspect perhaps I may be misunderstanding something about the way the bgp_agent_map file works. Any help or pointers are appreciated.

**Version**
```
# sfacctd -V
sFlow Accounting Daemon, sfacctd 1.7.6-git [20201226-0 (7ad9d1b)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.2
libpcap version 1.8.1
MariaDB 10.3.27
PostgreSQL 110010
sqlite3 3.27.2
rabbimq-c 0.11.0-pre
rdkafka 1.6.1
jansson 2.13.1
MaxmindDB 1.5.2
ZeroMQ 4.3.2
Redis 1.0.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.2.0
netfilter_log

System:
Linux 4.4.0-211-generic #243-Ubuntu SMP Thu Apr 29 09:14:13 UTC 2021 x86_64

Compiler:
gcc 8.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

**Appreciation**
Thank you again Paolo for this amazing open source project! If I could star this project multiple times I would!

**Comment by floatingstatic** [comment]
One more bit of info since it may be related:

```
sfacctd_1   | INFO ( default/core/BGP ): [203.0.113.1] BGP peers usage: 1/4
sfacctd_1   | INFO ( default/core/BGP ): [172.16.10.100] Capability: MultiProtocol [1] AFI [1] SAFI [1]
sfacctd_1   | INFO ( default/core/BGP ): [172.16.10.100] Capability: MultiProtocol [1] AFI [2] SAFI [1]
sfacctd_1   | INFO ( default/core/BGP ): [172.16.10.100] Capability: 4-bytes AS [41] ASN [65534]
sfacctd_1   | INFO ( default/core/BGP ): [172.16.10.100] BGP_OPEN: Local AS: 65534 Remote AS: 65534 HoldTime: 90
```

sfacctd shows the initial connection from the source IPv4 of the route collector BGP session (203.0.113.1) but then starts logging everything as coming from 172.16.10.100 (router id), which is why I am using 172.16.10.100 in the agent map. For what it is worth I have tried swapping 203.0.113.1 as the IP we use in the agent map and the behavior does not seem to change.

**Comment by paololucente** [comment]
Hi Jeremiah ( @floatingstatic ),

The fact `sfacctd_net` and `sfacctd_as` are set to `bgp` and resolving IPv4 addresses works, makes me wonder whether it is possible for some reason that IPv6 routes are not making it to pmacct (despite i see that the MP capability is being exchanged fine). Can you temporarily enable logging of BGP messages for example to a file, to keep it simple ie. `bgp_daemon_msglog_file`, and check you are receiving the IPv6 routes just fine?

Paolo

**Comment by floatingstatic** [comment]
Hi Paolo, I hope you are well. Thank you very much for your reply.

I can collect some data with `bgp_daemon_msglog_file`, however I am reasonably confident that the IPv6 routes are in the rib within the bgp process in sfacctd due to using `bgp_table_dump_file` to get a dump of the rib data every 5 minutes and inspecting the output. When I looked at a bgp table / rib dump in json format at the same timestamp as print flush I see the the IPv6 route I expected my example flow above to resolve to. I apologize if this was not clear from my long block of text above, but I believe this confirms that IPv6 routes are in the rib. Specifically:

```
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 2, "safi": 1, "ip_prefix": "2603:6080::/28", "bgp_nexthop": "2001:2000:3080:1fb6::1", "as_path": "1299 7843 11426", "comms": "1299:35000", "ecomms": "SoO:2:3 SoO:3:1 ?", "origin": "i", "local_pref": 50, "med": 99}
```

Some brief data from the dump showing IPv4 and IPv6 routes from the same `peer_ip_src` (I only have this sfacctd instance peered to just the one route collector so every route in the file has the same `peer_ip_src` and `peer_tcp_port` for both IPv4 and IPv6 prefixes (of course the `afi` is not the same). 

IPv4:

```
$ head -3 bgp-1625838000.json
{"timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump_init", "dump_period": 300, "seq": 0}
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 1, "safi": 1, "ip_prefix": "0.0.0.0/0", "bgp_nexthop": "62.115.187.56", "as_path": "", "origin": "i", "local_pref": 50}
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 1, "safi": 1, "ip_prefix": "1.0.0.0/24", "bgp_nexthop": "206.108.236.61", "as_path": "13335", "comms": "13335:10106 13335:19000 13335:20050 13335:20500 13335:20530", "ecomms": "SoO:2:2 SoO:3:1 ?", "origin": "i", "local_pref": 55, "med": 95}
```

IPv6:

```
$ grep :: bgp-1625838000.json | head -3
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 2, "safi": 1, "ip_prefix": "::/0", "bgp_nexthop": "2001:2000:3080:1fb6::1", "as_path": "", "origin": "i", "local_pref": 50}
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 2, "safi": 1, "ip_prefix": "2001::/32", "bgp_nexthop": "2001:504:47::1b1b:0:1", "as_path": "6939", "ecomms": "SoO:2:2 SoO:3:1 ?", "origin": "i", "local_pref": 55, "med": 110}
{"seq": 0, "timestamp": "2021-07-09 13:40:00", "peer_ip_src": "203.0.113.1", "peer_tcp_port": 48381, "event_type": "dump", "afi": 2, "safi": 1, "ip_prefix": "2001:4:112::/48", "bgp_nexthop": "2001:504:47::1b1b:0:1", "as_path": "6939 112", "ecomms": "SoO:2:2 SoO:3:1 ?", "origin": "i", "local_pref": 55, "med": 110}
```


If I count the IPv6 routes in the table dump it aligns with what I see exported from my route collector which leads me to believe that I have a full set of IPv6 routes to work with within sfacctd.. 

Is there anything else you can think of that may be causing the mapping to not take place? For what it is worth I tried a couple of additional things  but none of them yielded a positive result:

- used the neighbor IP of the route collector instead of the router ID in the bgp agent map
- tried setting `bgp_disable_router_id_check` to true 

Looking at `bgp_lookup.c` wonder if `tmp_bgp_lookup_compare_ports` might help, but it is not clear to me that it will. Any suggestions are greatly appreciated.

**Comment by floatingstatic** [comment]
I have isolated the problem further. It turns out that I am in fact getting some IPv6 flows aggregated to prefixes via bgp:

```
{"event_type": "purge", "peer_ip_src": "203.0.113.1", "iface_out": 45001, "ip_dst": "2620:12a:8001::2", "net_dst": "2620:12a:8000::", "mask_dst": 44, "sampling_rate": 32768, "stamp_inserted": "2021-07-12 13:29:00", "stamp_updated": "2021-07-12 13:30:01", "packets": 1, "bytes": 109}
{"event_type": "purge", "peer_ip_src": "203.0.113.1", "iface_out": 17002, "ip_dst": "2620:12a:8000::2", "net_dst": "2620:12a:8000::", "mask_dst": 44, "sampling_rate": 32768, "stamp_inserted": "2021-07-12 13:29:00", "stamp_updated": "2021-07-12 13:30:01", "packets": 1, "bytes": 90}
```

The above flows "ingress" flows (the output interface is facing a server in one of our pops). On the opposite direction (flow from a server to something external) we do not see the BGP prefix aggregation and I think I have one small detail that may point to why. We use MPLS on egress so the ethertype is 0x8847. Oddly for IPv4 egress flows this works fine, but not for IPv6.


Some sample sflow packets follow if they may be of any use in debugging further.

IPv6:
![image](https://user-images.githubusercontent.com/5504449/125331905-9dbb1000-e316-11eb-97df-76adc3ff71d0.png)


IPv4:
![image](https://user-images.githubusercontent.com/5504449/125332003-b4616700-e316-11eb-9c23-567fa0d281d7.png)

**Comment by paololucente** [comment]
Hi Jeremiah,

Interesting development indeed, thanks for the extra details. Could you provide me by unicast email a sFlow sample containing some of this VLAN-tagged, MPLS-labelled IPv6 traffic? I'd like to replay it through sfacctd to see whether it ever hits the BGP lookup code or not (i suspect it does not because that is just a standard operation for any kind of v4 or v6 traffic).

Would that not be possible (i mean, to share a brief capture), this may be the part of code to have a look at and, as i was saying, i would really start from checking whether the bgp_srcdst_lookup() is invoked:

https://github.com/pmacct/pmacct/blob/master/src/sfacctd.c#L2013-#L2061 

Paolo

**Comment by floatingstatic** [comment]
Hi Paolo, yes I have a pcap I will have to clean up (it is rather large) and send you later today.

Thanks for pointing me at that block of code. I downloaded the latest code from the master branch and added some debug log lines:

```
--- a/src/sfacctd.c
+++ b/src/sfacctd.c
@@ -2053,7 +2053,10 @@ void finalizeSample(SFSample *sample, struct packet_ptrs_vector *pptrsv, struct
       if (config.nfacctd_isis) isis_srcdst_lookup(&pptrsv->vlanmpls6);
       if (config.bgp_daemon_to_xflow_agent_map) BTA_find_id((struct id_table *)pptrs->bta_table, &pptrsv->vlanmpls6, &pptrsv->vlanmpls6.bta, &pptrsv->vlanmpls6.bta2);
       if (config.nfacctd_flow_to_rd_map) SF_find_id((struct id_table *)pptrs->bitr_table, &pptrsv->vlanmpls6, &pptrsv->vlanmpls6.bitr, NULL);
-      if (config.bgp_daemon) bgp_srcdst_lookup(&pptrsv->vlanmpls6, FUNC_TYPE_BGP);
+      if (config.bgp_daemon) {
+          Log(LOG_INFO, "INFO (TESTING): *** calling bgp_srcdst_lookup() for ipv6 mpls flow***\n");
+          bgp_srcdst_lookup(&pptrsv->vlanmpls6, FUNC_TYPE_BGP);
+      }
       if (config.bgp_daemon_peer_as_src_map) SF_find_id((struct id_table *)pptrs->bpas_table, &pptrsv->vlanmpls6, &pptrsv->vlanmpls6.bpas, NULL);
       if (config.bgp_daemon_src_local_pref_map) SF_find_id((struct id_table *)pptrs->blp_table, &pptrsv->vlanmpls6, &pptrsv->vlanmpls6.blp, NULL);
       if (config.bgp_daemon_src_med_map) SF_find_id((struct id_table *)pptrs->bmed_table, &pptrsv->vlanmpls6, &pptrsv->vlanmpls6.bmed, NULL);
```

It seems as though that section of code is being called based on log entries. 

```
sfacctd_1   | INFO (TESTING): *** calling bgp_srcdst_lookup() for ipv6 mpls flow***
sfacctd_1   | INFO (TESTING): *** calling bgp_srcdst_lookup() for ipv6 mpls flow***
sfacctd_1   | INFO (TESTING): *** calling bgp_srcdst_lookup() for ipv6 mpls flow***
```


I will see if I can isolate it further using my caveman "just add log entries" approach. I appreciate your input and support as always.

**Comment by floatingstatic** [comment]
Confirmed that https://github.com/pmacct/pmacct/commit/144ec82bda0784aaf35ed70832d7c0f9fe545c45 fixes this issue! Thank you @paololucente for your excellent support and generosity with your time to look into this issue with me!
