### ISSUE TITLE
How does stitching work?

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#516]
Could you explain in detail how stitching works (or should work) in sfacctd and nfacctd, particularly with long-lasting flows? 

I have a config for sfacctd that includes
```
    aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface, sampling_rate, label
    sfacctd_stitching: true
    amqp_refresh_time: 300
```
I thought that this would combine all flows with the same src_host, dst_host, etc. that arrive within each 300 sec period, dump that information to my rabbitmq queue, then start over resetting timestamp_min and the number of bytes. However, I am seeing some flows with durations over 300 sec. 

What would be the behavior without a refresh_time?  Would it keep aggregating flows in memory until some timeout? What timeout?

Thanks!

I am using sfacctd 1.7.6-git

**Comment by paololucente** [comment]
Hi Lisa ( @lisaens ),

Thanks for getting in touch about this. Let me start from the easiest part: if no amqp_refresh_time is set, as per docs, a default one is imposed and that is 60 secs. 

The way in which stitching should behave is precisely as you described. Especially in the case of flows exported via NetFlow, where a degree of caching happens before export, i may see how duration may go over 300 secs, ie. a long-lasting flow coming in late (hence making the timestamp_min way in the past) and a short-lasting flow coming in right at the end of the 300 secs interval between flushes to RabbitMQ (and for this specific case there is nfacctd_pro_rating); this should not be the case for sFlow though: if you could send me some data to review, even via unicast email, i'd be happy to have a look at it in case we are hitting a bug or so. Just as matter of test, can you set `sfacctd_time_new: true` and see if that makes any difference?

Paolo

**Comment by lisaens** [comment]
Hi,
Thanks for the information.
As a followup, say I have sflow, no amqp_refresh_time and sfacctd_stitching:false. What should happen if I include timestamp_arrival in the aggregation list vs if I do not? 
Timestamp_arrival is the only timestamp field available for sflow, correct? 

I'll try another test to see if I see the overly-long duration flows again. It might take some time for me to get together the info to send.  What kind of data do you need? A tcpdump? Just output from sfacctd written to a file?  I also have output from nfdump (sfcapd) for comparison.   (Is unicast email different than regular email?!)

**Comment by paololucente** [comment]
`aggregate` defines the aggregation key. Including `timestamp_arrival` in the `aggregate` config directive would originate a significant data de-aggregation since the time of arrival would be part of the key. Maybe this is what you are looking for.

If, instead, you are looking for a more aggregated view, you can turn on historical accounting, ie.

```
amqp_history: 5m
amqp_history_offset: m
```

The net effect is that pmacct will populate a stamp_inserted field as part of the aggregation key and it will be valued with the time at the basis of the current time-bin; time-bin being 5 minutes in the example above, ie. 10:00, 10:05, 10:10, 10:15, etc. Let's say that you align `amqp_refresh_time` to the duration of the time bin, for such duration, bytes and packets counters of the aggregates will be summed.

Paolo

**Comment by lisaens** [comment]
I'd like to reopen this issue finally.
I've run a new test with incoming **sflow** data, writing to files, with 
	print_refresh_time: 60
        aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface, sampling_rate, label
        sfacctd_stitching: true
        timestamps_since_epoch: true
        timestamps_secs: false

I ran for a several minutes and got a file each minute, as expected.
In the first one, the max. duration is 44 sec (I didn't start exactly on on the minute).
In the 2nd file, the max. duration is 44+60 = 104 sec.
In the 3rd file, the max. duration is 104+60 = 164 sec.
In each file, I see flows are ending at the time given by the file name, as expected, but timestamp_min is always the same as timestamp_min in the first file (for example flows that are in all of the files examined). I was expecting timestamp_min to be at most 1 minute less than timestamp_max.

I've not confirmed whether the number of packets and bytes reported is cumulative or not; I think not. 

This is reminiscent of how netflow works at the router, with "updates" being sent out every n seconds. Is this the intended behavior?   
Will it work the same if I send the data to a rabbit queue rather than print to a file? I assume so.

Also, is there a way to get more precision in timestamp_min and timestamp_max? They are always rounded or truncated to the nearest second.
