### ISSUE TITLE
Does bmp collector daemon refreshing whole bgp route table information from network device every interval

### ISSUE THREAD

**Issue by tongorz** [pmacct/pmacct#523]
Does bmp collector daemon refreshing whole bgp route table information from network device every interval?
Or the bmp dump data is just an aggregation of the bmp real time log?
It would be nice if there is some description on how bmp collector daemon generate bmp dump messages.
Thanks.

**Comment by paololucente** [comment]
Hi @tongorz ,

You have both options: message log, ie. bmp_daemon_msglog_* config directives, is for real-time logging of BGP messages via BMP; dumps, ie. bmp_dump_* config directives, are for full BGP route table dump at regular (configurable) time intervals. The two are not mutually exclusive and are strictly sequenced meaning: you can use the dumps as check-points and consider only the real-time logs after the most recent dump.

Paolo

**Comment by tongorz** [comment]
> Hi @tongorz ,
> 
> You have both options: message log, ie. bmp_daemon_msglog_* config directives, is for real-time logging of BGP messages via BMP; dumps, ie. bmp_dump_* config directives, are for full BGP route table dump at regular (configurable) time intervals. The two are not mutually exclusive and are strictly sequenced meaning: you can use the dumps as check-points and consider only the real-time logs after the most recent dump.
> 
> Paolo

I get It. Thanks. The issue can be closed.
