### ISSUE TITLE
pmbmpd dynamic partition_key seems not work 

### ISSUE THREAD

**Issue by tongorz** [pmacct/pmacct#524]
**Description**
pmbmpd dynamic partition_key seems not work.
The partition_key of the raw message consumed from kafka is b'$bmp_router', which should be ip address of the router.

Configuration is shown as follow:
> bmp_daemon_ip: 0.0.0.0
bmp_daemon_port:` 1790
bmp_daemon_max_peers: 1000
!
bmp_daemon_msglog_kafka_broker_host:  *******
bmp_daemon_msglog_kafka_topic: net-bmp
bmp_daemon_msglog_kafka_partition_key: $bmp_router
!
bmp_dump_refresh_time: 60
bmp_dump_kafka_broker_host: *******
bmp_dump_kafka_topic: net-bmp
bmp_dump_kafka_partition_key: $bmp_router

The raw message from kafka is like this:
> net-bmp:0:565110461: key=b'$bmp_router' value=b'{"seq": 6199963, "timestamp": "2021-08-12 10:38:00", "is_post": 0, "is_in": 1, "peer_ip": "######", "peer_tcp_port": 0, "event_type": "dump", "afi": 1, "safi": 1, "ip_prefix": "######", "bgp_nexthop": "######", "as_path": "######", "origin": "u", "local_pref": 0, "bmp_router": "######", "bmp_router_port": 26821, "bmp_msg_type": "route_monitor", "writer_id": "default/1818"}' timestamp_ms=1628735881992

Version:
> pmacct BMP Collector Daemon, pmbmpd 1.7.6-git [RELEASE]
Arguments:
 '--sysconfdir=/etc' '--enable-bmp-bins' '--enable-jansson' '--enable-kafka' '--disable-bgp-bins' '--disable-st-bins' '--enable-l2' '--enable-traffic-bins'
Libs:
cdada 0.3.2
libpcap version 1.5.3
rdkafka 0.11.4
jansson 2.10
System:
Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64
Compiler:
gcc 4.8.5

**Comment by paololucente** [comment]
Hi @tongorz ,

Well spotted, see https://github.com/pmacct/pmacct/issues/378 . TL;DR: it's now all honored and working in master code which is imminently going in freeze for 1.7.7 release.

Paolo
