### ISSUE TITLE
timestamp_end all is 0 and aggregate failed

### ISSUE THREAD

**Issue by forever765** [pmacct/pmacct#526]
**Description**
I'm using pmacctd docker image and docker host mode to collect NIC data.

**Version**
Docker version 20.10.7, build f0df350.

NetFlow Accounting Daemon, nfacctd 1.7.6-git [20201226-0 (7ad9d1b)]
Arguments:  '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.2
libpcap version 1.8.1
MariaDB 10.3.27
PostgreSQL 110010
sqlite3 3.27.2
rabbimq-c 0.11.0-pre
rdkafka 1.6.1
jansson 2.13.1
MaxmindDB 1.5.2
ZeroMQ 4.3.2
Redis 1.0.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.2.0
netfilter_log

System:
Linux 5.4.132 #0 SMP Sat Aug 7 07:56:57 2021 x86_64

Compiler:
gcc 8.3.0

**pmacctd.conf**
plugins: print
print_refresh_time: 30
print_output_file: /var/log/pmacctd/flow.csv
print_output: csv
interface: br-lan
snaplen: 750
aggregate: class, src_host, dst_host, src_port, dst_port, proto, flows, timestamp_start, timestamp_end
pidfile: /var/run/pmacctd.pid
logfile : /var/log/pmacctd/pmacctd.log
daemonize: false
debug: false

**output result**
CLASS,SRC_IP,DST_IP,SRC_PORT,DST_PORT,PROTOCOL,TIMESTAMP_START,TIMESTAMP_END,PACKETS,FLOWS,BYTES
Unknown/RDP,192.168.123.88,192.168.123.212,65057,3389,udp,2021-09-03 18:53:30.726113,0000-00-00 00:00:00.000000,1,0,103
Unknown/RDP,192.168.123.88,192.168.123.212,65057,3389,udp,2021-09-03 18:53:30.726140,0000-00-00 00:00:00.000000,1,0,103
Unknown/RDP,192.168.123.88,192.168.123.212,65057,3389,udp,2021-09-03 18:53:30.726150,0000-00-00 00:00:00.000000,1,0,109
Unknown/RDP,192.168.123.88,192.168.123.212,65057,3389,udp,2021-09-03 18:53:30.726158,0000-00-00 00:00:00.000000,1,0,109
Unknown/RDP,192.168.123.212,192.168.123.88,3389,65057,udp,2021-09-03 18:53:30.726434,0000-00-00 00:00:00.000000,1,0,40
Unknown/Unknown,192.168.123.1,192.168.123.44,8080,55776,tcp,2021-09-03 18:53:30.797104,0000-00-00 00:00:00.000000,1,1,52
Unknown/Unknown,192.168.123.44,192.168.123.1,55776,8080,tcp,2021-09-03 18:53:30.797287,0000-00-00 00:00:00.000000,1,1,52
Unknown/RDP,192.168.123.212,192.168.123.88,3389,65057,udp,2021-09-03 18:53:30.854673,0000-00-00 00:00:00.000000,1,0,219
Unknown/RTP,144.213.5.4,192.168.123.110,10167,10038,udp,2021-09-03 18:53:30.855870,0000-00-00 00:00:00.000000,1,0,48

**question**
1. why is the TIMESTAMP_END field all displayed as 0? 
2. I hope that flows can be aggregated through src_host and dst_host. I tried to use pmacctd config: [aggregate: class, src_host, dst_host, src_port, dst_port, proto] , it works but no timestamp. But when I add the [timestamp_start] field, It will not be able to aggregate. I guess it’s because the last 6 digits of the timestamp are inconsistent, right? So what fields should I add to achieve the goal?

**Comment by paololucente** [comment]
Hi @forever765 ,

Answering to your second question, you want to enable historical accounting and not use timestamp_start, timestamp_end: precisely as you hinted, instead of aggregating those fields would generate some massive de-aggregation. You can review how to enable historical accounting here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2567-#L2588 , specifically the `print_history` line. I'd recommend to keep in sync `print_refresh_time` and `print_history` values. 

Paolo

**Comment by forever765** [comment]
Hi @paololucente ,
Thank you for your reply. According to your advice, I changed the config file, now pmacctd will generate a csv every 15s and aggregation function is working. But I hope output of pmacctd is as close to real-time as possible. Can I only shorten the [print_output] and [print_history] option?

The pmacctd.conf is as follows:
```plugins: print
print_refresh_time: 15
print_output: csv
print_output_file: /var/log/pmacctd/file-%Y%m%d-%H%M%S.csv
print_history: 15s
# print_history_roundoff: m
interface: br-lan
snaplen: 750
aggregate: class, src_host, dst_host, src_port, dst_port, proto
pidfile: /var/run/pmacctd.pid
logfile : /var/log/pmacctd/pmacctd.log
daemonize: false
debug: true```

**Comment by paololucente** [comment]
Hi @forever765 ,

The more real time you can go is 1 second - is that OK? If so i can recommend an alternative approach:

```
print_refresh_time: 1 
timestamps_secs: true
aggregate: class, src_host, dst_host, src_port, dst_port, proto, timestamp_start
```

Refresh time is set to one second, that will cause pmacct to dump data every 1 second. With `timestamps_secs: true` we cut timestamps to the second level, trashing any more specific granularity. Finally we bring back `timestamp_start` in the picture as time reference. Any samples arriving within that 1 second of the same `class, src_host, dst_host, src_port, dst_port` will be aggregated together. 

Paolo

**Comment by forever765** [comment]
Hi @paololucente ,
Thank you for your suggestion. It works, but this will cause the records to be very scattered and not easy to observe. Finally I set the [print_refresh_time] to 10 seconds and it works well.
