### ISSUE TITLE
CISCO NEL ASR1000 WITHOUT DATA FROM post_nat_port_src and port_src

### ISSUE THREAD

**Issue by marcosvinicius1221** [pmacct/pmacct#527]
**Descreption**
@paololucente I'm trying to get NEL data from ASR 1002-X, but post_nat_port_src and port_src data are not included in the output file the configuration of the pmacct I'm using is pretty simple, but I think something's missing, and that's something I'm not finding

Here's a configuration I'm using.

**configuration file**
pre_tag_map: /opt/netflow/conf/pretag.map
!
plugins: print[traffic], print[nat]
!
pre_tag_filter[traffic]: 10
aggregate[traffic]: src_host, dst_host, peer_src_ip, peer_dst_ip, in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, src_mask, dst_mask, src_as, dst_as, tcpflags
print_output_file[traffic]: /tmp/traffic-%Y%m%d_%H%M.txt
print_output[traffic]: csv
print_history[traffic]: 5m 
print_history_roundoff[traffic]: m 
print_refresh_time[traffic]: 300
print_output_file_append[traffic]: true
!
pre_tag_filter[nat]: 20
aggregate[nat]: src_host, post_nat_src_host, src_port, post_nat_src_port, proto, nat_event, timestamp_start 
print_output_file[nat]: /tmp/cgn-%Y%m%d_%H%M.txt
print_output[nat]: json
print_history[nat]: 5m 
print_history_roundoff[nat]: m 
print_refresh_time[nat]: 300
print_output_file_append[nat]: true

**pretag**
set_tag=10 sample_type=flow
set_tag=20 sample_type=event
set_tag=20 is_bi_flow=true

**Data output in jSON file**
{"event_type": "purge", "ip_src": "100.66.6.66", "port_src": 0, "ip_proto": "icmp", "post_nat_ip_src": "xxx.xxx.xxx.xxx", "post_nat_port_src": 0, "nat_event": 1, "timestamp_start": "2021-09-08 13:44:59.835000", "stamp_inserted": "2021-09-08 13:40:00", "stamp_updated": "2021-09-08 13:45:01"}

**##**

Can you tell me if there is something missing from the configuration file?

Thank you very much in advance

**Comment by paololucente** [comment]
Hi @marcosvinicius1221 ,

For the actual case of ICMP traffic, like in your `Data output in jSON file`, it is fine that ports are zero. Do you have some example with TCP or UDP traffic with the same behaviour? If so, could you check (ie. with Wireshark) if the original NEL traffic from the router does include (and populate) such information? 

Paolo
