### ISSUE TITLE
Port Mirroring Challenge

### ISSUE THREAD

**Issue by jmilleriec** [pmacct/pmacct#532]
**Description**
I've been trying to stand up pmacct as an alternative to ntopng, i'd like more control over the data for monitoring purposes.  I'm using a port miror and Ntopng seems to capture accurate flows and bandwidth usage, but i'd much rather have more control, so I turned to pmacct.  I've tried dozens of different settings and configurations, different refreshes, kafka_history settings.

I've seen a couple of references to port mirrors in the settings, and i've tried to make those adjustments in my config, but it doesn't seem to change anything.

I can't seem to get pmacct to report the bytes correctly, they are substantially lower than what ntopng and the router/switch are reporting as far as bytes.  The ip addresses, mac's and vlan's all show up in the data, but the bytes are substantially lower.  I've been scanning the internet for what i might be doing wrong and i'm at my wits end.

I don't know if this is the right place to put this, but i don't know where else to turn, the software seems perfect for what i 'm looking to build but i can't get the bytes to report correctly.  Feel free to delete this if this is inappropriate, but I'd love to figure out a solution if anyone can help.  Port mirror is on eth1.  

Any help is appreciated...

!
plugins: kafka
!
promisc: true
kafka_output: json
timestamps_secs: true
kafka_topic: SWKNet30
kafka_refresh_time: 60
kafka_broker_host: 192.168.1.79
kafka_history: 1m
kafka_history_roundoff: m
pcap_interface: eth1
sampling_rate: 1
nfacctd_pro_rating: true
#aggregate: src_host,vlan,src_mac,dst_host,dst_mac,timestamp_start
aggregate: src_host,vlan,src_mac,dst_host,dst_mac

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.6-git [RELEASE]

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.2
libpcap version 1.8.1
rdkafka 0.11.6
jansson 2.12

System:
Linux 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l

Compiler:
gcc 8.3.0

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi Jim ( @jmilleriec ),

One clarification, since you mention port mirroring but then show the output of `nfacctd -V` and i see in your config a mix of libpcap settings and NetFlow settings: are you simply mirroring live traffic off of a switch port and want to collect it with libpcap (like you would do with tcpdump / wireshark) or you are rather intending to collect a NetFlow feed?

I am assuming you are in the former case but please confirm. If correct, can you also confirm how much traffic in Mbps / Gbps more or less are you throwing at the daemon?

Paolo

**Comment by jmilleriec** [comment]
Hi Paolo, thank you so much for responding.  I included the nfacctd version as that's what the issue template recommended including, i'm using pmacctd like this with the above config file: sudo pmacctd -f ./pmak1.conf

I was also experimenting with sending the output to goflow through the nfprobe plugin, but that really wasn't doing too much for me.  If the pro_rating setting is causing issues i can certainly take that out.

My use case is that i'd like to actively monitor bandwidth usage over time, the most were looking at right now is between 150-250 MBps.

Yes, mirroring live traffic from a switch port that is mirroring the uplink to the gateway serving the building.

We're more interested right now in bandwidth monitoring (i think most refer to that as "accounting" information), than in monitoring live flows, but that will be useful in the future as well.  

I've learned an enormous amount in the last few weeks, so I hope I'm not bothering you with these questions, I love your software, its exactly what i need if i can get it to report bytes accurately.  We provide internet service to apartment buildings, so i need something that will allow us to integrate into a broader management infrastructure, and the kafka plugin is perfect for that.

Thanks,
Jim

**Comment by paololucente** [comment]
Hi Jim,

All clear.

You can safely remove `nfacctd_pro_rating` and `sampling_rate` from the config. Can you check with a few `ps axuw | grep pmacctd` whether any of the processes go to 100% CPU? Also if you do a few times a `killall -INT pmacctd`, you should get a few statistics on stdout; can you check that `dropped_packets` remains to zero?

Should dropped_packets increase, i recommend to switch from classic libpcap to PF_RING-enabled libpcap; it would transparently present itself as a normal libpcap to pmacct so no changes are involved. If you install it in a non-default location, you can use the knobs described here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L234

Another tip, this more generic, is to switch from homegrown internal buffering to ZeroMQ. You can read more about it here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1172-#L1230

Paolo

**Comment by jmilleriec** [comment]
Thanks Paolo, I think I've done most of what you've suggested.  Removed those items from the config.  And to be clear, I'm not using this on a live building network, just prototyping at home, several different vlan's with streaming TV's on each vlan, so i should see anywhere from 2-5Mbps Bytes Rcvd steady on each VLAN.  I don't get even close to that.  

I'm not dropping packets so I didn't try the PF_RRING.  I'm assuming ZeroMQ is for larger scale deployments, but this is just a prototype.

Its strange, everything appears to be working correctly, but the bytes that show up in Kafka just don't make sense.

Here's the pmacctd startup:
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git (RELEASE)
INFO ( default/core ):  '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/home/pi/pma/scripts/pmak1.conf'.
INFO ( default/core ): [eth1,0] link type is: 1
INFO ( default_kafka/kafka ): cache entries=16411 base cache memory=46213376 bytes
INFO ( default_kafka/kafka ): JSON: setting object handlers.


Result of killall:
INFO ( default/core ): OK, Exiting ...
NOTICE ( default/core ): +++
NOTICE ( default/core ): [eth1,0] received_packets=432216 dropped_packets=0
NOTICE ( default/core ): ---

I can't recall ever seeing any dropped packets when stopping the pmacctd.

Result of grep pmacctd:
pi@raspberrypi:~ $ ps axuw | grep pmacctd
root     15979  0.0  0.0   9948  3312 pts/0    S+   20:16   0:00 sudo pmacctd -f ./pmak1.conf
root     15980  0.4  0.2  16576 11220 pts/0    S+   20:16   0:02 pmacctd: Core Process [default]
root     15989  0.3  1.3  61716 54172 pts/0    S+   20:16   0:02 pmacctd: Kafka Plugin [default_kafka]
pi       23148  0.0  0.0   7348   556 pts/1    R+   20:27   0:00 grep --color=auto pmacctd

Not really sure what I'm missing.

Jim

**Comment by paololucente** [comment]
Hi Jim,

So, to be clear. In this very identical setup you just plug some other tool and you see all expected traffic? Traffic gets dumped to Kafka every 60 secs, so is it all good with the math there (ie. convert to Bps doing `(X * 8) / 60`)? Also, if only counting Bytes, every 60 secs you have to sum with the previous 60 secs (and so forth) to get the total amount of Bytes since you started pmacct? Maybe all obvious (sorry!), just checking.

Paolo

**Comment by jmilleriec** [comment]
Yes, ntopng seems to capture and move it into influxdb as expected.  The way data is being sent to kafka does appear to come in spikes, even beyond once a minute, but the bytes themselves are much lower than what ntopng is reporting.

It looks like pf_ring libpcap was actually built by the ntopng folks, so i'm assuming they are using that for their tool, so i was going to install that libpcap like you recommended above.

I'm a little confused where you stated this: "_Also, if only counting Bytes, every 60 secs you have to sum with the previous 60 secs (and so forth) to get the total amount of Bytes since you started pmacct?_"

So for any given time bin, you have to add all previous time bins for the "primary key" aggregates (let's say time, dst_host, src_host, vlan to keep it simple) to get an accurate count of bytes for that time bin?  I guess i'm not really following that, but if that's the case i'm definitely not doing that after i pick it up off of kafka.  After I get it off of kafka i just write it to influxdb basically as it comes off of kafka.

Jim

**Comment by paololucente** [comment]
Hi Jim,

> So for any given time bin, you have to add all previous time bins for the "primary key" aggregates (let's say time, dst_host, src_host, vlan to keep it simple) to get an accurate count of bytes for that time bin?

No, each time-bin is independent. Time-bin being 1 minute as per your config. I am not really familiar with ntopng so the point i wanted to make is: if ntopng cumulates bytes counts since start of the application - and you compare that against the last time-bin output to Kafka by pmacct - then numbers won't match up. The base time of the time-bin is indicated by the `stamp_inserted` field. Like, you can see total bytes from when you start pmacct by doing a `SELECT SUM(bytes) FROM <table> ;` ; you can sum the bytes by time-bin doing a `SELECT SUM(bytes), stamp_inserted FROM <table> GROUP BY stamp_inserted;` . Maybe i am saying the obvious but it's just to make sure.

With that CPU utilization and no signs of dropped packets, i am almost 100% sure the issue is later in the pipeline, ie. either how it is ingested in the DB from Kafka or how data is being queried from the DB.

Paolo

**Comment by jmilleriec** [comment]
gotcha, thanks Paolo, yes, i did a "sum" comparison" over time against ntopng and pmacct a while ago like you described and it was very different.

i'll look at how its going into and out of kafka and make sure that's all going correctly.

Thanks again for all your help, I'm determined to get this figured out, and really appreciate your assistance.

I'll check back in shortly with what i've found.

Thanks,
Jim

**Comment by jmilleriec** [comment]
Hi Paolo, you were correct, influxdb entries were being overwritten when the same host and time bin were submitted, so I needed to add a unique value in order to prevent that behavior.

Sorry for all the tail chasing, really appreciate your help, now I need to incorporate layer 7 now that bandwidth accounting is working... :-)

Jim

**Comment by paololucente** [comment]
Wonderfulness Jim, thanks for confirming & happy all is working out (so far :-D). Paolo
