### ISSUE TITLE
Sflow aggregation questions

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#535]
I'd like to return to a question I posted earlier. (Sorry for dropping the subject when other work came up.)

I've run a new test with incoming **sflow** data, writing to files, with 
	print_refresh_time: 60
        aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface, sampling_rate, label
        sfacctd_stitching: true
        timestamps_since_epoch: true
        timestamps_secs: false

I ran for several minutes and got a file each minute, as expected.
In the first one, the max. duration is 44 sec (I didn't start exactly on on the minute).
In the 2nd file, the max. duration is 44+60 = 104 sec.
In the 3rd file, the max. duration is 104+60 = 164 sec.
In each file, I see flows ending at the time given by the file name, as expected, but for flows that are in multiple files, timestamp_min is always the same as timestamp_min in the first file. I was expecting timestamp_min to be at most timestamp_max minus 1 minute.

I've not confirmed whether the number of packets and bytes reported is cumulative or not; I think not. 

This is reminiscent of how netflow works at the router, with "updates" being sent out every n seconds (n being the active timeout). Is this the intended behavior?   

Also, is there a way to get more precision in timestamp_min and timestamp_max? They are always rounded or truncated to the nearest second.

_Originally posted by @lisaens in https://github.com/pmacct/pmacct/issues/516#issuecomment-931620922_

**Comment by paololucente** [comment]
Hi Lisa ( @lisaens ),

I can confirm that the counters are not cumulative; every time you flush to the file (60 secs per your config), they get reset. 

The fact `timestamp_min` is not reset though, even after a period of inactivity, is definitely a bug - thanks for having spotted it. I should have addressed it with one of the two commits above; the other does instead address the other point you raised, also very true, that both `timestamp_min` and `timestamp_max` were clamped to second granularity (this was though a specific bug for sFlow). 

Can you please give latest & greatest coe a try and confirm it working / making sense to you? Should i find you positive, this work should be back ported to the SQL plugins.

Paolo

**Comment by lisaens** [comment]
Looking good now! 
I'm seeing the maximum durations and timestamp_min values that I'd expect if everything is reset after the refresh time.
Plus, timestamp_min and _max now have 6 decimal places. 

Thank you for the quick fix!
