### ISSUE TITLE
Nfacctd pretag field "ip" is not work with ipv6 address or prefix

### ISSUE THREAD

**Issue by mxlogin** [pmacct/pmacct#537]
Hello,

**Description**
I use as a source of ipfix flows juniper equipment with ipv6 address.
In pretag I set this ipv6 address to field "ip"
but it looks like the pretag of it does not understand the ipv6 address
Because
INFO ( out/mysql ): *** Purging cache - END (PID: 45020, QN: 0/0, ET: 0)
INFO ( in/mysql ): *** Purging cache - END (PID: 45022, QN: 0/0, ET: X)

But if I set this field to "0.0.0.0", the ipv6 ipfix flows were selected.

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.8-git [20211015-0 (b3cbdba9)

**Comment by paololucente** [comment]
Fix handled in commits cf04814bf1a38171655d820f87a83c3b52b56c60 and 9bf398751e3051955d8d184d073e58215f72cc63 . Tested working by Max ( @mxlogin )
