### ISSUE TITLE
Bind to VRF interface for inter-VRF BGP peering

### ISSUE THREAD

**Issue by WRMSRwasTaken** [pmacct/pmacct#538]
**Description**
I am running BIRD inside a VRF on a Linux host (actually multiple) without any route leaking whatsoever (unreachable route with a high metric inside the VRF). I am using pmacct as a sflow probe for the interfaces in that VRF, and I'd like to enrich the sflow data with BGP ASN information, for this I need a peering with BIRD to export the BGP fulltable to the pmacct peer.

Unfortunately, I am not able to bind the pmacct BGP listening socket inside the VRF as pmacct has no native configuration option for this. Setting something like `10.3.1.5%vrf-test` for `bgp_daemon_ip` doesn't work either because pmacct complains about an invalid IP address then.

Configuring that one BGP peer in BIRD to pmacct without the VRF config key in BIRD makes it spam about invalid next hops because the VRF BIRD runs in can't reach the main VRF pmacct is running because of the isolation due to the high metric default route.

Running pmacct with `ip vrf exec ...` isn't also an option because the sflow receiver address is also in the main VRF only. My workaround currently is setting `net.ipv4.tcp_l3mdev_accept` to `1` and bind pmacct to `0.0.0.0` which makes it also reachable from the VRF then but I consider this to be a rather hacky solution and I'd like to avoid that.

Maybe a new config item called something like `bgp_daemon_interface` could be specified where it is possible to specify the VRF to bind to, which would use `SO_BINDTODEVICE`.

Using BMP (and placing BMP communication into the main VRF) isn't an option for me, because BIRD doesn't support it (yet).

**Version**
```
pmacct IMT plugin client, pmacct 1.7.5-git (20200510-00)
 '--prefix=/usr' '--mandir=/usr/share/man' '--sbindir=/usr/bin' '--enable-ipv6' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-64bit' '--enable-threads' '--enable-jansson' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fcommon' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

**Appreciation**
![grafik](https://user-images.githubusercontent.com/4244869/138167466-777bc4de-411c-4c39-bdee-f0847f02ee7f.png)

**Comment by paololucente** [comment]
Hi Marcel ( @WRMSRwasTaken ),

I get your scenario and probably the limit of using bgp_daemon_ip: you may have the same IP configured on multiple interfaces on the same VM belonging to different VRFs. To be honest with you, i never played with VRF on Linux before and have zero dev environment ready for this. The dev looks relatively easy and quick to do - would you be able to give me access to a VM, for about a week or so, where i can dev without having to write code blindly?

Paolo
