### ISSUE TITLE
BMP: pmacct fails to detect certain cases of unsuccessfully exchanged ADD-PATH capability

### ISSUE THREAD

**Issue by andydavidson** [pmacct/pmacct#539]
**Description**
We see lots, an unexplainable number of default (both v4 and v6) routes, and some updates for nonsensical or illegal CIDR prefixes, e.g. 1.15.1.0/21.  I am confident that the updates when sent to us are for non-default prefixes, and are do not contain false CIDR prefixes.

They all seem to come through one particular BMP peer, who use a Juniper MX204 router.  Lots of other Juniper MXen send to us without us seeing this weird behaviour.

I will try to attach a screenshot from our DB showing some of the defaults in a five minute window, the same window that I took an attached PCAP for.

I spoke to Job who suspected the `BGP_BUFFER_SIZE` might be too small for the needs of `bmp.c`

**Version**
```root@bmpcollector:~# pmbmpd -V
pmacct BMP Collector Daemon, pmbmpd 1.7.6-git [20200923-4 (4b12919)]

Arguments:
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-fcommon' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'

Libs:
libpcap version 1.8.1
MariaDB 10.3.27
PostgreSQL 110010
sqlite3 3.27.2
rabbimq-c 0.9.0
rdkafka 0.11.6
jansson 2.12
MaxmindDB 1.3.2
ZeroMQ 4.3.1
netfilter_log

System:
Linux 5.10.0-0.bpo.3-cloud-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64

Compiler:
gcc 8.3.0
```

[Screenshot 2021-10-20 at 16 26 15](https://user-images.githubusercontent.com/4937503/138284465-39699ad4-524a-4a53-8729-02301871dc61.png)
[bmp.zip](https://github.com/pmacct/pmacct/files/7389293/bmp.zip)

**Comment by paololucente** [comment]
Andy ( @andydavidson ) confirmed earlier in the week that the above fixes are working for him. Closing.
