### ISSUE TITLE
sfacctd bgp no dst_host data

### ISSUE THREAD

**Issue by danyrlz** [pmacct/pmacct#542]
Hello Paolo,

We're using sfacctd 1.7.8-git [20211022-0 (74f38484)] and bgp daemon to fetch all bgp data.
The problem is that DST data(as_dst, peer_as_dst and as_path) is missing while the SRC one is fine:

+--------+-------------+---------+---------------------+
| as_dst | peer_as_dst | as_path | stamp_inserted      |
+--------+-------------+---------+---------------------+
|      0 |           0 | NULL    | 2021-10-22 17:45:00 |
|      0 |           0 | NULL    | 2021-10-22 17:45:00 |
|      0 |           0 | NULL    | 2021-10-22 17:45:00 |
|      0 |           0 | NULL    | 2021-10-22 17:45:00 |
+--------+-------------+---------+---------------------+

The same result is achieved using the memory plugin.

Here is the config:

plugins: mysql[bgp1]

sql_table_version: 9
sql_locking_style: none
sql_table_type: bgp
sql_optimize_clauses: true
sql_dont_try_update: true
sql_multi_values: 204880000
sql_cache_entries: 5000000

sql_history_roundoff[bgp1]: m
sql_history[bgp1]: 5m
sql_refresh_time[bgp1]: 300
sql_table[bgp1]: sfacct_bgp1_5min

sfacctd_port: 6343
sfacctd_renormalize: true
networks_cache_entries: 1000003

bgp_daemon: true
bgp_daemon_ip: x.x.x.x
bgp_daemon_max_peers: 100
bgp_table_dump_refresh_time: 300

sfacctd_as: bgp
bgp_src_as_path_type: bgp
bgp_peer_src_as_type: bgp

bgp_agent_map: /etc/pmacct/agent_to_peer5a.map
pre_tag_map: /etc/pmacct/pretag/peer5.map
pre_tag_label_filter[bgp1]: ing

bgp_daemon_pipe_size: 10240000
plugin_buffer_size: 102400
plugin_pipe_size:  102400000

aggregate[bgp1]: peer_src_ip, src_mac, dst_mac, vlan, src_host, dst_host, src_as, dst_as, peer_src_as, peer_dst_as, as_path, tag, tag2

When the dst host is checked in the bgpdump the prefix is present(bgp peer announces full internet BGP table).
I can send you the lookups in private. Let me know what additional debug should we perform?

Thanks,

**Comment by paololucente** [comment]
We determined this was due to BGP having ADD-PATH data but sFlow data not having a (BGP) next-hop to match upon.
