### ISSUE TITLE
compile option "--disable-ipv6" doesn't work?

### ISSUE THREAD

**Issue by maplewf** [pmacct/pmacct#544]
Hi, 

I'm trying to disable ipv6 during compilation. But it seems doesn't work. I'm using pmacct 1.7.6:

```
./configure --disable-ipv6
configure: WARNING: unrecognized options: --disable-ipv6
checking for a BSD-compatible install... /usr/bin/install -c
...
```

**Comment by paololucente** [comment]
Hi @maplewf ,

Yes, to confirm that it is by design: IPv6 is integral part and can't be removed anymore.

Paolo
