### ISSUE TITLE
AS_DST numbers are not compatible with those in networks_file

### ISSUE THREAD

**Issue by strahinjalalic** [pmacct/pmacct#545]
Hi Paolo,

Hope you're doing fine. I am writing this issue down because of some troubles that I found out recently. We are developing NetFlow/jFlow software and using pmacct to help us out. The problem is in incompatibility of as_dst column in database and the one we specified in networks file. 

![ip_as_dst](https://user-images.githubusercontent.com/39598182/141121563-9742df24-e2a3-4676-883d-aee48248cf58.png)
This is printscreen example from our database.

![bgp_as](https://user-images.githubusercontent.com/39598182/141121648-6f5f8a04-a8ad-49dd-82d6-dd8f6da6fd61.png)
And this is printscreen of valid AS number in networks file.

We also captured packets on server using **tcpdump** and found out that AS numbers are correct there, so we thought the problem may be in pmacct (or in missconfiguration of nfacctd file at least).

Reach us out if something is unclear in this message.

Thanks & Best regards,
Strahinja

**Comment by paololucente** [comment]
Hi Strahinja ( @strahinjalalic ),

Great to read from you. Can you please pass me (here or via unicast email) your current config to make a more precise assessment?

Paolo

**Comment by strahinjalalic** [comment]
Hi Paolo,

Thanks for reply. Sure I can, i'll just leave that here.

![pmacct](https://user-images.githubusercontent.com/39598182/141951875-88b84787-cc4e-48c9-94e2-775c816689e6.png)

**Comment by paololucente** [comment]
Thanks & i see.

I am assuming that, despite the path is not absolute for `networks_file`, it is being read correctly and you don't have any warnings in the config about it - true?

Can you try two things: 1) commenting out the `nfacctd_as` directive and adding `networks_file_no_lpm: true` and, if it does not work, 2) de-comment the `nfacctd_as` directive and add a `nfacctd_net: file`?

Paolo

**Comment by strahinjalalic** [comment]
Hi Paolo, 

Yes, that is absolutely true, networks_file is loaded without any problems and warnings.

I tried both of your solutons and results are still same.

Best regards,
Strahinja

**Comment by paololucente** [comment]
Ack, thanks Strahinja for the quick feedback.

Allow me a bit of time to reproduce the issue. Meanwhile question to you: where does this 48737 AS number come from, in your opinion? Not seeing a BGP/BMP peering in your config, i am thinking this must be coming from your NetFlow, true? Or is it "invented"? 

Paolo

**Comment by paololucente** [comment]
One more thing, i just tested master code and i seem to be unable to reproduce the issue. Can you confirm what version / code are you running (output of `nfacctd -V` would do)? If not running master code or (recently released) 1.7.7, can you give a try to either of these?

Paolo

**Comment by strahinjalalic** [comment]
Thanks for fast replies Paolo. 

As far as I understand, I think those ASN-s are invented. I think that because we tried to capture packets on NetFlow port 2055 and then analyze them in Wireshark software. Therefore, all ASN-s are correct. 

I will post the output of NetFlowAccountigDaemon version command below.
![nfacctd](https://user-images.githubusercontent.com/39598182/142382132-22cfe3ad-09ef-4be5-9b0c-a5f376b220f2.png)

Best regards,
Strahinja

**Comment by paololucente** [comment]
Hi Strahinja,

Thanks for your previous feedback & unfortunately i am unable to reproduce the issue with latest & greatest code (which is not what you are running but i believe it won't change much). Any chance i can access with this setup via ssh and troubleshoot this further?

Paolo

**Comment by strahinjalalic** [comment]
Hi Paolo,

Yes, of course. I will mail you ssh access and other info.

Best regards,
Strahinja

**Comment by paololucente** [comment]
Hi Strahinja,

Thanks for your patience with this. I should have been able to nail the offending code. Can you please give a try to latest master code and confirm it all works well for you now?

Paolo

**Comment by strahinjalalic** [comment]
Hi Paolo,

Don't bother yourself, we suggested you were too busy. We are delight to inform you everything is perfect now, thanks for resolving our problem! 

Best regards,
Strahinja
