### ISSUE TITLE
adding ifalias to the ipfix data

### ISSUE THREAD

**Issue by vishnubraj** [pmacct/pmacct#546]
Juniper routers don't support exporting ifAlias details in the IPFIX or Netflowv9 data, is it possible to include the ifalias_in and ifalias_out to the IPFIX or NETFLOWv9 data via PMACCT?

**Comment by paololucente** [comment]
Hi Vishnu ( @vishnubraj ), 

You mean like by correlating with SNMP, for example? If so, no. But you can do that as part of your post-processing / enrichment. 

Paolo

**Comment by vishnubraj** [comment]
Hi Paolo,

Thanks for your answer. I will close this ticket.

Vishnu
