### ISSUE TITLE
pmacct 1.6.0 - Failing to build with jansson plugin while libs are in non standard location

### ISSUE THREAD

**Issue by swiftugandan** [pmacct/pmacct#55]
I am trying to build the pmacct package with jansson enabled. I am using a non standard location for the library (as shown below), but I get a make error claiming that jansson.h does not exist. Please advise ...

STEPS
```
wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
tar -xvzf jansson-2.7.tar.gz
cd jansson-2.7/
./configure make
DESTDIR=/tmp/jansson/ make install
export JANSSON_LIBS="-L/tmp/jansson/usr/local/lib/ -ljansson"
export JANSSON_CFLAGS="-I/tmp/jansson/usr/local/include/"

cd ../pmacct-1.6.0/
./configure --enable-jansson
```

OUTPUT
```
.
.
.
PLATFORM ..... : x86_64
OS ........... : Linux 3.13.0-92-generic
COMPILER ..... : gcc
CFLAGS ....... : -O2 -g -O2 
LIBS ......... : -lpcap  -ldl -L/usr/local/lib -lz -lpthread
LDFLAGS ...... : -Wl,--export-dynamic 
PLUGINS ...... :  jansson
```

MAKE
```
/tmp/pmacct-1.6.0$ make
Making all in src
gmake[1]: Entering directory `/tmp/pmacct-1.6.0/src'
Making all in nfprobe_plugin
gmake[2]: Entering directory `/tmp/pmacct-1.6.0/src/nfprobe_plugin'
  CC     libnfprobe_plugin_la-nfprobe_plugin.lo
In file included from common.h:30:0,
                 from nfprobe_plugin.c:53:
./../pmacct.h:338:21: fatal error: jansson.h: No such file or directory
 #include <jansson.h>
                     ^
compilation terminated.
gmake[2]: *** [libnfprobe_plugin_la-nfprobe_plugin.lo] Error 1
gmake[2]: Leaving directory `/tmp/pmacct-1.6.0/src/nfprobe_plugin'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/tmp/pmacct-1.6.0/src'
make: *** [all-recursive] Error 1
```

**Comment by paololucente** [comment]
Hi,

If you do a ./configure --help you will see this towards the end of the output:

  JANSSON_CFLAGS		C compiler flags for JANSSON, overriding pkg-config
  JANSSON_LIBS			linker flags for JANSSON, overriding pkg-config

Did you already try pointing these variables to your custom location? JANSSON_CFLAGS should point to the path where the headers are, ie. -I/path/to/headers; JANSSON_LIBS should point to the path where the lib(s) are, ie. -L/path/to/libs

**Comment by swiftugandan** [comment]
Hi,

Yes I did point the variables to the custom location:(See: Steps above ...)

export JANSSON_LIBS="-L/tmp/jansson/usr/local/lib/ -ljansson"
export JANSSON_CFLAGS="-I/tmp/jansson/usr/local/include/"

**Comment by vincentbernat** [comment]
In `src/nfprobe_plugin/Makefile.am`, we need to add:

```
AM_LDFLAGS = @JANSSON_LIBS@
AM_CFLAGS  = @JANSSON_CFLAGS@
```

(maybe GeoIP is also used?)

As we discussed by email, those CFLAGS/LIBS could be copied into CFLAGS/LIBS inside configure, but then everything will link with the lib.

**Comment by paololucente** [comment]
Hi @swiftugandan ,

With the two commits referenced above, this should be fixed now. Some build code refinements may still be possible in the forthcoming days but the basics to make this work are already in master code. Can you confirm it working for you?
