### ISSUE TITLE
Schema registry not matching topic name

### ISSUE THREAD

**Issue by cpmarvin** [pmacct/pmacct#555]
**Description**

When nfacctd writes to confluent schema registry the topic name is different, An extra -acct-data is added. Is this expected behaviour , i'm using ksql to create a stream and can't find the schema because of diffrent names.

/opt/pmacct/etc/v0.1$ cat netflow.conf | grep kafka
plugins: kafka[data]
kafka_output[data]: avro
kafka_topic[data]: **data_host_raw_1m_test2**
kafka_refresh_time[data]: 60
kafka_history[data]: 1m
kafka_history_roundoff[data]: m
kafka_avro_schema_registry[data]: http://kafka-uk:8081
kafka_broker_host[data]: kafka-uk

[2021-12-07 13:58:39,225] INFO 10.208.2.27 - - [07/Dec/2021:13:58:39 +0000] "POST /subjects/**data_host_raw_1m_test2-acct-data-value**/versions HTTP/1.1" 200 8 "-" "libserdes" POSTsT (io.confluent.rest-utils.requests)

-acct-data- is the extra here.

**Version**
/opt/pmacct/etc/v0.1$ ../../sbin/nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.8-git [20211206-0 (0cc3b488)]

Thanks!

**Comment by paololucente** [comment]
Hi Catalin ( @cpmarvin ),

Yes, it is intended & aligned with the schema name (or let me re-phrase: when the schema registry gets involved, the schema name drives a bit it all). So "acct" suffix is appended (as opposed to "bgp", "bmp", etc.) and "data" suffix is appended (as opposed to "init", "close", etc.) to say it's about traffic flows and the actual data.

I understand this could be confusing at first and it should be documented better, put this already on my todo list. Would you regard this as sufficient action or this is beyond bothersome, ie. it does not allow you to make it a workable scenario?

Paolo

**Comment by cpmarvin** [comment]
thanks for the info Paolo.

It should simple for me to take the output of avro_schema_file and map it to the topic i need.

**Comment by paololucente** [comment]
Wonderful Catalin, thanks for confirming. I will then go ahead and close the issue. Paolo
