### ISSUE TITLE
Using pcap_interfaces_map directive will cause aggregate_filter to not work as expected

### ISSUE THREAD

**Issue by mdpuma** [pmacct/pmacct#564]
Hello,

We tried to capture traffic statistics from single interfaces. All options which are needed we had found, but when we have tried to use pmacct on multiple interfaces, we have found that pcap_interfaces_map, will cause pmacctd to ignore aggregate_filter directive and all traffic is captured, even if i use aggregate_filter or aggregate_filter[x] as option.

pmacctd config:

```
daemonize: false
pidfile: /var/run/pmacctd.pid
syslog: daemon

! pcap_interface: ens1f0

plugins: print
print_refresh_time: 10
print_output: formatted

plugin_buffer_size: 10485760
plugin_pipe_size: 104857600

aggregate: src_mac, dst_host
aggregate_filter: ether dst host 00:15:2c:18:ac:00

pcap_interfaces_map: /etc/pmacct/interfaces.map
```

interfaces.map
```
ifindex=8	ifname=ens1f0 direction=in
ifindex=26	ifname=bond4 direction=in
```

**Comment by mdpuma** [comment]
Well, i have tried also this case.

```
daemonize: false
pidfile: /var/run/pmacctd.pid
syslog: daemon

pre_tag_map: /etc/pmacct/inbound.map
plugins: print[in], print[out]

plugin_buffer_size: 10485760
plugin_pipe_size: 104857600

aggregate[in]: src_mac, dst_host
aggregate[out]: dst_mac, src_host

aggregate_filter[in]: ether dst host 00:15:2c:18:ac:00
aggregate_filter[out]: ether src host 00:15:2c:18:ac:00

print_refresh_time[in]: 60
print_refresh_time[out]: 60

print_output[in]: formatted
print_output[out]: formatted

pcap_interfaces_map: /etc/pmacct/interfaces.map
```

```
ifindex=8	ifname=ens1f0 direction=in
ifindex=26	ifname=bond4 direction=in
```

I m getting all traffic, no matter which aggregate_filter i have applied, but this directive have effect only when i have only one interface in interfaces.map file.

**Comment by paololucente** [comment]
Hi @mdpuma ,

Thank you for the extra insight. I could reproduce the issue and fix it (see above the relevant commit). Can you give it a try (either apply the commit to the code you are running or switch to latest & greatest master code)?

Paolo

**Comment by mdpuma** [comment]
Hello,

I m still getting all traffic, no matter which aggregate_filter directive is set.

**Comment by paololucente** [comment]
Hi @mdpuma ,

I fail to reproduce the issue with the information i have in this Issue. Can you confirm you did apply the fix as in https://github.com/pmacct/pmacct/commit/79c2c9084bd97b1af6576bdfcceb465b17a30c07 . Are you running master code or did you apply to a previous version and, if so, which one?

Let me know if it is possible for me to troubleshoot this issue on your box with an SSH access. If so please reach out via unicast email.

Paolo

**Comment by mdpuma** [comment]
Hello,

My fault, last commit 79c2c90 have solved this issue.
