### ISSUE TITLE
Can't able to receive the Sflow data, We added more details in description

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#565]
Hi @paololucente 
**Description**
We try to collect the data from sflow v5 but we can't receive the data

Conf file for sflow
```
daemonize: false
sfacctd_port: 9992
sfacctd_renormalize: true
plugins: print
print_output:csv
print_output_file:/etc/pmacct/%Y%m%d%H%M.csv
```
We used the below cmd to execute the above configuration file 

`sfacctd -f /etc/pmacct/pmacct_sflow.conf -D`

We also checked the debug option, we didn't receive any error, our system received the packets for the flow.

I used tcpdump cmd, we received data when we execute tcpdump cmd
`tcpdump -i any port 9992 `

**Version**
**Sfacctd version**

sFlow Accounting Daemon, sfacctd 1.7.4-git (20191013-00)

Arguments:
 '--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
rabbimq-c 0.8.0
jansson 2.11

System:
Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64

Compiler:
gcc 7.4.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

**Comment by paololucente** [comment]
Hi @AnanthGopal ,

Please check this https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L2947-#L2988 . You checked already point 1, please check also point 2. See if any of the other points do apply as well.

Paolo

**Comment by AnanthGopal** [comment]
thank you @paololucente. We received the sflow data
