### ISSUE TITLE
ipfix/netflow v9: wrong length for the IANA element `tcpControlBits`(6)

### ISSUE THREAD

**Issue by ethuleau** [pmacct/pmacct#567]
**Description**
pmacct does not use the right field length to encode TCP flags of flow.
IANA define an IPFIX element named `tcpControlBits` with the ID `6` to carry that TCP flags information.
pmacct is correctly use that field but it does not respect the [length of 2 octets fixed by IANA](https://www.iana.org/assignments/ipfix/ipfix.xhtml#ipfix-information-elements). It uses a [length of 1 octet](https://github.com/pmacct/pmacct/blob/master/src/nfprobe_plugin/netflow9.c#L931-L941).

**Version**
Provide the version in use. An output of -V is typically good, ie. `nfacctd -V`

```
root@srv5:~# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.5.2 (20150907-00)
 --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --enable-mmap --enable-pgsql --with-pgsql-includes=/usr/include/postgresql --enable-mysql --enable-sqlite3 --enable-ipv6 --enable-v4-mapped --enable-64bit --enable-threads --enable-jansson --enable-geoip --enable-rabbitmq

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

Bug seems to be there on master branch too https://github.com/pmacct/pmacct/blob/master/src/nfprobe_plugin/netflow9.c#L931-L941

**Comment by paololucente** [comment]
Hi Edouard,

Thanks for explaining. Based on pmacct experience of receiving from network kits from usual suspect vendors, my recommendation would be for you to accept a 1-byte field for TCP flags (as i was commenting previously, pmacct does receive only a 1 byte field for TCP flags and that seems to work against all major vendors), perhaps in addition to the IANA-documented 2 bytes specification. 

Paolo

**Comment by paololucente** [comment]
Hi Edouard,

It just ignores the whole field if TCP flags is 2 octet long. Consider that in that same document where the 2 octet long field is specified, the door for a 1 octet long version is wide open, see here:

```
If exported as a single octet with reduced-size encoding, this Information
Element covers the low-order octet of this field (i.e, bits 0x80 to 0x01),
omitting the ECN Nonce Sum and the three Future Use bits. A collector
receiving this Information Element with reduced-size encoding must not
assume anything about the content of these four bits.

Exporting Processes exporting this Information Element on behalf of a
Metering Process that is not capable of observing any of the ECN Nonce
Sum or Future Use bits SHOULD use reduced-size encoding, and only
export the least significant 8 bits of this Information Element. 
```

Since most, if not all, of big vendor IPFIX implementations are not greenfield but brownfield (ie. evolved from NetFlow v5 and/or NetFlow v9), i am not surprised they all still do export this field as 1 octet long.

In any case, thanks to your report, i will add support for collecting the 2 octet version, ignoring the first octet. I do not plan though to implement this for the export part, that is nfprobe.

Paolo

**Comment by ethuleau** [comment]
oh I missed that comment part about reduced-size encoding. Thanks to pmacctt, my collector support it now :)

**Comment by paololucente** [comment]
> oh I missed that comment part about reduced-size encoding. Thanks to pmacctt, my collector support it now :)

And vice-versa. I have now added limited support for collecting the 2 bytes encoding, focusing only on the second octet. Thank YOU!

Paolo
