### ISSUE TITLE
Collecting netflow utilizing pmacctd and nfacctd. No collection of netflow from nfacctd.

### ISSUE THREAD

**Issue by P-IM** [pmacct/pmacct#568]
Hi!

I am trying to get the netflow and store it in a CSV file. The following are my configuration files:
pmacctd.conf:
daemoniz: false
pcap_interface: enp0s3
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, timestamp_start, timestamp_end
plugins: nfprobe
nfprobe_receiver: 127.0.0.1:2100
nfprobe_version: 9

nfacctd.conf:
daemonize: false
nfacctd_interface: enp0s3
nfacctd_port: 127.0.0.1
nfacctd_port: 2100
plugins: print[netflow]
aggregate[netflow]: src_host, dst_host, src_port, dst_port, proto, tos, timestamp_start, timestamp_end
timesampts_since_epoch: true
print_output[netflow]: csv
print_output[netflow]: csv
print_output_file_append[netflow]: true
print_refresh_time: 1
print_output_file[netflow]: Coll_Netflow.csv

I run ./pmacctd -f pmacctd.conf on one terminal and on the other I run ./nfacctd -f nfacctd.conf. The issue that I am coming across is that on the nfacctd terminal it's not collecting any netflow. What appears when it's trying to print the netflow is the following for all of them:
INFO ( netflow/print ): *** Purgin cache - START (PID: *PIDnumber*) ***
NFO ( netflow/print ): *** Purgin cache - END (PID: *PIDnumber*, QN: 0/0, ET: X) ***

And no csv file is created.

**Comment by paololucente** [comment]
Hi @P-IM ,

Is it the issue that pmacctd/nfprobe is not exporting data, ie. maybe timeouts need to be tweaked, or that nfacctd is not collecting it? Did you confirm this with some tcpdump, ie. `tcpdump -i lo -n port 2100`? There was recently an issue opened around nfprobe & timeouts, you can look here: https://github.com/pmacct/pmacct/issues/566 . 

Paolo

**Comment by paololucente** [comment]
Hi @P-IM ,

At a closer look i can see how `nfacctd_interface: enp0s3` could screw up nfacctd collection, although i see you removed it from your second configuration.

In the second config you make pmacctd listen on `pcap_interface: lo`, which may or may not have traffic - i believe the original `pcap_interface: enp0s3` in the first configuration was correct.

Can you try these two changes and see if it helps? Also, i trust you are not running any firewall on the `lo` interface, true?

Paolo

**Comment by P-IM** [comment]
Hi Paolo,
I was able to capture the netflow and be able to store it in a csv file. 

I did the change of putting back on enp0s3 on the pcap_interface. In addition, I did the following command on the terminal for nfacctd:
./nfacctd -f nfacctd.conf -o ~/(directories)/Netflow.csv
And I was able to capture netflow and create the csv file.

Thank you for the help!

**Comment by paololucente** [comment]
Thanks for confirming, i will close this issue.

Paolo
