### ISSUE TITLE
pcap_interface with random ifconfig-name

### ISSUE THREAD

**Issue by zzgundam** [pmacct/pmacct#570]
I want to account the custom docker bridge interfaces,which have random names(like below),how should I write in pmacctd.conf? 
```
br-35f08c91d76f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 172.99.103.1  netmask 255.255.255.0  broadcast 172.99.103.255
```

**Comment by paololucente** [comment]
Hi @zzgundam ,

Can you fix the name to something predictable as they say here? https://stackoverflow.com/questions/43981224/docker-how-to-set-iface-name-when-creating-a-new-network

Paolo
