### ISSUE TITLE
Pmacctd can't see flows with just basic configuration

### ISSUE THREAD

**Issue by q2dg** [pmacct/pmacct#571]
**Description**
I'm running pmacctd daemon with this basic configuration...

![pmacct-conf](https://user-images.githubusercontent.com/7274874/154259792-42e389a2-62f8-4308-aff1-e3729712233b.png)

and this Systemd service file

![pmacct-systemd](https://user-images.githubusercontent.com/7274874/154259846-10b1c5a2-2158-4394-80da-f093cc550466.png)

It seems all it's ok. But when I run _pmacct -s_ I can see just few flows, not all of them. Specifically, if, for instance, I connect via SSH to the same machine where pmacctd is running (or, rather, to the IP address whose belongs to the network interface monitored by pmacctd; "enp0s8"), I can't see any flow having 22 as its destination or source port. The same happens if I connect to a HTTP server running in the same machine than pmacctd does and I download something from it: no flow is seen having 80 as its destination or source port.

I'm sure I'm doing some stupid thing badly, but I can't get the clue.
Thanks a lot for your work and apologize in advance for my clumsiness

**Version**

![pmacct-version](https://user-images.githubusercontent.com/7274874/154259700-0e6b927a-eb07-4080-9600-8b44a6a319cd.png)

PD: Using another plugin like "print" or "nfprobe" has the same behaviour

**Comment by q2dg** [comment]
I've tried with a simple tcp connection using netcat between machine where pmacctd daemon is running and another machine in the same LAN. No records. Meanwhile, pmacct -s show connections multicast packets, pumbling dns/http queries from the system...but connections made from MY programs from LAN to the pmacctd server machine no. I'm really desperated.

**Comment by paololucente** [comment]
Hi @q2dg ,

Not sure, do you have multiple active interfaces on your machine? Is it possible traffic exits one interface and enters a different one and/or any other sort of asymmetry? Otherwise, well, it is very strange indeed as you should be able to see all traffic originated from / terminated to the machine were you run pmacctd.

Paolo

**Comment by q2dg** [comment]
YES!! It was that!! I have another network card in the same lan. If I disable it, it works!! 
But...why this happens?? I mean, in case there was a asymmetry in the response (!!??), I do connect explicitly to the interface monitored by pmacct, so it should see at least a inbound flow, shouldn't it? There's something I don't get yet.
Thanks a lot for your kind answer!!!

**Comment by q2dg** [comment]
Thanks. I didn't close the issue by myself because I wanted to know why the presence of an active but unused network card influences so much in pmacct's result when monitoring another different network card on the same system.

**Comment by paololucente** [comment]
pmacct relies on libpcap. I am rather sure you will be able to confirm the same results with, for example, tcpdump as well. Why this happens, i can't unfortunately comment as i know little about the setup.
