### ISSUE TITLE
Question: Port numbers are 0

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#572]
I hope this isn't too general a question... I'm seeing a lot of flows with source and destination ports of 0. Any idea what this means or indicates?  These are flows going across international links. I've seen them in both sflow and netflow data.

$ sfacctd -V
sFlow Accounting Daemon, sfacctd 1.7.8-git [20211011-1 (324cdd74)]
Arguments:
 '--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

**Comment by q2dg** [comment]
Maybe it's related to "ports_file" directive?

**Comment by lisaens** [comment]
I'm not using a ports file, so that could not be it, if I understand what you're referring to.

In googling "port 0", I've found references to packet fragmentation, attacks, scanning, and bitTorrent. Possible clues but I'm still not sure what I'm seeing.  Any chance sfacctd or nfacctd is not interpreting headers correctly or something?

**Comment by lisaens** [comment]
Interesting!  So if a TCP session is broken up, the source port will be 0. What about the destination port? Anyone have any more information on this? More references?

**Comment by lisaens** [comment]
Thanks for the comments. We'll ponder this for a while!
