### ISSUE TITLE
how to record new connection packets only？

### ISSUE THREAD

**Issue by zzgundam** [pmacct/pmacct#573]
to record new connection packets only,i can do it by using iptables like this:
iptables -A -p tcp -m conntrack --ctstate NEW -j log
how to do it with pmacct？

**Comment by paololucente** [comment]
You could isolate TCP packets with the SYN flag, ie. `pmacctd "tcp[tcpflags] & (tcp-syn) != 0"`. The same expression you should be able to pass in a config as part of `pcap_filter` or `aggregate_filter`.
