### ISSUE TITLE
IPv6 prefixes in networks_file mapped to ::

### ISSUE THREAD

**Issue by rodecker** [pmacct/pmacct#577]
**Description**
Since version 1.7.7 IPv6 prefixes in the networks_file are no longer handled properly.

My pmacctd.conf contains the following:

> ! pmacctd.conf
> daemonize: false
> pre_tag_map: /etc/pmacct/pretag.map
> networks_file: /etc/pmacct/networks.lst
> networks_file_no_lpm: true
> aggregate: label, tag, in_iface, out_iface, src_mac, dst_mac, peer_src_ip, src_as, dst_as, src_net, dst_net, src_host, dst_host, etype, src_port, dst_port, proto, tcpflags
> sfacctd_port: 6343
> sfacctd_as: longest
> sfacctd_net: longest
> sfacctd_renormalize: true
> plugins: print

And my networks file:

> ! networks.lst
> 65001,2001:DB8::/32
> 65001,10.0.0.0/24

When trying to load this file in pmacctd/sfacctd version 1.7.7 I see the following:

> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v4 nh:  peer asn: 0 asn: 65001 net: 10.0.0.0 mask: 24
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
> INFO ( default/core ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v6 nh:  peer_asn: 0 asn: 65001 net: :: mask: 32
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v6 contains a default route
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] IPv6 Networks Cache successfully created: 32771 entries.

Every single IPv6 flow is incorrectly mapped to src_as 65001 and dst_as 65001.

When loading the same file with a checkout from master (today, 382980208414d247fa38575db100beb5be9e4126):

> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v4 nh:  peer asn: 0 asn: 65001 net: 10.0.0.0 mask: 24
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
> INFO ( default/core ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v6 nh:  peer_asn: 0 asn: 0 net: :: mask: 0
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] v6 contains a default route
> DEBUG ( default/core ): [/etc/pmacct/networks.lst] IPv6 Networks Cache successfully created: 32771 entries.

IPv6 flows are now no longer mapped to any AS.

Finally, I tried version 1.7.6:

> DEBUG ( default_kafka/kafka ): [/etc/pmacct/networks.lst] v4 nh:  peer asn: 0 asn: 65001 net: 10.0.0.0 mask: 24
> DEBUG ( default_kafka/kafka ): [/etc/pmacct/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
> INFO ( default_kafka/kafka ): [/etc/pmacct/networks.lst] map successfully (re)loaded.
> DEBUG ( default_kafka/kafka ): [/etc/pmacct/networks.lst] v6 nh:  peer_asn: 0 asn: 65001 net: 2001:db8:: mask: 32
> DEBUG ( default_kafka/kafka ): [/etc/pmacct/networks.lst] IPv6 Networks Cache successfully created: 32771 entries. 

With this version IPv6 flows are correctly mapped.

**Version**

> sFlow Accounting Daemon, sfacctd 1.7.7-git [RELEASE]
> 
> Arguments:
>  '--enable-jansson' '--enable-kafka' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
> 
> Libs:
> cdada 0.3.5
> libpcap version 1.5.3
> rdkafka 0.11.4
> jansson 2.13
> 
> Plugins:
> memory
> print
> nfprobe
> sfprobe
> tee
> kafka
> 
> System:
> Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64
> 
> Compiler:
> gcc 4.8.5

**Appreciation**
pmacct is love

**Comment by paololucente** [comment]
Hi Martin ( @rodecker ),

Thanks very much for reporting this. Indeed this is a bug introduced in 1.7.7. I should have fixed the situation with the commit above, can you please give it a try?

Paolo

**Comment by rodecker** [comment]
Hi @paololucente,

Now it works. Thanks for the blazingly fast support!

Cheers,
Martin
