### ISSUE TITLE
Questions about details of aggregation by pmacct

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#579]
A few questions about aggregation...
1. When aggregating and stitching, if aggregation starts at time t, are all flows dumped at once at t+refresh_time, no matter when they were first seen? Or will each individual flow be dumped at the time it was first seen + refresh_time?  
2. There is nothing like an inactive timeout, correct? Flows will only be dumped at the end of the refresh_time, even if no matching traffic has been seen since the start of the interval?
3. Aggregated flows will have timestamp_min and timestamp_max added to the output. For sflow, these would be the first and last times that a sample came in during the refresh interval. For netflow, would timestamp_min be the minimum timestamp_start  and timestamp_max the maximum timestamp_end? Or would timestamp_max be the largest timestamp_start, or what?  

For context, we are trying to determine if we can stitch raw flows together into longer flows, up to a max of 1 hr, using pmacct.  Up to now, we have been using the logstash aggregation filter, which works differently. 
For sflow, I think this can be done, though stitched flows may take longer to emerge from aggregation since we can't set an inactive timeout to say 5 minutes.
For netflow, I'm not so sure it will work. For long-lasting flows, netflow "updates" come in every minute (due to active timeouts at the router), each with the same start time, a new end time, and just an additional number of packets and bytes.
If I use `aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface, sampling_rate, label, timestamp_start` , `nfacctd_stitching: true` , and `amqp_refresh_time: 3600` , the "updates" will be added together for 1 hour. Will the start and end times be timestamp_start and the last timestamp_end? A problem is that if a flow lasts longer than 1 hr, the next "update" after the first refresh time will have the same old start time, which will not match up with the sum of bytes that the next hour of aggregation will give.   
Any thoughts?

**Comment by paololucente** [comment]
Hi Lisa ( @lisaens ),

Thanks for your questions, they point out to the fact documentation can be expanded. To your 3 questions:

1) All flows are dumped at once at t+refresh_time;
2) Correct: no, there is nothing like an inactive timeout;
3) To confirm that for sFlow it's like you say, the first and last times that a sample came in during the refresh interval; For netflow, it's your first guess, timestamp_min is the minimum timestamp_start and timestamp_max is the maximum timestamp_end.

May i counter-ask two things:

1) How does the logstash aggregation filter work?
2) Let's forget for a moment how pmacct does work, what would be your ideal scenario? It almost seems like that you want to:
    * bring sFlow to a NetFlow logic with stitching and timeouts and
    * keep short timers on your routers wrt NetFlow and consolidate them in bigger flows at the collector retaining the same / a similar export process collector -> backend like NetFlow does on the router -> collector segment.
    
    True? Not true?

Paolo

**Comment by lisaens** [comment]
Thanks for those details!

Logstash aggregation works by specifying what you want to aggregate by (we use the 5-tuple of src and dst IPs, ports, and protocol) and also active and inactive timeouts. As raw flows come in, it will watch for a match. If no matches have come in for inactive-timeout seconds (time between start of current flow and start of last flow), it declares the aggregation finished and pushes it out. If matches are still coming in, but active-timeout seconds have passed, it ends the aggregation anyway and the next match would start a new one. 

You are basically right about what we want to do. Our main interest is in flows of science data, which can be quite long. Usually these are broken up at the router into separate raw flows, either due to short inactive timeouts at the router (we can't easily control the settings) or actual gaps in the traffic. We've been trying to stitch together the raw flows, as long as gaps are under say 5 minutes, based on the 5-tuple. Recently, we thought perhaps we should break up long flows into 1 hour pieces. We'd not need to wait as long until they appeared in elasticsearch and the pieces could be "aggregated," by source organization for example, in grafana at the time it was displayed.  
In any case, having the correct start and end times and number of bytes in each final flow is important, whether we break flows into pieces or not.

Things are pretty clear with sflow, but netflow has been a bear due to the way it sends out updates while a flow is active, which all have the same start time but the number of bytes is not cumulative. If ALL the updates are aggregated, things are great, but if you break up the sequence at 1  hour, the sums of the 2nd and later sets of updates will have the problem that the start time won't match up with the total number of bytes.  I was thinking of moving the start time forward by whole hours for any flow with a duration of over 1 hour, but this won't work with nfacctd since the very start of a flow might occur only halfway through the refresh time of 1 hour, so the first piece might have a duration of 30 minutes. Fine, but then, I wouldn't know how much to adjust the start time of later pieces (without saving or looking up that first flow, which I can't do).  Hope this makes sense.

**Comment by lisaens** [comment]
We're going to try a hybrid approach, using sfacctd to aggregate sflows for 5 minutes, then let logstash aggregate further. For netflow, we'll not do anything with nfacctd and let logstash do all aggregation. 
You can close this issue. Thanks for the info!

**Comment by paololucente** [comment]
Thank you Lisa ( @lisaens ) for the follow-up. I will go ahead and close this issue. Also good food for thoughts for other people in your same or similar scenario. Paolo
