### ISSUE TITLE
Version pmacct-1.7.7 not available in this repository

### ISSUE THREAD

**Issue by Bonnietwin** [pmacct/pmacct#580]
Version pmacct-1.7.7 was released on 7th Nov 2021 on the pmacct website but has not been made available in this repository which only has the 1.7.6 version available.

Is github no longer being used for providing the pmacct source tarball?

If I select tags then 1.7.7 is listed but it only provides the "Source Code" assets and not the pmacct-1.7.7.tar.gz asset.

**Comment by paololucente** [comment]
Hi @Bonnietwin ,

Thank you for your note. You are right, i have just made the 1.7.7 release here on GitHub. 

Paolo
