### ISSUE TITLE
Incorrect flow classification 

### ISSUE THREAD

**Issue by q2dg** [pmacct/pmacct#581]
**Description**

**1.-** I have compiled pmacctd with nDPI in order to get flow classification. 

**2.-** I have pmacctd running with this configuration:

_daemonize:true
pcap_interface:enp0s3
aggregate:src_host,dst_host,src_port,dst_port,class
plugins:memory_

**3.-** But when I do _pmacct -s_ I see in column "CLASS" wrong protocols. For instance, SSH traffic is seen as "Usenet/Usenet" or plain HTTP traffic (made by curl) is seen as "FTP_CONTROL/FTP_CONTROL". It's not what I was expecting for.

Maybe I'm doing something wrong but I've just followed these instructions: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1233 

Thanks a lot!

**Version**
Pmacctd's one: 1.7.8-git [20220225-1 (b68222d9)]
nDPI's one: 3.4-stable (currently pmacctd can't be compiled with nDPI v4.2, which is its current version...maybe it's worthy open another different issue about this but I supose you already are aware of it )

**Comment by paololucente** [comment]
Hi @q2dg ,

On your last point, i did pass a fix so to make pmacct compile against 4.0-stable (which is better than 3.4-stable ;)). Unfortunately wrt 4.2-stable there is something non-trivial not working out, maybe a change to the structure of headers. If you have a moment to give it a try, let me know if compiling against 4.0-stable does bring any benefit to your situation. 

I also invite you to try to play with pmacct config knobs that directly influence nDPI, all the classifier_* ones: https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L3292-L3332

Hope any of this would help.

Paolo

**Comment by q2dg** [comment]
Hello
I don't know if I'll be very helpful...I've tried to compile pmacct with nDPI 4.0 and I've got this error when running make command

![Captura de 2022-03-01 19-30-35](https://user-images.githubusercontent.com/7274874/156228152-b5e32896-00bd-4d97-a22b-fab59b6a26f1.png)

What I've done is this (but I'm just a "parrot" repeating commands seen somewhere...):

*To get nDPI 4.0:

_sudo dnf install make gcc git bison flex libpcap-devel libtool autoconf pkgconfig automake autogen json-c-devel numactl-devel libgcrypt-devel pcre2-devel
git clone  --branch=4.0-stable --depth=1  https://github.com/ntop/nDPI 
cd nDPI
./autogen.sh
./configure --prefix=/usr
make
sudo make install
sudo ldconfig_

*To get pmacct:

_sudo dnf install libpcap-devel pkgconfig libtool autoconf automake make libstdc++-devel gcc-c++ 
git clone https://github.com/pmacct/pmacct
cd pmacct
./autogen.sh
./configure --enable-jansson --enable-ndpi
make_   **<--Here is the error**
_sudo make install_

Sorry for disturbing you. Consider closing this issue if it's not rellevant to pmacct itself, anyway. 
Thanks!

**Comment by paololucente** [comment]
Hi @q2dg ,

I am not sure, i started noticing that from 4.0 it seems it gets installed in /usr/lib instead of /usr/local/lib .. probably now there are two versions of the lib available - one old, one new? But total not sure about it. I can only say that i am managing to compile pmacct against a correctly installed nDPI 4.0 and using the exact same compile switch as you and the pmacct commit 84e24385:

```
$ pmacctd -V
Promiscuous Mode Accounting Daemon, pmacctd 1.7.8-git [20220301-0 (84e24385)]

Arguments:
 '--enable-jansson' '--enable-ndpi' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.8.1
jansson 2.12
nDPI 4.0.0-3212-f98fa675

[..]
```

**Comment by paololucente** [comment]
Cool to know you did manage to compile against nDPI 4.0. Things were mostly working for all plugins except the memory (IMT) one - which is probably exactly the one you were using :-D I've fixed the issue, see commit above. Can you check if things are now working out for you?
