### ISSUE TITLE
Cisco ASA NSEL is_bi_flow behavior 

### ISSUE THREAD

**Issue by ixodis** [pmacct/pmacct#582]
Hello Paolo!

I have some questions about “is_bi_flow” behavior with Cisco ASA NSEL. As I can see it “checks the presence of both initiatorOctets and responderOctets in a flow to infer that it is a bi-directional flow”. 

ASA has several types of ID 233 field:

•	1—Flow created
•	2—Flow deleted
•	3—Flow denied
•	4—Flow alert
•	5—Flow update

Flow records with types 2 and 5 has initiatorOctets and responderOctets so nfacctd marks them as a bi-flow (that’s ok):

 ![2 and 5](https://user-images.githubusercontent.com/67434136/156389861-0416ae10-4b09-4a0d-bf54-05bbb8344be9.png)

But records with ID 233 = 1 or 3 hasn’t initiatorOctets and responderOctets so nfacctd marks them as NOT a bi-flow:

 ![1 and 3](https://user-images.githubusercontent.com/67434136/156389856-790f185d-fa79-4274-ae02-60da22ca5799.png)

I suppose that it wrong behavior because Cisco guide (https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html#bidirectionalflows ) tells us that “The flow records reported by NSEL on the ASAs describe both directions of the flow” so NSEL is bi-flow by default for all types of flows regardless of ID 233 field. 

I think it would be more correct to mark not only flow record but the whole exporter (peer_src_ip) as a bi-flow device if there are initiatorOctets and responderOctets fields in its templates. What do you think about it?

**Comment by paololucente** [comment]
Hi @ixodis ,

I guess - but please correct me if i am wrong - that the flows with initiatorOctets and responderOctets will have the two bytes count saved in the `packets` and `bytes` counters; while the others, who appear not to have any counters, will be treated as events and simply have none of the two counters populated. In other words, there is no explicit classification as bi-flow or event, if not for the different handling of the counters.

What do you see wrong in this behavior and/or how does this behavior impact your work? Just to be sure i catch your point here.

Paolo

**Comment by ixodis** [comment]
The main problem is to determine the direction of traffic in the next step of flow processing (after nfacctd) – which host is the source and which one is the destination. 

Bidirectional flow is characterized by the fact that: “The flow records reported by NSEL on the ASAs describe both directions of the flow. The data records explicitly define the source (initiator) and destination (responder) of the connection, and you can use this information to determine the direction of flow, if required by collector application” (https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html#bidirectionalflows) .

So if we receive NSEL flow record we can be sure that the source host is the initiator of the connection (nevertheless there are some confusing cases with UDP traffic like VoIP when we can’t explicitly define the initiator). We don't need to look at other metrics (tcp & icmp flags, timers, etc) like we do so with unidirectional flows (https://www.plixer.com/blog/netflow-direction-and-its-value-to-troubleshooting ).

NSEL events that have no two counters (initiatorOctets and responderOctets) are also bidirectional flows. These counters are not guaranteed indicators of bi-flow: “In addition, some NSEL records include two byte counter fields, NF_F_FWD_FLOW_DELTA_BYTES and NF_F_REV_FLOW_DELTA_BYTES, which provide direction-specific traffic data.” (Cisco’s guide).

**Comment by paololucente** [comment]
Hi @ixodis ,

> The main problem is to determine the direction of traffic in the next step of flow processing (after nfacctd) – which host is the source and which one is the destination.

Right, i see. So how would you propose to improve the heuristic of the check of `is_bi_flow`? I would need some practical direction that would work for your case. Note that `pre_tag_map` works on a flow-by-flow basis, it can't set context for future flows.

An alternative could be to set the map as `label=bi_flow   ip=X.X.X.X` although you should update the map every time you introduce a new device exporting NSEL - not sure if practical for your situation.

Paolo

**Comment by ixodis** [comment]
Our flow processing scheme is: 

 

Exporter -> Nfacctd -> Apache Flink -> DB

 

All aggregation, math funtions (bytes/packets summarization, etc), direction determination are implemented on Flink.

 

We already tried to set the map as label=bi_flow ip=X.X.X.X and it is not good for us in case of new exporter appearing as you said - we must update the map file manually before new flow records arrives to the nfacctd otherwise it can break the processing logic on Flink

 

The only solution we found is to look at the flow template and find some vendor specific fields there:

 

                NF_F_FW_EXT_EVENT - 33002

                NF_F_FWD_FLOW_DELTA_BYTES - 231

                NF_F_REV_FLOW_DELTA_BYTES - 232

                NF_F_INGRESS_ACL_ID - 33000

                NF_F_EGRESS_ACL_ID - 33001

                NF_F_FW_EXT_EVENT - 33002

                NF_F_USERNAME - 40000

               

If we found these fields we can mark that exporter as bi-flow (NSEL) device. The similar logic is implemented in Nfdump: https://github.com/phaag/nfdump#cisco-asa-nsel-extension---network-security-event-logging__

 

Is it possible to make such functionality in nfacctd? It will be great if the set of fields could be defined by user (not hardcoded) because they may vary depending on the exporter or its firmware version.

 

Btw can nfacctd write templates to Kafka?

**Comment by paololucente** [comment]
Hi @ixodis ,

I did implement `is_nsel` in pre_tag_map as a true/false. true matches NSEL, false matches non-NSEL packets. Just in case you have a stream with different kind of data and you want to tag them differently and split onto different plugins. I don't have data to test with, i just got inspiration from `is_bi_flow` code - can you give it a try? Should it not work, can you please send me a brief trace with some NSEL data via unicast email? The heuristic i implemented is very basic - checking whether firewallEvent (233) field is there or not, i am open to input in case this is too simplistic.

One question, i see in the output you sent above that there is also some Post NAT fields. Are they decoded fine? Or they are not of interest to you? If they are decoded fine then i guess there must be also a natEvent (230) field?

Paolo

**Comment by ixodis** [comment]
Hi Paolo!

firewallEvent (233) field is not good indicator of bi-flow because Palo Alto firewalls use this field too:  https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-admin/monitoring/netflow-monitoring/netflow-templates.html .  It’s not NSEL but unidirectional Netflow v9

I am not yet ready to say how well the NAT event is detected, I will send you tcpdumps of Cisco ASA NSEL with NAT via email

**Comment by paololucente** [comment]
Hi @ixodis ,

To clarify: `is_bi_flow` remained untouched, it is working as before. I added a `is_nsel` which bases on the presence of firewallEvent (233). One could set one, the other or both in any combination of true/false to match what is being looked for. 

Paolo

**Comment by paololucente** [comment]
Hi @ixodis ,

Thank you also for the traces. I profited on them to properly implement `fw_event` (which before was oddly muxed onto `nat_event` and, although probably both won't appear in the same NetFlow message, it's good to keep them separate) and verify that NAT'd fields are decoded properly. 

Paolo
