### ISSUE TITLE
pcap sampling_rate incorrectly set in export

### ISSUE THREAD

**Issue by rodecker** [pmacct/pmacct#585]
**Description**

When configuring `samping_rate` this value is used for the number of packets to sample, but the reported sampling rate is always set to 1.

My `pmacctd.conf` contains:
> daemonize: false
> pre_tag_map: /etc/pmacct/pretag.map
> networks_file: /etc/pmacct/networks.lst
> networks_file_no_lpm: true
> !
> aggregate: label, sampling_rate, in_iface, out_iface, src_mac, dst_mac, src_as, dst_as, src_net, dst_net, src_host, dst_host, etype, src_port, dst_port, proto, tcpflags
!
> pcap_ifindex: map
> pcap_interfaces_map: /etc/pmacct/iface.map
> sampling_rate: 10
> pmacctd_as: longest
> pmacctd_net: longest
> !
> plugins: kafka
> kafka_broker_host: 10.0.0.1
> kafka_output: json
> kafka_refresh_time: 30
> kafka_history: 5m
> kafka_history_roundoff: m
> kafka_max_writers: 1

I start a flow of one ping per second and see the following export to kafka:

> "sampling_rate": 1
> "packets": 3

The number of sampled packets is as expected (1 in 10 over a 30 second period = 3 packets), but I would expect the  sampling_rate to be set to 10 (or 0, if exporting this value is not supported with pcap sampling).

**Version**
> Promiscuous Mode Accounting Daemon, pmacctd 1.7.8-git [20220303-0 (d1e03eb)]
> 
> Arguments:
 > '--enable-jansson' '--enable-kafka' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
> 
> Libs:
> cdada 0.3.5
> libpcap version 1.5.3
> rdkafka 0.11.4
> jansson 2.13
> 
> Plugins:
> memory
> print
> nfprobe
> sfprobe
> tee
> kafka
> 
> System:
> Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64
> 
> Compiler:
> gcc 4.8.5

**Appreciation**
\o/

**Comment by paololucente** [comment]
Hi Martin ( @rodecker ),

Thanks very much for reporting this issue. I should have just fixed it with the commit above. Can you give it a try if this is working for you?

Paolo

**Comment by rodecker** [comment]
Hi @paololucente,

For the same test (a flow of 1 ping per second over a 30 second period) the sampling rate is now set correctly:

> "sampling_rate": 10
> "packets": 3

Thanks for this!

But there seems to be another, related issue. When I add `pmacctd_renormalize: true` to the config I get:

> "sampling_rate": 1
> "packets": 3

So in this case `sampling_rate` is correctly set back to 1, but `packets` (and `bytes`) are not adjusted accordingly.

Cheers,
Martin

**Comment by paololucente** [comment]
Hi Martin ( @rodecker ),

Thanks again, you are indeed right. I passed another patch (see above) to address this issue. Let me know if this now works for you.

Paolo

**Comment by rodecker** [comment]
Hi @paololucente ,

I can confirm it works ok now 👍 

Cheers,
Martin

**Comment by paololucente** [comment]
Wonderfulness, thanks for confirming! I'll close this issue then. Paolo
