### ISSUE TITLE
Is it possible to run nfacctd tee plugin as non-root using capabilities? 

### ISSUE THREAD

**Issue by tomadeb** [pmacct/pmacct#589]
I'm trying to run nfacctd with transparent tee plugin and was wandering if it is possible to use capabilities instead of running as root.

So far, my testing, involving ambient capabilities via the systemd unit file, has been inconclusive.

Is it possible at all or should I give up :) ? 

Thanks in advance

**Comment by paololucente** [comment]
Hi @tomadeb ,

I did make tee plugin honor the nfacctd_nonroot directive (copied from existing pmacctd_nonroot) so to bypass the UID check. Plus i have updated docs, in fact a `setcap 'cap_net_raw=+ep' /path/to/nfacctd` did work for me to see nfacctd running successfully the tee plugin in transparent mode as non root. Let me know if you manage to give it a try and see it working for you.

Paolo
