### ISSUE TITLE
uacctd docker image couldn't start

### ISSUE THREAD

**Issue by zzgundam** [pmacct/pmacct#592]
uacctd docker image couldn't start.After started it just shown this message below and exit.I ran it with Privileged option.
`uacctd: error while loading shared libraries: libnetfilter_log.so.1: cannot open shared object file: No such file or directory`

How can I solve this problem?

**Comment by paololucente** [comment]
Hi @zzgundam ,

Unfortunately libnetfilter_log was dropped out of CentOS 8 official distribution and picked up by a 3rd party archive. You have two main options: use the Debian container or self-compile pmacct yourself on your CentOS.

Paolo

**Comment by msune** [comment]
>Unfortunately libnetfilter_log was dropped out of CentOS 8 official distribution and picked up by a 3rd party archive. You have two main options: use the Debian container or self-compile pmacct yourself on your CentOS.


Just to be sure, @zzgundam, are not talking about the dockerhub images but some self-generated docker image, correct?
