### ISSUE TITLE
unable to configure/compile with MySQL support on FreeBSD

### ISSUE THREAD

**Issue by freecris** [pmacct/pmacct#594]
Hi,

when I try to install pmacct from FreeBSD (13.x, 12.x) ports with MySQL support, I got a configure error:

```
checking whether to enable MySQL support... yes
checking for mysql_config... mysql_config
checking if MySQL version is >= 5.6.3... yes
checking for mysql_query in -lmysqlclient... yes
checking mysql.h usability... yes
checking mysql.h presence... no
configure: WARNING: mysql.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: mysql.h: proceeding with the compiler's result
checking for mysql.h... yes
checking mysql/mysql.h usability... yes
checking mysql/mysql.h presence... yes
checking for mysql/mysql.h... yes
checking for numa_bind in -lnuma... no
configure: error:
      ERROR: missing libnuma. Requirement for building MySQL.

```
pmacct version: 1.7.7
FreeBSD version: 12.3 or 13.0

Thank you

**Comment by paololucente** [comment]
Hi @freecris ,

As the message says you should get libnuma installed on your system. I am no expert of FreeBSD but i bet there are packages for it, like for most Linux distributions.

Paolo

**Comment by freecris** [comment]
Hi Paolo,

thanks for your reply.
I think we got a problem, there are no packages for libnuma for FreeBSD.
Maybe because of
"Description
The libnuma library offers a simple programming interface to the NUMA
(Non Uniform Memory Access) policy supported by the Linux kernel"

Do you think is this really necessary?

**Comment by freecris** [comment]
where can i send you your credentials?

**Comment by paololucente** [comment]
The specific problem mentioned in this Issue was resolved, hence closing up.
