### ISSUE TITLE
-c class pmacct's argument doesn't select desired flows (using memory plugin at least)

### ISSUE THREAD

**Issue by q2dg** [pmacct/pmacct#596]
**Description**
I've successfully compiled pmacct with last branch's nDPI support and when I do _pmacct -s_ flows are correctly classified. For instance, SSH traffic is seen as "unknown/SSH" below "Class" column (I don't know yet the meaning of "unknown" word but that's not the point)

BUT

When I do _pmacct -M SSH -c class_ (in order to see just the SSH traffic), there's no flow shown. I've tried _pmacct -M ssh -c class_, too, with same result. However, if I try _pmacct -M unknown/SSH -c class_ (or _pmacct -M unknown/ssh -c class_) I get the error "Server has not loaded any classifier for "unknown/SSH"", so I infer the value "SSH" (or "ssh") is a valid one for the -M argument, but it doesn't do its job. The most strange is when I try _pmacct -M unknown -c class_ because doing this all flows are shown, just like when doing _pmacct -s_

Thanks!

**Version**
pmacct IMT plugin client, pmacct 1.7.8-git (20220409-3 (d09284b0))
 '--enable-jansson' '--enable-ndpi' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

**Comment by paololucente** [comment]
Hi @q2dg ,

The issue should be addressed with the commits above. I start `pmacctd` then do, say, `pmacct -M ssh -c class` and now see results returning back.

Paolo

**Comment by q2dg** [comment]
Yes, I can confirm it is addressed!! Thanks a lot!!
I'll close the issue, thus. Thanks!
