### ISSUE TITLE
timestamp_start, timestamp_end, timestamp_arrival, timestamp_export not working

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#598]
Hi @paololucente 

Thanks for the wonderful tool,

**We try to capture the timestamp data by using PMACCT but it isn't working** 

We used the below configuration to generate the CSV file but the CSV file was not generated. If i removed timestamp_start, timestamp_end, timestamp_arrival, timestamp_export this fields, then CSV file was generated.

daemonize: false
nfacctd_port: 9997
nfacctd_time_new: true

plugins: print
timestamps_secs: true
aggregate: peer_src_ip, src_host, dst_host, proto, tos,src_port,dst_port, tcpflags, timestamp_start, timestamp_end, timestamp_arrival, timestamp_export

print_output:csv
print_output_file:/etc/pmacct/pmacct_9997_old/%Y%m%d%H%M.csv
print_history_roundoff:m
print_refresh_time:2

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191013-00)

Arguments:
 '--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
rabbimq-c 0.8.0
jansson 2.11

System:
Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64

Compiler:
gcc 7.4.0

**Comment by paololucente** [comment]
Hi @AnanthGopal ,

I tested your above config with pmacct 1.7.7 (latest stable) and master code here on GitHub - in both cases successfully. I see you are running an almost 3 years old release and would encourage you to upgrade to something more recent.

Paolo

**Comment by AnanthGopal** [comment]
Thank you @paololucente 

We updated the **PMACCT** version 1.7.7 but TIMESTAMP_START,TIMESTAMP_END,TIMESTAMP_EXPORT don't provide a correct date. 
below the image I highlighted those values, how can I resolve this issue

![image](https://user-images.githubusercontent.com/13050426/164476052-3ab276a9-3280-4479-af2d-4ae66fc54628.png)

**Comment by paololucente** [comment]
What kind of flows are you exporting? Is it NetFlow v5? Or is it something more modern like NetFlow v9 / IPFIX? If it's v5, you may try to play with the `nfacctd_time_secs` (by default false, you could try to set it to true). If not, and if you are sure the time is set up correctly on the router (those wrong times are all read from NetFlow packets), then please send me a capture of your flows via unicast email.

Paolo

**Comment by AnanthGopal** [comment]
okay thank you @paololucente
