### ISSUE TITLE
How to use filter in the pre_tag_map file

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#599]
Hi,
I'd like to be able to add a label to flows depending on which port they are coming in on. Is that possible?
Sflow data is coming into my host on port 9998 and netflow is coming in on port 9999.
I'm have nfacctd and sfacctd processes, hoping to use just one pre_tag_map file.
I tried this pre_tag_map file:
```
set_label=sfacct--Sflow#Sensor    filter='port 9998'
set_label=nfacct--Netflow#Sensor  filter='port 9999'
```
but no labels were added.
Are the filters looking at the src and dst ports of the flows themselves? Is there a syntax error? 

Thanks

**Version**
$ nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.7-git [RELEASE]

Arguments:
 '--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.5.3
rabbimq-c 0.8.0
jansson 2.10

Plugins:
memory
print
nfprobe
sfprobe
tee
amqp

System:
Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64

Compiler:
gcc 4.8.5

**Comment by paololucente** [comment]
Hi Lisa,

Yes, to confirm it is like you say `the filters [are] looking at the src and dst ports of the flows themselves`.

What i could do for you on the wave of the recent `is_nel` and `is_nsel` keys, is to add a couple extra keys a-la `is_sflow` and `is_netflow` (probably i will use slightly different names, maybe even the daemon name instead of the protocol name) that would perform easy checks: if, say, `is_sflow` is invoked by sfacctd return true (match!) else return false, and similarly for `is_netflow`. Would that work for you? Should i find you positive, I can have this done pretty quickly, maybe even this week.

Paolo

**Comment by paololucente** [comment]
Hi Lisa,

Another thing that could help & that would require zero work and be even finer grained than the approach i was suggesting above: i see that you are compiling pmacct with rabbitmq-c support, probably you are exporting JSONs to a RabbitMQ broker. Consider that every message gets a `writer_id` giving few info about the specific collector and plugin making the write. Among these info there is the daemon name that you can set via `core_proc_name`. Say you call your daemon `nfacctd_9999`, that would be included as part of the writer_id. 

Paolo

**Comment by lisaens** [comment]
Thanks for the suggestions.
The first one wouldn't really work for us since, in production, we'll have more than 1 sflow and more than 1 netflow. 
The second idea is intriguing. So in the *facctd.conf files, we'd set core_proc_name to something that identifies the flows (port number or other string), then do we add writer_id to the aggregation list so it gets added to the output or will it just be there?  The field will only be there when we write to a rabbit queue (not when writing to csv files)?  In the logstash pipeline that reads the info from the rabbit queue, we can parse the writer_id to get the label we want, so that could get rid of the need for pre_tag_map files.

**Comment by paololucente** [comment]
Exactly, all you said. The `writer_id` is already added by default so you just set the `core_proc_name` and you are in pole position. You are right, this is for Kafka and RabbitMQ but not CSV files, rationale being: when you pick up stuff from a broker, things are mixed up; when you pick up a CSV file, you know a-priori which collector did write it, you could embed the info even in the filename.
