### ISSUE TITLE
Broken SQL reference schemas

### ISSUE THREAD

**Issue by Logan2211** [pmacct/pmacct#60]
The reference schemas on 1.6 appear to be broken. I was seeing the following on 1.6 with a version 9 table config:
```nfacctd[2966]: ERROR ( sir/mysql ): Unknown column 'net_dst' in 'where clause'```

So after a little digging, I've turned off `tmp_net_own_field`, and now it is failing with:
```ERROR ( sir/mysql ): Unknown column 'mask_dst' in 'where clause'```

It seems like the expected schema changed in 1.6 but the reference schemas were never updated.

Additionally, from an operator standpoint it would be helpful if the reference schemas were idempotent. ie.
```
create database if not exists pmacct;
use pmacct;

create table if not exists acct_v9 (
```
(no drop database/table statements)

**Comment by Logan2211** [comment]
Followup: I see the `README.mask` document now, so I understand that it is expected that the operator will create the mask_* columns manually when needed. imo, they should be part of the reference schemas defaulted to NULL so maybe that change could be considered.

**Comment by paololucente** [comment]
You see, this would lead to create a new schema, say, v10. Changing an existing schema version would kill the purpose of versioning; roughly ten years ago, SQL tables versioning wanted to be a quick start for network engineers not really familiar with RDBMS - to avoid them crafting SQL schemas. Nowadays on one hand the existing schemas already cover the very basics, on the other the landscape changed a bit: overall i feel there is no need to roll out new default schemas.
