### ISSUE TITLE
is it possible to remove the delicate data's within the particular elapse time by using aggregate filter?

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#600]
Hi @paololucente 

Thanks for the wonderful tool, 

**Description**

Considering we received the data from a different host if we received the same flow data within a few seconds, we consider that flow data is delicate, We don't need those data.

**For example:**
We received the below data from PMACCT
src_ip      dstip     port  protocol  timestamp
1.1.1.1     1.1.1.1   2       tcp          2022-04-19 09:01:31
1.1.1.1     1.1.1.1   2       tcp          2022-04-19 09:02:00 

The Timestamp of the first data is  2022-04-19 09:01:31 and the second data is 2022-04-19 09:02:00
The timestamp difference is 30seconds, so we consider this data to be delicate data we don't need those data. 

is it possible to achieve the above scoria by using an aggregate filter?

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191013-00)

Arguments:
'--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.8.1
rabbimq-c 0.8.0
jansson 2.11

System:
Linux 4.18.0-305.12.1.el8_4.x86_64 https://github.com/pmacct/pmacct/pull/1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64

Compiler:
GCC 7.4.0

**Comment by paololucente** [comment]
Hi @AnanthGopal ,

It seems you are asking the same as per this Issue https://github.com/pmacct/pmacct/issues/342 , would you say so? If positive then, no, this is not possible yet and should be done still as part of the data post-processing. 

Paolo

**Comment by ebgp** [comment]
I believe the original poster means 'duplicate' data, not 'delicate' data? ( Thus not relevant for issue #342 )
