### ISSUE TITLE
Using environment variables in configs

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#601]
Sorry for so many questions, but I have another... about using environment variables in nfacctd and sfacctd config files. 

I made a systemd unit file including
```
[Service]
# Environment variables for nfacctd.conf
Environment=PORT=9998
Environment=PRE_TAG_MAP=/etc/pmacct/pretag.map
Environment=QUEUE_KEY=nf_queue
ExecStart=/usr/local/sbin/nfacctd -f /etc/pmacct/nfacctd.conf
```
and an nfacctd.conf file including these lines referring to the env values, with defaults defined as well:
```
nfacctd_port: ${PORT:9999}
pre_tag_map: ${PRE_TAG_MAP:/etc/pmacct/pretag.map}
amqp_routing_key: ${QUEUE_KEY:deidentifier_raw}
```
When I start the nfacctd service, it fails.
Log lines:
```
 WARN: [/etc/pmacct/nfacctd.conf:8] Invalid value. Ignored.         (line 8 is the nfacctd_port line)
 INFO ( default/core ): Start logging ...
 INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.7-git (RELEASE)
 INFO ( default/core ):  '--enable-rabbitmq' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
 INFO ( default/core ): Reading configuration file '/etc/pmacct/nfacctd.conf'.
 INFO ( default/core ): [PRE_TAG_MAP] (re)loading map.
 WARN ( default/core ): [PRE_TAG_MAP] file not found.
nfacctd.service: main process exited, code=exited, status=1/FAILURE
Unit nfacctd.service entered failed state.
nfacctd.service failed.
```
This would be really useful for our situation where we will have many flow exporters sending to different ports on one host. With the above setup, we'd have to create a new systemd file with different environment variables for each flow exporter, but we'd need only one sfacctd.conf file and one nfacctd.conf file. (And hopefully one pre_tag_map file - see the other question/issue I submitted.)

**Comment by paololucente** [comment]
Hi Lisa,

I total see your point, total makes sense. From a dev perspective, though, it is not a low hanging fruit: ie. how deep you go? Do you allow variable expansion in bulk or only for certain directives for which it does make sense to? Tied do this, it is easy in a C program to look for known environment variables but non-trivial it is to reckon the user injected a variable there - in doing that, what shells would you support? Which jargons of which shells?

I am thinking we have two main ways to go here:

1) you resolve this in a sort of config pre-processor, a shell script, something you give your config template and outputs the real config that pmacct should read; would you be able to write such a pre-processor - even limited to your scope - and contribute it back to the community, that would be awesome;

2) attempt to expand env variables in a C program (pmacct) but, as i was saying above, this will likely be a limited exercise where we will convert the problem space into: support env variable X for config knob Y using shell Z, ie. you can't call the variable Q or use shell W. If going this way, i will leave the issue open and label it as an enhancement.

Let me know which way looks more intriguing to you.

Paolo

**Comment by msune** [comment]
@lisaens you could use `ExecStartPre` of `systemd` to do that [1]. Something like this:

```
[Service]
# Environment variables for nfacctd.conf
Environment=PORT=9998
Environment=PRE_TAG_MAP=/etc/pmacct/pretag.map
Environment=QUEUE_KEY=nf_queue
ExecStartPre=envsubst < /etc/pmacct/nfacctd.conf.template > /etc/pmacct/nfacctd.conf
ExecStart=/usr/local/sbin/nfacctd -f /etc/pmacct/nfacctd.conf
```

where `nfacctd.conf.template` is what you pasted, with the env. variables, will _probably_ work. Mind, it's just a hint, I didn't test it.

[1]
```
ExecStartPre=, ExecStartPost=
Additional commands that are executed before or after the command in ExecStart=, respectively. Syntax is the same as for ExecStart=, except that multiple command lines are allowed and the commands are executed one after the other, serially.

If any of those commands (not prefixed with "-") fail, the rest are not executed and the unit is considered failed.

ExecStart= commands are only run after all ExecStartPre= commands that were not prefixed with a "-" exit successfully.

ExecStartPost= commands are only run after the commands specified in ExecStart= have been invoked successfully, as determined by Type= (i.e. the process has been started for Type=simple or Type=idle, the last ExecStart= process exited successfully for Type=oneshot, the initial process exited successfully for Type=forking, "READY=1" is sent for Type=notify, or the BusName= has been taken for Type=dbus).

Note that ExecStartPre= may not be used to start long-running processes. All processes forked off by processes invoked via ExecStartPre= will be killed before the next service process is run.

Note that if any of the commands specified in ExecStartPre=, ExecStart=, or ExecStartPost= fail (and are not prefixed with "-", see above) or time out before the service is fully up, execution continues with commands specified in ExecStopPost=, the commands in ExecStop= are skipped.

Note that the execution of ExecStartPost= is taken into account for the purpose of Before=/After= ordering constraints.
```
