### ISSUE TITLE
Some src_net and dst_net aggregated to 0.0.0.0 (BGP)

### ISSUE THREAD

**Issue by charlyforot** [pmacct/pmacct#603]
Hello Paulo.

**Description**
Sometime sfacctd aggregate src_net or dst_net to 0.0.0.0 whereas it correctly found the src_as, dst_as, peer_src_ip, peer_dst_ip.
It represents 17% of my data each minute.

Example :
`
{"event_type": "purge", "mac_src": OK, "mac_dst": OK, "etype": "800", "as_src": 64510, "as_dst": 64513, "as_path": "64513", "local_pref": 100, "med": 0, "peer_ip_src": OK, "peer_ip_dst": OK, "iface_in": OK, "iface_out": OK, "ip_src": OK, "net_src": "0.0.0.0", "ip_dst":OK, "net_dst": OK, "mask_src": 0, "mask_dst": 18, "port_src": OK, "port_dst": OK, "tcp_flags": "16", "ip_proto": "tcp", "tos": 0, "flows": 1, "packets": 160, "bytes": 21728, "writer_id": "default_kafka/20459"}`

I tried:

- dump the BGP table and this one is correct, no lack of information.
- use the memory plugin instead of kafka, it's the same problem.
- map sfacctd_as and sfacctd_net to "longest", it's the same problem.

Configuration :
```
sfacctd_ip: <my_ip>
sfacctd_as: bgp
sfacctd_net: bgp
sfacctd_renormalize: true

logfile : /var/log/sfacctd.log

bgp_daemon: true
bgp_daemon_ip: <my_ip>
bgp_daemon_max_peers: 3

plugins: kafka
kafka_output: json
kafka_topic: pmacct.acct
kafka_broker_host: pmastic
kafka_refresh_time: 60
kafka_history: 1m
kafka_history_roundoff: m

aggregate: src_as, dst_as, etype, src_host, dst_host, src_net, dst_net, src_mask, dst_mask, src_port, dst_port, src_mac, dst_mac, proto, in_iface, out_iface, peer_dst_ip, peer_src_ip, tcpflags, flows, tos, local_pref, med, as_path
```

**Version**
```
2022-04-27T09:41:07+02:00 INFO ( default/core ): sFlow Accounting Daemon, sfacctd 1.7.7-git (RELEASE)
2022-04-27T09:41:07+02:00 INFO ( default/core ):  '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
```

Thnak you for your help !

**Comment by paololucente** [comment]
Hi Charly ( @charlyforot ),

Thanks for getting in touch about this. It is indeed intriguing how, in your example above, resolution is all set to `bgp` yet src_as is populated whereas `net_src` and `mask_src` are both zeroed out - as you described. May i ask for a quick test with GitHub master code (instead of 1.7.7 release) to confirm this is still happening?

Paolo

**Comment by charlyforot** [comment]
I just test with the current master branch, I confirm this is the same problem.

To add more details, I receive sflow packets from 3 routers and i have an iBGP session with these routers thaks to the pmacct bgp daemon.
I can add that i found some identical prefixes in the dump of bgp table but with a different next hop because of the iBGP session with each router. Can it be a problem ?

**Comment by paololucente** [comment]
> I just test with the current master branch, I confirm this is the same problem.
Ack!

> To add more details, I receive sflow packets from 3 routers and i have an iBGP session with these routers thaks to the pmacct bgp daemon. I can add that i found some identical prefixes in the dump of bgp table but with a different next hop because of the iBGP session with each router. Can it be a problem ?

No, what will happen is that flows from each router will be correlated to the iBGP session of that router, reflecting the fact that traffic for the same prefix is headed to different BGP next-hops depending on the router. Can you somehow find a correlation among the issues? For example: all instances are related to one single router or related to the same prefix(es), etc.? Or is it total random?

Also is this all happening at steady state, right? I mean: when you start sfacctd, flows are already coming in continuously; otoh the BGP RIB is yet to be formed and - depending on retry timeouts and amount of data - it may take even some minutes in order for all data to be there. Just to make sure this is not related to that startup period of time.

**Comment by charlyforot** [comment]
I confirm that appear at any moment, I let pmacct running during 24h and there is no improvement. To be sure, I dumped the BGP table at a specific instant and I looked in the data to see if each prefix was present. And it was the case.

I'm going to find a correlation.

**Comment by charlyforot** [comment]
Something interresting : all ASN and net not aggregated are marked as "origin" : "i" in the bgp table, whereas all ASN and net aggregated are marked as "origin" : "u" ?

**Comment by charlyforot** [comment]
Something interesting, all ASN and net not aggregated are marked as "origin: "i" in the dump of bgp table

**Comment by charlyforot** [comment]
I can't find some correlation, it's random.

**Comment by paololucente** [comment]
Thank you so much for your thorough analysis! I think we have nailed the cause (these default routes), let's now try to allow me to reproduce the issue. Can you paste the default routes in a message here?

**Comment by charlyforot** [comment]
I have removed the announcement of these default routes and it's the same problem.
I have tested to have just one BGP session with on router and collect only sflow packets from this one, and it's again the same problem, I really don't know why because I checked all IP addresses and there are matching a prefix in the dump of the bgp table.

**Comment by charlyforot** [comment]
There is a example of my dump ( I voluntary hide IPs and ASN)
`{"timestamp": "2022-04-27 10:08:00", "peer_ip_src": "OK", "peer_tcp_port": 55905, "event_type": "dump_init", "dump_period": 120, "seq": 1}
{"seq": 1, "timestamp": "2022-04-27 10:08:00", "peer_ip_src": "OK", "peer_tcp_port": 55905, "event_type": "dump", "afi": 1, "safi": 1, "ip_prefix": "OK", "bgp_nexthop": "OK", "as_path": "1234 1235 1236", "comms": "123:1234 456:4567", "origin": "i", "local_pref": 150, "med": 0}
{"seq": 1, "timestamp": "2022-04-27 10:08:00", "peer_ip_src": "OK", "peer_tcp_port": 55905, "event_type": "dump", "afi": 1, "safi": 1, "ip_prefix": "OK", "bgp_nexthop": "OK", "as_path": "1234 1235 1236", "comms": "123:1234 456:4567", "origin": "i", "local_pref": 150, "med": 0}
`

**Comment by paololucente** [comment]
Hi @charlyforot ,

Would it be possible for me to have a look at the issue on your box? Unfortunately nothing comes to mind as to what may be causing the problem with the info collected so far: tour config is right and pretty basic, BGP announcements are basic too (ie. no signs of complications like VPNs, ADD-PATH, etc.) plus the fact that some BGP data is populated correctly while the network data is not is really puzzling. If this is a possibility, let's continue the conversation via unicast email.

Paolo

**Comment by charlyforot** [comment]
Thanks @paololucente for the help. You are right.

The solution for people who has the same problem is to check that your bgp daemon on routers have the correct configuration with pmacct bgp daemon. In particular, **be sure to have configured pmacct as route reflector client on the routers**.
If not, pmacct will receive only partial bgp tables and will no aggregate some prefixes.
