### ISSUE TITLE
 string attributes with variable length are not persisted

### ISSUE THREAD

**Issue by jukrut** [pmacct/pmacct#604]
**Description**

custom_primitives.conf
```
name=interfaceName          field_type=82   len=vlen    semantics=str
name=egressVRFID            field_type=235  len=4     semantics=u_int
name=ingressVRFID            field_type=234  len=4     semantics=u_int
name=vrfname                field_type=236  len=8    semantics=str
name=observationDomainName  field_type=300  len=8    semantics=str
```
db.schema.sql
```
create table %Y_%m_%d (
    id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
    ip_dst CHAR(45) NOT NULL,
    packets BIGINT    UNSIGNED  NOT NULL,
    bytes BIGINT      UNSIGNED  NOT NULL,
    stamp_inserted          DATETIME,
    stamp_updated           DATETIME,
    interfaceName           VARCHAR(16),
    egressVRFID             INT         UNSIGNED,
    ingressVRFID             INT         UNSIGNED,
    VRFname                 VARCHAR(16),
    observationDomainName   VARCHAR(16),
    PRIMARY KEY (id)
);
```
nfacct.conf
```
debug: true

! IP address to listen for flow data
nfacctd_ip: 0.0.0.0

! port to listen for flow data
nfacctd_port: 4739

aggregate_primitives: /etc/config/primitives.conf

nfacctd_time_new: true
aggregate[destination]: dst_host, egressVRFID, ingressVRFID, vrfname, observationDomainName,interfaceName

plugins: mysql[destination]

! SQL connection settings
sql_host[destination]: db
sql_user[destination]: ipfix
sql_passwd[destination]: ipfix
sql_db[destination]: ipfix

sql_optimize_clauses[destination]: true
sql_table[destination]: %Y_%m_%d
sql_table_schema[destination]: /etc/config/destination_schema.sql
sql_refresh_time[destination]: 5
sql_history[destination]: 1d
```
[pmacct.zip](https://github.com/pmacct/pmacct/files/8631210/pmacct.zip)

it logs
```
DEBUG ( destination/mysql ): INSERT INTO `2022_05_05` (stamp_updated, stamp_inserted, ip_dst, egressvrfid, ingressvrfid, vrfname, observationdomainname, interfacename, packets, bytes) VALUES (FROM_UNIXTIME(1651753616), FROM_UNIXTIME(1651708800), '192.168.178.100', 1, 2, 'v234567', 'o234567', '', 11236, 12521)
```

if I configure the primitives like
```
name=interfaceName          field_type=82   len=9    semantics=str
name=egressVRFID            field_type=235  len=4     semantics=u_int
name=ingressVRFID            field_type=234  len=4     semantics=u_int
name=vrfname                field_type=236  len=8    semantics=str
name=observationDomainName  field_type=300  len=8    semantics=str

```
it is persisted as `"i2345678"`
```
DEBUG ( destination/mysql ): INSERT INTO `2022_05_05` (stamp_updated, stamp_inserted, ip_dst, egressvrfid, ingressvrfid, vrfname, observationdomainname, interfacename, packets, bytes) VALUES (FROM_UNIXTIME(1651754171), FROM_UNIXTIME(1651708800), '192.168.178.100', 1, 2, 'v234567', 'o234567', 'i2345678', 75098, 80615)
```

the strings are null terminated.

I ran with the latest docker image
****
**Version**

compiled latetest master

+

NetFlow Accounting Daemon, nfacctd 1.7.7-git [20211107-0 (ef37a415)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.8.1
MariaDB 10.3.31
PostgreSQL 110013
sqlite3 3.27.2
rabbimq-c 0.11.0
rdkafka 1.8.2
jansson 2.14
MaxmindDB 1.6.0
ZeroMQ 4.3.2
Redis 1.0.3
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.4.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64

Compiler:
gcc 8.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi Jurgen ( @jukrut ),

How is field_type / IE 82 defined in your NetFlow v9/IPFIX template? Is it defined as variable-length or does it have a fixed length? If the former then we may be hitting a bug of some form; if the latter then you can't define it variable-length in pmacct, as pmacct would be missing indication of the actual length from the protocol (this looks compatible with the behavior that you are getting), probably to be explained better in the docs? Let me know.

Paolo

**Comment by jukrut** [comment]
Hi Paolo,

up to my judgement seems like a bug.

I did attach a pcap as zip archive to the ticket.
![image](https://user-images.githubusercontent.com/56029738/167077739-875fa731-3f35-483f-b643-f19e7d05599c.png)
can you access it, otherwise I can also send you the pcap via mail, as you mentioned in the other issues.

![image](https://user-images.githubusercontent.com/56029738/167077307-5b28740d-1437-4829-a095-580c4fb94a82.png)

^ screenshot from wireshark.

![image](https://user-images.githubusercontent.com/56029738/167077373-4c6f4a25-8ed8-4150-8bd5-c2e13d4ba2cf.png)
^value

![image](https://user-images.githubusercontent.com/56029738/167077400-6b3c9399-2282-405f-a7db-507ca22cc9aa.png)
^ before the value the length

```
[A.5](https://www.rfc-editor.org/rfc/rfc5101#appendix-A.5).  Variable-Length Information Element Examples

[A.5.1](https://www.rfc-editor.org/rfc/rfc5101#appendix-A.5.1).  Example of Variable-Length Information Element with Length
        Inferior to 255 Octets

>    0                   1                   2                   3
>    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
>   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
>   |       5       |          5 octet Information Element          |
>   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
>   |                               |
>   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 
looks fine acording to rfc5101.

I don't wont to be a wiseass and point to a spec, I just gather infos as I am a really new to this protocol :)

thx for your support

Jürgen

**Comment by paololucente** [comment]
Hi Jurgen,

Oh fantastic, it is a variable-length defined variable & i definitely missed the capture in your previous message. Let me review and come back to you.

Paolo

**Comment by jukrut** [comment]
I could have wrote a sentence like:

And a uploaded the pcaps: "file.zip" :)

it looked more obvious in markdown source code then the rendered variant

**Comment by paololucente** [comment]
Hi Jurgen, 

> it looked more obvious in markdown source code then the rendered variant
Exactly, yet apologies for having missed it.

The issue should be resolved now with https://github.com/pmacct/pmacct/commit/976c26b18bc8c958cfe3470654fab55d1f992488 . It does test fine against your trace. Can you give it a try and confirm you are happy?

Paolo

**Comment by jukrut** [comment]
Hi Paolo!

just compiled it and tested main branch and it works!!

thank you very much for the quick fix!

For usage in production a release would be perfect, do you plan to release current master soon?

```
DEBUG ( destination/mysql ): INSERT INTO `2022_05_12` (stamp_updated, stamp_inserted, ip_dst, egressvrfid, ingressvrfid, vrfname, observationdomainname, interfacename, packets, bytes) VALUES (FROM_UNIXTIME(1652339276), FROM_UNIXTIME(1652306400), '192.168.178.100', 1, 2, 'v234567', 'o234567', 'i23456', 212419, 212977)
```

**Comment by paololucente** [comment]
Hi Jurgen,

Perfect, great to read & thanks for the swift confirmation!

The patch will be included in the next release, yes, but that is expected in about a couple of months for now. You can totally use the patch against 1.7.7, like you did.

I will go ahead and close this issue.

Paolo

**Comment by jukrut** [comment]
Hi Paolo,
I just have a question regarding something related.
https://github.com/pmacct/pmacct/blob/master/examples/primitives.lst.example#L52
I tested without \x00 terminated strings and it works.

Is this just luck, or don't vlen strings have not to be null terminated?

**Comment by paololucente** [comment]
It is no luck, in fact not trusting whether the string has null termination (in fact, not carrying it in NetFlow / IPFIX has proofed over time to be a pretty standard behavior), one more byte is reserved and zeroed upfront (serving as terminating zero). See here: https://github.com/pmacct/pmacct/blob/master/src/pkt_handlers.c#L3414-L3415 . I will relax the statement in the docs. 

Paolo
