### ISSUE TITLE
Tags and Releases?

### ISSUE THREAD

**Issue by lisaens** [pmacct/pmacct#608]
Quick question...
Do you regularly tag releases? The last tag listed in github is 1.7.7 from 11/8/21, but it seems like a lot has happened since then. We are just starting to transition to using pmacct, so should we build it from master? And then should we rebuild from master every so often or wait for a new tag? 
What about any docker images?

Thanks

**Comment by paololucente** [comment]
Hi Lisa ( @lisaens ), yes, there is a degree of trying to be diligent with both tags & releases.

Tags are always timely, forking off the release code to its own branch in case some hot fixes will be needed.

Releases at times have happened to be less timely mainly for my dissatisfaction towards the auto-generated assets by GitHub that led to the Note Well header, ie. `[NOTE WELL: Please download the pmacct-1.7.7.tar.gz asset; DO NOT download any of the assets called "Source code" in either tar.gz or zip format]`, in each release description.

In recent years there have been two main releases per year. Although exact dates have been fluid, the rule was more or less: freeze code Jul-Aug and release one month later (except major issues found) and freeze code Dec-Jan and release one month later (except major issues found).

Paolo

**Comment by paololucente** [comment]
Right, exactly. That happened during freeze time. When code does freeze, a branch and a tag is issued. When it is released, the release is created. Occasionally some hot fixes may make it to the branch if found of extreme importance. Paolo
