### ISSUE TITLE
use Pmacctd to export Netflow to Nfacctd， but Nfacctd got nothing

### ISSUE THREAD

**Issue by DarmJarlo** [pmacct/pmacct#609]
Hello， I‘m a student trying to learn some monitoring methods.I'm using pmacct 1.7.6. I have tried configurations like(first screenshot is for nfacctd)
![d0ec0aa1a60353281090c2bbceedade](https://user-images.githubusercontent.com/90767428/172493128-d64e93f7-cf4a-4bd0-850e-89142fb19890.png)
![ce6238e24dc34a5cc1df1bd614587ba](https://user-images.githubusercontent.com/90767428/172493143-62040858-a949-46e9-aef4-308891407394.png)
And I tried to make some traffic through mininet,
![b4938e68b90a00e0aa714eb882d28c3](https://user-images.githubusercontent.com/90767428/172494459-eaaf6cc2-2e92-486a-91ab-e23125834ea8.png)
 the ifconfig showed me
![8ca2e05af7be226777df678b56553aa](https://user-images.githubusercontent.com/90767428/172493358-9b1c2cea-b688-4d99-94d2-d21e5d0341e1.png)
But it seems that I cannot capture any flow on the nfacctd side,here is the log for nfacctd
![fb5600d59796e060efdf53007740a6e](https://user-images.githubusercontent.com/90767428/172493616-70ad2701-1229-47f6-a069-23d2d7587f5f.png)
And here is the log for pmacctd
![1654633963676](https://user-images.githubusercontent.com/90767428/172494183-5d49422c-7206-4a8f-8902-5d96c870977a.png)

I use tcpdump and it showed it has captured sth,
![612c14fbcbf842de3d72ed523df3abb](https://user-images.githubusercontent.com/90767428/172493795-6bc89702-8c1f-4365-a2fd-74e31d521f68.png)
It's really wired.Could you help me? I was stuck here for two days,thanks very much!
Best regards,
Jar

**Comment by DarmJarlo** [comment]
And also no data is sent to mysql 
![e339db024d0842587f8b462365531f3](https://user-images.githubusercontent.com/90767428/172494661-942f866e-2d77-48d5-a01e-a18c595d2bf1.png)

**Comment by DarmJarlo** [comment]
I think it works now， but when I use pmacct exporter and send the netflow to pmacct collector（just on the lo address）， it takes me too much time ，usually after 6 minutes I can receive the first flow. Do you know what is happening here? My aim is to implement a real-time monitoring.Thanks!
![d2eb77da9d8a46e80d99e7b60e1799b](https://user-images.githubusercontent.com/90767428/172933272-bcbb74eb-1e9a-4eba-8cd9-3b633ba1e37b.png)

**Comment by paololucente** [comment]
Hi @DarmJarlo ,

Wonderful you got progress. Please look at the `nfprobe_timeouts` in order to tweak responsiveness of your export (like you would do on a router), please experiment with those. Should you one day introduce packet sampling, ie. `sampling_rate`, then you could avoid timeouts and caching by defining `nfprobe_dont_cache` (don't do that without sampling); should you be interested in sampling data but be concerned about its accuracy, you can read this document: https://sflow.org/packetSamplingBasics/index.htm .

Paolo

**Comment by DarmJarlo** [comment]
Thanks for the answer, but I still have this problem( it didn't always appear but still usually). Is the timeouts you have mentioned the timeout of the packets that I am monitoring or the packets that pmacctd sends to nfacctd? Actually, I have a problem with the exporting( pmacctd sent flow very later)
And another question is that when I am using sampling rate ， sometimes I receive fewer packets as expected（for example，I send 350000 packets from host1 to host2  and  sampling rate is 5000， sometimes I received rightly 70 packets but sometimes I only got 7 packets，I am using the ciciddos2019 dataset）.Do you know why?
Thanks,
Jia
