### ISSUE TITLE
nfacctd_templates_receiver not working 

### ISSUE THREAD

**Issue by ixodis** [pmacct/pmacct#611]
Hello Paolo!

I have several nfacctd running on different servers with load balancer in front of these servers. In this scheme not all servers receive netflow templates so I try to use nfacctd_templates_receiver and nfacctd_templates_port to replicate them. I expect that the template comes to the first nfacctd server (10.0.0.1 on the picture) then it will be sent by nfacctd_templates_receiver to the replicator (10.0.0.10) on port udp/10000, and then the replicator will send it to all other nfacctd servers on port udp/20000.

 ![image001](https://user-images.githubusercontent.com/67434136/174057775-cf7bd17d-47a7-4ea2-a0d0-2a7285b070a3.png)
The problem is that the #1 nfacctd server does not send the template to the replicator when the template arrives. I did a tcpdump on this server (tcpdump –i eth0 port 20000 or port 10000) and it is empty.

 

Replicators configs:

tee.conf:
 

> nfacctd_port: 10000
> plugins: tee[a]
> tee_receivers[a]: /opt/pmacct/conf/templates_replicator/tee.lst
> tee_transparent[a]: true

tee.lst:

> id=1 ip=[10.0.0.1:20000](http://10.0.0.1:20000/),[10.0.0.2:20000](http://10.0.0.2:20000/),[10.0.0.3:20000](http://10.0.0.3:20000/)

 

 

Nfacctds configs:

> plugins: kafka
> kafka_broker_host: *
> kafka_config_file: /opt/pmacct/conf/ssl.property_lz4
> nfacctd_port: 3057
> nfacctd_templates_port: 20000
> nfacctd_templates_receiver: [10.0.0.10:10000](http://10.0.0.10:10000/)
> aggregate_primitives: /opt/pmacct/primitives/primitives_common
> aggregate: *
> timestamps_utc: true
> #debug_internal_msg: true
> #debug: true
> logfile: /var/log/nfacctd

 

 

Nfacttd debug log (I cleared it of Kafka and Received/Discarded NetFlow/IPFIX packet messages) 
is in the attachment

[log.txt](https://github.com/pmacct/pmacct/files/8918316/log.txt)

**Comment by paololucente** [comment]
Hi Roman ( @ixodis ),

Thanks for reporting this. I did just try to reproduce the issue, both sending to local host and to some remote host, and it all works. But generating the message is pending detecting and isolating the templates. Detecting i believe is not the issue (since it is used for NetFlow / IPFIX collection), isolating might be. Can you send me privately a sample of some of your packets that do include the templates?

Just as a side question: from, say, server `nfacctd #1` can you ping successfully the replicator?

Paolo

**Comment by ixodis** [comment]
I sent the dump to the mail.  All nfacctds servers and the replicator are on the same subnet, there are no firewalls between them

**Comment by paololucente** [comment]
Hi Roman ( @ixodis ),

This should be addressed with this commit: https://github.com/pmacct/pmacct/commit/f131a971cb29877f53d99b4479bd4550a84a447a . Can you give it a try and let me know if this is all working for you too?

Paolo
