### ISSUE TITLE
Does pmacctd_flow_lifetime key has effect using only sfprobe plugin (sFlow) ?

### ISSUE THREAD

**Issue by leofds** [pmacct/pmacct#612]
Hello Paolo!

I am testing sFlow with the follow configuration:
```
plugins:sfprobe
pcap_interface:eth0
sampling_rate:10
sfprobe_receiver:192.168.0.20:2056
```
It's works well.

Does the key `pmacctd_flow_lifetime ` or `pmacctd_flow_tcp_lifetime `  has effect using only sfprobe plugin ?

**Comment by paololucente** [comment]
Hi Leonardo ( @leofds ),

Nice you have a working config. To confirm that, no, those config keys have no effect when using the sfprobe plugin. They are part of the pmacct-internal flow management which is required when collecting traffic and enabling the `flows` primitive.

Paolo

**Comment by leofds** [comment]
Thanks, Paolo!
