### ISSUE TITLE
Pmacct receive very less amount of flow data

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#613]
Hi @paololucente , Thank you provide this too

**Description**

We use pmacct in our application, but our client shares a lot of traffic into particular port 9995, in pmacct received only 100 to 200 records only. below I added the version details and Pmacct config file details

tcpdump received a lot of packets, below command is used to check the tcpdump 

`tcpdump -i any port 9995`

**Version**

NetFlow Accounting Daemon, nfacctd 1.7.7-git [20211107-0 (ef37a415)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.8.1
MariaDB 10.3.31
PostgreSQL 110013
sqlite3 3.27.2
rabbimq-c 0.11.0
rdkafka 1.8.2
jansson 2.14
MaxmindDB 1.6.0
ZeroMQ 4.3.2
Redis 1.0.3
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.4.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64

Compiler:
gcc 8.3.0

**Pmacct config file**

`daemonize: false
nfacctd_port: 9995
nfacctd_time_new: true
timestamps_utc: true
nfacctd_stitching: true
timestamps_secs: true

aggregate[pmacct_amqp9995]: peer_src_ip, src_host, dst_host, proto, tos,src_port,dst_port, tcpflags, timestamp_start, timestamp_end, timestamp_arrival, timestamp_export
aggregate_filter[pmacct_amqp9995]:(not tcp) or ((tcp[tcpflags] & (tcp-syn) != 0) and (tcp[tcpflags] & (tcp-ack) == 0))
plugins: amqp[pmacct_amqp9995],print[pmacct_9995],print[pmacct_full_9995]
amqp_host[pmacct_amqp9995]: 127.0.0.1
amqp_persistent_msg[pmacct_amqp9995]: true
amqp_user[pmacct_amqp9995]:  guest
amqp_passwd[pmacct_amqp9995]: guest
amqp_exchange[pmacct_amqp9995]: pmacct
amqp_routing_key[pmacct_amqp9995]: acct
amqp_refresh_time[pmacct_amqp9995]: 10
amqp_history[pmacct_amqp9995]: 5m
amqp_history_roundoff[pmacct_amqp9995]: m

aggregate[pmacct_9995]: peer_src_ip, src_host, dst_host, proto, tos,src_port,dst_port, tcpflags, timestamp_start, timestamp_end, timestamp_arrival, timestamp_export
aggregate_filter[pmacct_9995]:(not tcp) or ((tcp[tcpflags] & (tcp-syn) != 0) and (tcp[tcpflags] & (tcp-ack) == 0))
print_output[pmacct_9995]:csv
print_output_file[pmacct_9995]:/etc/pmacct/pmacct_9995/filter/%Y%m%d%H%M.csv
print_history_roundoff[pmacct_9995]:m
print_refresh_time[pmacct_9995]:2

aggregate[pmacct_full_9995]: peer_src_ip, src_host, dst_host, proto, tos,src_port,dst_port, tcpflags, timestamp_start, timestamp_end, timestamp_arrival, timestamp_export
print_output[pmacct_full_9995]:csv
print_output_file[pmacct_full_9995]:/etc/pmacct/pmacct_9995/no_filter/%Y%m%d%H%M.csv
print_history_roundoff[pmacct_full_9995]:m
print_refresh_time[pmacct_full_9995]:2
`

**Comment by paololucente** [comment]
HI @AnanthGopal , 

I would start from:

1) pointing you to this troubleshooting https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L3060-L3073 so to check whether there is any packet loss,

2) suggesting to verify that there is only one process (as expected) listening onto port 9995 (due to SO_REUSEPORT, if there are more, they may load balance and potentially over write each other content in the output files and

3) finally, add `print_output_file_append: true` to the config of `pmacct_9995` and `pmacct_full_9995` files so to make sure that any intermediate writes (ie. because cache is to small or something) do not get overwritten.

Paolo
