### ISSUE TITLE
Should the Aggregate field change the "Flow sample" when using sFlow?

### ISSUE THREAD

**Issue by leofds** [pmacct/pmacct#616]
Hi Paolo. 

I have **NetFlow** and **sFlow** working well together, but I have a question about the different behaviors with these protocols using `aggregate: src_host, dst_host, src_port, dst_port, proto, tos`.

Using nfdump, I could see that the "Flow sample" of the **NetFlow** changes according to the added values in the `aggregate` field.
If I add `proto` e.g., I can see different "Flow sample" for each protocol, but if I don't use it, different protocols are merged into a same "Flow sample". This is a point.

Using **sFlow** the values of the `aggregate` field don't change the "Flow sample".

This behavior is correctly ?

**Comment by paololucente** [comment]
Hi Leonardo,

Yes, this is correct behavior. Reason being the "Flow sample" in sFlow does consist of a sampled portion of the packet headers so there you have everything; then it's upon collection that you can cherry-pick the primitives of interest. In NetFlow v9 / IPFIX you can perform this cherry-picking already in the exporter instead.

Paolo
