### ISSUE TITLE
aggregate netflow data by the 5-tuple protocol, srcip, dstip, srcport and dstport.

### ISSUE THREAD

**Issue by hhamed1989** [pmacct/pmacct#624]
**Description**
Hello,
before I start working with pmacct, I try nfdump. and we have an option to aggregate netflow data by the 5-tuple protocol, srcip, dstip, srcport and dstport for 10 min for example, Therefore, the data of these ten minutes was summarized based on the mentioned fields.
now i can't see this option on pmacct, could you please help me to find how aggregate netflow data by the 5-tuple protocol, srcip, dstip, srcport and dstport

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.8-git [20220705-0 (0620321a)]

Arguments:
 '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '-                                                                                                             -enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.9.1 (with TPACKET_V3)
jansson 2.14

Plugins:
memory
print
nfprobe
sfprobe
tee

System:
Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64

Compiler:
gcc 9.4.0

**Comment by paololucente** [comment]
Hi @hhamed1989 ,

Intersecting with your other Issue where you posted your config.

> aggregate: src_host, src_port, dst_host, dst_port, proto, tcpflags, peer_src_ip

This should give you the 5-tuple you are looking for. Maybe want to add `timestamp_start` and `timestamp_end` so to isolate individual flows? You did not qualify whether this was your goal or not.

> print_refresh_time: 60
> print_history: 1m

Setting `print_refresh_time` to 600 and `print_history` to 10m should give you the 10 mins aggregation you are looking for

Paolo

**Comment by hhamed1989** [comment]
Hi @paololucente

I changed print_refresh_time to 600 and print_history to 10m. and add flows to aggregate :
aggregate: src_host, src_port, dst_host, dst_port, proto, peer_src_ip, flows

but not show how many flows received from the router and aggregated. just show 1 flow . I also added timestamp_start and timestamp_end but nothing changed. When 2 or more flows are aggregated I just want to know the number of flows are aggregated .

{"event_type": "purge", "peer_ip_src": "172.16.1.161", "ip_src": "172.16.1.65", "ip_dst": "172.16.1.188", "port_src": 9996, "port_dst": 9996, "ip_proto": "udp", "stamp_inserted": "2022-07-19 10:20:00", "stamp_updated": "2022-07-19 10:34:06", "flows": 1, "packets": 1872, "bytes": 2569620}

**Comment by paololucente** [comment]
hi @hhamed1989 ,

I see about the `flows` counter, very strange. Two questions:
* Did you verify (maybe with `timestamp_start` and `timestamp_end`) that the router does respect the active flow timeout of 1 minute?
* Can you say if, despite `flows` not being correct, if `packets` and `bytes` counters are looking good?

Paolo
