### ISSUE TITLE
Segmentation fault with 32 plugins

### ISSUE THREAD

**Issue by jeremmfr** [pmacct/pmacct#63]
I would like to create more than 31 plugins but I have a Segmentation fault on start.
Exemple configuration =>

```
nfacctd_ip: 0.0.0.0
nfacctd_port: 9998

plugin_pipe_size: 32576000
plugin_buffer_size: 325760
sql_max_writers: 99

!debug: true
!daemonize: true
!logfile: /space/logs/pmacct/nfaccttd.log

nfacctd_disable_checks: true

plugins: amqp[in_1], amqp[in_2], amqp[in_3], amqp[in_4], amqp[in_5], amqp[in_6], amqp[in_6], amqp[in_7], amqp[in_8], amqp[in_9], amqp[in_10], amqp[in_11], amqp[in_12], amqp[in_13], amqp[in_14], amqp[in_15], amqp[in_16], amqp[in_17], amqp[in_18], amqp[in_19], amqp[in_20], amqp[in_21], amqp[in_22], amqp[in_23], amqp[in_24], amqp[in_25], amqp[in_26], amqp[in_26], amqp[in_27], amqp[in_28], amqp[in_29], amqp[in_30], amqp[in_31], amqp[in_32]

!! amqp
amqp_host: localhost
amqp_user: pmacct
amqp_passwd: pmacct
```
Can you help me ?

Best regards

**Comment by paololucente** [comment]
Dear,

Simplest would be to re-define the following in pmacct-defines.h to some higher value and recompile:

#define MAX_N_PLUGINS 32

But i'm actually wondering: what is your use-case for that? Do you want to comment on here or reach out by unicast email?

Cheers,
Paolo

**Comment by jeremmfr** [comment]
Thanks for help. It's ok now.

I detected a maximum of messages per second on one rabbitmq queue. I cut my flows with aggregate_filter on different rabbitmq exchange/queue. So I need to create as many plugins that queues.

**Comment by paololucente** [comment]
Great to know it's OK now.

Thanks also for the extra info on your use-case for this. I will not take any action for now but will happy to re-open the issue in case it gets more traction.
