### ISSUE TITLE
tee_plugin.c: undeclared identifier 'hincl' while building with --enable-ndpi flag

### ISSUE THREAD

**Issue by vvek-work** [pmacct/pmacct#637]
**Description**
I am trying to build the project with the following configuration.

`./configure --disable-bgp-bins --disable-bmp-bins --disable-st-bins --enable-jansson --enable-zmq --enable-threads --enable-64bit --enable-ndpi`

I found the following error while compiling the project.

> tee_plugin.c:738:70: error: use of undeclared identifier 'hincl'
>     setsockopt(s, IPPROTO_IP, IP_HDRINCL, &hincl, (socklen_t) sizeof(hincl));
>                                                                      ^
> tee_plugin.c:738:44: error: use of undeclared identifier 'hincl'
>     setsockopt(s, IPPROTO_IP, IP_HDRINCL, &hincl, (socklen_t) sizeof(hincl));
>                                            ^
> 2 errors generated.
> make[3]: *** [libtee_plugin_la-tee_plugin.lo] Error 1
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all] Error 2
> make: *** [all-recursive] Error 1

I looked into the code but couldn't find the declaration of `hincl`.

**Version**
I am building from the `master` branch only.

**OS**
Model Name:	MacBook Pro
Model Identifier:	MacBookPro17,1
Chip:	Apple M1
Total Number of Cores:	8 (4 performance and 4 efficiency)
Memory:	16 GB
System Firmware Version:	7459.141.1
OS Loader Version:	7459.141.1

Let me know if you need further details from my end.

**Comment by paololucente** [comment]
Hi @vvek-work ,

Thanks for reporting this & being in touch. I should have just fixed it, it was due to a missing variable declaration. It would be great if you can confirm it compiling now (or not, or whether you stumble into any other compiling issues).

Paolo

**Comment by vvek-work** [comment]
@paololucente Thanks for the prompt response and resolution. Everything compiles fine.
