### ISSUE TITLE
uacctd segfault on 1.7.6-2

### ISSUE THREAD

**Issue by levin1** [pmacct/pmacct#638]
When i use ICMP traffic there is a segfault in function find_flow line `memcpy(&my_tlh, pptrs->tlh_ptr, MyTCPHdrSz);` not sure how to fix this.

**Comment by ikle** [comment]
Proposed quick fix: https://github.com/pmacct/pmacct/pull/639

**Comment by paololucente** [comment]
Thanks @levin1 for raising this issue and thanks Alexei ( @ikle ) for proposing the quick fix and for the subsequent conversation about it, it makes sense. Just merged #639 and going to close this issue. Paolo
