### ISSUE TITLE
netflow v9: timestamp_end sometimes before timestamp_start

### ISSUE THREAD

**Issue by jwestfall69** [pmacct/pmacct#640]
**Description**
I've noticed that we sometimes get a timestamp_end that is before timestamp_start, which means a negative flow duration.  The difference is usually around -4290000 when this happens.  For example

```
{"event_type": "purge", ... , "timestamp_start": "1664491696.000000", "timestamp_end": "1660196759.000000", "packets": 2, "bytes": 824}
```

These flows are coming from juniper mx routers.  

**Version**
This was originally seen on an older version but also happens with master..

```
NetFlow Accounting Daemon, nfacctd 1.7.8-git [RELEASE]

Arguments:
 '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.10.0 (with TPACKET_V3)
jansson 2.13.1

Plugins:
memory
print
nfprobe
sfprobe
tee

System:
Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-2 (2022-02-28) x86_64

Compiler:
gcc 10.2.1
```

**Debug info**
I added some debug output in nfacctd to print out the raw data related to timestamp_end as its being calculated to track down if its the router or nfacctd causing the problem.  It results in stuff like

```
fstime: 66888064, unix_secs: 1664488348, sysuptime: 66892000, result: 1664488345
fstime: 66884992, unix_secs: 1664488348, sysuptime: 66892000, result: 1664488341
fstime: 66892160, unix_secs: 1664488348, sysuptime: 66892000, result: 1660193381 <----
fstime: 66879872, unix_secs: 1664488348, sysuptime: 66892000, result: 1664488336
fstime: 66881408, unix_secs: 1664488348, sysuptime: 66892000, result: 1664488338
```

fstime and sysuptime are both msec values.  It appears the router is providing its sysuptime in second resolution, but the fstime with msec resolution.  This is resulting in cases where fstime > sysuptime and causing a bad calculated value.

```
      pdata->time_end.tv_sec = ntohl(((struct struct_header_v9 *) pptrs->f_header)->unix_secs)-
        ((ntohl(((struct struct_header_v9 *) pptrs->f_header)->SysUptime)-ntohl(fstime))/1000);
```
which is basically

```
timestamp_end = unix_secs - (sysuptime - fstime)/1000
```

Given that the code is dropping the msec part of the values, perhaps the easy solution is to just change it to this (fixes it for me)

```
timestamp_end = unix_secs - ((sysuptime / 1000) - (fstime / 1000))
```
Just note that this change will be needed in 4 locations within the code.  2x for pdata->time_end.tv_sec  and 2x for pdata->time_start.tv_sec.  If you would like a PR with these changes let me know.

**Comment by jwestfall69** [comment]
I was thinking about this some more last night and why there is the huge -4290000 difference when this happens.

Every part of the calculation is a uint32_t variable.  The compiler is treating the result of

```
(sysuptime - fstime)
```
as a uint32_t, however the actual calculation is negative and results in an underflow of the uint32_t.  This causes the results to be a number up in the 4.29B range, which then gets divided by 1000 and lands us at the ~4290000 difference.

So I think the better fix would be to tell the compiler to treat the result of the above subtraction as an int32_t.

```
(int32_t)(sysuptime - fstime)
```

```
     pdata->time_end.tv_sec = ntohl(((struct struct_header_v9 *) pptrs->f_header)->unix_secs)-
        ((int32_t)(ntohl(((struct struct_header_v9 *) pptrs->f_header)->SysUptime)-ntohl(fstime))/1000);
```

**Comment by paololucente** [comment]
Hi Jim ( @jwestfall69 ),

I was wondering: do you believe this is an issue in pmacct rather than in the Juniper MX export, ie. the timestamps encoded in the flows? Being coded in the same time unit (msec), why the start flow time or end flow time would be greater than the system uptime? If you see through the code, if debug is enabled, you would get warnings about this very condition. 

Paolo

**Comment by jwestfall69** [comment]
Hi

I've only seen the issue with Juniper MX's at this point.  I kinda assume the router must internally be keeping track of its uptime in seconds then converts that to milliseconds when doing the flow exports.  This results in all the sysuptime values ending in 000 as seen above.  However the MX appears to send the first/last switched values with full millisecond resolution, which is causing the situation where those values can be milliseconds larger then sysuptime.

Its kinda of a weird situation as to where the issue exists and what should be fixed.  It would be nice if pmacct didn't underflowing the uint32_t in its timestamp calculation to avoid generating a non-sense timestamp value.

**Comment by jwestfall69** [comment]
Maybe this will help better explain

```
#include <stdio.h>
#include <stdint.h>

int main(void) {
  uint32_t fstime = 66892160;
  uint32_t systime = 66892000;
  uint32_t unixtime = 1664488348;
  uint32_t result;

  result = unixtime - (systime - fstime)/1000;
  printf("%u\n", result);

  result = unixtime - (int)(systime - fstime)/1000;
  printf("%u\n", result);
}
```
The values come from my original post for the entry that had the bad time.    The first calculation is how pmacct currently calculates the timestamp and the latter is what I will submit in a PR.

```
$ ./a.out 
1660193381
1664488348
```

In the first calculation the compiler is treating all parts of the calculation as unsigned.  However ```systime - fstime``` is actually a negative number.  This causes an underflow with it being unsigned, resulting in a very large value.   The latter way is telling the compiler to treat the result of ```systime - fstime``` as a signed to avoid the underflow.
