### ISSUE TITLE
Memory Leak in PMBMP process

### ISSUE THREAD

**Issue by purifp** [pmacct/pmacct#644]
**Description**

I'm using the BMP collector and using a file with ROAs (rpki_roas_file ) which is reloaded every 30 minutes using: pkill -USR2 pmbmpd (centos 7). I have realized that after the reload, the process memory increases

 ps -eo size,pid,user,command --sort -size
       688.17 Mb pmbmpd: Core Process [default] 
       816.17 Mb pmbmpd: Core Process [default] 
       816.17 Mb pmbmpd: Core Process [default] 
       816.17 Mb pmbmpd: Core Process [default] 
       816.17 Mb pmbmpd: Core Process [default] 
       880.17 Mb pmbmpd: Core Process [default] 
       944.17 Mb pmbmpd: Core Process [default] 
      1136.17 Mb pmbmpd: Core Process [default] 
      1200.17 Mb pmbmpd: Core Process [default] 
      1200.17 Mb pmbmpd: Core Process [default] 
      1200.17 Mb pmbmpd: Core Process [default] 
      1264.17 Mb pmbmpd: Core Process [default] 

If I stop the crontab, the memory size remains in the same size 

This is the config that I am using 

**** config file ****
bmp_daemon_ip: 0.0.0.0
bmp_daemon_port: 1790
bmp_daemon_max_peers: 1000
bmp_daemon: true
!
rpki_roas_file: /opt/rpki/export.json
!
#debug: true
#debug_internal_msg: true
!
bmp_daemon_msglog_kafka_broker_host: 127.0.0.1
bmp_daemon_msglog_kafka_broker_port: 9092
bmp_daemon_msglog_kafka_topic: bmp

Plugins :  '--enable-jansson' '--enable-kafka'

**Version**
pmbmpd 1.7.9-git

**Comment by paololucente** [comment]
Hi Puri ( @purifp ),

Thanks very much for getting in touch about this. I should have just addressed the issue with the commit https://github.com/pmacct/pmacct/commit/0ac421cc48b43813f8f8aa1d3a8b475039e435ba . Can you give it a try and confirm it working OK for you?

Thanks,
Paolo

**Comment by purifp** [comment]
Hi Paolo, good news! I just downloaded it , I tell you something next monday. thanks!!!

**Comment by purifp** [comment]
Paolo, I am afraid, it still happens.. 

       688.29 Mb pmbmpd: Core Process [default] 
       816.29 Mb pmbmpd: Core Process [default] 
       880.29 Mb pmbmpd: Core Process [default] 
       880.29 Mb pmbmpd: Core Process [default] 
       944.29 Mb pmbmpd: Core Process [default] 

I am using Centos 7 release 3.10.0-1160.25.1.el7.x86_64, and I reload the file every 30 minutes with this script

sudo crontab -l
*/30 * * * * bash /mypath/download_roas.sh

<---download_roas.sh-->
#!/bin/bash
rm /mypath/export.json
wget https://rpki.gin.ntt.net/api/export.json -P /mypath/
sudo pkill -USR2 pmbmpd

If you need more information, do not hesitate to contact me

**Comment by paololucente** [comment]
Hi Puri,

Can you give this one more try with latest code from master? I just pushed another fix after further analising the memory leak.

Paolo

**Comment by purifp** [comment]
Hi Paolo
I have been reloading the roas file every 30 min for 24h and the process memory doesn´t increase, thanks so much!!!

**Comment by paololucente** [comment]
Thank you for confirming, Puri!
