### ISSUE TITLE
"sql_history_roundoff: w" resets the date on both Sunday and Monday night

### ISSUE THREAD

**Issue by toreanderson** [pmacct/pmacct#647]
**Description**

`sql_history_roundoff: w` resets the date on **both** Sunday and Monday night.

This can be seen in the database, see below. It is expected per the documentation that the timestamp should reset midnight tonight (`2022-11-21 00:00:00`, i.e. Monday), but *not* expected that it should also have happened yesterday (Sunday).

```
mysql> SET time_zone = "+00:00";
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT UNIQUE(FROM_UNIXTIME(stamp_inserted)) from acct_in;
+---------------------------------+
| (FROM_UNIXTIME(stamp_inserted)) |
+---------------------------------+
| 2022-11-14 00:00:00             |
| 2022-11-20 00:00:00             |
| 2022-11-21 00:00:00             |
+---------------------------------+
3 rows in set (0.04 sec)

mysql> SELECT UNIQUE(FROM_UNIXTIME(stamp_inserted)) from acct_out;
+---------------------------------+
| (FROM_UNIXTIME(stamp_inserted)) |
+---------------------------------+
| 2022-11-14 00:00:00             |
| 2022-11-21 00:00:00             |
| 2022-11-20 00:00:00             |
+---------------------------------+
3 rows in set (0.06 sec)
```

This is the `sfacctd.conf` file contents:

```
aggregate[in]: src_as,src_net,src_mask
aggregate[out]: dst_as,dst_net,dst_mask
networks_file: /etc/pmacct/networks.lst
plugin_exit_any: true
plugins: mysql[in], mysql[out]
pre_tag_filter[in]: 1
pre_tag_filter[out]: 2
pre_tag_map: /etc/pmacct/internet_uplinks.map
propagate_signals: true
sfacctd_as: longest
sfacctd_net: longest
sfacctd_port: 6345
sfacctd_renormalize: true
sql_db[in]: sfacctd_dfz
sql_db[out]: sfacctd_dfz
sql_history[in]: 1w
sql_history[out]: 1w
sql_history_roundoff[in]: w
sql_history_roundoff[out]: w
sql_host[in]: sflow-db
sql_host[out]: sflow-db
sql_optimize_clauses[in]: true
sql_optimize_clauses[out]: true
sql_passwd[in]: <snip>
sql_passwd[out]: <snip>
sql_refresh_time[in]: 60
sql_refresh_time[out]: 60
sql_table[in]: acct_in
sql_table[out]: acct_out
sql_table_schema[in]: /etc/pmacct/in.schema
sql_table_schema[out]: /etc/pmacct/out.schema
sql_table_version[in]: 9
sql_table_version[out]: 9
sql_user[in]: sfacctd_dfz
sql_user[out]: sfacctd_dfz
timestamps_since_epoch[in]: true
timestamps_since_epoch[out]: true
```

**Version**

```
sFlow Accounting Daemon, sfacctd 1.7.9-git [20221119-0 (c9d7d154)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.8.1
MariaDB 10.3.36
PostgreSQL 110018
sqlite3 3.27.2
rabbimq-c 0.11.0
rdkafka 2.0.0
jansson 2.14
MaxmindDB 1.7.1
ZeroMQ 4.3.4
Redis 1.1.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 4.4.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64

Compiler:
gcc 8.3.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

**Comment by paololucente** [comment]
Hi Tore ( @toreanderson ),

Just to collect some more info for this round in order to characterize the issue better. The so-called roundoff (align intervals with calendar time rather than startup time) is a one-off thing that is calculated at initialization time so it is unlikely to be generating such a repeating behavior.

Is this a new config / setting? Or a modified config where you only changed `sql_history_roundoff` and this problem started appearing? Or is it something that has always been taken place and you just realized? Also, can you show a few more instances of this problem and also include the value for `stamp_updated` other than `stamp_inserted`, i am curious when the actual bogus event does take place. Is the host running on UTC time and regularly sync'd up by NTP?

Paolo

**Comment by toreanderson** [comment]
Hi Paolo,

I got this behaviour when setting this up from begin with, using `sql_history_roundoff: w` from day one. First I got it using `DATETIME`, then I threw out the database contents and tried again with `timestamps_since_epoch` but got the same result.

As for showing a few more instances - the above is what my database currently contains, as I threw out the previous contents when moving to `timestamps_since_epoch` . I am attaching output from `SELECT stamp_inserted,stamp_updated FROM acct_out` in case that is helpful: [SELECT-stamp_inserted,stamp_updated-FROM-acct_out.txt.gz](https://github.com/pmacct/pmacct/files/10065591/SELECT-stamp_inserted.stamp_updated-FROM-acct_out.txt.gz). If you want more occurrences, I guess I will have to wait another a week.

The time zone inside the container (I'm using the official one from Docker Hub) is set to UTC. NTP is active and works.

```console
$ sudo podman exec -it sfacctd_dfz sh -c 'ls -l /etc/localtime; date'
lrwxrwxrwx 1 root root 27 Nov 14 00:00 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
Tue Nov 22 08:52:54 UTC 2022
```

That said, I tried to understand what is going myself, and found this code:

https://github.com/pmacct/pmacct/blob/83898c349c633ec4c5f4b3ab8afc52fd45a91ff2/src/util.c#L375-L382

I will be the first to admit that I am not a very experienced programmer, so I might be missing something here, but it would appear to me that `tm_wday` will be set to ***either*** 0 (Sunday; if `tm_wday` was initially 0) ***or*** 1 (Monday; if `tm_weekday` was initially 1, 2, 3, 4, 5 or 6) after the while loop has completed. This seems consistent with the behaviour that I observe.

**Comment by toreanderson** [comment]
By the way, this query is a bit interesting:

`SET time_zone = "+00:00"; SELECT FROM_UNIXTIME(stamp_inserted),FROM_UNIXTIME(stamp_updated) FROM acct_out ORDER BY stamp_updated;`

```
+-------------------------------+------------------------------+
| FROM_UNIXTIME(stamp_inserted) | FROM_UNIXTIME(stamp_updated) |
+-------------------------------+------------------------------+
| 2022-11-14 00:00:00           | 2022-11-15 14:04:01          |
| 2022-11-14 00:00:00           | 2022-11-15 14:04:01          |
| 2022-11-14 00:00:00           | 2022-11-15 14:04:01          |
(…many lines with stamp_inserted unchanged…)
| 2022-11-14 00:00:00           | 2022-11-20 02:12:38          |
| 2022-11-14 00:00:00           | 2022-11-20 02:12:38          |
| 2022-11-14 00:00:00           | 2022-11-20 02:12:38          |
| 2022-11-20 00:00:00           | 2022-11-20 02:15:01          |
| 2022-11-20 00:00:00           | 2022-11-20 02:15:01          |
| 2022-11-20 00:00:00           | 2022-11-20 02:15:01          |
(…many lines with stamp_inserted unchanged…)
| 2022-11-20 00:00:00           | 2022-11-21 02:12:35          |
| 2022-11-20 00:00:00           | 2022-11-21 02:12:35          |
| 2022-11-20 00:00:00           | 2022-11-21 02:12:35          |
| 2022-11-21 00:00:00           | 2022-11-21 02:15:01          |
| 2022-11-21 00:00:00           | 2022-11-21 02:15:01          |
| 2022-11-21 00:00:00           | 2022-11-21 02:15:01          |
(…many lines with stamp_inserted unchanged…)
```

So it seems that between around 02:12:40 UTC and 02:15:00 there is a period with no updates, after which the `stamp_updated` finally updates. I find that quite odd, I had assumed that `stamp_updated` with move to a new date at the same time as `stamp_inserted` did.

The reason why there are no updates in the period *might* be due to a database backup, I am not 100% sure but will try to find out (or at least get logs from the sfacctd container in that period). But even if it is a database backup happening and blocking updates, I don't quite understand why that would trigger a new `stamp_inserted` rounding-off event. Strange…

**Comment by toreanderson** [comment]
Eureka! I found out what was happened 2022-11-20 and 2022-11-21 around 02:13 UTC - the container image gets upgraded and restarted (forget everything I said about database backups). So here's what I believe is happening:

1. You have some kind of automated system that builds and publishes a new version of `docker.io/pmacct/sfacctd:bleeding-edge` to Docker Hub every night sometime after 01:15 UTC.
2. I have an automated system that looks for updates every hour at around xx:15, and if there are any, pulls the new image and restarts it.
3. The previous two points means the container is updated and restarted every night. This in turn means that the roundoff *«one-off thing that is calculated at initialization»* will actually occur every night.
4. As previously noted, the rounding-off algorithm in `util.c:roundoff_time()` appears to consider that a week starts on Sunday if the algorithm was run (read: if the `sfacctd` process was started on) on Sunday, or on Monday if run any other day.

Thus, the restarts on Sunday and Monday night mark the beginning of a new week in the database. I would consider this a bug, considering that the documentation states that `[*_]history_roundoff: w` should make the week start on Monday, with no caveat that it the week starts on Sunday if the `sfacctd` process was started on a Sunday:

https://github.com/pmacct/pmacct/blob/83898c349c633ec4c5f4b3ab8afc52fd45a91ff2/CONFIG-KEYS#L1368-L1370

For what it is worth I don't really care if the week starts on Sunday or Monday (though I'd intuitively expect the system locale to be how that is defined, absent any explicit configuration in `sfacctd.conf`), as long as a rounded-off period is exactly seven days.

**Comment by paololucente** [comment]
Hi Tore ( @toreanderson ),

Thanks for the investigation & putting me on the right path. The super small fix above should make it all consistent, any day of the week the base time of the time slot should now be set to the day 0, or Sunday. Please let me know if this seems to work for you.

You also raise the point of resetting the week to Sunday or Monday and locale. To be honest with you, i am not the most familiar with localized environments so, if you have tips & it is not about opening the Pandoras's box, i would be glad to get input. Another way of viewing it is that realistically we have two choices here, we can have a true/false config flag for that and call it a day. Let me know your thoughts, you were mentioning that this reconciliation may be enough for you - that is an option too, we could consider this issue closed & i can add to my todo list to think / research further improvements.

Paolo

**Comment by toreanderson** [comment]
I'm happy with this fix, was going to suggest making it `while (rounded->tm_wday) {` myself. :smile:

As long as one `stamp_inserted` bracket in the database covers exactly a whole week, it does not matter where it starts and ends. Don't worry about respecting the system locale for my sake.

Anyway, there are four occurrences of the string `Monday` remaining in CONFIG-KEYS. I think most, if not all, of those now should be changed to `Sunday`.

**Comment by paololucente** [comment]
Thanks for the feedback & i will hence close this issue like this for the time being. Wrt docs, i replaced one instance of those `Monday` with `Sunday`; the others are correct as that behavior comes from `%W` handling (vs `%w` handling) in date functions in libc.
