### ISSUE TITLE
JSON Input plugin

### ISSUE THREAD

**Issue by sshaygan** [pmacct/pmacct#648]
Feature request: Is there anyway to import JSON to PMACCT ? I am rendering neflows/sflow using logstash and I wonder if there is any way that I can import them to PMACCT! 
Thank you 
 

**Version**
All Versions

**Comment by paololucente** [comment]
Hi @sshaygan ,

To confirm that no, currently there is not  such a support. I am curious though why would you use logstash as a pre-processor for pmacct and what would be a JSON output from logstash. 

Paolo

**Comment by sshaygan** [comment]
Thank you, we already use logstash pipeline for monitoring and was wondering if I can just re-use it and send part of the traffic for accounting. That is the whole reason. I can basically output the traffic as anything I want except netflow/sflow/IPFiX. The JSON output is just as a simple key,value dictionary of translated sflow
