### ISSUE TITLE
Aggregation filter stop working

### ISSUE THREAD

**Issue by analogic** [pmacct/pmacct#650]
**Description**
Sample config:

```
plugins: memory[in], memory[out], memory[in6], memory[out6], memory[inpppoe], memory[outpppoe], memory[in6pppoe], memory[out6pppoe]
aggregate[in]: dst_host
aggregate_filter[in]: (dst net 178.../21 or dst net 185.../22) or (vlan and (dst net 178.../21 or dst net 185.../22)) or (vlan and (dst net 178.../21 or dst net 185.../22))
imt_path[in]: /tmp/pmacct_in.pipe
```

There are multiple aggregate filters, doing just accounting of our subnets per IP address, source is mirror port on switch. Problem is that it worked flawless until now. Even couple hours after start everything is ok but then things get messy and filters somewhat stop working and pmacct just start account everything and processes start to eat machine CPU&memory in big way:

```
# docker exec -ti pmacct2 pmacct -p /tmp/pmacct_in.pipe -s -O csv

188.27.190.151,60,26,3119
190.218.245.75,60,3,3447
54.36.149.0,60,291,937132
54.36.148.33,60,281,935417
85.14.248.91,60,666,136635
89.234.64.77,60,23,1748
2a03:ab00:104:dd0::,60,451690,541625913
151.106.68.214,60,4948,999559
34.246.254.163,60,140,31563
34.95.120.195,60,586,97521
188.253.231.153,60,1,134
184.190.150.62,60,1,132
3.224.200.106,60,760,88604
2607:5300:60:1920::,60,2470,289423
3.123.120.111,60,555,125621
139.47.81.22,60,1,40
49.228.99.223,60,4,1324
23.99.199.208,60,2627,1369753
106.205.251.209,60,1,311
217.25.222.205,60,15,8699
42.107.224.147,60,1,134
....
```

Machine keeps sitting for months without touching, so I don't thing it might origin from net/software changes. Are there any corner cases where aggregate filter might fail and pmacct keep aggregating? Am I missing something?

**Version**
1.7.7

**Comment by analogic** [comment]
I see something suspicious:
```
2022-11-26T07:41:44.190943525Z WARN ( default/core ): [ens160f0] has become unavailable; throttling ...
2022-11-26T07:41:44.209463118Z INFO ( default/core ): [ens160f0,0] link type is: 1
2022-11-26T07:54:28.062170980Z WARN ( out/memory ): Unable to allocate more memory pools, clear stats manually!
2022-11-26T07:54:31.125546230Z WARN ( outpppoe/memory ): Unable to allocate more memory pools, clear stats manually!
2022-11-26T07:56:05.357763937Z WARN ( out6/memory ): Unable to allocate more memory pools, clear stats manually!
2022-11-26T07:56:15.679127833Z WARN ( out6pppoe/memory ): Unable to allocate more memory pools, clear stats manually!
```

**Comment by analogic** [comment]
According to https://github.com/pmacct/pmacct/blob/938d16c891525cfc592b29c90b61ff57eb085527/src/pmacctd.c#L1195 it seems that pmacct tries to fix situation but it is not working in our case.

I'll try to use pcap_interface_wait=false and restart whole process with supervisor. Feel free to close this issue, reloading pcap should work, but it might be specific to our setup

**Comment by analogic** [comment]
Saga continues, another trigger

Nov 27 19:40:43 echelon kernel: [24479202.701907] pmacctd[1784303]: segfault at 7f3d86cd2540 ip 000055b05df7b05a sp 00007fff95709b68 error 4 in pmacctd[55b05def3000+a6000]
Nov 27 19:40:43 echelon kernel: [24479202.701917] Code: 00 00 00 48 83 87 c8 00 00 00 01 48 01 87 b8 00 00 00 c3 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 b8 01 00 00 00 48 85 ff 74 15 <80> bf c0 00 00 00 00 74 0c 31 c0 80 bf cc 00 00 00 00 0f 9
5 c0 c3

will try to run once again and dump core

**Comment by paololucente** [comment]
Hi @analogic ,

Thanks for getting in touch. If i am correct, the original problem is successfully worked around - true? But there is now a second (unrelated?) issue where possibly the daemon is crashing, right? Look forward receiving more info, like you said, a pass through gdb with a backtrace or such (ie. a run under valgrind).

Paolo

**Comment by analogic** [comment]
Well both logs led to same result - agregate filter forgotten and thus memory filled and due another data processing of all items also disk filled. I will try to debug as much as possible but the bug seems to be dependent on some type of traffic or machine state. I know that without additional info we can't do much, so now I am just waiting when this happen again hoping that core will be dumped. If not I'll use valgrind...
Thanks Paolo!

**Comment by analogic** [comment]
Closing. Bug didn't happen again and we were forced to move to netflow
