### ISSUE TITLE
nfacctd: Nfv9 packets received, but nothing is printed

### ISSUE THREAD

**Issue by laurentduru** [pmacct/pmacct#652]
INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.9-git (20221128-0 (0c071170))

Hi Paolo,

Very similar to issue 326.

Command launch for test : 
**nfacctd -l 2060 -P print -d**

After receiving the **template from a Cisco WLC (Wifi controller)**: 
DEBUG ( default/core ): Processing NetFlow/IPFIX flowset [0] from [x.x.x.x:32778] seqno [3261064]
DEBUG ( default/core ): NfV9 agent         : x.x.x.x:1
DEBUG ( default/core ): NfV9 template type : flow
DEBUG ( default/core ): NfV9 template ID   : 261
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
DEBUG ( default/core ): | 0          | 365                [365  ] |      0 |      6 |
DEBUG ( default/core ): | 0          | 366                [366  ] |      6 |      4 |
DEBUG ( default/core ): | 0          | 95                 [95   ] |     10 |      4 |
DEBUG ( default/core ): | 0          | 147                [147  ] |     14 |     33 |
DEBUG ( default/core ): | 0          | direction          [61   ] |     47 |      1 |
DEBUG ( default/core ): | 0          | in bytes           [1    ] |     48 |      8 |
DEBUG ( default/core ): | 0          | in packets         [2    ] |     56 |      8 |
DEBUG ( default/core ): | 0          | 98                 [98   ] |     64 |      1 |
DEBUG ( default/core ): | 0          | 195                [195  ] |     65 |      1 |
DEBUG ( default/core ): | 0          | 367                [367  ] |     66 |      6 |
DEBUG ( default/core ): -------------------------------------------------------------
DEBUG ( default/core ): Netflow V9/IPFIX record size : 72
DEBUG ( default/core ):

Flows are processed : 
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x.x.x.x:32778] version [9] seqno [3261233]
DEBUG ( default/core ): Processing NetFlow/IPFIX flowset [261] from [x.x.x.x:32778] seqno [3261233]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x.x.x.x:32778] version [9] seqno [3261234]
DEBUG ( default/core ): Processing NetFlow/IPFIX flowset [261] from [x.x.x.x:32778] seqno [3261234]
DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x.x.x.x:32778] version [9] seqno [3261235]

But no print :
CINFO ( default_print/print ): *** Purging cache - START (PID: 1710696) ***
INFO ( default_print/print ): *** Purging cache - END (PID: 1710696, QN: 0/0, ET: X) ***

For complete information, the same pmacct instance received flow form other type sources and works well.
If I use a tee instead of print to forward the flow to a collector, the flow collector as destination can handle the flow and template.

**Comment by paololucente** [comment]
Hi Laurent ( @laurentduru ),

Thanks for getting in touch about this. I guess this is mainly because staMacAddress (IE 365) and staIPv4Address (IE 366) are unknown to pmacct. Mapping those to, say, `src_host` and `src_mac` primitives, would yield to much better results (ie. actual outputting some data out). Rest of the primitives, ie. wtpMacAddress (IE 367) and wlanSSID (IE 147), could be configured as custom primitives, i can show you an example of that.

Mapping staMacAddress and staIPv4Address to something known it's relatively easy for me to do, i should be able to return something working even by the end of the day. If you could send me some sample data via unicast email, that would be even better so that i can test it working before committing. 

Paolo

**Comment by paololucente** [comment]
Hi Laurent,

As you may see, i did already attempt to write some simple code for the field mapping. I guess that if you now start nfacctd as: `nfacctd -l 2060 -P print -d -c src_host,src_mac,direction` it should print something out. Let me knof if this is (not) the case.

Paolo

**Comment by laurentduru** [comment]
Hi Paolo,

Many thanks for such quick answer.
The solution is on a production platform, I can't rapidily update the code.

To complete, I tried to use these primitives and aggregate on these : 
```
name=wlanSSID   field_type=147  len=33  semantics=str
name=staMacAddress   field_type=365  len=66  semantics=str
name=staIPv4Address   field_type=366  len=4  semantics=str
name=wtpMacAddress   field_type=367  len=4  semantics=str
```
Are there mandatory fields for aggregation like src_host, src_mac, if missing no print ?

_I guess that if you now start nfacctd as: nfacctd -l 2060 -P print -d -c src_host,src_mac,direction._
Do you mean before or after applying your code update ?
For now if I try, nfattcd says "direction" primitive is unkown, if I try without "direction", no output

_If you could send me some sample data via unicast email, that would be even better so that i can test it working before committing._
For sure, how can I do that privately ?

**Comment by laurentduru** [comment]
Paolo,

I tested the code update on a test bed with pcap file, there is some output.
I have now to test further with custom primitives, I'll let you know.

Many thanks

**Comment by paololucente** [comment]
Hi Laurent,

> For now if I try, nfattcd says "direction" primitive is unkown, if I try without "direction", no output

My bad, `sampling_direction`

> I tested the code update on a test bed with pcap file, there is some output.
> I have now to test further with custom primitives, I'll let you know.

Perfect, keep me posted

> For sure, how can I do that privately ?

It seems things are working out nicely so perhaps no need to send a pcap over. But should we get stuck again: https://github.com/pmacct/pmacct/blob/master/AUTHORS#L6

Paolo

**Comment by laurentduru** [comment]
Hi Paolo,

We updated pmacct on our production platform and the updated code did the job :  
- staMacAddress is available through src_mac
- staIPv4Address through src_host

custom primitive wlanSSID is also OK, need more work for wtpMacAddress

Many thanks
