### ISSUE TITLE
Application Name not resolved even though enable-ndpi flag is enabled

### ISSUE THREAD

**Issue by vvek-work** [pmacct/pmacct#654]
Hello,

I am trying to get the application name/protocol details through pmacct. I have followed the steps from GitHub to enable the ndpi however I am not able to receive application details through pmacct.  I have checked with my network team and they confirmed that data is available in flow monitor cache 
"class" field has "unknown" data only.

Please let me know if I have missed something... or incase if you need further details to check the issue.

nfacctd -V

> NetFlow Accounting Daemon, nfacctd 1.7.9-git [20221129-2 (1adbf79b)]
> 
> Arguments:
>  '--disable-bgp-bins' '--disable-bmp-bins' '--disable-st-bins' '--enable-jansson' '--enable-zmq' '--enable-threads' '--enable-64bit' '--enable-ndpi' '--enable-l2' '--enable-traffic-bins'
> 
> Libs:
> cdada 0.4.0
> libpcap version 1.10.1
> jansson 2.14
> ZeroMQ 4.3.4
> nDPI 4.2.0
> 
> Plugins:
> memory
> print
> nfprobe
> sfprobe
> tee
> 
> System:
> Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
> 
> Compiler:
> clang 14.0.0
> 
> For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.

My Cisco 9300 has the below-mentioned configuration,

> flow record QA_8.0_NBAR
> match ipv4 version
> match ipv4 protocol
> match application name
> match connection client ipv4 address
> match connection server ipv4 address
> match connection server transport port
> match flow observation point
> collect flow direction
> collect connection initiator
> collect connection new-connections
> collect connection client counter packets long
> collect connection client counter bytes network long
> collect connection server counter packets long
> collect connection server counter bytes network long
> collect timestamp absolute first
> collect timestamp absolute last

nfacctd.conf:

> plugins: print[NetFlow]
> nfacctd_port:2055
> zmq_address: tcp://localhost:9450
> logfile: NetFlow_1671703393592.log
> loglevel: 7
> snaplen: 65535
> use_ip_next_hop: true
> aggregate[NetFlow]: export_proto_seqno, src_host, dst_host, peer_src_ip, peer_dst_ip, in_iface, out_iface, src_port, dst_port, proto, sampling_rate, flows, tcpflags, tag, export_proto_version, tos, class, timestamp_start, timestamp_end, src_as, dst_as, peer_dst_as
> print_output_file[NetFlow]:NetFlow
> print_output[NetFlow]: json
> print_history[NetFlow]: 1m
> print_history_roundoff[NetFlow]: m
> print_refresh_time[NetFlow]: 60
> plugin_pipe_zmq: true
> print_num_protos: true
> pre_tag_map: tag.rule
> print_cache_entries[NetFlow]: 16411
> tmp_asa_bi_flow : true
> nfacctd_net : netflow
> nfacctd_as : netflow
> nfacctd_peer_as : true

Wireshark packet dump:

> Frame 8621: 1466 bytes on wire (11728 bits), 1466 bytes captured (11728 bits) on interface en0, id 0
> Ethernet II, Src: Fortinet_e6:1e:87 (90:6c:ac:e6:1e:87), Dst: Apple_58:f7:f7 (b0:be:83:58:f7:f7)
> Internet Protocol Version 4, Src: 172.16.8.2, Dst: 10.20.40.70
> User Datagram Protocol, Src Port: 49163, Dst Port: 2055
> Cisco NetFlow/IPFIX
>     Version: 9
>     Count: 18
>     SysUptime: 3937786.224000000 seconds
>     Timestamp: Dec 22, 2022 15:27:53.000000000 IST
>     FlowSequence: 35665
>     SourceId: 16777217
>     FlowSet 1 [id=0] (Data Template): 258
>         FlowSet Id: Data Template (V9) (0)
>         FlowSet Length: 72
>         Template (Id = 258, Count = 16)
>             Template Id: 258
>             Field Count: 16
>             Field (1/16): DIRECTION
>             Field (2/16): flowStartMilliseconds
>             Field (3/16): flowEndMilliseconds
>             Field (4/16): biflowDirection
>             Field (5/16): newConnectionDeltaCount
>             Field (6/16): responderPackets
>             Field (7/16): initiatorPackets
>             Field (8/16): Unknown(45004)
>             Field (9/16): Unknown(45005)
>             Field (10/16): Unknown(45009)
>             Field (11/16): observationPointId
>             Field (12/16): Unknown(41105)
>             Field (13/16): Unknown(41106)
>             Field (14/16): IP_PROTOCOL_VERSION
>             Field (15/16): PROTOCOL
>             Field (16/16): APPLICATION_ID
>     FlowSet 2 [id=258] (17 flows)
>         FlowSet Id: (Data) (258)
>         FlowSet Length: 1332
>         [Template Frame: 2]
>         Flow 1
>             Direction: Egress (1)
>             [Duration: 6.000000000 seconds (milliseconds)]
>             Biflow Direction: Initiator (1)
>             New Connection Delta Count: 0
>             Responder Packets: 0
>             Initiator Packets: 1
>             Unknown Field Type: Type 45004: Value (hex bytes): 0a 14 28 de
>             Unknown Field Type: Type 45005: Value (hex bytes): ac d9 c2 8a
>             Unknown Field Type: Type 45009: Value (hex bytes): 01 bb
>             Observation Point Id: 4294967308
>             Unknown Field Type: Type 41105: Value (hex bytes): 00 00 00 00 00 00 00 00
>             Unknown Field Type: Type 41106: Value (hex bytes): 00 00 00 00 00 00 00 46
>             IPVersion: 4
>             Protocol: TCP (6)
>             Classification Engine ID: PANA-L7 (13)
>             Selector ID: 000208
>         Flow 2
>             Direction: Egress (1)
>             [Duration: 15.000000000 seconds (milliseconds)]
>             Biflow Direction: Initiator (1)
>             New Connection Delta Count: 1
>             Responder Packets: 0
>             Initiator Packets: 4
>             Unknown Field Type: Type 45004: Value (hex bytes): 0a 14 28 bb
>             Unknown Field Type: Type 45005: Value (hex bytes): 0a 64 19 54
>             Unknown Field Type: Type 45009: Value (hex bytes): 00 a1
>             Observation Point Id: 4294967308
>             Unknown Field Type: Type 41105: Value (hex bytes): 00 00 00 00 00 00 00 00
>             Unknown Field Type: Type 41106: Value (hex bytes): 00 00 00 00 00 00 01 48
>             IPVersion: 4
>             Protocol: UDP (17)
>             Classification Engine ID: IANA-L4 (3)
>             Selector ID: 0000a1
>         Padding: 0000

cisco_core#show flow monitor APP-OUT cache | inc APPLICATION

> APPLICATION NAME:          layer7 ms-teams
> APPLICATION NAME:          port http
> APPLICATION NAME:          layer7 google-services
> APPLICATION NAME:          layer7 google-services
> APPLICATION NAME:          port http
> APPLICATION NAME:          port http
> APPLICATION NAME:          port snmp
> APPLICATION NAME:          port http
> APPLICATION NAME:          port http
> APPLICATION NAME:          port http
> APPLICATION NAME:          layer7 statistical-conf-audio

**Comment by paololucente** [comment]
Hi @vvek-work ,

If i am correct, you are receiving NetFlow / IPFIX from a device configured with NBAR support - true? If so, nDPI is out of the picture as that is a DPI library for traffic collected via libpcap (pmacctd) or ULOG (uacctd). We should rather understand why pmacct, then, is unable to make sense of the exported flows with Application ID. Could you please share a trace of some NetFlow packets (flows, templates and options) via unicast email? 

Paolo

**Comment by vvek-work** [comment]
Thanks for the prompt reply,

You are right, I am receiving NetFlow / IPFIX from a device configured with NBAR support.

I have checked with sFlow from the other device and everything works as expected. I am able to collect data from the 'class' attribute.

I have sent pcap file on paolo@pmacct.net

> cisco_core#show flow exporter Vivek 
> Flow Exporter Vivek:
>   Description:              User defined
>   Export protocol:          NetFlow Version 9
>   Transport Configuration:
>     Destination IP address: 10.20.40.70
>     Source IP address:      172.16.8.2
>     Source Interface:       Vlan20
>     Transport Protocol:     UDP
>     Destination Port:       2055
>     Source Port:            49621
>     DSCP:                   0x0
>     TTL:                    255
>     Output Features:        Used

**Comment by vvek-work** [comment]
@paololucente Hello,
Update on the issue, We have used another application with the same lab environment and we are able to retrieve the Application details from the NetFlow/IPFIX.

I have seen the latest commit related to the gRPC module.

Please let me know if you required additional information/data to help with the debugging process.

Vvek

**Comment by paololucente** [comment]
To round this up, from the evidence provided it looked like the device was not exporting classes information via NetFlow / IPFIX options.
