### ISSUE TITLE
make fail for 1.6.1 or master branch

### ISSUE THREAD

**Issue by Rico29** [pmacct/pmacct#68]
Hello,
I have a problem compiling pmacct 1.6.1 or master branch (=1.6.2) : 

sh automake.sh and ./configure are OK, but "make" returns this error : 

gmake[2]: Entering directory `/usr/local/src/pmacct-1.6.1/src'
  CC     libdaemons_la-nl.lo
In file included from bgp/bgp.h:24,
                 from nl.c:37:
bgp/bgp_table.h:33: error: redefinition of typedef ‘afi_t’
isis/isis.h:34: note: previous declaration of ‘afi_t’ was here
bgp/bgp_table.h:34: error: redefinition of typedef ‘safi_t’
isis/isis.h:35: note: previous declaration of ‘safi_t’ was here
gmake[2]: *** [libdaemons_la-nl.lo] Error 1
gmake[2]: Leaving directory `/usr/local/src/pmacct-1.6.1/src'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/usr/local/src/pmacct-1.6.1/src'
make: *** [all-recursive] Error 1

Any tip ?
Regards,
Cédric

**Comment by paololucente** [comment]
Hi Cedric,

Thanks for this. The issue should be solved with the last commit - can you please confirm? Also, since i did never run into such a problem, can you say which OS (and version) did you experience this?

Cheers,
Paolo

**Comment by Rico29** [comment]
Hi Paolo,
Everything is fine after git pull.
I was experiencing this problem on CentOS release 6.7 (Final)
Regards,
Cédric
