### ISSUE TITLE
Issue using direction with nfprobe collector

### ISSUE THREAD

**Issue by ppnaik1890** [pmacct/pmacct#687]
**Description**
We are facing issue leveraging the nfprobe direction with pmacct. Our `pmacct.conf` file is as below:
```
! pmacctd configuration example
! 
!!! docs link::
! https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS
!!! generic flags
daemonize: false
debug: true
! pcap_interface - Capture specific interface (if not set a default interface is selected by the Operating System )
pcap_interface: eth0
!!! plugins - nfprobe is the plugin to export flowlogs
plugins: nfprobe[in], nfprobe[out]

nfprobe_direction[in]:in
nfprobe_direction[out]:out

nfprobe_ifindex[in]: 1
nfprobe_ifindex[out]: 1

!!! flow-logs fields
aggregate: src_host, dst_host, in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, tcpflags
!!! nfprobe plugin configuration
plugin_pipe_size: 102400
timestamps_secs: true
!nfprobe_dont_cache: true
nfprobe_timeouts: tcp=5:tcp.rst=5:tcp.fin=5:udp=5:icmp=5:general=5:maxlife=5
!!! Endpoint to receive flow-logs
nfprobe_receiver: 127.0.0.1:2055
!!! Enable IPFIX
nfprobe_version: 10
```
With this conf file, we see duplicate flow entries marked as `IN` and `OUT`. 
Example flow below:
```
{
    "Type": "IPFIX",
    "TimeReceived": 1685441744,
    "SequenceNum": 0,
    "SamplingRate": 0,
    "FlowDirection": 1,
    "SamplerAddress": "127.0.0.1",
    "TimeFlowStart": 1685441737,
    "TimeFlowEnd": 1685441744,
    "TimeFlowStartMs": 1685441737834,
    "TimeFlowEndMs": 1685441744392,
    "Bytes": 276,
    "Packets": 5,
    "SrcAddr": "9.202.1.92",
    "DstAddr": "9.12.235.167",
    "Etype": 2048,
    "Proto": 6,
    "SrcPort": 51498,
    "DstPort": 9000,
    "InIf": 0,
    "OutIf": 1,
    "SrcMac": "00:00:00:00:00:00",
    "DstMac": "00:00:00:00:00:00",
    "SrcVlan": 0,
    "DstVlan": 0,
    "VlanId": 0,
    "IngressVrfId": 0,
    "EgressVrfId": 0,
    "IpTos": 0,
    "ForwardingStatus": 0,
    "IpTtl": 0,
    "TcpFlags": 19,
    "IcmpType": 0,
    "IcmpCode": 0,
    "Ipv6FlowLabel": 0,
    "FragmentId": 0,
    "FragmentOffset": 0,
    "BiFlowDirection": 0,
    "SrcAs": 0,
    "DstAs": 0,
    "NextHop": "",
    "NextHopAs": 0,
    "SrcNet": 0,
    "DstNet": 0,
    "BgpNextHop": [],
    "BgpCommunities": [],
    "AsPath": [],
    "HasMpls": false,
    "MplsCount": 0,
    "Mpls_1Ttl": 0,
    "Mpls_1Label": 0,
    "Mpls_2Ttl": 0,
    "Mpls_2Label": 0,
    "Mpls_3Ttl": 0,
    "Mpls_3Label": 0,
    "MplsLastTtl": 0,
    "MplsLastLabel": 0,
    "MplsLabelIp": [],
    "ObservationDomainId": 0,
    "ObservationPointId": 0,
    "CustomInteger_1": 0,
    "CustomInteger_2": 0,
    "CustomInteger_3": 0,
    "CustomInteger_4": 0,
    "CustomInteger_5": 0,
    "CustomBytes_1": [],
    "CustomBytes_2": [],
    "CustomBytes_3": [],
    "CustomBytes_4": [],
    "CustomBytes_5": [],
    "CustomList_1": []
  }
  ```
  ```
{
    "Type": "IPFIX",
    "TimeReceived": 1685441744,
    "SequenceNum": 0,
    "SamplingRate": 0,
    "FlowDirection": 1,
    "SamplerAddress": "127.0.0.1",
    "TimeFlowStart": 1685441737,
    "TimeFlowEnd": 1685441744,
    "TimeFlowStartMs": 1685441737834,
    "TimeFlowEndMs": 1685441744392,
    "Bytes": 276,
    "Packets": 5,
    "SrcAddr": "9.202.1.92",
    "DstAddr": "9.12.235.167",
    "Etype": 2048,
    "Proto": 6,
    "SrcPort": 51498,
    "DstPort": 9000,
    "InIf": 0,
    "OutIf": 1,
    "SrcMac": "00:00:00:00:00:00",
    "DstMac": "00:00:00:00:00:00",
    "SrcVlan": 0,
    "DstVlan": 0,
    "VlanId": 0,
    "IngressVrfId": 0,
    "EgressVrfId": 0,
    "IpTos": 0,
    "ForwardingStatus": 0,
    "IpTtl": 0,
    "TcpFlags": 19,
    "IcmpType": 0,
    "IcmpCode": 0,
    "Ipv6FlowLabel": 0,
    "FragmentId": 0,
    "FragmentOffset": 0,
    "BiFlowDirection": 0,
    "SrcAs": 0,
    "DstAs": 0,
    "NextHop": "",
    "NextHopAs": 0,
    "SrcNet": 0,
    "DstNet": 0,
    "BgpNextHop": [],
    "BgpCommunities": [],
    "AsPath": [],
    "HasMpls": false,
    "MplsCount": 0,
    "Mpls_1Ttl": 0,
    "Mpls_1Label": 0,
    "Mpls_2Ttl": 0,
    "Mpls_2Label": 0,
    "Mpls_3Ttl": 0,
    "Mpls_3Label": 0,
    "MplsLastTtl": 0,
    "MplsLastLabel": 0,
    "MplsLabelIp": [],
    "ObservationDomainId": 0,
    "ObservationPointId": 0,
    "CustomInteger_1": 0,
    "CustomInteger_2": 0,
    "CustomInteger_3": 0,
    "CustomInteger_4": 0,
    "CustomInteger_5": 0,
    "CustomBytes_1": [],
    "CustomBytes_2": [],
    "CustomBytes_3": [],
    "CustomBytes_4": [],
    "CustomBytes_5": [],
    "CustomList_1": []
  }
  ```
**Version**
```
pmacct -V
pmacct IMT plugin client, pmacct 1.7.9-git (20230601-0 (dd304a95))
 '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
 ```

Can you please help us debug/fix the issue. Or point us to same configuration required to fix this. Thanks!

**Comment by eranra** [comment]
HI @paololucente, thanks for your help ( in advance :-) 

To extend and crisp the challenge that @ppnaik1890 describes above: 

What we see is that :

nfprobe_direction[in]:in
nfprobe_direction[out]:out

Do not work as we expect :-( it does not filter accurately `in` and `out`

We can get to the behavior we need with two instances of pmacct, each with `pcap_direction:in` and `pcap_direction:out` respectively, but with a single instance of pmacct ( and two configurations of the probs using `nfprobe_direction` ) things do not work. 

To conclude, `pcap_direction` works for us, while `nfprobe_direction` ( in the current way we configure it ) does not work 

@msune @ ^^^

**Comment by paololucente** [comment]
Hi @eranra , @ppnaik1890 ,

First and foremost, thanks for getting in touch.

The behavior you are hitting is expected since for a dynamic attribution of direction using `nfprobe_direction`, as explained in the docs, you should use `tag` or `tag2` values where, in turn, the tag value is the output of a `pre_tag_map` evaluation. You can find an example here: https://github.com/pmacct/pmacct/blob/faf603e3cf1bdb5f4e84bfb82fb2a9784581e13b/QUICKSTART#L1442 . 

Would you have discriminators, ie. subnets, MAC addresses, etc. in orders to make such in/out evaluation possible? If not, ie. if having to rely on the interface where the packet was received from / delivered to then you either need to resort back to `pcap_direction` and multiple instances or to ULOG / NFLOG and hence the `uacctd` daemon.

Of course should we want to explore different ways to accomplish the same, and would you have some proposals, i'd be open to feedback - here or by unicast email.

Paolo

**Comment by eranra** [comment]
@paololucente, thanks for the elaborated answer. Any reason why you are not supporting `pcap_direction` per each of the named probs? This should theoretically allow the usage of just one pmacct instance.

**Comment by paololucente** [comment]
Hi @eranra ,

You could resort to `pcap_interfaces_map`, ie. https://github.com/pmacct/pmacct/blob/07212e786346d6eaa5ab24e21119e52d8b4cdf63/CONFIG-KEYS#L529 , as part of which you could also define a direction per interface (under the hood it does implement the `pcap_direction` per each of the specified interfaces). See an example of the map here: https://github.com/pmacct/pmacct/blob/master/examples/pcap_interfaces.map.example .

Paolo

**Comment by eranra** [comment]
@paololucente this is perfect --- I feel that this is what we need. We will test and report !!!

**Comment by eranra** [comment]
Going to test this right now :-) and update!

**Comment by eranra** [comment]
@paololucente this doesn't seem to work  :-( 

With the configuration map :

```
ifindex=777	ifname=eth0	direction=in
ifindex=888	ifname=eth0	direction=out
```

I get::

```
$ sudo pmacctd -f ./pmacctd.inout.conf
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.9-git (20230601-0 (dd304a95))
INFO ( default/core ):  '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/home/eranra/Downloads/pmacctd.inout.conf'.
INFO ( default/core ): [/home/eranra/Downloads/pmacct.interfaces.map] (re)loading map.
INFO ( default/core ): [/home/eranra/Downloads/pmacct.interfaces.map] map successfully (re)loaded.
ERROR ( default/core ): interface (-i) and pcap_interfaces_map directives are mutually exclusive. Exiting.
```

**Comment by paololucente** [comment]
@eranra , cool. Can you please add to the config `pcap_ifindex: map` and see if that makes your ifIndexes happy?

**Comment by eranra** [comment]
@paololucente this is good enough for us --- but not really consistent, so you might want to fix it. But for us, this should be good enough. It goes like this::

With the following map file::
```
ifindex=100	ifname=eth0	direction=in
ifindex=200	ifname=eth0	direction=out
```

And pmacct file::

```
daemonize: false
timestamps_secs: true

plugins: nfprobe[netflow]

aggregate: src_mac, dst_mac,src_host,dst_host,in_iface,out_iface,src_port, dst_port,proto,tos, tcpflags

aggregate_filter[netflow]: (src net 13 or dst net 13)

pcap_ifindex: map
pcap_interfaces_map: /home/eranra/Downloads/pmacct.interfaces.map

nfprobe_receiver: 127.0.0.1:2055
```

We get::

![image](https://github.com/pmacct/pmacct/assets/3080696/91f36c89-a995-457d-98fc-07631106b032)

With that, we can use the `InIf` and `OutIf` fields to distinguish between in and out flows --- I am not sure why they are both 100 and I am not getting 100 for in and 200 for out this is probably a bug but this is good enough for what we need.

**Comment by eranra** [comment]
@paololucente, thanks for the quick and helpful support  :-)

**Comment by paololucente** [comment]
@eranra , my pleasure. I will add some notes to the docs and close this issue. Wrt the behaviour you are experiencing, i guess it lies in the fact that `nfprobe` does organize uni-directional flows into bi-flows since testing with `print` plugin it did work all right for me. I will do some further investigation on this. Paolo
