### ISSUE TITLE
Get IP flows exporter

### ISSUE THREAD

**Issue by balioune** [pmacct/pmacct#691]
**Description**
Hi all,
I'm collecting Netflow traffic using pmacct and I wonder how to get the IP of flow exporter (router) with aggregate parameter 

** Like this **
aggregate: src_host, dst_host, src_port, dst_port, src_as, dst_as, label, ..., exporter
Thanks

**Comment by paololucente** [comment]
Hi @balioune ,

You are looking for the `peer_src_ip` primitive.

Paolo
