### ISSUE TITLE
configure: error: Could not find libcdada

### ISSUE THREAD

**Issue by skinfrakkiirid** [pmacct/pmacct#709]
Issue after fixing previous issue on Red Hat 8:

checking for cdada_get_ver in -lcdada... no
configure: error: Could not find libcdada

**Comment by skinfrakkiirid** [comment]
yum whatprovides /libcdada

Error: No Matches found

**Comment by paololucente** [comment]
Hi @skinfrakkiirid , 

Thanks for getting in touch. When you say Red Hat 8, do you mean RHEL 8? Master code is tested against RockyLinux 8/9 and, until recently, it was tested against CentOS 7/8 -- i am not sure about RHEL 8.

For sure libcdada is not available via yum. If cloning the pmacct repo here on GitHub, libcdada will be automatically downloaded for you as a dependency (you don't have to do any extra action); if downloading the latest released code, ie. `http://www.pmacct.net/pmacct-1.7.8.tar.gz`, libcdada is part of the tarball. I may only foresee problems if you use the GitHub release artifacts, ie. `https://github.com/pmacct/pmacct/archive/refs/tags/v1.7.8.tar.gz` (simply don't use them). 

Paolo
