### ISSUE TITLE
route distinguisher (RD) looks wired when dump the BGP table.

### ISSUE THREAD

**Issue by m4ccbr** [pmacct/pmacct#73]
Hi,

I started playing with pmacct and I noticed that the route distinguisher RD looks wired when dumping the BGP table in a file. Is there any reason why?

here it is an example:

"rd": "1:40.0.17.10:256

The IP address is inverted, it should be 10.17.0.40 and the 2nd part should be 1806 instead.
Is this a bug? pls find below the complete output from the file. 

[root@hostname]# cat bgp-10_197_1_114-2016_11_29T20_05_00.txt | grep 10.12.95.16
{"timestamp": "2016-11-29 20:05:00", "peer_ip_src": "10.17.1.14", "event_type": "dump", "ip_prefix": "10.12.95.16/28", "bgp_nexthop": "10.17.1.14", "as_path": "65346", "comms": "65346:39", "ecomms": "RT:65432:2", "origin": 0, "local_pref": 100, "rd": "1:40.0.17.10:256"}

BR

**Comment by paololucente** [comment]
Hi Alberto,

Thanks for submitting this issue. As you see i was able to reproduce and fix it. Can you please see if latest code works for you?

Thanks,
Paolo

**Comment by m4ccbr** [comment]
Hi, looks great now :) (Y), I will execute more tests and I let you now
