### ISSUE TITLE
Sample configuration for pmbmp writing into a kafka 

### ISSUE THREAD

**Issue by ACodingfreak** [pmacct/pmacct#734]
Hi All,

I am new to pmacct and wanted to check if there is any example with respect to pmbmp where pmacct acts a BMP collector and writes all BMP messages into a kafka bus.

I was only successful in bringing up the BMP session between cisco iosxr and pmacct and writing the messages into a file with below configurations

cat /etc/pmacct/pmbmpd.conf
!
bmp_daemon: true
bmp_daemon_msglog_output: /var/log/pmacct/bmp.log
bmp_daemon_ipprec: 4
!

pmbmp -f /etc/pmacct/pmbmpd.conf

**Comment by paololucente** [comment]
Hi @ACodingfreak ,

Would this help to get minimally started? https://github.com/pmacct/pmacct/blob/0b5dd0aefa19f5a7a874e929d8c5f8f2b2074de6/QUICKSTART#L2408

Paolo
