### ISSUE TITLE
Triggered processes by print module being infinitely leaved in zombie state

### ISSUE THREAD

**Issue by MuriloChianfa** [pmacct/pmacct#737]
**Description**
Hello guys, im testing the nfacctd with print module, and i have founded a bug when using the "**print_trigger_exec**" cfg key.

If I leave it on for a long time, it creates many processes with a zombie state, like this:
![zombies](https://github.com/pmacct/pmacct/assets/60560085/5e7b26c2-b091-4b26-a0e0-97ed2ec3616a)

The longer I leave it running, the more of these processes are created, until there comes a point where the machine is very slow.
Do you think I'm doing something wrong?

My lab environment:
![current-state](https://github.com/pmacct/pmacct/assets/60560085/e797d86f-7333-4bbe-a352-a2faa65ef367)

**Version**
Using official latest docker image.
```bash
NetFlow Accounting Daemon, nfacctd 1.7.8-git [20221231-1 (723b0cb2)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.8.1
MariaDB 10.3.36
PostgreSQL 110018
sqlite3 3.27.2
rabbimq-c 0.11.0
rdkafka 2.0.0
jansson 2.14
MaxmindDB 1.7.1
ZeroMQ 4.3.2
Redis 1.1.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 4.2.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64

Compiler:
gcc 8.3.0
```

**Appreciation**
My appreciations, kind regards, from Brazil.

**Comment by paololucente** [comment]
Ola' @MuriloChianfa , can you please try the `bleeding-edge` container instead of `latest` and check if you are still getting those zombies? Also, should you try with a dumb script, say just a script that does nothing or exits - do you still get the zombies? Paolo

**Comment by MuriloChianfa** [comment]
Using now with bleeding-edge version and a dumb script but the problem still occurring.
I also noticed that the more plugins: print[x]... we have, the faster it fills with zombies.

_Version:_
pmacct IMT plugin client, pmacct 1.7.9-git (20231101-0 (a091a85e))

**Comment by paololucente** [comment]
Hi @MuriloChianfa ,

Please see revised documentation part of this commit https://github.com/pmacct/pmacct/commit/d00d45e4fdb22bc9599c9fb6b0ee4ea92e46b6c3 . In short, when running Docker, please do it with the `--init` flag or `init: true` if using docker-compose; that should do.

Paolo
