### ISSUE TITLE
MPLS VPN v6 prefixes is not dump to a file

### ISSUE THREAD

**Issue by m4ccbr** [pmacct/pmacct#74]
Hi, 
As you could notice below, I'm dumping the BGP to a file and I'm not able to see MPLS VPN IPv6 prefixes in the dumped file.

Here it is the configuration I'm using today.

[root@linux-9dc70 etc]# cat pmacct.conf                                           
                                                                                  
interface: eno33559296                                                            
bgp_daemon: true                                                                  
bgp_daemon_ip: 10.17.1.18                                                       
bgp_agent_map: /opt/pmacct/peers.map                                              
                                                                                  
bgp_table_dump_file: /opt/pmacct/log/bgp-$peer_src_ip-%Y_%m_%dT%H_%M_%S.txt       
bgp_table_dump_refresh_time: 180    

[root@linux-9dc70 log]# cat bgp-10_197_1_114-2016_12_05T16_18_00.txt | grep 2001
[root@linux-9dc70 log]# 

here it is a printout from my router where I peer with the bgp daemon.
  Table bgp.l3vpn-inet6.0 Bit: 20002
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Advertised prefixes:          5022

user1@hostname-re0> show bgp neighbor 10.17.1.18 
Peer: 10.17.1.18+179 AS 65001 Local: 10.17.1.14+50967 AS 65001
  Description: pmacct
  Type: Internal    State: Established  (route reflector client)Flags: <Sync RSync>
  Last State: EstabSync     Last Event: RecvKeepAlive
  Last Error: Hold Timer Expired Error
  Export: [ BGP_EXPORT ] Import: [ BGP_IMPORT ]
  Options: <Preference Cluster AddressFamily Rib-group Refresh>
  Options: <MtuDiscovery>
  Address families configured: inet-vpn-unicast inet6-vpn-unicast
  Holdtime: 90 Preference: 170
  Number of flaps: 30
  Last flap event: Closed
  Error: 'Hold Timer Expired Error' Sent: 1 Recv: 0
  Peer ID: 10.17.1.18    Local ID: 10.17.25.1      Active Holdtime: 90
  Keepalive Interval: 30         Group index: 2    Peer index: 0   
  BFD: disabled, down
  NLRI for restart configured on peer: inet-vpn-unicast inet6-vpn-unicast
  NLRI advertised by peer: inet-vpn-unicast inet6-vpn-unicast
  NLRI for this session: inet-vpn-unicast inet6-vpn-unicast
  Peer does not support Refresh capability
  Stale routes from peer are kept for: 300
  Peer does not support Restarter functionality
  Peer does not support Receiver functionality
  Peer supports 4 byte AS extension (peer-as 65001
  Peer does not support Addpath
  Table bgp.l3vpn.0 Bit: 10002
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: in sync
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
    Advertised prefixes:          47761
  Table bgp.l3vpn-inet6.0 Bit: 20002
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: in sync                 
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
    Advertised prefixes:          5022
  Table VRF1.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF2.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF3.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF4.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0     
  Table VRF5.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF6.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF7.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF8.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF9.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0     
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF10.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF11.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF12.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF13.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF14.inet6.0
    RIB State: BGP restart is complete  
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF15.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF16.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF17.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF18.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0     
    Suppressed due to damping:    0
  Table VRF19.inet.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Table VRF20.inet6.0
    RIB State: BGP restart is complete
    RIB State: VPN restart is complete
    Send state: not advertising
    Active prefixes:              0
    Received prefixes:            0
    Accepted prefixes:            0
    Suppressed due to damping:    0
  Last traffic (seconds): Received 26   Sent 1    Checked 24  
  Input messages:  Total 11941  Updates 0       Refreshes 0     Octets 226879
  Output messages: Total 107333 Updates 95391   Refreshes 0     Octets 18099491
  Output Queue[0]: 0
  Output Queue[1]: 0
  Output Queue[2]: 0
  Output Queue[3]: 0
  Output Queue[4]: 0
  Output Queue[5]: 0
  Output Queue[6]: 0
  Output Queue[7]: 0
  Output Queue[8]: 0
  Output Queue[9]: 0
  Output Queue[10]: 0
  Output Queue[11]: 0
  Output Queue[12]: 0
  Output Queue[13]: 0
  Output Queue[14]: 0
  Output Queue[15]: 0
  Output Queue[16]: 0                   
  Output Queue[17]: 0
  Output Queue[26]: 0
  Output Queue[27]: 0
  Output Queue[29]: 0
  Output Queue[30]: 0

**Comment by paololucente** [comment]
Hi Alberto,

Can you please confirm pmacct was compiled with --enable-ipv6 ? You can confirm that with a /path/to/<pmacct_daemon> -V

Paolo

**Comment by m4ccbr** [comment]
Hi Paolo,

here it is the output:
[root@linux-9dc70 sbin]# ./pmacctd -V
Promiscuous Mode Accounting Daemon, pmacctd 1.6.2-git (20161204-00)
 '--enable-plabel' '--bindir=/opt/pmacct/bin' '--sbindir=/opt/pmacct/sbin'
'--sysconfdir=/opt/pmacct/etc/' '--enable-jansson' '--enable-ipv6'

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net
>.

thx


Alberto Santos CCIE #26648
JNCIS-SP
*"...Fix your DNS, make it dual-stack, take your mail server and make it
dual-stack, take your web server and make it dual-stack..." by Randy
Bush/RIPE IPv6*

**Comment by paololucente** [comment]
Hi Alberto,

Can you please test latest code and check IPv6 MPLS VPN NLRIs are now making it to the dump?

Paolo

**Comment by m4ccbr** [comment]
I've just tested and now I can see MPLS VPN v6 in th file 

thx a lot again
