### ISSUE TITLE
Question | Application ID having length of 4.

### ISSUE THREAD

**Issue by smit1682** [pmacct/pmacct#741]
**Description**

Hello,
I am using V9 NetFlow from Cisco Switch when I use nfacctd to parse this flow, I am getting **unknown** in the class field,
so first I captured this flow via Wireshark, I found that in the flow template, **the application ID has length 4,** and it has the application name,

In codebase of pmacct I found that there is one check in process_v9_packet method, which is,

  `if ((tpl->tpl[NF9_APPLICATION_ID].len == 2 || tpl->tpl[NF9_APPLICATION_ID].len == 3 || tpl->tpl[NF9_APPLICATION_ID].len == 5) &&
	    tpl->tpl[NF9_APPLICATION_NAME].len > 0)`
	    
same condition is applied in NF_process_classifiers method

so I changed that with below condition,

`if (tpl->tpl[NF9_APPLICATION_ID].len > 0)`

now, i found that application name is being resolved in class field, and found less occurrence of unknown.

But i found this log,
`2023-11-08T19:48:03+05:30 WARN ( default/core ): Finished elements in class table (512). Raise via classifier_table_num.`

which is ouccred only one time,
so i have three questions, about this scenario
1) what is this condition of application id length stands for ? 
2) what wrong can be happened when i changed to application length > 0 ?
3) what is the reason of warning log.

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.9-git [20230328-0 (33209e86)]

Arguments:
 '--prefix=/usr/local/pmacct' '--enable-jansson' '--enable-zmq' '--enable-ndpi' 'PKG_CONFIG_PATH=/usr/local/pmacct/lib/pkgconfig' 'NDPI_CFLAGS=-I/opt/nDPI-4.6-stable/src/include' 'NDPI_LIBS=-L/opt/nDPI-4.6-stable/src/lib/.libs -lndpi' 'JANSSON_LIBS=-L/usr/local/pmacct/lib -ljansson' 'JANSSON_CFLAGS=-I/usr/local/pmacct/include' 'ZMQ_LIBS=-L/usr/local/pmacct/lib -lzmq' 'ZMQ_CFLAGS=-I/usr/local/pmacct/include' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.9.1 (with TPACKET_V3)
jansson 2.14
ZeroMQ 4.3.5
nDPI 4.6.0

Plugins:
memory
print
nfprobe
sfprobe
tee

System:
Linux 5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64

Compiler:
gcc 9.4.0

**Comment by paololucente** [comment]
Hi @smit1682 , any chance you could share privately (by email) a brief pcap sample of your NetFlow (templates, options and flows) so to more effectively look into this issue? Paolo

**Comment by smit1682** [comment]
@paololucente i have shared pcap to id: `paolo@pmacct.net` with subject `PMACCT | issue: Application ID having length of 4.`

**Comment by paololucente** [comment]
Hi Smit ( @smit1682 ),

With the two commit above this issue should be resolved. One makes sure ApplicationID with length 4 makes through. The other allows to increase the classifiers cache via `classifier_num_roots`, i tried setting it to 10240 against your pcap trace and all worked well. Let me know if it all appears to work for you too.

Paolo
