### ISSUE TITLE
Question: nfacctd storage

### ISSUE THREAD

**Issue by Winsor** [pmacct/pmacct#743]
**Description**

Hello!
Can I configure nfacctd to save ipfix flow to binary file instead of database? print plugin output only to text file?
ipfix_exporter->nfacctd_collector->nfacctd_aggregate->binary file...
Thanks for the infos!

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.9-git [20231110-0 (fa1ddcd4)] 

Arguments:
 '--enable-pgsql' '--enable-jansson' '--enable-l2'  '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.5.0
libpcap version 1.8.1
PostgreSQL 90624
jansson 2.9

Plugins:
memory
print
nfprobe
sfprobe
tee
postgresql

System:
Linux 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64

**Comment by paololucente** [comment]
Hi @Winsor ,

Can you qualify better your question? When you say binary, do you mean a binary format? If so, pmacct does support Apache Avro (and i can elaborate more about it); if, instead, you are looking for a binary dump of the packets from the wire, no, that is not supported as there are other tools for that (tshark, tcpdump, etc.).

Paolo

**Comment by Winsor** [comment]
I would like to use the nfacctd as a collector and aggregator (to reduce the space occupied by data), and then use any software (self-made or others) to process the data. Processing tasks occur quite rarely, so the main task is storage. since the main task is data collection - I use local postgresql and 2nd tablespaces - active (ext3) and archive (based on btrfs). ~600kk records remain in one table after the current aggregation, one table per day. Unfortunately, one "select...where..." on one table can take up to 20 minutes... and if I need statistics, for example, for a month - then it is a pain. exactly a binary file, for example in the format https://www.ietf.org/archive/id/draft-ietf-ipfix-file-01.html.

**Comment by paololucente** [comment]
Thanks of the further elaboration, @Winsor . I am checking with people familiar to that draft to better understand where things stand. Allow me a couple of days for such investigation, meanwhile let me confirm there is no such support available right now. Paolo

**Comment by rightkick** [comment]
For better performance I would look into exporting netflow and then working
with netflow data or export to rabbitmq and then have them stored to some
time series db for better performance.

**Comment by Winsor** [comment]
@paololucente thank you! I will wait for answers.


> For better performance I would look into exporting netflow
thanx! yes, i was thinking about the intermediate stage too , but my problem is that I did not find a way to save the data to a local file only with nfacctd for further processing. as example:
juniper_ipfix_flows -> nfacctd_collector + nfacctd_aggregator -> ???? ->processing_stored_neflow/ipfix -> time_series_db
????  - 
if it is tee plugin - how to save it to a file?
if it is amqp plugin - do you have an example of using rabbitmq to store ipfix to file?

**Comment by paololucente** [comment]
Hi @Winsor ,

I did speak to somebody "close to the matter" and it was confirmed that that draft would result in "just another binary format" without any specific space / processing advantage compared to generic binary formats. We speak here binary formats but let's not underestimate the space performance of good old JSON files then passed through a `gzip -9`.

So a pipeline may look like: juniper_ipfix_flows -> nfacctd_collector + nfacctd_aggregator -> print plugin (writing to local files).

For sure i would recommend against storing data in a relational database, like @rightkick was saying, it's not going to scale; if you like PostgreSQL, you could use TimescaleDB (time-series engine for PostgreSQL) with compression and all. In this case the pipeline could look like:  juniper_ipfix_flows -> nfacctd_collector + nfacctd_aggregator -> kafka plugin -> kafka <- TimescaleDB. 

Let me know if you like one scenario better than the other - assuming you like at least one :) I can then point you to further examples and docs.

Paolo

**Comment by Winsor** [comment]
Thanks for the answer!
> processing advantage compared to generic binary formats
in which binary formats, in principle, nfacctd can store data, except for db? print plugin store in different text formats only,if i'm not mistaken... I had hoped that the binary format would allow to reduce the space and simplify the processing of the request. after all, it is easy to process the json, but before that it needs to be unzipped, which takes some time during processing.

> the space performance of good old JSON files then passed through a `gzip -9`
is it possible to save data through the plugin immediately in a compressed form?

> For sure i would recommend against storing data in a relational database
> Let me know if you like one scenario better than the other
looking at my tasks desires in general - what can you recommend? basic requirements:
aggregation at the initial stage
maximum storage of statistics
reduction of intermediate stages (as example, if it is a print - then compression on the fly, without an additional pipe).

**Comment by Winsor** [comment]
@paololucente  thanks for the clarification!
