### ISSUE TITLE
Trouble writing data to database

### ISSUE THREAD

**Issue by udostanic** [pmacct/pmacct#747]
Hello, I'm using sfacctd and I have problem with writing data to database. I have tried to write data to a txt file and it is working. I'm using PostgreSQL. In /var/log/syslog I have this error.
![image](https://github.com/pmacct/pmacct/assets/22859855/984ffe1c-7f63-4427-9732-a62a2b379f81)

This is from /var/log/postgresql/
![image](https://github.com/pmacct/pmacct/assets/22859855/924d88ba-19c7-4750-b23a-7153aa3e590b)

I have created database and granted all privileges to user, also in config file I have set sql_host, sql_user, sql_passwd, sql_db. What am I doing wrong?

**Comment by paololucente** [comment]
Hi @udostanic , 

If you try to connect by hand with `psql`, does it work? I mean not only using the DB, username and password but also forcing the connection to go via TCP, ie. `psql [ .. ] -h localhost`. 

Paolo

**Comment by udostanic** [comment]
Hello @paololucente,
I have tried to connect to psql through terminal like you mentioned and it works fine.

**Comment by paololucente** [comment]
Whav version of pmacct are you using? A copy/paste of `sfacctd -V` would do.

**Comment by udostanic** [comment]
![image](https://github.com/pmacct/pmacct/assets/22859855/816fe7f8-d5fa-4b99-a9ec-480dafd2e24b)

**Comment by paololucente** [comment]
Unfortunately that output omits the most important info on the first line where version and commit version is present

**Comment by udostanic** [comment]
Sorry for bad screenshot, here is a full version
![image](https://github.com/pmacct/pmacct/assets/22859855/6f172ed7-46de-4210-befd-2951761db52c)

**Comment by paololucente** [comment]
Thanks @udostanic , while i try to reproduce, can you just try removing the `sql_host` from the config and connect with the local database without using TCP? Or do you have some specific reason to prefer TCP over UNIX socket? Paolo

**Comment by udostanic** [comment]
I tried to remove `sql_host` from config and it still won't write data to database. Database and application are on the same server so there isn't specific reason to use TCP. I confirm that I have PostgreSQL 14 running on the server.

I don't have any errors in PostgreSQL log, so I have used syslog where I see same error from the first post in this thread:
![image](https://github.com/pmacct/pmacct/assets/22859855/3ba34e1d-30fa-46b6-a294-b6a5c024ff49)

**Comment by paololucente** [comment]
Hi @udostanic ,

I was able to reproduce the issue and the last commit should address it. Could you please download latest master code and confirm it working for you?

Paolo

**Comment by udostanic** [comment]
I've tested with new version and everything works fine. Thanks @paololucente

**Comment by paololucente** [comment]
Thanks for confirming @udostanic
