### ISSUE TITLE
Add IPv6 support to Proxy Protocol Header parsing

### ISSUE THREAD

**Issue by pothier-peter** [pmacct/pmacct#748]
**Description**
The Proxy Protocol Header code in src/network.c only supports IPv4.
Add support for IPv6.

**Version**
pmbmpd 1.7.8

**Appreciation**
Thank you Paolo. I am willing to contribute this IPv6 support code.

**Comment by paololucente** [comment]
Hi Peter ( @pothier-peter ), Absolutely, that would be a very useful contribution. Look forward if you could contribute the code to implement it! Paolo

**Comment by pothier-peter** [comment]
Pull Request: https://github.com/pmacct/pmacct/pull/750
