### ISSUE TITLE
Not all prefixes in the BGP table is dumped to a file.

### ISSUE THREAD

**Issue by m4ccbr** [pmacct/pmacct#75]
Hi,

I'm dumping the BGP table every 3 minutes and I realized we are missing some prefixes in the dumped file.
We are currently advertising 47761 prefixes, but not all prefixes get dumped. When comparing the file size together with the amount of prefixes we send, it looks like we are missing a lot of routes in the BGP file.

Amount of prefixes sent:
RIB State: VPN restart is complete
Advertised prefixes: 47761

amount of lines in the BGP file.
[root@linux-9dc70 pmacct]# wc -l  bgp-10_197_1_114-2016_12_05T16_21_00.txt 
38762 bgp-10_197_1_114-2016_12_05T16_21_00.txt

here it is the config we are using today: 
[root@linux-9dc70 etc]# cat pmacct.conf                                           
                                                                                  
interface: eno33559296                                                            
bgp_daemon: true                                                                  
bgp_daemon_ip: 10.17.1.18                                                       
bgp_agent_map: /opt/pmacct/peers.map                                              
                                                                                  
bgp_table_dump_file: /opt/pmacct/log/bgp-$peer_src_ip-%Y_%m_%dT%H_%M_%S.txt       
bgp_table_dump_refresh_time: 180    

printout from the router.
user1@hostname-re0> show bgp neighbor 10.17.1.18
Peer: 10.17.1.18+179 AS 65001 Local: 10.17.1.14+50967 AS 65001
Description: pmacct
Type: Internal State: Established (route reflector client)Flags: 
Last State: EstabSync Last Event: RecvKeepAlive
Last Error: Hold Timer Expired Error
Export: [ BGP_EXPORT ] Import: [ BGP_IMPORT ]
Options: 
Options: 
Address families configured: inet-vpn-unicast inet6-vpn-unicast
Holdtime: 90 Preference: 170
Number of flaps: 30
Last flap event: Closed
Error: 'Hold Timer Expired Error' Sent: 1 Recv: 0
Peer ID: 10.17.1.18 Local ID: 10.17.25.1 Active Holdtime: 90
Keepalive Interval: 30 Group index: 2 Peer index: 0
BFD: disabled, down
NLRI for restart configured on peer: inet-vpn-unicast inet6-vpn-unicast
NLRI advertised by peer: inet-vpn-unicast inet6-vpn-unicast
NLRI for this session: inet-vpn-unicast inet6-vpn-unicast
Peer does not support Refresh capability
Stale routes from peer are kept for: 300
Peer does not support Restarter functionality
Peer does not support Receiver functionality
Peer supports 4 byte AS extension (peer-as 65001
Peer does not support Addpath
Table bgp.l3vpn.0 Bit: 10002
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: in sync
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Advertised prefixes: 47761
Table bgp.l3vpn-inet6.0 Bit: 20002
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: in sync
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Advertised prefixes: 5022
Table VRF1.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF2.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF3.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF4.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF5.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF6.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF7.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF8.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF9.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF10.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF11.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF12.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF13.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF14.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF15.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF16.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF17.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF18.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF19.inet.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Table VRF20.inet6.0
RIB State: BGP restart is complete
RIB State: VPN restart is complete
Send state: not advertising
Active prefixes: 0
Received prefixes: 0
Accepted prefixes: 0
Suppressed due to damping: 0
Last traffic (seconds): Received 26 Sent 1 Checked 24
Input messages: Total 11941 Updates 0 Refreshes 0 Octets 226879
Output messages: Total 107333 Updates 95391 Refreshes 0 Octets 18099491
Output Queue[0]: 0
Output Queue[1]: 0
Output Queue[2]: 0
Output Queue[3]: 0
Output Queue[4]: 0
Output Queue[5]: 0
Output Queue[6]: 0
Output Queue[7]: 0
Output Queue[8]: 0
Output Queue[9]: 0
Output Queue[10]: 0
Output Queue[11]: 0
Output Queue[12]: 0
Output Queue[13]: 0
Output Queue[14]: 0
Output Queue[15]: 0
Output Queue[16]: 0
Output Queue[17]: 0
Output Queue[26]: 0
Output Queue[27]: 0
Output Queue[29]: 0
Output Queue[30]: 0

**Comment by paololucente** [comment]
Hi Alberto,

Can you please perform some analysis on these 38k routes dumped vs 47k routes injected? For example: if you test several times, is it always the same set of routes being dumped? If yes: can you get a few prefixes that do not make it and determine similarities? Output of any other test(s) that you may think of is of course welcome.

Paolo

**Comment by m4ccbr** [comment]
Hi Paolo, for some reason it looks ok now, I always had issues with the old versions 1.6.0 and 1.6.1, but with 1.6.2 it looks like I get all of IPv4 routes. I will try the new code and monitor the files again.

**Comment by paololucente** [comment]
Hi Alberto, I'm going to close this issue for now. Feel free to re-open it in case you bump into the issue again.

Cheers,
Paolo
