### ISSUE TITLE
nfacctd_templates_receiver  container Operation not permitted

### ISSUE THREAD

**Issue by triggerhappy17** [pmacct/pmacct#751]
Hi and thanks for this great project and any support provided. 

**Description**
when attempting to use your container as a rootless user and setting 'nfacctd_templates_receiver' the application fails to start - 
ERROR ( default/core ): socket() error: Operation not permitted

running the container as root with --privileged option allows the container to start. Why would this option require elevated privileged? The port is > 1024

running the container as the root user with podman without --privilege gives the below seg fault

nfacctd[852464]: segfault at e1a8 ip 000055d50a853df1 sp 00007ffcc54efc70 error 4 in nfacctd[55d50a77f000+117000] likely on CPU 71 (core 17, socket 1)
Code: 89 df 74 5d 48 8d 4c 24 08 48 8d 54 24 10 c7 44 24 18 02 00 00 00 e8 1e cb f2 ff 83 f8 ff 74 1c 48 8b 6c 24 08 48 85 ed 74 12 <48> 8b 75 18 48 85 f6 74 09 8b 55 10 41 3b 14 24 76 3d 48 83 c4 4

Reproduce:
set below option in your conifguration and run container as a rootless user
nfacctd_templates_receiver: x.x.x.x:10000

podman run --rm  --privileged  --volume conf/:/etc/pmacct:ro docker.io/pmacct/nfacctd:v1.7.8

note, application will start with debug enabled but segfaults after a few seconds.

**Version**
docker.io/pmacct/nfacctd:v1.7.8

it would be nice to understand this limitation and any known workarounds. Running this application rootless works very well until we wish to spin up more instances, requiring nfacctd_templates_receiver feature.

**Comment by triggerhappy17** [comment]
Adding -cap-add SYS_ADMIN resolves this but grants extra privileges that might not be required

**Comment by paololucente** [comment]
Hi @triggerhappy17 ,

Super user privileges are needed because templates, in order to make sense to a final receiver, have to be spoofed so that it looks like the original sender is sending them over. Spoofing requires socket flags that are restricted to super user only. Hope this explains.

Paolo

**Comment by triggerhappy17** [comment]
thanks for your quick reply.

I am quite new to the container world and ipfix/netflow but I suspect this operation is not available in a non-root container unless you have any experience you can share. I was thinking about having nfacct spun up in a container which could clone on load and send templates to a loadbalance which would send to a tee instance to share amongst all containers. 

something like the below:
                              ----- nfacct1                              
--> IPFIX --> VIP |                            | templates VIP ----|   ----- tee1   (TEE VIP to push templates to frontend )
                              -----nfacct2                           

Do you have any plans to offer on supporting  a message bus for sharing templates ? Ie: kafka / rabbitmq / redis - produce/consume  templates which would not require elevate privileges?

**Comment by paololucente** [comment]
Hi @triggerhappy17 ,

> I suspect this operation is not available in a non-root container

That is right.

> Do you have any plans to offer on supporting a message bus for sharing templates ? Ie: kafka / rabbitmq / redis - produce/consume templates which would not require elevate privileges?

Unfortunately this is not currently in the plans and it's not a quick win either.

Paolo
