### ISSUE TITLE
Adding timestamp to stderr logging

### ISSUE THREAD

**Issue by sgaragan** [pmacct/pmacct#759]
**Description**
When deploying pmacct on Kubernetes, logging is configured to be sent to stderr which is the standard logging model for a K8s deployment.  However, the log messages do not seem to have any timestamps so there is no way to know when an issue occurred.  For the log messages sent to syslog or a specific log file, timestamps are included with those messages (in syslog via the vsyslog function, log file has timestamps explicitly added to the output message)

**Version**
1.7.10

**Comment by job** [comment]
Pipe the proces output into `ts` or `logger`?

**Comment by job** [comment]
https://medium.com/@linuxschooltech/creating-timestamps-with-the-ts-command-in-linux-4e5e49f78278

**Comment by paololucente** [comment]
Hi Sean ( @sgaragan ), in addition to the suggestion from the great @job i have passed a patch to uniform the output of stderr and logfile, hence including a timestamp in the stderr output. Tested it, it seems to work fine, please give it a try yourself (see commit above). I have also added a piece of documentation for people upgrading since this will break any script parsing stderr output. Paolo

**Comment by job** [comment]
@paololucente is that enabled by default? I'm not sure timestamping should be enabled by default, as it breaks with conventions

**Comment by paololucente** [comment]
I made it new default but, sure, i could totally make it optional and save backward compatibility. Let me go in this direction.

**Comment by sgaragan** [comment]
> Hi Sean ( @sgaragan ), in addition to the suggestion from the great @job i have passed a patch to uniform the output of stderr and logfile, hence including a timestamp in the stderr output. Tested it, it seems to work fine, please give it a try yourself (see commit above). I have also added a piece of documentation for people upgrading since this will break any script parsing stderr output. Paolo

Thanks Paolo, I will look at getting it redeployed when the change goes in with the optional config (which I agree makes sense, if making it a default will break backward compatibility)

**Comment by paololucente** [comment]
Hi Sean ( @sgaragan ), Job ( @job ), this is now done. The config knob to enable timestamp when logging on stderr is `log_stderr_tstamp`, by default false. It should be set to `true` in the config, ie. : `log_stderr_tstamp: true` to enable the feature. Will also review documentation soon. Paolo
