### ISSUE TITLE
[nfacctd] Setting AS information from BGP no longer works in bleeding-edge

### ISSUE THREAD

**Issue by SanderDelden** [pmacct/pmacct#768]
**Description**
In the latest commit (bleeding-edge) setting `nfacctd_as` to `bgp` will result in the ASN for all flows being set to 0. Changing the setting to `netflow` results in the correct AS data being printed again. The same thing goes for `bgp_peer_src_as_type`.

Setting both `nfacctd_as` and `bgp_peer_src_as_type` to `bgp` in 1.7.8 works without any issues. 

**Version**
The `bleeding-edge` Docker tag was used: nfacctd 1.7.10-git (20240312-1 (2a627473))

**Appreciation**
Please consider starring this project to boost our reach on github!
✅

If any additional information is required, please let me know.

**Comment by paololucente** [comment]
Hi Sander ( @SanderDelden ),

I had a quick try at this and i seem unable to reproduce the issue. Is the config in Issue 769 valid also for this issue? Also, can you look in the log if there is anything suspicious? Any warning / error message?

Paolo

**Comment by SanderDelden** [comment]
Hi Paolo,

My apologies, should've included the configuration in my initial comment. I've stripped the configuration down to the bare minimum for testing purposes, here you go:

`nfacctd.conf`:
```
plugins: print[TEST]

bgp_daemon: true
bgp_daemon_port: 179
nfacctd_as: bgp
bgp_daemon_max_peers: 1
bgp_agent_map: /etc/pmacct/mappings/bgp.map
nfacctd_port: 5009

aggregate[TEST]: dst_as
print_output_file[TEST]: /tmp/pmacct/1m_TEST.json
print_output[TEST]: json
print_history[TEST]: 1m
print_history_roundoff[TEST]: m
print_refresh_time[TEST]: 60
print_output_file_append[TEST]: true
```

`bgp.map`:
```
bgp_ip=x.x.x.x  ip=0.0.0.0/0
```

All entries in `1m_TEST.json` look as follows:
```
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:48:00", "stamp_updated": "2024-03-15 09:50:01", "packets": 101479, "bytes": 100798205}
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:49:00", "stamp_updated": "2024-03-15 09:50:01", "packets": 144579, "bytes": 143524105}
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:49:00", "stamp_updated": "2024-03-15 09:51:01", "packets": 99910, "bytes": 99144753}
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:50:00", "stamp_updated": "2024-03-15 09:51:01", "packets": 140996, "bytes": 139505374}
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:50:00", "stamp_updated": "2024-03-15 09:52:01", "packets": 102410, "bytes": 102121809}
{"event_type": "purge", "as_dst": 0, "stamp_inserted": "2024-03-15 09:51:00", "stamp_updated": "2024-03-15 09:52:01", "packets": 142988, "bytes": 141700933}
```

The configuration above works in 1.7.8 but the first purge of the cache has all the AS numbers listed as "0". I assume this has to do with the BGP session not being instantly established. This is no problem, just thought I'd mention it.

I've check the (debug) logging and nothing strange is observed.

**Comment by paololucente** [comment]
Hi Sander ( @SanderDelden ),

I did manage to reproduce the scenario but unfortunately not the issue - both 1.7.8 and latest commit do work fine. Can you try to set `nfacctd_net: bgp` too and see if it makes any difference? Also, any ADD-PATH capability involved in the BGP feed?

Paolo

**Comment by SanderDelden** [comment]
Hi Paolo,

Setting `nfacctd_net: bgp` unfortunately does not change the output. We are not using ADD-PATH. If it is of use to you I can provide a PCAP of the BGP traffic.

**Comment by SanderDelden** [comment]
Hi Paolo,

Would a Teams session (or any other application of your preference) to debug this be possible?

**Comment by paololucente** [comment]
This could work, yes. Can we switch to unicast email for the details?

**Comment by paololucente** [comment]
Summarizing troubleshooting that took place by unicast email: flow data was including ingress / egress VRF ID. Recent code got more rigorous respecting presence of these fields, as a result of that the lookup in Global Routing Table did not work out.

To facilitate the outcome of the new situation a new feature was developed and a piece of documentation added,
https://github.com/pmacct/pmacct/blob/3962f97ce755274059a0d37646ab65920b8ff72b/UPGRADE#L11 . With these pieces in place, the resolution of the issue was successful.

Paolo
