### ISSUE TITLE
Sflow ipv6 tos field parsing of Traffic Class field in packet header.

### ISSUE THREAD

**Issue by supaflyg** [pmacct/pmacct#772]
**Description**
Sfacctd tos field is omitting right 2 bits of the tc field for ipv6 sflow sampled traffic. 

Example: sfacctd ipv6 tos field returns value 28 with TC value of  00011100 and 00011101.

Ipv4 tos values are representative of the TOS in the packet header.

If this is expected behavior is there method or means to extract the value of all 8 bits of the ipv6 TC field?

If not, is there a configuration or setting that I am missing for ipv6 tos field parsing?

**Version**
$ sfacctd -V
sFlow Accounting Daemon, sfacctd 1.7.8-git [RELEASE]

Arguments:
 '--enable-jansson' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-st-bins' '--enable-kafka' '--enable-bgp-bins' '--enable-bmp-bins'

Libs:
cdada 0.4.0
libpcap version 1.10.1 (with TPACKET_V3)
rdkafka 2.3.0
jansson 2.13.1

Plugins:
memory
print
nfprobe
sfprobe
tee
kafka

System:
Linux 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64

Compiler:
gcc 11.4.0

*

**Comment by paololucente** [comment]
Hi @supaflyg ,

Thanks for bringing this up. Could you send me a pcap where the issue can be reproduced and we can have an expected right outcome? Here or by unicast email.

Paolo

**Comment by paololucente** [comment]
This was resolved with commit https://github.com/pmacct/pmacct/commit/d1239c1146cddc36eb164b05d86162ea711735cb  . Closing.
