### ISSUE TITLE
Slow restarting sfacctd daemon

### ISSUE THREAD

**Issue by udostanic** [pmacct/pmacct#785]
Hello Paolo,
I'm wondering if there is a way to start sfacctd daemon faster. Currently, it takes about 40 minutes to start writing to database (I'm using PostgreSQL), also I need to call `sudo sfacctd -f sfacctd.conf` twice. I have tested and if I call it once, daemon won't write data to database. Am I doing something wrong or this is how pmacct (sfacctd) works?

Thanks,
Uros

**Comment by paololucente** [comment]
Hi @udostanic ,

Definitely there is something wrong going on, unless of course the daemon is instructed to write after 40 minutes. Can you paste here (or by unicast email) an output of `sfacctd -V` along with your config and any maps that may be called by the sfacctd config.

Paolo
