### ISSUE TITLE
[sfacctd] Filter problem

### ISSUE THREAD

**Issue by udostanic** [pmacct/pmacct#788]
Hello @paololucente,
I'm using sfacctd plugin and I want to filter in my 4 of 20 tables by interface in and interface out. I added
`set_tag=1 in=1234` in pre-tag.map and I'm calling this tag in my .conf file. I also have `id=x ip=a.b.c.x` line below set_tag lines. Error is that if i try to add `jeq` command to jump to line with id if tag is correct i'm not getting data in my tables where I'm not using filter. I have tried another option to add id lines at the top of the pre-tag.map file and below to add set_tag lines, but then it won't write data to tables where I'm using filters. I hope I'm not confused you so much with this 'error'.

Best regards,
Uros

**Comment by paololucente** [comment]
Hi Uros ( @udostanic ),

Can you provide a sample of both your config and the intended / erroring `pre_tag_map`? Also, to have all info captured in the same issue, can you say what version are you running?

Paolo

**Comment by udostanic** [comment]
Hello Paolo,
sfacctd -V gave me this output:
![image](https://github.com/pmacct/pmacct/assets/22859855/1cc5cd65-a82f-4d7c-a025-de8726003c60)

This is my current pre_tag_map:

```
id=104 ip=x.y.z.104 jeq=test1
set_tag=1 agent_id=104 in=1000005 label=test1
set_tag=2 agent_id=104 out=19001
set_tag=3 agent_id=104 out=14001
```
I have tried to use set_tag first and then to have line where I specify id for ip address but it doesn't make a sense.

Here is a part of my conf file:

```
pre_tag_filter[ports5in]:1
pre_tag_filter[ports5out1]:2
pre_tag_filter[ports5out2]:3

aggregate[ports5in]:  vlan, src_port, dst_port, in_iface, out_iface
aggregate[ports5out1]:  vlan, src_port, dst_port, in_iface, out_iface
aggregate[ports5out2]:  vlan, src_port, dst_port, in_iface, out_iface
```
After this part of code goes part for my database configuration, then goes plugin config for writing to table. 
I have tried many combination but unsuccessful. My goal is to write agent id from pre_tag_map and filter a few tables (in future it can be 15/20 tables, but not  sure). Let me know if you need any other information.

Uros

**Comment by paololucente** [comment]
Hi Uros,

How about simplifying your map to:

```
set_tag=1 ip=x.y.z.104 in=1000005
set_tag=2 ip=x.y.z.104 out=19001
set_tag=3 ip=x.y.z.104 out=14001
```

`agent_id` is an old alias for `set_tag`. Also `id` is an unsupported key. I guess in the logs the daemon must be complaining of all of this.

Paolo

**Comment by udostanic** [comment]
Thank you, this map is working perfect. One more question, if I have more than one agent, what I am supposed to do to catch all of them?

**Comment by paololucente** [comment]
You could either skip the `ip=` clause alltogether or set it to `ip=0.0.0.0/0`

Paolo
