### ISSUE TITLE
bgp_logdump.c : Kafka / AMQP typo?

### ISSUE THREAD

**Issue by weyfonk** [pmacct/pmacct#79]
Hi Paolo,

I haven't been able to test this,  but am surprised to see that in `bgp_logdump.c`,  `p_kafka_set_topic()` is called on an AMQP host pointer at [line 282](https://github.com/pmacct/pmacct/blob/master/src/bgp/bgp_logdump.c#L282) instead of a Kafka host pointer.
I thought I would report this in case it was a typo and fixing it could prevent unexpected behaviours.
In case it isn't, please feel free to close this issue and accept my apologies (and ideally let me know or comment the reason for this) :)

**Comment by paololucente** [comment]
Hi Corentin,

You are right & i've just committed the fix. I've also tried grepping though the code to spot any similar issues but it seems that is the only instance. Thanks!

Cheers,
Paolo
