### ISSUE TITLE
Netflow missing important fields

### ISSUE THREAD

**Issue by midyrp** [pmacct/pmacct#790]
**Description**
I configured a debian server with pmacct in order to collect netflow data. I managed to get it into postgres but I only see source and destination IP. No ports or protocol

 agent_id |     class_id     |      mac_src      |      mac_dst      | vlan | as_src | as_dst |          ip_src           |     ip_dst      | port_src | port_dst | tcp_flags | ip_proto | tos | packets |   bytes   | flows |   stamp_inserted    |    stamp_updated    
----------+------------------+-------------------+-------------------+------+--------+--------+---------------------------+-----------------+----------+----------+-----------+----------+-----+---------+-----------+-------+---------------------+---------------------
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.24.60.34              | 192.168.37.67   |        0 |        0 |         0 |        0 |   0 |     102 |      6804 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 192.168.37.200            | 172.24.60.37    |        0 |        0 |         0 |        0 |   0 |     612 |    127428 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.25.10.37              | 172.24.60.1     |        0 |        0 |         0 |        0 |   0 |    1164 |     90885 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.24.60.37              | 192.168.37.200  |        0 |        0 |         0 |        0 |   0 |     614 |     48700 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.24.60.1               | 172.25.10.37    |        0 |        0 |         0 |        0 |   0 |    1164 |    252954 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.25.10.37              | 192.168.37.1    |        0 |        0 |         0 |        0 |   0 |     804 |     62098 |     0 | 2024-06-10 10:45:00 | 2024-06-10 10:55:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 192.168.37.55             | 172.24.60.224   |        0 |        0 |         0 |        0 |   0 |      42 |      2660 |     0 | 2024-06-10 10:40:00 | 2024-06-10 10:45:01
        0 | unknown          | 00:00:00:00:00:00 | 00:00:00:00:00:00 |    0 |      0 |      0 | 172.24.60.224             | 192.168.37.55   |        0 |        0 |         0 |        0 |   0 |      35 |      3120 |     0 | 2024-06-10 10:40:00 | 2024-06-10 10:45:01
     

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.7-git [RELEASE]

Arguments:
 '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-pgsql-includes=/usr/include/postgresql' '--enable-l2' '--enable-ipv6' '--enable-plabel' '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-rabbitmq' '--enable-zmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-64bit' '--enable-threads' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins' '--enable-nflog' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-fcommon' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/build/pmacct-Gh56jN/pmacct-1.7.7=. -fstack-protector-strong -Wformat -Werror=format-security'

Libs:
cdada 0.3.5
libpcap version 1.10.3 (with TPACKET_V3)
MariaDB 10.11.2
PostgreSQL 150006
sqlite3 3.40.1
rabbimq-c 0.11.0
rdkafka 2.0.2
jansson 2.14
MaxmindDB 1.7.1
ZeroMQ 4.3.4
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64

Compiler:
gcc 12.2.0

**Config**
daemonize: true
pidfile: /var/run/nfacctd.pid
syslog: daemon
aggregate: src_host,dst_host
pcap_filter: net 0.0.0.0/0
plugins: pgsql
nfacctd_ip: 0.0.0.0
nfacctd_port: 2055

sql_table_version: 7

sql_refresh_time: 300
sql_history: 5m
sql_history_roundoff: m

logfile: /tmp/nfacctd.log

**routers**
Mikrotik ROS 7.12.1 and 6.49.10 
tested netflow v5 and v9

**Comment by paololucente** [comment]
Hi @midyrp ,

It would be important to make sure this information is part of the data being sent over via NetFlow v5/v9 by the router. Did you check this is the case (ie. with Wireshark)? If you wish, i'd be happy to help / double check your findings. I'd need you send me a brief sample of your NetFlow data in pcap format (ie. taken with tcpdump / wireshark) via unicast email.

Paolo

**Comment by midyrp** [comment]
Hello Paolo,
I've tried netflow analyzers before, the data is in there. I've checked with tcpdump but i'll make and send you some captures from both software versions. Just might be usefull to you in devellopment.

**Comment by midyrp** [comment]
Thank you! That does the trick. Maybe I could/should have found i in the documentation. (ps: the command for me was nfacctd -a and not capital A as argument) More to experiment, but moving forward fast now.
