### ISSUE TITLE
 Not receive sflow data when we use the pretag filter

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#792]
**Description**
We do not receive sflow data when we use the pre-tag filter. If we remove the pre-tag filter, we get flow data in PMACCT.

Config File
`sfacctd_port: 9991
sfacctd_time_new: true
timestamps_utc: true
sfacctd_stitching: true
timestamps_secs: true
maps_row_len:2472
plugins: print[pmacct_9991]

aggregate[pmacct_9991]: peer_src_ip, src_host, dst_host, proto, src_port, dst_port
pre_tag_map[pmacct_9991]:/etc/pmacct/pmacct_pretag_9995.map
pre_tag_filter[pmacct_9991]:100
print_output[pmacct_9991]:csv
print_output_file[pmacct_9991]:/etc/pmacct/pmacct_9991/filter/%Y%m%d%H%M.csv
print_history[pmacct_9991]: 5m
print_history_offset[pmacct_9991]: m
print_history_roundoff[pmacct_9991]:m
print_output_file_append[pmacct_9991]: true
print_refresh_time[pmacct_9991]:300`

Below is the configuration we used in the pmacct_pretag_9995.map file

`set_tag=100 ip=192.168.50.220 filter=' not (src net 0.0.0.0 or dst net 255.255.255.255 or src port 0 or dst port 0) and (tcp or udp) and ip'`

A similar filter configuration works on netflow but not on sflow.

**Version**
Output of nfacctd -V:

`NetFlow Accounting Daemon, nfacctd 1.7.7-git [20211107-0 (https://github.com/pmacct/pmacct/commit/ef37a415504c9c3e6afeaecb2f0cce4eb698e648)]

Arguments:
'--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.8.1
MariaDB 10.3.31
PostgreSQL 110013
sqlite3 3.27.2
rabbimq-c 0.11.0
rdkafka 1.8.2
jansson 2.14
MaxmindDB 1.6.0
ZeroMQ 4.3.2
Redis 1.0.3
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.4.0
netfilter_log

Plugins:
memory
print
nfprobe
sfprobe
tee
mysql
postgresql
sqlite
amqp
kafka

System:
Linux 5.4.17-2136.307.3.1.el8uek.x86_64 https://github.com/pmacct/pmacct/pull/2 SMP Mon May 9 17:29:47 PDT 2022 x86_64

Compiler:
gcc 8.3.0

**Comment by paololucente** [comment]
Hi @AnanthGopal ,

Is it possible flows are being collected differently for sFlow and NetFlow. For example, sFlow may be reporting the VLAN that NetFlow may be not? If so, the filter has to be adjusted accordingly ie. with a trailing `... and vlan`. Also the presence of the MPLS layer may require tuning the filter.

Should nothing help, you could send over a brief sample of your sFlow traffic so that i could reproduce the problem at my end.

Paolo
