### ISSUE TITLE
Get timestamp without residual value 2024-07-12 14:44:00.XXXXX

### ISSUE THREAD

**Issue by balioune** [pmacct/pmacct#794]
**Description**

Hi,
I'm using Kafka to store PMACCT Netflow data and then parse them to ClickHouse.
I would like to know how to configure PMACCT to send timestamp like "2024-07-12 10:44:00" and NOT like "2024-07-12 10:44:00.142331" ?
BR,

**Version**
./nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.3-git (20190418-00+c4)

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-debug' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
rdkafka 1.5.0
jansson 2.5

System:
Linux 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64

Compiler:
gcc 4.8.5

**Comment by paololucente** [comment]
Hi @balioune ,

You should be looking for the `timestamps_secs: true` config directive. I checked for you and it is available in 1.7.3.

Paolo

**Comment by balioune** [comment]
Thanks @paololucente
