### ISSUE TITLE
Nexthop inconsistency between advertised routes and bgp table dumped in a file.

### ISSUE THREAD

**Issue by m4ccbr** [pmacct/pmacct#80]
Hi again :),

I noticed some of the dumped BGP routes have some inconsistencies in the next hop attribute,  as you can see below, we are announcing one nexthop, but we see another in the dumped file. 

print out from the advertised routes
* 10.20.255.8:1:10.20.5.0/24 (2 entries, 1 announced)
 BGP group IBGP_pmacct type Internal
     Route Distinguisher: 10.20.255.8:1
     VPN Label: 16
     Nexthop: 10.20.255.8
     Localpref: 100
     AS path: [64021] I
     Communities: target:64021:1
     Cluster ID: 10.20.255.1
     Originator ID: 10.20.255.8

* 10.20.255.8:8/:10.7.9.128/25 (2 entries, 1 announced)
 BGP group IBGP_pmacct type Internal
     Route Distinguisher: 10.20.255.8:8
     VPN Label: 19
     Nexthop: 10.20.255.8
     Localpref: 100
     AS path: [64021] I
     Communities: 64021:8 target:64021:8
     Cluster ID: 10.20.255.1
     Originator ID: 10.20.255.8

{"timestamp": "2016-12-10 11:15:00", "peer_ip_src": "10.20.1.114", "event_type": "dump", "ip_prefix": "10.20.5.0/24", "bgp_nexthop": "10.20.255.4", "as_path": "", "ecomms": "RT:64021:1", "origin": 0, "local_pref": 100, "rd": "1:10.20.255.8:1"}

{"timestamp": "2016-12-10 11:15:00", "peer_ip_src": "10.20.1.114", "event_type": "dump", "ip_prefix": "10.7.9.0/25", "bgp_nexthop": "10.20.255.8", "as_path": "", "comms": "64021:8", "ecomms": "RT:64021:8 ", "origin": 0, "local_pref": 100, "rd": "1:10.20.255.8:8"}

**Comment by paololucente** [comment]
Hi Alberto,

I'd have a similar question as for the last case you opened. In order to troubleshoot this further i'd need some analysis at your end, like:

* Is this the only inconsistency or can you spot more?
* Is it persistent across runs, ie. given same input you get same output? 
* Should you be able to change the input, ie. advertise a subset of routes, is the inconsistency still there and is the same?

We should narrow it down to something that i can reproduce in lab or that gives us a clue in what is going on.

What puzzles me so far is: 1) 10.20.255.4 is a too well formed IP address to be a symptom of spurious data or corruption; 2) nexthop is part of the main bgp_attr structure (unlike communities or AS-PATH that are referenced) and hence having a sane local preference but a wrong nexthop is really strange.

Cheers,
Paolo

**Comment by m4ccbr** [comment]
Hi Paolo,

here are some of the answers.

Is this the only inconsistency or can you spot more? 
there are more prefixes like that one

Is it persistent across runs, ie. given same input you get same output? 
Yes, every run I get the same problem

Should you be able to change the input, ie. advertise a subset of routes, is the inconsistency still there and is the same?
I will create a new loopback and see how it will look like.

2) nexthop is part of the main bgp_attr structure (unlike communities or AS-PATH that are referenced) and hence having a sane local preference but a wrong nexthop is really strange. I agree with you, it does not make any sense, I don't if the fact that it is a MPLS VPN routes triggers a problem.

**Comment by paololucente** [comment]
Hi Alberto,

You say "there are more prefixes like that one": is the inconsistency always only related to the nexthop attribute? Btw is 10.20.255.4 a valid nexthop at all in your network? 

Thanks for trying to change the input a bit and see how the issue develops. To your point, valid, whether this is related to MPLS VPN routes - I guess you don't have a chance to advertise some comparable amount of non MPLS VPN routes?

**Comment by m4ccbr** [comment]
Hi Paolo,

You say "there are more prefixes like that one": is the inconsistency always only related to the nexthop attribute? Yes, it is only the nexthop, RD, communities and ext communities everything looks ok so far.

You say "there are more prefixes like that one": is the inconsistency always only related to the nexthop attribute? Btw is 10.20.255.4 a valid nexthop at all in your network? Tes it is a valid next hop in the network, it is one of my PEs, but the network is not originated by .4 in this case where the nexthop does not match the IP address in the RD.

I guess you don't have a chance to advertise some comparable amount of non MPLS VPN routes? nop ;(

cheers,

**Comment by paololucente** [comment]
Hi Alberto, i reviewed code and tried several tricks to try to reproduce this in lab - all with no luck. I'd be more than happy to support you further with this issue but at this point i believe only way to make progress would be to remotely access your setup. Should i find you positive on the idea, please drop me a private email.

**Comment by m4ccbr** [comment]
not sure if you would be able to access my setup, but I will create a similar setup at home with some vMXs and there I can grant you access :) I will try to advertise the same routes I'm advertising it today to see if I can find the inconsistence there as well and then I will drop an email explaining how to get access :+1: does it sound ok to you?

**Comment by paololucente** [comment]
Thanks and, yes, it sounds fantastic. Look forward to it.

**Comment by paololucente** [comment]
Hi Alberto,

Happy New Year! I'm marking this with wontfix and closing for now. I still look forward if we can reproduce this issue somewhere i can get access to and make progress to resolution.
