### ISSUE TITLE
Time unit of time-related member variable values ​​in structures for NDPI

### ISSUE THREAD

**Issue by jungwon-w** [pmacct/pmacct#812]
**Description**

In the structures for NDPI, there are time-related member variables as follows.

```
/* flow tracking */
typedef struct pm_ndpi_flow_info {
 ...
 u_int64_t last_seen;
 ...
} pm_ndpi_flow_info_t;

/* flow preferences */
typedef  struct pm_ndpi_workflow_prefs {
 ...
 u_int32_t idle_scan_period;
 u_int32_t idle_max_time;
 ...
} pm_ndpi_workflow_prefs_t;

/* workflow main structure */
typedef  struct pm_ndpi_workflow {
 ...
 u_int64_t last_time;
 u_int64_t last_idle_scan_time;
...
} pm_ndpi_workflow_t;
```

The default value of 'idle_max_time' is defined as 600 (NDPI_IDLE_MAX_TIME) seconds, but looking at the code, it appears that the time unit of the values ​​stored in each time-related variable is processed in milliseconds, not seconds.
In the pm_ndpi_workflow_process_packet() function, the time the packet was received is stored in the 'time' variable.
```
/* setting time */
time = ((uint64_t) pptrs->pkthdr->ts.tv_sec) * NDPI_TICK_RESOLUTION + pptrs->pkthdr->ts.tv_usec / (1000000 / NDPI_TICK_RESOLUTION);
```
Isn't the value of this 'time' variable in milliseconds?
And this 'time' variable is stored in workflow->last_time and flow->last_seen, and compared with other time-related setting values.
Looking at the code and official documentation, it appears that these time-related values ​​are defined in seconds.

In particular, if 'idle_max_time' is set to the default value (600), the value is too small if the time unit is milliseconds.
When searching for idle flows to expire in pm_ndpi_node_idle_scan_walker() function, it compares the 'idle_max_time' value, so the flow expires in 600 milliseconds.

**Version**
1.7.9

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi @jungwon-w ,

You are essentially right, i just pushed a commit to address this issue. My suspicion is that in some previous version of the nDPI API these values were expressed in seconds, and it remained as such in pmacct. I have now reviewed code and docs and adapted them with the latest available sample of code integration in nDPI.

Paolo

**Comment by jungwon-w** [comment]
Thanks for checking.

Best regards.
