### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by vincentbernat** [pmacct/pmacct#82]
It would help if releases were tagged.

By looking at the history of ChangeLog, I could get the most recent ones:

```
git tag v1.6.1 7702361b938344e56ec1fc2db83f9957c0d91c61
git tag v1.6.0 a86c805a3838dfd158d546c358e1fb928bdd3bf2
git tag v1.5.3 2eb7432f4a9e99f863a409ee35c0b85f8c4d94b0~1
git tag v1.5.2 2021a8849fe6366c7bc741bc0a4ecad6df8c0937
git tag v1.5.1 181b22d734adf32dcdb92404a90bdf98ce82d8c4~1
git tag v1.5.0 7815a7f9f95c7a676b2fbeac501a0c6941cdc574
git tag v0.14.3 e5df23390ab975937c1f84f4f6b87172d2c3cc88~1
git tag v0.14.2 d0391bfa5469fbb43ef9ebf14fd6c07464a889e2~1
git tag v0.14.1 9a83d5985b89a7a2746975f1cd203002b2827cb7
git tag v0.14.0 1f9d84bb9cd19aae9fc2fe0a2cfcfae64fc05925
```

I am using `~1` to refer to the previous commit when the current commit both set date for the new version and bump the number to the next version. I suppose you generate tarball between the two steps.

**Comment by job** [comment]
Thanks for the legwork. https://github.com/pmacct/pmacct/releases

@paololucente going forward, after a new version number is committed please issue something along the lines of:

```
ed file
git commit -am "bump version to NN"
git tag vNN
git push --tags
```

**Comment by vincentbernat** [comment]
Note it's possible to integrate all that in the build system in a way that you only have to tag to make a release, while still ensuring that generated tarballs have the right version. Stolen from libbsd:
 - https://github.com/vincentbernat/lldpd/blob/master/get-version
 - https://github.com/vincentbernat/lldpd/blob/master/configure.ac#L11
 - https://github.com/vincentbernat/lldpd/blob/master/Makefile.am#L30 (don't forget `EXTRA_DIST` too)

I can do a PR for that if it's something we want.

**Comment by job** [comment]
@vincentbernat if I am not mistaken, the `configure` and `Makefile` would then depend on it being run in a git repository, while the tarballs that pmacct traditionally releases are just standalone distributions without the git history. Can you elaborate?

**Comment by vincentbernat** [comment]
The `get-version` generates a `.dist-version` that is included in the tarballs generated with `make dist`.

**Comment by job** [comment]
@vincentbernat I don't see that in lldpd looking at https://github.com/vincentbernat/lldpd/archive/0.9.5.tar.gz ?

```Vurt:lldpd-0.9.5 job$ cat .dist-version
cat: .dist-version: No such file or directory```

Feel free to make a PR if you think this can be improved upon, might be easier to converse over a PR then in this issue :-)
