### ISSUE TITLE
Potential memory leak in bmp_rib_type_print

### ISSUE THREAD

**Issue by mxyns** [pmacct/pmacct#820]
Hey @paololucente 

**Description**
The `bmp_rib_type_print` function allocates a string that is never freed

```c
char *bmp_rib_type_print(u_int8_t in)
{
  char *out = NULL;
  int value_len;

  if (in <= BMP_RIB_MAX) {
    value_len = strlen(bmp_rib_types[in]);
    out = malloc(value_len + 1 /* null */); // Alloc
    sprintf(out, "%s", bmp_rib_types[in]);
  }
  else {
    out = malloc(3 /* value len */ + 1 /* null */); // Alloc
    sprintf(out, "%u", in);
  }

  return out; // Return alloc buffer
}
```

Use
```c
json_object_set_new_nocheck(obj, "bmp_rib_type", json_string(bmp_rib_type_print(bdata->chars.rib_type))); /// Does not free
```

The result of this function is always used in logdumps which do not free the memory. I think we could avoid the malloc and sprintf, return bmp_rib_types[in] directly and return a static string for the error, or have the output buffer be a parameter of the function that could be either a heap or stack allocated string.

**Version**
Built from source, last version on master (commit hash 3439a67c2c961782b8146d988b88fa881c291fc5)

**Comment by paololucente** [comment]
Hey Maxence ( @mxyns ),

Thanks for this, very well spotted. I should have got it fixed: https://github.com/pmacct/pmacct/commit/4606091087a20c977bad76b27e096e93bde6fd76

Paolo

**Comment by paololucente** [comment]
For sure, i just wanted to avoid two things: 1) the static length thing (although 128 bytes is a fair length) and 2) a static allocation (we have plenty i am aware but, especially in sections of the code where there is parallelization, ie. `bmp_dump_workers`, i wanted to avoid to add statics. Paolo

**Comment by mxyns** [comment]
Right, I didn't think about parallelization, though I think it wouldn't be an issue if you use stack allocated (but non-static) arrays. The length can be a future bug if this array length changes in the future
