### ISSUE TITLE
Question | Is there any support to know Flow Per Second or Packet per second?

### ISSUE THREAD

**Issue by smit1682** [pmacct/pmacct#832]
**Description**

Hello @paololucente , I am using PMACCT project for flow monitoring, I have one use case, which is to get actual FPS(Flow per second) or PPS(Packet per second), like how much packets are arriving at PMACCT socket per second. 
And also the size of packets (to calculate actual volume bytes of arriving packets)

my current problem is: we are agggrigating the flow, and nfacct print plugin sending me aggregated  flow data after 5min,  so I can't get the actual FPS and also the volume of packets

so do we have any configuration to get these two parameters?
if we don't have this configuration, can you guide me on how to archive this parameters,
(like we are storing nfacct pid in file, similar to that can we also get FPS and Bytes?)

**Version**
NetFlow Accounting Daemon, nfacctd 1.7.9 [RELEASE]

**Comment by paololucente** [comment]
Hi @smit1682 ,

No, there is no support for per-second counters, you would have to calculate yourself. One way is with the `print` plugin, if 5 mins is too sparse, you could do it every 1 minute for example. If also 1 minute is too sparse (or you need something ad-hoc), you could use the `memory` plugin: 1) you query the table whenever needed (ad-hoc times, every 10 secs, etc.), 2) with `pmacct -s -e` you also reset the counters and 3) keep the previous download timestamp as reference to figure out the new per-second figures.

Paolo

**Comment by smit1682** [comment]
Thank you @paololucente for the response, I will consider your suggestions,

Also, can you tell me, in the codebase which file is the entry point, 
where is our packet listener socket, if I want to add code after receiving the packet, in which file and where can I add the code? 

Again, THANK YOU SO MUCH for your Assistance.

**Comment by paololucente** [comment]
Hi Smit ( @smit1682 ),

Please contact me directly by email for development issues. I'll be happy to help given i have all the details, including the daemon you are running, what you are trying to achieve, etc.

Paolo
