### ISSUE TITLE
Bug warning in bmp_daemon_ha

### ISSUE THREAD

**Issue by Ja1rman** [pmacct/pmacct#834]
**Description**
I turned on `bmp_daemon_ha: true` and specified the cluster settings. But I see warnings in the output and if you remove these settings, HA still works and does not give errors.

`pmacctd-test  | WARN: [/etc/pmacct/pmbmpd.conf:10] Unknown key: bmp_daemon_ha_cluster_name. Ignored.
pmacctd-test  | WARN: [/etc/pmacct/pmbmpd.conf:11] Unknown key: bmp_daemon_ha_cluster_id. Ignored.`

**Version**
I'm using docker with tag latest
$ pmbmpd -V
pmacct BMP Collector Daemon, pmbmpd 1.7.9-git [20240618-0 (a2f3eaa7)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.5.0
libpcap version 1.10.0 (with TPACKET_V3)
MariaDB 10.5.23
PostgreSQL 130014
sqlite3 3.34.1
rabbimq-c 0.13.0
rdkafka 2.5.0
jansson 2.14
MaxmindDB 1.10.0
ZeroMQ 4.3.4
Redis 1.2.0
GnuTLS 3.7.1
avro-c
serdes
nDPI 4.6.0
netfilter_log

System:
Linux 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64

Compiler:
gcc 10.2.1

**Comment by paololucente** [comment]
Hi Roman ( @Ja1rman ),

Thanks for reporting this. Any chance you can test bleeding-edge, which is the latest version in master? I tried to reproduce the issue but without success, both config directives are swallowed allright.

Paolo

**Comment by Ja1rman** [comment]
Yeah, no warnings
