### ISSUE TITLE
PostgreSQL slow select.

### ISSUE THREAD

**Issue by pzelektron** [pmacct/pmacct#840]
Hi.
I use uacctd to collect data on two routers. Data are sent to nfacctd on 3 separate machine. I use PostgreSQL to store data.
This is my config :
```
! uacctd configuration
!
!
!

!systemctl enable uacctd
!iptables -I FORWARD ! -i eth0 -m state --state NEW -p tcp -j NFLOG --nflog-group 5 --nflog-prefix "5" --nflog-threshold 50
!tcpdump -s 0 -n -i nflog:5
uacctd_group: 5
daemonize: true
!
! interested in in and outbound traffic
aggregate: src_host, dst_host , src_port, dst_port, proto,timestamp_start


!
! storage methods
plugins: pgsql
sql_host: x.x.x.x
sql_user: uacctd
sql_db: uacctd
sql_passwd: ****
sql_table_version: 1

sql_refresh_time: 30
timestamps_secs: true
sql_history: 1m
sql_history_roundoff: m
sql_dont_try_update: true

-------------------

!/etc/pmacct/nfacctd.conf
! nfacctd configuration
! NetFlow Accounting Daemon, nfacctd 1.7.7-git [RELEASE]
! https://github.com/pmacct/pmacct/blob/master/QUICKSTART
! https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS
! https://github.com/pmacct/pmacct/blob/master/sql/README.timestamp
!
!

daemonize: true
pidfile: /var/run/nfacctd.pid
syslog: daemon
nfacctd_port: 9995
!
! interested in in and outbound traffic
aggregate: src_host, dst_host , src_port, dst_port, proto,timestamp_start
!
! storage methods
plugins: pgsql
sql_host: 127.0.0.1
sql_passwd: ****
sql_table_version: 1

sql_refresh_time: 300
timestamps_secs: true
sql_history: 5m
sql_history_roundoff: m
sql_dont_try_update: true

!timestamps_since_epoch: true
!timestamps_secs: true
```
Data collection works fine but there is lot of data :
```
SELECT pg_size_pretty(pg_database_size('uacctd'));
 pg_size_pretty
----------------
 385 GB
```
So when I try to find something like that :
`select ip_src,ip_dst,port_src,port_dst,stamp_inserted,stamp_updated,timestamp_start from acct where ip_dst='178.211.137.89' and timestamp_start between '2024-09-04 8:00:00' and '2024-09-04 9:00:00' order by timestamp_start;`
It takes 3-4 hours .
How I can improve this select ?
I just think to rename every day uacctd to uacctd_dd_mm_rrrr and create new empty uacctd. But maybe there is better way ?

**Comment by paololucente** [comment]
Hi @pzelektron ,

Definitely keeping a traffic matrix like that in a single PostgreSQL table is not a good idea as the size will sky-rocket (as it's doing for you) and the database will like not perform (like it's happening). That starts to be a Big Data problem and not one for traditional RDBMS.

You could certainly try to divide the dataset in daily tables, it all boils down how big they get. Another thing you may try is to use a non-relational engine for PostgreSQL like TimescaleDB. Other random advices:
* aggregate data in prefixes (ie. use src_net, dst_net instead of src_host, dst_host) with a `networks_file`;
* filter ip prefixes that may not be of interest, like those lying on the internet, with a `networks_file_filter`;
* keep only keep ports of interest with a `ports_file`; 
* or don't organize data in a traffic matrix, do a inbound vs outbound data;

Paolo

**Comment by pzelektron** [comment]
Hi.
Thanks for reply. For me this data should look in this way. I think this is absolute minimum. I have to log all users connections. And keep it one year. So I just wrote sql script :
```
BEGIN;

--  rename table
DO $$
BEGIN
	EXECUTE 'ALTER TABLE IF EXISTS acct RENAME TO acct_'||TO_CHAR(now(), 'DD_MM_YYYY')||';';
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS acct (
    mac_src macaddr NOT NULL DEFAULT '0:0:0:0:0:0',
    mac_dst macaddr NOT NULL DEFAULT '0:0:0:0:0:0',
    ip_src inet NOT NULL DEFAULT '0.0.0.0',
    ip_dst inet NOT NULL DEFAULT '0.0.0.0',
    port_src INT NOT NULL DEFAULT 0,
    port_dst INT NOT NULL DEFAULT 0,
    ip_proto SMALLINT NOT NULL DEFAULT 0,
    packets INT NOT NULL,
    bytes BIGINT NOT NULL,
    stamp_inserted timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    stamp_updated timestamp without time zone,
    timestamp_start timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(0)--,
    --timestamp_start_residual timestamp without time zone,
    --CONSTRAINT acct_pk PRIMARY KEY (mac_src, mac_dst, ip_src, ip_dst, port_src, port_dst, ip_proto, stamp_inserted,timestamp_start)
);

CREATE TABLE IF NOT EXISTS daty (
    tabela varchar(100) NOT NULL,
    czas_wykonania timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);

insert into daty
select 'acct_'||TO_CHAR(now(), 'DD_MM_YYYY'),now();

-- Perm
GRANT SELECT, INSERT, UPDATE, DELETE ON acct TO uacctd;

COMMIT;
```
Now just must add this to cron and run every day. For me this is the simplest solutions. On my test environment works ok. Tomorrow I can confirm how it runs on production.
I hope nothing breaks :)

**Comment by paololucente** [comment]
Hi @pzelektron ,

Awesome, thanks for confirming your choice. Keep me posted, hoping all goes well.

Paolo

**Comment by paololucente** [comment]
Thanks @pzelektron  for confirming, excellent! Paolo
