### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by mdomore** [pmacct/pmacct#89]
Hi,

i try to compile pmacct with rabbitmq.

I have pmacct 1.5.1, rabbitmq-server 3.5.7, and last rabbitmq-c release.
./configure works great.
but make failed

amqp_common.c: In function ‘p_amqp_connect’:
**amqp_common.c:175:77: error: incompatible type for argument 7 of ‘amqp_exchange_declare’
                         amqp_cstring_bytes(amqp_host->exchange_type), 0, 0, amqp_empty_table);**
                                                                             ^
In file included from /usr/local/include/amqp.h:765:0,
                 from amqp_common.h:23,
                 from amqp_common.c:27:
/usr/local/include/amqp_framing.h:798:11: note: expected ‘amqp_boolean_t {aka int}’ but argument is of type ‘amqp_table_t {aka const struct amqp_table_t_}’
 AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_b
           ^
**amqp_common.c:174:3: error: too few arguments to function ‘amqp_exchange_declare’
   amqp_exchange_declare(amqp_host->conn, 1, amqp_cstring_bytes(amqp_host->exchange),**
   ^
In file included from /usr/local/include/amqp.h:765:0,
                 from amqp_common.h:23,
                 from amqp_common.c:27:
/usr/local/include/amqp_framing.h:798:11: note: declared here
 AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_b
           ^
amqp_plugin.c: In function ‘amqp_plugin’:
amqp_plugin.c:65:3: warning: implicit declaration of function ‘pm_setproctitle’ [-Wimplicit-function-declaration]
   pm_setproctitle("%s [%s]", "RabbitMQ/AMQP Plugin", config.name);
   ^
amqp_plugin.c: In function ‘amqp_handle_routing_key_dyn_strings’:
amqp_plugin.c:455:5: warning: implicit declaration of function ‘addr_to_str’ [-Wimplicit-function-declaration]
     addr_to_str(ip_address, &elem->pbgp->peer_src_ip);
     ^
amqp_plugin.c:477:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘pm_id_t {aka long unsigned int}’ [-Wformat=]
     snprintf(buf, newlen, "%u", config.post_tag);
                           ^
amqp_plugin.c:477:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘pm_id_t {aka long unsigned int}’ [-Wformat=]
amqp_plugin.c:497:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘pm_id_t {aka long unsigned int}’ [-Wformat=]
     snprintf(buf, newlen, "%u", elem->primitives.tag);
                           ^
amqp_plugin.c:497:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘pm_id_t {aka long unsigned int}’ [-Wformat=]

Anyone help ?

**Comment by paololucente** [comment]
Hi,

pmacct 1.5.1 looks very old: please try with latest release or current GitHub code.

Paolo

**Comment by mdomore** [comment]
my bad.

Thx for quick response
