### ISSUE TITLE
nfacctd segfault print plugin

### ISSUE THREAD

**Issue by zamog** [pmacct/pmacct#90]
Running nfacctd 1.6.1 on centos 7 with the following config:
daemonize: true
plugins: kafka[dsthost],print[all]
aggregate[dsthost]: dst_host
kafka_output[dsthost]: json
kafka_topic[dsthost]: pmacct.acct
kafka_refresh_time[dsthost]: 300
kafka_history[dsthost]: 5m
kafka_history_roundoff[dsthost]: m
nfacctd_port: 9992
!
aggregate[all]: dst_host, src_host, dst_port, src_port
print_refresh_time[all]: 300
print_history[all]: 300
print_history_roundoff[all]: m
print_output_file_append[all]: true
print_output_file[all]: /opt/Data/as/netflow-%Y-%m-%d-%H-%M.csv
print_latest_file[all]: /opt/Data/as/netflow.latest
print_output[all]: csv

compile info:
NetFlow Accounting Daemon, nfacctd 1.6.1 (20161001-00+c5)
 '--enable-sqlite3' '--enable-jansson' '--enable-ipv6' '--enable-kafka' '--enable-rabbitmq' '--enable-pgsql' '--enable-mysql' '--enable-plabel' '--enable-geoipv2'

after ~ 5 min the nfacctd print process crash with the following message: 
segfault at 31 ip 00007f5114a0938c sp 00007ffcff007798 error 4 in libc-2.17.so[7f5114989000+1b6000]
please advise

**Comment by paololucente** [comment]
Hi,

Please try the same with latest code from GitHub and check whether it still crashes. If it does, please follow QUICKSTART document chapter XXII "Miscellaneous notes and troubleshooting tips", especially section A. 

Paolo

**Comment by zamog** [comment]
Thanks for the prompt response, i compile the latest code (nfacctd 1.6.2-git (20161231-00)) and it seems to solve the problem !
Happy new year

**Comment by paololucente** [comment]
Great stuff. Happy new year to you too.
