### ISSUE TITLE
amqp_avro_schema_routing_key Appears to not be working

### ISSUE THREAD

**Issue by Jhors2** [pmacct/pmacct#95]
Version:
```
pmacct, pmacct client 1.6.1 (20161001-00+c5)
 '--enable-rabbitmq' '--enable-jansson' '--enable-geoip' '--enable-avro'

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

When amqp_avro_schema_routing_key is set, I get the following error:
`Unknown key: amqp_avro_schema_routing_key. Ignored.`

Is this known?

**Comment by paololucente** [comment]
Hey Jerred,

amqp_avro_schema_routing_key is post 1.6.1 and can be traced back to commit f54eec6892b63d9c936a9e324f9501a5d7a11520 from Nov, 2016. I'd suggest to give a try to master code if really needing the feature.

Paolo
