### ISSUE TITLE
Interface with timestamp_end was 1970

### ISSUE THREAD

**Issue by whitetiger21022014** [pmacct/pmacct#97]
Dear pmacct Team,
I monitor an eth1 interface of Centos and timestamp_end always '1970-01-01 08:00:00.0'
If my configuration has problem, please help me

P/s: my purpose will calculate exact duration of connection = timestamp_end - timestamp_start
Thanks,

Server: CentOS 6.3, pmacctd 1.6.0-git (20160606-00) and also tested with **pmacctd 1.6.2-git (20170203-00)**

**Command and config file:	pmacctd -f /etc/pmacct2.conf**
daemonize: false
plugins: memory[in], memory[out]
interface: eth1

aggregate[in]:  dst_host,src_host,timestamp_start,timestamp_end,dst_port,src_port,proto
aggregate[out]: dst_host,src_host,timestamp_start,timestamp_end,dst_port,src_port,proto
aggregate_filter[in]: src net 192.168.0.0/16
aggregate_filter[out]: dst net 192.168.0.0/16
imt_path[in]: /tmp/pmacct_in.pipe
imt_path[out]: /tmp/pmacct_out.pipe

**Show:	pmacct -p /tmp/pmacct_in.pipe -s**
SRC_IP           DST_IP           SRC_PORT  DST_PORT  PROTOCOL    TIMESTAMP_START                TIMESTAMP_END                  PACKETS               BYTES
192.168.111.138  192.168.111.1    22        62071     tcp         2017-02-03 22:56:57.585742     1970-01-01 08:00:00.0          1                     712
192.168.111.138  192.168.111.1    22        62071     tcp         2017-02-03 22:54:40.578268     1970-01-01 08:00:00.0          1                     1336
...................

**Comment by paololucente** [comment]
Hi John,

This is expected behaviour. What you essentially want is to build flows, with start and end times. Can you please have a look at this email thread: https://www.mail-archive.com/pmacct-discussion@pmacct.net/msg03194.html . In the reply email i propose the same solution i'd propose you for your case. Let me know if that works for you.

Cheers,
Paolo

**Comment by whitetiger21022014** [comment]
Hi Paolo,
I just followed your link, used nfprobe (softflowd) and got exact TIMESTAMP_END. It works as expected.
Thanks for your support

**Comment by whitetiger21022014** [comment]
Hi Paolo,
With nfprobe netflow, i can get TIMESTAMP_END, but can not detect **'classifiers feature'**

**Comment by paololucente** [comment]
Hi John,

Can you post your configurations to this point? It should work. Did you get the classification feature working before switching to the proposed nfprobe setup?

Paolo

**Comment by whitetiger21022014** [comment]
Hi Paolo,
With old test, I can get classifiers because I don't think softflowd can send classifiers! and don't include line as snaplen: 700
I just read document and all is okay now. Thank for your pmacct

One last question, because I don't insert flows to database, just use memory pipe. So If you know any link/script that provide aggregation please let me know that link, ex:
SRC_IP           DST_IP           SRC_PORT  DST_PORT  PROTOCOL      BYTES
11.11.11.11 22.22.22.22       12345          80              tcp                   30
11.11.11.11 22.22.22.22       12346          80              tcp                   50
11.11.11.11 22.22.22.22       12347          80              tcp                    20

Will aggregation and summary eg. Dest port to one line as below
**11.11.11.11 22.22.22.22                           80              tcp                    100 (bytes)**

**Comment by paololucente** [comment]
Hi John,

I'm not aware of any cooked scripts that you can adapt in this sense. It does not look you need a complex script for that but there is enough logics that you need one.

Paolo
