### ISSUE TITLE
[SFACCT] ARP trafic not displayed in JSON Logs

### ISSUE THREAD

**Issue by rataman** [pmacct/pmacct#98]
Hi,

I have a problem with sfacct to display ARP traffic in logs (json)
I use version 1.6.2 and Alcatel-Lucent Enterprise Omniswitch equipments which support sFlow V5.

I can see multicast (VRRP) and unicast flow captured by sfacct but not ARP traffic. 
I verified in the .pcap with wireshark and sFlow datagram contains well ARP traffic.

**_sfacct.conf_**
```
daemonize: true
syslog: daemon
pidfile: /var/run/sfacctd.pid

plugins: print
print_output: json

sfacctd_counter_file: /pmacct/TMP/sFlow-Counters.txt
sfacctd_counter_output: json

interface: eth0

aggregate: src_host, dst_host, peer_src_ip, peer_dst_ip, in_iface, out_iface, src_port, dst_port, proto, tos, src_mask, dst_mask, tcpflags,

print_refresh_time: 60
print_history: 1m
print_output_file: /pmacct/LOGS/sFlow-file-%Y%m%d-%H%M.txt
print_history_roundoff: m
```

**_JSON output_**

`{"event_type": "purge", "peer_ip_src": "0.0.0.0", "peer_ip_dst": "", "iface_in": 1024, "iface_out": 0, "ip_src": "10.55.51.253", "ip_dst": "224.0.0.18", "mask_src": 0, "mask_dst": 0, "port_src": 0, "port_dst": 0, "tcp_flags": "0", "ip_proto": "vrrp", "tos": 192, "packets": 1, "bytes": 68}`

**_sFlow header_**

![sflow_arp_header](https://cloud.githubusercontent.com/assets/13472044/22647389/7c560f6e-ec71-11e6-82eb-5c71c4cfd0e4.jpg)

Do you want .pcap file for further  investigation ?

Best Regards

**Comment by paololucente** [comment]
Hi,

You are actually bumping in something known: pmacct being an IP accounting tool, it does not report on protocols different than IP. 

Paolo

**Comment by rataman** [comment]
Thanks for your answer !
