### ISSUE TITLE
v6 not supported by nfprobe_receiver in config?

### ISSUE THREAD

**Issue by regulatre** [pmacct/pmacct#99]
Specifying `nfprobe_receiver: [ipv6address]:port` and then running `pmacctd -f /etc/netflow/config -i eth0` results in error: `Syntax error: not weighted brackets. Exiting`.  

My goal is to generate IPv6 netflow packets from Linux server.

**Comment by paololucente** [comment]
Hi Brad,

Thanks for filing this. This is clearly a bug. I can provide a workaround while i fix it; the following would work:

plugins: nfprobe[<plugin name>]
!
nfprobe_receiver[<plugin name>]: [ipv6address]:port

Cheers,
Paolo

**Comment by paololucente** [comment]
Hi Brad,

This is now solved and tested working for me. Please give it a try yourself and re-open this issue in case of further issues.

Thanks,
Paolo
